// GENERATED CODE - DO NOT MODIFY BY HAND
// coverage:ignore-file
// ignore_for_file: type=lint
// ignore_for_file: unused_element, unused_import, deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: use_function_type_syntax_for_parameters
// ignore_for_file: unnecessary_const, avoid_init_to_null
// ignore_for_file: invalid_override_different_default_values_named
// ignore_for_file: prefer_expression_function_bodies
// ignore_for_file: annotate_overrides, invalid_annotation_target
// ignore_for_file: unnecessary_question_mark
// Generated by dust.

part of 'update.dart';

final class _$PaymentUpdateRepository implements PaymentUpdateRepository {
  const _$PaymentUpdateRepository(this._db);

  final DatabaseExecutor _db;

  @override
  Future<Result<ExecResult, SqlxError>> capture(String id, String capturedAt) {
    return _db.execute(
      r'''
UPDATE payment_collections
SET status = 'captured', captured_at = ?
WHERE id = ? AND status = 'authorized'
''',
      [capturedAt, id],
    );
  }

  @override
  Future<Result<ExecResult, SqlxError>> completeOrder(String orderId) {
    return _db.execute(
      r'''
UPDATE orders
SET payment_status = 'captured', status = 'completed'
WHERE id = ? AND status != 'cancelled'
''',
      [orderId],
    );
  }
}
