// GENERATED CODE - DO NOT MODIFY BY HAND
// coverage:ignore-file
// ignore_for_file: type=lint
// ignore_for_file: unused_element, unused_import, deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: use_function_type_syntax_for_parameters
// ignore_for_file: unnecessary_const, avoid_init_to_null
// ignore_for_file: invalid_override_different_default_values_named
// ignore_for_file: prefer_expression_function_bodies
// ignore_for_file: annotate_overrides, invalid_annotation_target
// ignore_for_file: unnecessary_question_mark
// Generated by dust.

part of 'admin_order_detail.dart';

const DeepCollectionEquality _adminOrderDetailItemsEquality = DeepCollectionEquality();

mixin _$AdminOrderDetail implements Serializable {
  @override
  String toString() {
    final self = this as AdminOrderDetail;
    return 'AdminOrderDetail('
        'billingAddress: ${self.billingAddress}, '
        'createdAt: ${self.createdAt}, '
        'currencyCode: ${self.currencyCode}, '
        'customerName: ${self.customerName}, '
        'discountTotal: ${self.discountTotal}, '
        'displayId: ${self.displayId}, '
        'email: ${self.email}, '
        'fulfillmentStatus: ${self.fulfillmentStatus}, '
        'id: ${self.id}, '
        'items: ${self.items}, '
        'paymentAmount: ${self.paymentAmount}, '
        'paymentCapturedAt: ${self.paymentCapturedAt}, '
        'paymentCreatedAt: ${self.paymentCreatedAt}, '
        'paymentProvider: ${self.paymentProvider}, '
        'paymentRecordStatus: ${self.paymentRecordStatus}, '
        'paymentStatus: ${self.paymentStatus}, '
        'placedAt: ${self.placedAt}, '
        'promotionCode: ${self.promotionCode}, '
        'shippingAddress: ${self.shippingAddress}, '
        'shippingName: ${self.shippingName}, '
        'shippingTotal: ${self.shippingTotal}, '
        'status: ${self.status}, '
        'subtotal: ${self.subtotal}, '
        'tax: ${self.tax}, '
        'total: ${self.total}, '
        'updatedAt: ${self.updatedAt}'
        ')';
  }

  @override
  bool operator ==(Object other) {
    final self = this as AdminOrderDetail;
    return identical(this, other) ||
        other is AdminOrderDetail &&
            runtimeType == other.runtimeType &&
            other.billingAddress == self.billingAddress &&
            other.createdAt == self.createdAt &&
            other.currencyCode == self.currencyCode &&
            other.customerName == self.customerName &&
            other.discountTotal == self.discountTotal &&
            other.displayId == self.displayId &&
            other.email == self.email &&
            other.fulfillmentStatus == self.fulfillmentStatus &&
            other.id == self.id &&
            _adminOrderDetailItemsEquality.equals(other.items, self.items) &&
            other.paymentAmount == self.paymentAmount &&
            other.paymentCapturedAt == self.paymentCapturedAt &&
            other.paymentCreatedAt == self.paymentCreatedAt &&
            other.paymentProvider == self.paymentProvider &&
            other.paymentRecordStatus == self.paymentRecordStatus &&
            other.paymentStatus == self.paymentStatus &&
            other.placedAt == self.placedAt &&
            other.promotionCode == self.promotionCode &&
            other.shippingAddress == self.shippingAddress &&
            other.shippingName == self.shippingName &&
            other.shippingTotal == self.shippingTotal &&
            other.status == self.status &&
            other.subtotal == self.subtotal &&
            other.tax == self.tax &&
            other.total == self.total &&
            other.updatedAt == self.updatedAt;
  }

  @override
  int get hashCode {
    final self = this as AdminOrderDetail;
    return Object.hashAll([
      runtimeType,
      self.billingAddress,
      self.createdAt,
      self.currencyCode,
      self.customerName,
      self.discountTotal,
      self.displayId,
      self.email,
      self.fulfillmentStatus,
      self.id,
      _adminOrderDetailItemsEquality.hash(self.items),
      self.paymentAmount,
      self.paymentCapturedAt,
      self.paymentCreatedAt,
      self.paymentProvider,
      self.paymentRecordStatus,
      self.paymentStatus,
      self.placedAt,
      self.promotionCode,
      self.shippingAddress,
      self.shippingName,
      self.shippingTotal,
      self.status,
      self.subtotal,
      self.tax,
      self.total,
      self.updatedAt,
    ]);
  }

  Map<String, Object?> serialize() =>
      _$AdminOrderDetailSerialize(this as AdminOrderDetail);

  Map<String, Object?> toJson() => serialize();
}

final class $AdminOrderDetailSerializer implements Serializer<AdminOrderDetail, Map<String, Object?>> {
  const $AdminOrderDetailSerializer();

  @override
  Map<String, Object?> serialize(AdminOrderDetail value) => _$AdminOrderDetailSerialize(value);
}
final class $AdminOrderDetailDeserializer implements Deserializer<AdminOrderDetail, Map<String, Object?>> {
  const $AdminOrderDetailDeserializer();

  @override
  AdminOrderDetail deserialize(Map<String, Object?> json) => _$AdminOrderDetailDeserialize(json);
}

Map<String, Object?> _$AdminOrderDetailSerialize(AdminOrderDetail instance) {
  return <String, Object?>{
    'billing_address': JsonHelper.encodeWithCodec<Option<AdminOrderAddress>, Object?>(
      (AdminOptionalOrderAddressCodec()),
      instance.billingAddress,
    ),
    'created_at': instance.createdAt.toIso8601String(),
    'currency_code': instance.currencyCode,
    'customer_name': instance.customerName,
    'discount_total': instance.discountTotal,
    'display_id': instance.displayId,
    'email': instance.email,
    'fulfillment_status': JsonHelper.encodeWithCodec<AdminOrderFulfillmentStatus, Object?>(
      (AdminOrderFulfillmentStatusCodec()),
      instance.fulfillmentStatus,
    ),
    'id': instance.id,
    'items': instance.items
        .map((item) => item.toJson())
        .toList(),
    'payment_amount': JsonHelper.encodeWithCodec<Option<int>, Object?>(
      (AdminOptionalIntCodec()),
      instance.paymentAmount,
    ),
    'payment_captured_at': JsonHelper.encodeWithCodec<Option<DateTime>, Object?>(
      (AdminOptionalDateTimeCodec()),
      instance.paymentCapturedAt,
    ),
    'payment_created_at': JsonHelper.encodeWithCodec<Option<DateTime>, Object?>(
      (AdminOptionalDateTimeCodec()),
      instance.paymentCreatedAt,
    ),
    'payment_provider': JsonHelper.encodeWithCodec<Option<String>, Object?>(
      (AdminOptionalStringCodec()),
      instance.paymentProvider,
    ),
    'payment_record_status': JsonHelper.encodeWithCodec<Option<AdminOrderPaymentRecordStatus>, Object?>(
      (AdminOptionalPaymentRecordStatusCodec()),
      instance.paymentRecordStatus,
    ),
    'payment_status': JsonHelper.encodeWithCodec<AdminOrderPaymentStatus, Object?>(
      (AdminOrderPaymentStatusCodec()),
      instance.paymentStatus,
    ),
    'placed_at': instance.placedAt.toIso8601String(),
    'promotion_code': JsonHelper.encodeWithCodec<Option<String>, Object?>(
      (AdminOptionalStringCodec()),
      instance.promotionCode,
    ),
    'shipping_address': JsonHelper.encodeWithCodec<Option<AdminOrderAddress>, Object?>(
      (AdminOptionalOrderAddressCodec()),
      instance.shippingAddress,
    ),
    'shipping_name': JsonHelper.encodeWithCodec<Option<String>, Object?>(
      (AdminOptionalStringCodec()),
      instance.shippingName,
    ),
    'shipping_total': instance.shippingTotal,
    'status': JsonHelper.encodeWithCodec<AdminOrderStatus, Object?>(
      (AdminOrderStatusCodec()),
      instance.status,
    ),
    'subtotal': instance.subtotal,
    'tax': instance.tax,
    'total': instance.total,
    'updated_at': instance.updatedAt.toIso8601String(),
  };
}

Map<String, Object?> _$AdminOrderDetailToJson(AdminOrderDetail instance) =>
    _$AdminOrderDetailSerialize(instance);

// factory AdminOrderDetail.fromJson(Map<String, Object?> json) => _$AdminOrderDetailFromJson(json);
AdminOrderDetail _$AdminOrderDetailDeserialize(Map<String, Object?> json) {
  final billingAddressValue = JsonHelper.decodeWithCodec<Option<AdminOrderAddress>, Object?>(
    (AdminOptionalOrderAddressCodec()),
    json['billing_address'],
    'billing_address',
  );
  final createdAtValue = JsonHelper.asDateTime(
    json['created_at'],
    'created_at',
  );
  final currencyCodeValue = JsonHelper.as<String>(
    json['currency_code'],
    'currency_code',
    'String',
  );
  final customerNameValue = JsonHelper.as<String>(
    json['customer_name'],
    'customer_name',
    'String',
  );
  final discountTotalValue = JsonHelper.as<int>(
    json['discount_total'],
    'discount_total',
    'int',
  );
  final displayIdValue = JsonHelper.as<int>(
    json['display_id'],
    'display_id',
    'int',
  );
  final emailValue = JsonHelper.as<String>(json['email'], 'email', 'String');
  final fulfillmentStatusValue = JsonHelper.decodeWithCodec<AdminOrderFulfillmentStatus, Object?>(
    (AdminOrderFulfillmentStatusCodec()),
    json['fulfillment_status'],
    'fulfillment_status',
  );
  final idValue = JsonHelper.as<String>(json['id'], 'id', 'String');
  final itemsValue = JsonHelper.decodeList(json['items'], 'items',
      (item, itemKey) => AdminOrderItem.fromJson(JsonHelper.asMap(item, itemKey)));
  final paymentAmountValue = JsonHelper.decodeWithCodec<Option<int>, Object?>(
    (AdminOptionalIntCodec()),
    json['payment_amount'],
    'payment_amount',
  );
  final paymentCapturedAtValue = JsonHelper.decodeWithCodec<Option<DateTime>, Object?>(
    (AdminOptionalDateTimeCodec()),
    json['payment_captured_at'],
    'payment_captured_at',
  );
  final paymentCreatedAtValue = JsonHelper.decodeWithCodec<Option<DateTime>, Object?>(
    (AdminOptionalDateTimeCodec()),
    json['payment_created_at'],
    'payment_created_at',
  );
  final paymentProviderValue = JsonHelper.decodeWithCodec<Option<String>, Object?>(
    (AdminOptionalStringCodec()),
    json['payment_provider'],
    'payment_provider',
  );
  final paymentRecordStatusValue = JsonHelper.decodeWithCodec<Option<AdminOrderPaymentRecordStatus>, Object?>(
    (AdminOptionalPaymentRecordStatusCodec()),
    json['payment_record_status'],
    'payment_record_status',
  );
  final paymentStatusValue = JsonHelper.decodeWithCodec<AdminOrderPaymentStatus, Object?>(
    (AdminOrderPaymentStatusCodec()),
    json['payment_status'],
    'payment_status',
  );
  final placedAtValue = JsonHelper.asDateTime(json['placed_at'], 'placed_at');
  final promotionCodeValue = JsonHelper.decodeWithCodec<Option<String>, Object?>(
    (AdminOptionalStringCodec()),
    json['promotion_code'],
    'promotion_code',
  );
  final shippingAddressValue = JsonHelper.decodeWithCodec<Option<AdminOrderAddress>, Object?>(
    (AdminOptionalOrderAddressCodec()),
    json['shipping_address'],
    'shipping_address',
  );
  final shippingNameValue = JsonHelper.decodeWithCodec<Option<String>, Object?>(
    (AdminOptionalStringCodec()),
    json['shipping_name'],
    'shipping_name',
  );
  final shippingTotalValue = JsonHelper.as<int>(
    json['shipping_total'],
    'shipping_total',
    'int',
  );
  final statusValue = JsonHelper.decodeWithCodec<AdminOrderStatus, Object?>(
    (AdminOrderStatusCodec()),
    json['status'],
    'status',
  );
  final subtotalValue = JsonHelper.as<int>(json['subtotal'], 'subtotal', 'int');
  final taxValue = JsonHelper.as<int>(json['tax'], 'tax', 'int');
  final totalValue = JsonHelper.as<int>(json['total'], 'total', 'int');
  final updatedAtValue = JsonHelper.asDateTime(
    json['updated_at'],
    'updated_at',
  );

  return AdminOrderDetail(
    id: idValue,
    displayId: displayIdValue,
    email: emailValue,
    customerName: customerNameValue,
    currencyCode: currencyCodeValue,
    subtotal: subtotalValue,
    shippingTotal: shippingTotalValue,
    discountTotal: discountTotalValue,
    tax: taxValue,
    total: totalValue,
    status: statusValue,
    paymentStatus: paymentStatusValue,
    fulfillmentStatus: fulfillmentStatusValue,
    shippingName: shippingNameValue,
    promotionCode: promotionCodeValue,
    placedAt: placedAtValue,
    createdAt: createdAtValue,
    updatedAt: updatedAtValue,
    items: itemsValue,
    shippingAddress: shippingAddressValue,
    billingAddress: billingAddressValue,
    paymentProvider: paymentProviderValue,
    paymentAmount: paymentAmountValue,
    paymentRecordStatus: paymentRecordStatusValue,
    paymentCreatedAt: paymentCreatedAtValue,
    paymentCapturedAt: paymentCapturedAtValue,
  );
}

AdminOrderDetail _$AdminOrderDetailFromJson(Map<String, Object?> json) =>
    _$AdminOrderDetailDeserialize(json);
