// GENERATED CODE - DO NOT MODIFY BY HAND
// coverage:ignore-file
// ignore_for_file: type=lint
// ignore_for_file: unused_element, unused_import, deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: use_function_type_syntax_for_parameters
// ignore_for_file: unnecessary_const, avoid_init_to_null
// ignore_for_file: invalid_override_different_default_values_named
// ignore_for_file: prefer_expression_function_bodies
// ignore_for_file: annotate_overrides, invalid_annotation_target
// ignore_for_file: unnecessary_question_mark
// Generated by dust.

part of 'admin_product_deleted.dart';

mixin _$AdminProductDeleted implements Serializable {
  @override
  String toString() {
    final self = this as AdminProductDeleted;
    return 'AdminProductDeleted('
        'deleted: ${self.deleted}, '
        'id: ${self.id}, '
        'object: ${self.object}'
        ')';
  }

  @override
  bool operator ==(Object other) {
    final self = this as AdminProductDeleted;
    return identical(this, other) ||
        other is AdminProductDeleted &&
            runtimeType == other.runtimeType &&
            other.deleted == self.deleted &&
            other.id == self.id &&
            other.object == self.object;
  }

  @override
  int get hashCode {
    final self = this as AdminProductDeleted;
    return Object.hashAll([
      runtimeType,
      self.deleted,
      self.id,
      self.object,
    ]);
  }

  Map<String, Object?> serialize() =>
      _$AdminProductDeletedSerialize(this as AdminProductDeleted);

  Map<String, Object?> toJson() => serialize();
}

final class $AdminProductDeletedSerializer implements Serializer<AdminProductDeleted, Map<String, Object?>> {
  const $AdminProductDeletedSerializer();

  @override
  Map<String, Object?> serialize(AdminProductDeleted value) => _$AdminProductDeletedSerialize(value);
}
final class $AdminProductDeletedDeserializer implements Deserializer<AdminProductDeleted, Map<String, Object?>> {
  const $AdminProductDeletedDeserializer();

  @override
  AdminProductDeleted deserialize(Map<String, Object?> json) => _$AdminProductDeletedDeserialize(json);
}

Map<String, Object?> _$AdminProductDeletedSerialize(AdminProductDeleted instance) {
  return <String, Object?>{
    'deleted': instance.deleted,
    'id': instance.id,
    'object': instance.object,
  };
}

Map<String, Object?> _$AdminProductDeletedToJson(AdminProductDeleted instance) =>
    _$AdminProductDeletedSerialize(instance);

// factory AdminProductDeleted.fromJson(Map<String, Object?> json) => _$AdminProductDeletedFromJson(json);
AdminProductDeleted _$AdminProductDeletedDeserialize(Map<String, Object?> json) {
  final deletedValue = JsonHelper.as<bool>(json['deleted'], 'deleted', 'bool');
  final idValue = JsonHelper.as<String>(json['id'], 'id', 'String');
  final objectValue = JsonHelper.as<String>(json['object'], 'object', 'String');

  return AdminProductDeleted(
    id: idValue,
    object: objectValue,
    deleted: deletedValue,
  );
}

AdminProductDeleted _$AdminProductDeletedFromJson(Map<String, Object?> json) =>
    _$AdminProductDeletedDeserialize(json);
