// GENERATED CODE - DO NOT MODIFY BY HAND
// coverage:ignore-file
// ignore_for_file: type=lint
// ignore_for_file: unused_element, unused_import, deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: use_function_type_syntax_for_parameters
// ignore_for_file: unnecessary_const, avoid_init_to_null
// ignore_for_file: invalid_override_different_default_values_named
// ignore_for_file: prefer_expression_function_bodies
// ignore_for_file: annotate_overrides, invalid_annotation_target
// ignore_for_file: unnecessary_question_mark
// Generated by dust.

part of 'admin_customer_address_deleted.dart';

mixin _$AdminCustomerAddressDeleted implements Serializable {
  @override
  String toString() {
    final self = this as AdminCustomerAddressDeleted;
    return 'AdminCustomerAddressDeleted('
        'deleted: ${self.deleted}, '
        'id: ${self.id}, '
        'object: ${self.object}, '
        'parentValue: ${self.parentValue}'
        ')';
  }

  @override
  bool operator ==(Object other) {
    final self = this as AdminCustomerAddressDeleted;
    return identical(this, other) ||
        other is AdminCustomerAddressDeleted &&
            runtimeType == other.runtimeType &&
            other.deleted == self.deleted &&
            other.id == self.id &&
            other.object == self.object &&
            other.parentValue == self.parentValue;
  }

  @override
  int get hashCode {
    final self = this as AdminCustomerAddressDeleted;
    return Object.hashAll([
      runtimeType,
      self.deleted,
      self.id,
      self.object,
      self.parentValue,
    ]);
  }

  Map<String, Object?> serialize() =>
      _$AdminCustomerAddressDeletedSerialize(this as AdminCustomerAddressDeleted);

  Map<String, Object?> toJson() => serialize();
}

final class $AdminCustomerAddressDeletedSerializer implements Serializer<AdminCustomerAddressDeleted, Map<String, Object?>> {
  const $AdminCustomerAddressDeletedSerializer();

  @override
  Map<String, Object?> serialize(AdminCustomerAddressDeleted value) => _$AdminCustomerAddressDeletedSerialize(value);
}
final class $AdminCustomerAddressDeletedDeserializer implements Deserializer<AdminCustomerAddressDeleted, Map<String, Object?>> {
  const $AdminCustomerAddressDeletedDeserializer();

  @override
  AdminCustomerAddressDeleted deserialize(Map<String, Object?> json) => _$AdminCustomerAddressDeletedDeserialize(json);
}

Map<String, Object?> _$AdminCustomerAddressDeletedSerialize(AdminCustomerAddressDeleted instance) {
  return <String, Object?>{
    'deleted': instance.deleted,
    'id': instance.id,
    'object': instance.object,
    'parent': instance.parentValue == null
        ? null
        : (instance.parentValue!).toJson(),
  };
}

Map<String, Object?> _$AdminCustomerAddressDeletedToJson(AdminCustomerAddressDeleted instance) =>
    _$AdminCustomerAddressDeletedSerialize(instance);

// factory AdminCustomerAddressDeleted.fromJson(Map<String, Object?> json) => _$AdminCustomerAddressDeletedFromJson(json);
AdminCustomerAddressDeleted _$AdminCustomerAddressDeletedDeserialize(Map<String, Object?> json) {
  final deletedValue = JsonHelper.as<bool>(json['deleted'], 'deleted', 'bool');
  final idValue = JsonHelper.as<String>(json['id'], 'id', 'String');
  final objectValue = JsonHelper.as<String>(json['object'], 'object', 'String');
  final parentValueValue = json['parent'] == null
      ? null
      : AdminCustomerDetail.fromJson(JsonHelper.asMap(json['parent'], 'parent'));

  return AdminCustomerAddressDeleted(
    id: idValue,
    parentValue: parentValueValue,
    object: objectValue,
    deleted: deletedValue,
  );
}

AdminCustomerAddressDeleted _$AdminCustomerAddressDeletedFromJson(Map<String, Object?> json) =>
    _$AdminCustomerAddressDeletedDeserialize(json);
