// GENERATED CODE - DO NOT MODIFY BY HAND
// coverage:ignore-file
// ignore_for_file: type=lint
// ignore_for_file: unused_element, unused_import, deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: use_function_type_syntax_for_parameters
// ignore_for_file: unnecessary_const, avoid_init_to_null
// ignore_for_file: invalid_override_different_default_values_named
// ignore_for_file: prefer_expression_function_bodies
// ignore_for_file: annotate_overrides, invalid_annotation_target
// ignore_for_file: unnecessary_question_mark
// Generated by dust.

part of 'admin_customer_detail.dart';

const DeepCollectionEquality _adminCustomerDetailAddressesEquality = DeepCollectionEquality();

mixin _$AdminCustomerDetail implements Serializable {
  @override
  String toString() {
    final self = this as AdminCustomerDetail;
    return 'AdminCustomerDetail('
        'addresses: ${self.addresses}, '
        'companyNameValue: ${self.companyNameValue}, '
        'createdAt: ${self.createdAt}, '
        'emailValue: ${self.emailValue}, '
        'firstNameValue: ${self.firstNameValue}, '
        'hasAccount: ${self.hasAccount}, '
        'id: ${self.id}, '
        'lastNameValue: ${self.lastNameValue}, '
        'phoneValue: ${self.phoneValue}, '
        'updatedAt: ${self.updatedAt}'
        ')';
  }

  @override
  bool operator ==(Object other) {
    final self = this as AdminCustomerDetail;
    return identical(this, other) ||
        other is AdminCustomerDetail &&
            runtimeType == other.runtimeType &&
            _adminCustomerDetailAddressesEquality.equals(other.addresses, self.addresses) &&
            other.companyNameValue == self.companyNameValue &&
            other.createdAt == self.createdAt &&
            other.emailValue == self.emailValue &&
            other.firstNameValue == self.firstNameValue &&
            other.hasAccount == self.hasAccount &&
            other.id == self.id &&
            other.lastNameValue == self.lastNameValue &&
            other.phoneValue == self.phoneValue &&
            other.updatedAt == self.updatedAt;
  }

  @override
  int get hashCode {
    final self = this as AdminCustomerDetail;
    return Object.hashAll([
      runtimeType,
      _adminCustomerDetailAddressesEquality.hash(self.addresses),
      self.companyNameValue,
      self.createdAt,
      self.emailValue,
      self.firstNameValue,
      self.hasAccount,
      self.id,
      self.lastNameValue,
      self.phoneValue,
      self.updatedAt,
    ]);
  }

  Map<String, Object?> serialize() =>
      _$AdminCustomerDetailSerialize(this as AdminCustomerDetail);

  Map<String, Object?> toJson() => serialize();
}

final class $AdminCustomerDetailSerializer implements Serializer<AdminCustomerDetail, Map<String, Object?>> {
  const $AdminCustomerDetailSerializer();

  @override
  Map<String, Object?> serialize(AdminCustomerDetail value) => _$AdminCustomerDetailSerialize(value);
}
final class $AdminCustomerDetailDeserializer implements Deserializer<AdminCustomerDetail, Map<String, Object?>> {
  const $AdminCustomerDetailDeserializer();

  @override
  AdminCustomerDetail deserialize(Map<String, Object?> json) => _$AdminCustomerDetailDeserialize(json);
}

Map<String, Object?> _$AdminCustomerDetailSerialize(AdminCustomerDetail instance) {
  return <String, Object?>{
    'addresses': instance.addresses
        .map((item) => item.toJson())
        .toList(),
    'company_name': instance.companyNameValue,
    'created_at': instance.createdAt.toIso8601String(),
    'email': instance.emailValue,
    'first_name': instance.firstNameValue,
    'has_account': instance.hasAccount,
    'id': instance.id,
    'last_name': instance.lastNameValue,
    'phone': instance.phoneValue,
    'updated_at': instance.updatedAt.toIso8601String(),
  };
}

Map<String, Object?> _$AdminCustomerDetailToJson(AdminCustomerDetail instance) =>
    _$AdminCustomerDetailSerialize(instance);

// factory AdminCustomerDetail.fromJson(Map<String, Object?> json) => _$AdminCustomerDetailFromJson(json);
AdminCustomerDetail _$AdminCustomerDetailDeserialize(Map<String, Object?> json) {
  final addressesValue = JsonHelper.decodeList(json['addresses'], 'addresses',
      (item, itemKey) => AdminCustomerAddress.fromJson(JsonHelper.asMap(item, itemKey)));
  final companyNameValueValue = json['company_name'] == null
      ? null
      : JsonHelper.as<String>(json['company_name'], 'company_name', 'String');
  final createdAtValue = JsonHelper.asDateTime(
    json['created_at'],
    'created_at',
  );
  final emailValueValue = json['email'] == null
      ? null
      : JsonHelper.as<String>(json['email'], 'email', 'String');
  final firstNameValueValue = json['first_name'] == null
      ? null
      : JsonHelper.as<String>(json['first_name'], 'first_name', 'String');
  final hasAccountValue = JsonHelper.as<bool>(
    json['has_account'],
    'has_account',
    'bool',
  );
  final idValue = JsonHelper.as<String>(json['id'], 'id', 'String');
  final lastNameValueValue = json['last_name'] == null
      ? null
      : JsonHelper.as<String>(json['last_name'], 'last_name', 'String');
  final phoneValueValue = json['phone'] == null
      ? null
      : JsonHelper.as<String>(json['phone'], 'phone', 'String');
  final updatedAtValue = JsonHelper.asDateTime(
    json['updated_at'],
    'updated_at',
  );

  return AdminCustomerDetail(
    id: idValue,
    emailValue: emailValueValue,
    companyNameValue: companyNameValueValue,
    firstNameValue: firstNameValueValue,
    lastNameValue: lastNameValueValue,
    phoneValue: phoneValueValue,
    hasAccount: hasAccountValue,
    createdAt: createdAtValue,
    updatedAt: updatedAtValue,
    addresses: addressesValue,
  );
}

AdminCustomerDetail _$AdminCustomerDetailFromJson(Map<String, Object?> json) =>
    _$AdminCustomerDetailDeserialize(json);
