// GENERATED CODE - DO NOT MODIFY BY HAND
// coverage:ignore-file
// ignore_for_file: type=lint
// ignore_for_file: unused_element, unused_import, deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: use_function_type_syntax_for_parameters
// ignore_for_file: unnecessary_const, avoid_init_to_null
// ignore_for_file: invalid_override_different_default_values_named
// ignore_for_file: prefer_expression_function_bodies
// ignore_for_file: annotate_overrides, invalid_annotation_target
// ignore_for_file: unnecessary_question_mark
// Generated by dust.

part of 'admin_media.dart';

const DeepCollectionEquality _adminUploadedFileListFilesEquality = DeepCollectionEquality();

mixin _$AdminUploadedFile implements Serializable {
  @override
  String toString() {
    final self = this as AdminUploadedFile;
    return 'AdminUploadedFile('
        'filename: ${self.filename}, '
        'id: ${self.id}, '
        'mimeType: ${self.mimeType}, '
        'size: ${self.size}, '
        'url: ${self.url}'
        ')';
  }

  @override
  bool operator ==(Object other) {
    final self = this as AdminUploadedFile;
    return identical(this, other) ||
        other is AdminUploadedFile &&
            runtimeType == other.runtimeType &&
            other.filename == self.filename &&
            other.id == self.id &&
            other.mimeType == self.mimeType &&
            other.size == self.size &&
            other.url == self.url;
  }

  @override
  int get hashCode {
    final self = this as AdminUploadedFile;
    return Object.hashAll([
      runtimeType,
      self.filename,
      self.id,
      self.mimeType,
      self.size,
      self.url,
    ]);
  }

  Map<String, Object?> serialize() =>
      _$AdminUploadedFileSerialize(this as AdminUploadedFile);

  Map<String, Object?> toJson() => serialize();
}

mixin _$AdminUploadedFileList implements Serializable {
  @override
  String toString() {
    final self = this as AdminUploadedFileList;
    return 'AdminUploadedFileList('
        'files: ${self.files}'
        ')';
  }

  @override
  bool operator ==(Object other) {
    final self = this as AdminUploadedFileList;
    return identical(this, other) ||
        other is AdminUploadedFileList &&
            runtimeType == other.runtimeType &&
            _adminUploadedFileListFilesEquality.equals(other.files, self.files);
  }

  @override
  int get hashCode {
    final self = this as AdminUploadedFileList;
    return Object.hashAll([
      runtimeType,
      _adminUploadedFileListFilesEquality.hash(self.files),
    ]);
  }

  Map<String, Object?> serialize() =>
      _$AdminUploadedFileListSerialize(this as AdminUploadedFileList);

  Map<String, Object?> toJson() => serialize();
}

final class $AdminUploadedFileSerializer implements Serializer<AdminUploadedFile, Map<String, Object?>> {
  const $AdminUploadedFileSerializer();

  @override
  Map<String, Object?> serialize(AdminUploadedFile value) => _$AdminUploadedFileSerialize(value);
}
final class $AdminUploadedFileDeserializer implements Deserializer<AdminUploadedFile, Map<String, Object?>> {
  const $AdminUploadedFileDeserializer();

  @override
  AdminUploadedFile deserialize(Map<String, Object?> json) => _$AdminUploadedFileDeserialize(json);
}
final class $AdminUploadedFileListSerializer implements Serializer<AdminUploadedFileList, Map<String, Object?>> {
  const $AdminUploadedFileListSerializer();

  @override
  Map<String, Object?> serialize(AdminUploadedFileList value) => _$AdminUploadedFileListSerialize(value);
}
final class $AdminUploadedFileListDeserializer implements Deserializer<AdminUploadedFileList, Map<String, Object?>> {
  const $AdminUploadedFileListDeserializer();

  @override
  AdminUploadedFileList deserialize(Map<String, Object?> json) => _$AdminUploadedFileListDeserialize(json);
}

Map<String, Object?> _$AdminUploadedFileSerialize(AdminUploadedFile instance) {
  return <String, Object?>{
    'filename': instance.filename,
    'id': instance.id,
    'mime_type': instance.mimeType,
    'size': instance.size,
    'url': instance.url,
  };
}

Map<String, Object?> _$AdminUploadedFileToJson(AdminUploadedFile instance) =>
    _$AdminUploadedFileSerialize(instance);

// factory AdminUploadedFile.fromJson(Map<String, Object?> json) => _$AdminUploadedFileFromJson(json);
AdminUploadedFile _$AdminUploadedFileDeserialize(Map<String, Object?> json) {
  final filenameValue = JsonHelper.as<String>(
    json['filename'],
    'filename',
    'String',
  );
  final idValue = JsonHelper.as<String>(json['id'], 'id', 'String');
  final mimeTypeValue = JsonHelper.as<String>(
    json['mime_type'],
    'mime_type',
    'String',
  );
  final sizeValue = JsonHelper.as<int>(json['size'], 'size', 'int');
  final urlValue = JsonHelper.as<String>(json['url'], 'url', 'String');

  return AdminUploadedFile(
    id: idValue,
    url: urlValue,
    filename: filenameValue,
    mimeType: mimeTypeValue,
    size: sizeValue,
  );
}

AdminUploadedFile _$AdminUploadedFileFromJson(Map<String, Object?> json) =>
    _$AdminUploadedFileDeserialize(json);

Map<String, Object?> _$AdminUploadedFileListSerialize(AdminUploadedFileList instance) {
  return <String, Object?>{
    'files': instance.files
        .map((item) => _$AdminUploadedFileSerialize(item))
        .toList(),
  };
}

Map<String, Object?> _$AdminUploadedFileListToJson(AdminUploadedFileList instance) =>
    _$AdminUploadedFileListSerialize(instance);

// factory AdminUploadedFileList.fromJson(Map<String, Object?> json) => _$AdminUploadedFileListFromJson(json);
AdminUploadedFileList _$AdminUploadedFileListDeserialize(Map<String, Object?> json) {
  final filesValue = JsonHelper.decodeList(json['files'], 'files',
      (item, itemKey) => _$AdminUploadedFileDeserialize(JsonHelper.asMap(item, itemKey)));

  return AdminUploadedFileList(files: filesValue);
}

AdminUploadedFileList _$AdminUploadedFileListFromJson(Map<String, Object?> json) =>
    _$AdminUploadedFileListDeserialize(json);
