// GENERATED CODE - DO NOT MODIFY BY HAND
// coverage:ignore-file
// ignore_for_file: type=lint
// ignore_for_file: unused_element, unused_import, deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: use_function_type_syntax_for_parameters
// ignore_for_file: unnecessary_const, avoid_init_to_null
// ignore_for_file: invalid_override_different_default_values_named
// ignore_for_file: prefer_expression_function_bodies
// ignore_for_file: annotate_overrides, invalid_annotation_target
// ignore_for_file: unnecessary_question_mark
// Generated by dust.

part of 'admin_product_type.dart';

const DeepCollectionEquality _adminProductTypeListProductTypesEquality = DeepCollectionEquality();

mixin _$AdminCreateProductType implements Validatable, Serializable {
  @override
  String toString() {
    final self = this as AdminCreateProductType;
    return 'AdminCreateProductType('
        'value: ${self.value}'
        ')';
  }

  @override
  bool operator ==(Object other) {
    final self = this as AdminCreateProductType;
    return identical(this, other) ||
        other is AdminCreateProductType &&
            runtimeType == other.runtimeType &&
            other.value == self.value;
  }

  @override
  int get hashCode {
    final self = this as AdminCreateProductType;
    return Object.hashAll([
      runtimeType,
      self.value,
    ]);
  }

  /// Validates this `AdminCreateProductType`.
  ///
  /// Usage:
  /// ```dart
  /// final result = value.validate();
  /// if (result case Invalid(:final errors)) {
  ///   print(errors.first.message);
  /// }
  /// ```
  ValidationResult validate() {
    final self = this as AdminCreateProductType;
    final errors = <ValidationError>[];
    _AdminCreateProductTypeValidation._validateValue(self.value, errors);
    return errors.isEmpty ? const Valid() : Invalid(errors);
  }

  /// Throws [ValidationException] when this `AdminCreateProductType` is invalid.
  ///
  /// Usage:
  /// ```dart
  /// value.validateOrThrow();
  /// ```
  void validateOrThrow() {
    final result = validate();
    if (result case Invalid(errors: final errors)) {
      throw ValidationException(errors);
    }
  }

  Map<String, Object?> serialize() =>
      _$AdminCreateProductTypeSerialize(this as AdminCreateProductType);

  Map<String, Object?> toJson() => serialize();
}

mixin _$AdminUpdateProductType implements Validatable, Serializable {
  @override
  String toString() {
    final self = this as AdminUpdateProductType;
    return 'AdminUpdateProductType('
        'value: ${self.value}'
        ')';
  }

  @override
  bool operator ==(Object other) {
    final self = this as AdminUpdateProductType;
    return identical(this, other) ||
        other is AdminUpdateProductType &&
            runtimeType == other.runtimeType &&
            other.value == self.value;
  }

  @override
  int get hashCode {
    final self = this as AdminUpdateProductType;
    return Object.hashAll([
      runtimeType,
      self.value,
    ]);
  }

  /// Validates this `AdminUpdateProductType`.
  ///
  /// Usage:
  /// ```dart
  /// final result = value.validate();
  /// if (result case Invalid(:final errors)) {
  ///   print(errors.first.message);
  /// }
  /// ```
  ValidationResult validate() {
    final self = this as AdminUpdateProductType;
    final errors = <ValidationError>[];
    _AdminUpdateProductTypeValidation._validateValue(self.value, errors);
    return errors.isEmpty ? const Valid() : Invalid(errors);
  }

  /// Throws [ValidationException] when this `AdminUpdateProductType` is invalid.
  ///
  /// Usage:
  /// ```dart
  /// value.validateOrThrow();
  /// ```
  void validateOrThrow() {
    final result = validate();
    if (result case Invalid(errors: final errors)) {
      throw ValidationException(errors);
    }
  }

  Map<String, Object?> serialize() =>
      _$AdminUpdateProductTypeSerialize(this as AdminUpdateProductType);

  Map<String, Object?> toJson() => serialize();
}

mixin _$AdminProductType implements Serializable {
  @override
  String toString() {
    final self = this as AdminProductType;
    return 'AdminProductType('
        'createdAt: ${self.createdAt}, '
        'id: ${self.id}, '
        'updatedAt: ${self.updatedAt}, '
        'value: ${self.value}'
        ')';
  }

  @override
  bool operator ==(Object other) {
    final self = this as AdminProductType;
    return identical(this, other) ||
        other is AdminProductType &&
            runtimeType == other.runtimeType &&
            other.createdAt == self.createdAt &&
            other.id == self.id &&
            other.updatedAt == self.updatedAt &&
            other.value == self.value;
  }

  @override
  int get hashCode {
    final self = this as AdminProductType;
    return Object.hashAll([
      runtimeType,
      self.createdAt,
      self.id,
      self.updatedAt,
      self.value,
    ]);
  }

  Map<String, Object?> serialize() =>
      _$AdminProductTypeSerialize(this as AdminProductType);

  Map<String, Object?> toJson() => serialize();
}

mixin _$AdminProductTypeList implements Serializable {
  @override
  String toString() {
    final self = this as AdminProductTypeList;
    return 'AdminProductTypeList('
        'count: ${self.count}, '
        'limit: ${self.limit}, '
        'offset: ${self.offset}, '
        'productTypes: ${self.productTypes}'
        ')';
  }

  @override
  bool operator ==(Object other) {
    final self = this as AdminProductTypeList;
    return identical(this, other) ||
        other is AdminProductTypeList &&
            runtimeType == other.runtimeType &&
            other.count == self.count &&
            other.limit == self.limit &&
            other.offset == self.offset &&
            _adminProductTypeListProductTypesEquality.equals(other.productTypes, self.productTypes);
  }

  @override
  int get hashCode {
    final self = this as AdminProductTypeList;
    return Object.hashAll([
      runtimeType,
      self.count,
      self.limit,
      self.offset,
      _adminProductTypeListProductTypesEquality.hash(self.productTypes),
    ]);
  }

  Map<String, Object?> serialize() =>
      _$AdminProductTypeListSerialize(this as AdminProductTypeList);

  Map<String, Object?> toJson() => serialize();
}

extension _AdminCreateProductTypeValidation on AdminCreateProductType {
  static void _validateValue(String value, List<ValidationError> errors) {
    if (value.length < 1) {
      errors.add(ValidationError(field: 'value', message: 'Enter a product type'));
    }
    if (value.length > 255) {
      errors.add(ValidationError(field: 'value', message: 'Enter a product type'));
    }
    if (!RegExp('.*\\S.*').hasMatch(value)) {
      errors.add(ValidationError(field: 'value', message: 'Enter a product type'));
    }
  }

}
extension _AdminUpdateProductTypeValidation on AdminUpdateProductType {
  static void _validateValue(String value, List<ValidationError> errors) {
    if (value.length < 1) {
      errors.add(ValidationError(field: 'value', message: 'Enter a product type'));
    }
    if (value.length > 255) {
      errors.add(ValidationError(field: 'value', message: 'Enter a product type'));
    }
    if (!RegExp('.*\\S.*').hasMatch(value)) {
      errors.add(ValidationError(field: 'value', message: 'Enter a product type'));
    }
  }

}
final class $AdminCreateProductTypeSerializer implements Serializer<AdminCreateProductType, Map<String, Object?>> {
  const $AdminCreateProductTypeSerializer();

  @override
  Map<String, Object?> serialize(AdminCreateProductType value) => _$AdminCreateProductTypeSerialize(value);
}
final class $AdminCreateProductTypeDeserializer implements Deserializer<AdminCreateProductType, Map<String, Object?>> {
  const $AdminCreateProductTypeDeserializer();

  @override
  AdminCreateProductType deserialize(Map<String, Object?> json) => _$AdminCreateProductTypeDeserialize(json);
}
final class $AdminUpdateProductTypeSerializer implements Serializer<AdminUpdateProductType, Map<String, Object?>> {
  const $AdminUpdateProductTypeSerializer();

  @override
  Map<String, Object?> serialize(AdminUpdateProductType value) => _$AdminUpdateProductTypeSerialize(value);
}
final class $AdminUpdateProductTypeDeserializer implements Deserializer<AdminUpdateProductType, Map<String, Object?>> {
  const $AdminUpdateProductTypeDeserializer();

  @override
  AdminUpdateProductType deserialize(Map<String, Object?> json) => _$AdminUpdateProductTypeDeserialize(json);
}
final class $AdminProductTypeSerializer implements Serializer<AdminProductType, Map<String, Object?>> {
  const $AdminProductTypeSerializer();

  @override
  Map<String, Object?> serialize(AdminProductType value) => _$AdminProductTypeSerialize(value);
}
final class $AdminProductTypeDeserializer implements Deserializer<AdminProductType, Map<String, Object?>> {
  const $AdminProductTypeDeserializer();

  @override
  AdminProductType deserialize(Map<String, Object?> json) => _$AdminProductTypeDeserialize(json);
}
final class $AdminProductTypeListSerializer implements Serializer<AdminProductTypeList, Map<String, Object?>> {
  const $AdminProductTypeListSerializer();

  @override
  Map<String, Object?> serialize(AdminProductTypeList value) => _$AdminProductTypeListSerialize(value);
}
final class $AdminProductTypeListDeserializer implements Deserializer<AdminProductTypeList, Map<String, Object?>> {
  const $AdminProductTypeListDeserializer();

  @override
  AdminProductTypeList deserialize(Map<String, Object?> json) => _$AdminProductTypeListDeserialize(json);
}

Map<String, Object?> _$AdminCreateProductTypeSerialize(AdminCreateProductType instance) {
  return <String, Object?>{
    'value': instance.value,
  };
}

Map<String, Object?> _$AdminCreateProductTypeToJson(AdminCreateProductType instance) =>
    _$AdminCreateProductTypeSerialize(instance);

// factory AdminCreateProductType.fromJson(Map<String, Object?> json) => _$AdminCreateProductTypeFromJson(json);
AdminCreateProductType _$AdminCreateProductTypeDeserialize(Map<String, Object?> json) {
  final valueValue = JsonHelper.as<String>(json['value'], 'value', 'String');

  return AdminCreateProductType(value: valueValue);
}

AdminCreateProductType _$AdminCreateProductTypeFromJson(Map<String, Object?> json) =>
    _$AdminCreateProductTypeDeserialize(json);

Map<String, Object?> _$AdminUpdateProductTypeSerialize(AdminUpdateProductType instance) {
  return <String, Object?>{
    'value': instance.value,
  };
}

Map<String, Object?> _$AdminUpdateProductTypeToJson(AdminUpdateProductType instance) =>
    _$AdminUpdateProductTypeSerialize(instance);

// factory AdminUpdateProductType.fromJson(Map<String, Object?> json) => _$AdminUpdateProductTypeFromJson(json);
AdminUpdateProductType _$AdminUpdateProductTypeDeserialize(Map<String, Object?> json) {
  final valueValue = JsonHelper.as<String>(json['value'], 'value', 'String');

  return AdminUpdateProductType(value: valueValue);
}

AdminUpdateProductType _$AdminUpdateProductTypeFromJson(Map<String, Object?> json) =>
    _$AdminUpdateProductTypeDeserialize(json);

Map<String, Object?> _$AdminProductTypeSerialize(AdminProductType instance) {
  return <String, Object?>{
    'created_at': instance.createdAt.toIso8601String(),
    'id': instance.id,
    'updated_at': instance.updatedAt.toIso8601String(),
    'value': instance.value,
  };
}

Map<String, Object?> _$AdminProductTypeToJson(AdminProductType instance) =>
    _$AdminProductTypeSerialize(instance);

// factory AdminProductType.fromJson(Map<String, Object?> json) => _$AdminProductTypeFromJson(json);
AdminProductType _$AdminProductTypeDeserialize(Map<String, Object?> json) {
  final createdAtValue = JsonHelper.asDateTime(
    json['created_at'],
    'created_at',
  );
  final idValue = JsonHelper.as<String>(json['id'], 'id', 'String');
  final updatedAtValue = JsonHelper.asDateTime(
    json['updated_at'],
    'updated_at',
  );
  final valueValue = JsonHelper.as<String>(json['value'], 'value', 'String');

  return AdminProductType(
    id: idValue,
    value: valueValue,
    createdAt: createdAtValue,
    updatedAt: updatedAtValue,
  );
}

AdminProductType _$AdminProductTypeFromJson(Map<String, Object?> json) =>
    _$AdminProductTypeDeserialize(json);

Map<String, Object?> _$AdminProductTypeListSerialize(AdminProductTypeList instance) {
  return <String, Object?>{
    'count': instance.count,
    'limit': instance.limit,
    'offset': instance.offset,
    'product_types': instance.productTypes
        .map((item) => _$AdminProductTypeSerialize(item))
        .toList(),
  };
}

Map<String, Object?> _$AdminProductTypeListToJson(AdminProductTypeList instance) =>
    _$AdminProductTypeListSerialize(instance);

// factory AdminProductTypeList.fromJson(Map<String, Object?> json) => _$AdminProductTypeListFromJson(json);
AdminProductTypeList _$AdminProductTypeListDeserialize(Map<String, Object?> json) {
  final countValue = JsonHelper.as<int>(json['count'], 'count', 'int');
  final limitValue = JsonHelper.as<int>(json['limit'], 'limit', 'int');
  final offsetValue = JsonHelper.as<int>(json['offset'], 'offset', 'int');
  final productTypesValue = JsonHelper.decodeList(json['product_types'], 'product_types',
      (item, itemKey) => _$AdminProductTypeDeserialize(JsonHelper.asMap(item, itemKey)));

  return AdminProductTypeList(
    productTypes: productTypesValue,
    count: countValue,
    limit: limitValue,
    offset: offsetValue,
  );
}

AdminProductTypeList _$AdminProductTypeListFromJson(Map<String, Object?> json) =>
    _$AdminProductTypeListDeserialize(json);
