// GENERATED CODE - DO NOT MODIFY BY HAND
// coverage:ignore-file
// ignore_for_file: type=lint
// ignore_for_file: unused_element, unused_import, deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: use_function_type_syntax_for_parameters
// ignore_for_file: unnecessary_const, avoid_init_to_null
// ignore_for_file: invalid_override_different_default_values_named
// ignore_for_file: prefer_expression_function_bodies
// ignore_for_file: annotate_overrides, invalid_annotation_target
// ignore_for_file: unnecessary_question_mark
// Generated by dust.

part of 'admin_order_fulfillment.dart';

const DeepCollectionEquality _adminOrderFulfillmentDataValueEquality = DeepCollectionEquality();
const DeepCollectionEquality _adminOrderFulfillmentItemsEquality = DeepCollectionEquality();
const DeepCollectionEquality _adminOrderFulfillmentMetadataValueEquality = DeepCollectionEquality();

mixin _$AdminOrderFulfillment implements Serializable {
  @override
  String toString() {
    final self = this as AdminOrderFulfillment;
    return 'AdminOrderFulfillment('
        'canceledAtValue: ${self.canceledAtValue}, '
        'createdAt: ${self.createdAt}, '
        'createdByValue: ${self.createdByValue}, '
        'dataValue: ${self.dataValue}, '
        'deliveredAtValue: ${self.deliveredAtValue}, '
        'id: ${self.id}, '
        'items: ${self.items}, '
        'locationId: ${self.locationId}, '
        'markedShippedByValue: ${self.markedShippedByValue}, '
        'metadataValue: ${self.metadataValue}, '
        'packedAtValue: ${self.packedAtValue}, '
        'providerId: ${self.providerId}, '
        'requiresShipping: ${self.requiresShipping}, '
        'shippedAtValue: ${self.shippedAtValue}, '
        'shippingOptionIdValue: ${self.shippingOptionIdValue}, '
        'updatedAt: ${self.updatedAt}'
        ')';
  }

  @override
  bool operator ==(Object other) {
    final self = this as AdminOrderFulfillment;
    return identical(this, other) ||
        other is AdminOrderFulfillment &&
            runtimeType == other.runtimeType &&
            other.canceledAtValue == self.canceledAtValue &&
            other.createdAt == self.createdAt &&
            other.createdByValue == self.createdByValue &&
            _adminOrderFulfillmentDataValueEquality.equals(other.dataValue, self.dataValue) &&
            other.deliveredAtValue == self.deliveredAtValue &&
            other.id == self.id &&
            _adminOrderFulfillmentItemsEquality.equals(other.items, self.items) &&
            other.locationId == self.locationId &&
            other.markedShippedByValue == self.markedShippedByValue &&
            _adminOrderFulfillmentMetadataValueEquality.equals(other.metadataValue, self.metadataValue) &&
            other.packedAtValue == self.packedAtValue &&
            other.providerId == self.providerId &&
            other.requiresShipping == self.requiresShipping &&
            other.shippedAtValue == self.shippedAtValue &&
            other.shippingOptionIdValue == self.shippingOptionIdValue &&
            other.updatedAt == self.updatedAt;
  }

  @override
  int get hashCode {
    final self = this as AdminOrderFulfillment;
    return Object.hashAll([
      runtimeType,
      self.canceledAtValue,
      self.createdAt,
      self.createdByValue,
      _adminOrderFulfillmentDataValueEquality.hash(self.dataValue),
      self.deliveredAtValue,
      self.id,
      _adminOrderFulfillmentItemsEquality.hash(self.items),
      self.locationId,
      self.markedShippedByValue,
      _adminOrderFulfillmentMetadataValueEquality.hash(self.metadataValue),
      self.packedAtValue,
      self.providerId,
      self.requiresShipping,
      self.shippedAtValue,
      self.shippingOptionIdValue,
      self.updatedAt,
    ]);
  }

  Map<String, Object?> serialize() =>
      _$AdminOrderFulfillmentSerialize(this as AdminOrderFulfillment);

  Map<String, Object?> toJson() => serialize();
}

final class $AdminOrderFulfillmentSerializer implements Serializer<AdminOrderFulfillment, Map<String, Object?>> {
  const $AdminOrderFulfillmentSerializer();

  @override
  Map<String, Object?> serialize(AdminOrderFulfillment value) => _$AdminOrderFulfillmentSerialize(value);
}
final class $AdminOrderFulfillmentDeserializer implements Deserializer<AdminOrderFulfillment, Map<String, Object?>> {
  const $AdminOrderFulfillmentDeserializer();

  @override
  AdminOrderFulfillment deserialize(Map<String, Object?> json) => _$AdminOrderFulfillmentDeserialize(json);
}

Map<String, Object?> _$AdminOrderFulfillmentSerialize(AdminOrderFulfillment instance) {
  return <String, Object?>{
    'canceled_at': instance.canceledAtValue == null
        ? null
        : (instance.canceledAtValue!).toIso8601String(),
    'created_at': instance.createdAt.toIso8601String(),
    'created_by': instance.createdByValue,
    'data': instance.dataValue == null
        ? null
        : (instance.dataValue!)
        .map((key, value) => MapEntry(key, value)),
    'delivered_at': instance.deliveredAtValue == null
        ? null
        : (instance.deliveredAtValue!).toIso8601String(),
    'id': instance.id,
    'items': instance.items
        .map((item) => item.toJson())
        .toList(),
    'location_id': instance.locationId,
    'marked_shipped_by': instance.markedShippedByValue,
    'metadata': instance.metadataValue == null
        ? null
        : (instance.metadataValue!)
        .map((key, value) => MapEntry(key, value)),
    'packed_at': instance.packedAtValue == null
        ? null
        : (instance.packedAtValue!).toIso8601String(),
    'provider_id': instance.providerId,
    'requires_shipping': instance.requiresShipping,
    'shipped_at': instance.shippedAtValue == null
        ? null
        : (instance.shippedAtValue!).toIso8601String(),
    'shipping_option_id': instance.shippingOptionIdValue,
    'updated_at': instance.updatedAt.toIso8601String(),
  };
}

Map<String, Object?> _$AdminOrderFulfillmentToJson(AdminOrderFulfillment instance) =>
    _$AdminOrderFulfillmentSerialize(instance);

// factory AdminOrderFulfillment.fromJson(Map<String, Object?> json) => _$AdminOrderFulfillmentFromJson(json);
AdminOrderFulfillment _$AdminOrderFulfillmentDeserialize(Map<String, Object?> json) {
  final canceledAtValueValue = json['canceled_at'] == null
      ? null
      : JsonHelper.asDateTime(json['canceled_at'], 'canceled_at');
  final createdAtValue = JsonHelper.asDateTime(
    json['created_at'],
    'created_at',
  );
  final createdByValueValue = json['created_by'] == null
      ? null
      : JsonHelper.as<String>(json['created_by'], 'created_by', 'String');
  final dataValueValue = json['data'] == null
      ? null
      : JsonHelper.decodeMap(json['data'], 'data',
      (value, valueKey) =>
          value == null
              ? null
              : JsonHelper.as<Object>(value, valueKey, 'Object'));
  final deliveredAtValueValue = json['delivered_at'] == null
      ? null
      : JsonHelper.asDateTime(json['delivered_at'], 'delivered_at');
  final idValue = JsonHelper.as<String>(json['id'], 'id', 'String');
  final itemsValue = JsonHelper.decodeList(json['items'], 'items',
      (item, itemKey) => AdminFulfillmentItem.fromJson(JsonHelper.asMap(item, itemKey)));
  final locationIdValue = JsonHelper.as<String>(
    json['location_id'],
    'location_id',
    'String',
  );
  final markedShippedByValueValue = json['marked_shipped_by'] == null
      ? null
      : JsonHelper.as<String>(json['marked_shipped_by'], 'marked_shipped_by', 'String');
  final metadataValueValue = json['metadata'] == null
      ? null
      : JsonHelper.decodeMap(json['metadata'], 'metadata',
      (value, valueKey) =>
          value == null
              ? null
              : JsonHelper.as<Object>(value, valueKey, 'Object'));
  final packedAtValueValue = json['packed_at'] == null
      ? null
      : JsonHelper.asDateTime(json['packed_at'], 'packed_at');
  final providerIdValue = JsonHelper.as<String>(
    json['provider_id'],
    'provider_id',
    'String',
  );
  final requiresShippingValue = JsonHelper.as<bool>(
    json['requires_shipping'],
    'requires_shipping',
    'bool',
  );
  final shippedAtValueValue = json['shipped_at'] == null
      ? null
      : JsonHelper.asDateTime(json['shipped_at'], 'shipped_at');
  final shippingOptionIdValueValue = json['shipping_option_id'] == null
      ? null
      : JsonHelper.as<String>(json['shipping_option_id'], 'shipping_option_id', 'String');
  final updatedAtValue = JsonHelper.asDateTime(
    json['updated_at'],
    'updated_at',
  );

  return AdminOrderFulfillment(
    id: idValue,
    locationId: locationIdValue,
    providerId: providerIdValue,
    shippingOptionIdValue: shippingOptionIdValueValue,
    requiresShipping: requiresShippingValue,
    packedAtValue: packedAtValueValue,
    shippedAtValue: shippedAtValueValue,
    deliveredAtValue: deliveredAtValueValue,
    canceledAtValue: canceledAtValueValue,
    dataValue: dataValueValue,
    metadataValue: metadataValueValue,
    createdByValue: createdByValueValue,
    markedShippedByValue: markedShippedByValueValue,
    createdAt: createdAtValue,
    updatedAt: updatedAtValue,
    items: itemsValue,
  );
}

AdminOrderFulfillment _$AdminOrderFulfillmentFromJson(Map<String, Object?> json) =>
    _$AdminOrderFulfillmentDeserialize(json);
