import 'package:dust_dart/serde.dart';

part 'admin_media.g.dart';

/// One image persisted by the protected merchant upload boundary.
@Derive([ToString(), Eq(), Serialize(), Deserialize()])
@SerDe(renameAll: SerDeRename.snakeCase)
final class AdminUploadedFile with _$AdminUploadedFile {
  /// Creates an allowlisted upload response.
  const AdminUploadedFile({
    required this.id,
    required this.url,
    required this.filename,
    required this.mimeType,
    required this.size,
  });

  /// Decodes the generated upload response.
  factory AdminUploadedFile.fromJson(Map<String, Object?> json) =>
      _$AdminUploadedFileFromJson(json);

  /// Sanitized original name displayed back to the merchant.
  final String filename;

  /// Opaque storage key generated by the server.
  final String id;

  /// Content type proven from the file signature, not the request header.
  final String mimeType;

  /// Exact number of stored bytes.
  final int size;

  /// Public immutable asset URL accepted by product mutation APIs.
  final String url;
}

/// Files returned by one Medusa-shaped multipart upload request.
@Derive([ToString(), Eq(), Serialize(), Deserialize()])
@SerDe(renameAll: SerDeRename.snakeCase)
final class AdminUploadedFileList with _$AdminUploadedFileList {
  /// Creates a typed upload response.
  const AdminUploadedFileList({required this.files});

  /// Decodes the generated upload response.
  factory AdminUploadedFileList.fromJson(Map<String, Object?> json) =>
      _$AdminUploadedFileListFromJson(json);

  /// Successfully persisted files in multipart order.
  final List<AdminUploadedFile> files;
}
