// GENERATED CODE - DO NOT MODIFY BY HAND
// coverage:ignore-file
// ignore_for_file: type=lint
// ignore_for_file: unused_element, unused_import, deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: use_function_type_syntax_for_parameters
// ignore_for_file: unnecessary_const, avoid_init_to_null
// ignore_for_file: invalid_override_different_default_values_named
// ignore_for_file: prefer_expression_function_bodies
// ignore_for_file: annotate_overrides, invalid_annotation_target
// ignore_for_file: unnecessary_question_mark
// Generated by dust.

part of 'admin_product_media.dart';

mixin _$AdminCreateProductMedia implements Validatable, Serializable {
  @override
  String toString() {
    final self = this as AdminCreateProductMedia;
    return 'AdminCreateProductMedia('
        'id: ${self.id}, '
        'isThumbnail: ${self.isThumbnail}, '
        'url: ${self.url}'
        ')';
  }

  @override
  bool operator ==(Object other) {
    final self = this as AdminCreateProductMedia;
    return identical(this, other) ||
        other is AdminCreateProductMedia &&
            runtimeType == other.runtimeType &&
            other.id == self.id &&
            other.isThumbnail == self.isThumbnail &&
            other.url == self.url;
  }

  @override
  int get hashCode {
    final self = this as AdminCreateProductMedia;
    return Object.hashAll([
      runtimeType,
      self.id,
      self.isThumbnail,
      self.url,
    ]);
  }

  /// Validates this `AdminCreateProductMedia`.
  ///
  /// Usage:
  /// ```dart
  /// final result = value.validate();
  /// if (result case Invalid(:final errors)) {
  ///   print(errors.first.message);
  /// }
  /// ```
  ValidationResult validate() {
    final self = this as AdminCreateProductMedia;
    final errors = <ValidationError>[];
    _AdminCreateProductMediaValidation._validateId(self.id, errors);
    _AdminCreateProductMediaValidation._validateUrl(self.url, errors);
    return errors.isEmpty ? const Valid() : Invalid(errors);
  }

  /// Throws [ValidationException] when this `AdminCreateProductMedia` is invalid.
  ///
  /// Usage:
  /// ```dart
  /// value.validateOrThrow();
  /// ```
  void validateOrThrow() {
    final result = validate();
    if (result case Invalid(errors: final errors)) {
      throw ValidationException(errors);
    }
  }

  Map<String, Object?> serialize() =>
      _$AdminCreateProductMediaSerialize(this as AdminCreateProductMedia);

  Map<String, Object?> toJson() => serialize();
}

extension _AdminCreateProductMediaValidation on AdminCreateProductMedia {
  static void _validateId(String id, List<ValidationError> errors) {
    if (id.length < 1) {
      errors.add(ValidationError(field: 'id', message: 'Choose an image'));
    }
    if (id.length > 255) {
      errors.add(ValidationError(field: 'id', message: 'Choose an image'));
    }
  }

  static void _validateUrl(String url, List<ValidationError> errors) {
    if (url.length < 1) {
      errors.add(ValidationError(field: 'url', message: 'Choose an image'));
    }
    if (url.length > 2048) {
      errors.add(ValidationError(field: 'url', message: 'Choose an image'));
    }
  }

}
final class $AdminCreateProductMediaSerializer implements Serializer<AdminCreateProductMedia, Map<String, Object?>> {
  const $AdminCreateProductMediaSerializer();

  @override
  Map<String, Object?> serialize(AdminCreateProductMedia value) => _$AdminCreateProductMediaSerialize(value);
}
final class $AdminCreateProductMediaDeserializer implements Deserializer<AdminCreateProductMedia, Map<String, Object?>> {
  const $AdminCreateProductMediaDeserializer();

  @override
  AdminCreateProductMedia deserialize(Map<String, Object?> json) => _$AdminCreateProductMediaDeserialize(json);
}

Map<String, Object?> _$AdminCreateProductMediaSerialize(AdminCreateProductMedia instance) {
  return <String, Object?>{
    'id': instance.id,
    'is_thumbnail': instance.isThumbnail,
    'url': instance.url,
  };
}

Map<String, Object?> _$AdminCreateProductMediaToJson(AdminCreateProductMedia instance) =>
    _$AdminCreateProductMediaSerialize(instance);

// factory AdminCreateProductMedia.fromJson(Map<String, Object?> json) => _$AdminCreateProductMediaFromJson(json);
AdminCreateProductMedia _$AdminCreateProductMediaDeserialize(Map<String, Object?> json) {
  final idValue = JsonHelper.as<String>(json['id'], 'id', 'String');
  final isThumbnailValue = JsonHelper.as<bool>(
    json['is_thumbnail'],
    'is_thumbnail',
    'bool',
  );
  final urlValue = JsonHelper.as<String>(json['url'], 'url', 'String');

  return AdminCreateProductMedia(
    id: idValue,
    url: urlValue,
    isThumbnail: isThumbnailValue,
  );
}

AdminCreateProductMedia _$AdminCreateProductMediaFromJson(Map<String, Object?> json) =>
    _$AdminCreateProductMediaDeserialize(json);
