// GENERATED CODE - DO NOT MODIFY BY HAND
// coverage:ignore-file
// ignore_for_file: type=lint
// ignore_for_file: unused_element, unused_import, deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: use_function_type_syntax_for_parameters
// ignore_for_file: unnecessary_const, avoid_init_to_null
// ignore_for_file: invalid_override_different_default_values_named
// ignore_for_file: prefer_expression_function_bodies
// ignore_for_file: annotate_overrides, invalid_annotation_target
// ignore_for_file: unnecessary_question_mark
// Generated by dust.

part of 'admin_customer_group_deleted.dart';

mixin _$AdminCustomerGroupDeleted implements Serializable {
  @override
  String toString() {
    final self = this as AdminCustomerGroupDeleted;
    return 'AdminCustomerGroupDeleted('
        'deleted: ${self.deleted}, '
        'id: ${self.id}, '
        'object: ${self.object}'
        ')';
  }

  @override
  bool operator ==(Object other) {
    final self = this as AdminCustomerGroupDeleted;
    return identical(this, other) ||
        other is AdminCustomerGroupDeleted &&
            runtimeType == other.runtimeType &&
            other.deleted == self.deleted &&
            other.id == self.id &&
            other.object == self.object;
  }

  @override
  int get hashCode {
    final self = this as AdminCustomerGroupDeleted;
    return Object.hashAll([
      runtimeType,
      self.deleted,
      self.id,
      self.object,
    ]);
  }

  Map<String, Object?> serialize() =>
      _$AdminCustomerGroupDeletedSerialize(this as AdminCustomerGroupDeleted);

  Map<String, Object?> toJson() => serialize();
}

final class $AdminCustomerGroupDeletedSerializer implements Serializer<AdminCustomerGroupDeleted, Map<String, Object?>> {
  const $AdminCustomerGroupDeletedSerializer();

  @override
  Map<String, Object?> serialize(AdminCustomerGroupDeleted value) => _$AdminCustomerGroupDeletedSerialize(value);
}
final class $AdminCustomerGroupDeletedDeserializer implements Deserializer<AdminCustomerGroupDeleted, Map<String, Object?>> {
  const $AdminCustomerGroupDeletedDeserializer();

  @override
  AdminCustomerGroupDeleted deserialize(Map<String, Object?> json) => _$AdminCustomerGroupDeletedDeserialize(json);
}

Map<String, Object?> _$AdminCustomerGroupDeletedSerialize(AdminCustomerGroupDeleted instance) {
  return <String, Object?>{
    'deleted': instance.deleted,
    'id': instance.id,
    'object': instance.object,
  };
}

Map<String, Object?> _$AdminCustomerGroupDeletedToJson(AdminCustomerGroupDeleted instance) =>
    _$AdminCustomerGroupDeletedSerialize(instance);

// factory AdminCustomerGroupDeleted.fromJson(Map<String, Object?> json) => _$AdminCustomerGroupDeletedFromJson(json);
AdminCustomerGroupDeleted _$AdminCustomerGroupDeletedDeserialize(Map<String, Object?> json) {
  final deletedValue = JsonHelper.as<bool>(json['deleted'], 'deleted', 'bool');
  final idValue = JsonHelper.as<String>(json['id'], 'id', 'String');
  final objectValue = JsonHelper.as<String>(json['object'], 'object', 'String');

  return AdminCustomerGroupDeleted(
    id: idValue,
    object: objectValue,
    deleted: deletedValue,
  );
}

AdminCustomerGroupDeleted _$AdminCustomerGroupDeletedFromJson(Map<String, Object?> json) =>
    _$AdminCustomerGroupDeletedDeserialize(json);
