// GENERATED CODE - DO NOT MODIFY BY HAND
// coverage:ignore-file
// ignore_for_file: type=lint
// ignore_for_file: unused_element, unused_import, deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: use_function_type_syntax_for_parameters
// ignore_for_file: unnecessary_const, avoid_init_to_null
// ignore_for_file: invalid_override_different_default_values_named
// ignore_for_file: prefer_expression_function_bodies
// ignore_for_file: annotate_overrides, invalid_annotation_target
// ignore_for_file: unnecessary_question_mark
// Generated by dust.

part of 'admin_customer_group.dart';

const DeepCollectionEquality _adminCustomerGroupCustomersEquality = DeepCollectionEquality();
const DeepCollectionEquality _adminCustomerGroupListCustomerGroupsEquality = DeepCollectionEquality();

mixin _$AdminCustomerGroupCustomer implements Serializable {
  @override
  String toString() {
    final self = this as AdminCustomerGroupCustomer;
    return 'AdminCustomerGroupCustomer('
        'id: ${self.id}'
        ')';
  }

  @override
  bool operator ==(Object other) {
    final self = this as AdminCustomerGroupCustomer;
    return identical(this, other) ||
        other is AdminCustomerGroupCustomer &&
            runtimeType == other.runtimeType &&
            other.id == self.id;
  }

  @override
  int get hashCode {
    final self = this as AdminCustomerGroupCustomer;
    return Object.hashAll([
      runtimeType,
      self.id,
    ]);
  }

  Map<String, Object?> serialize() =>
      _$AdminCustomerGroupCustomerSerialize(this as AdminCustomerGroupCustomer);

  Map<String, Object?> toJson() => serialize();
}

mixin _$AdminCustomerGroup implements Serializable {
  @override
  String toString() {
    final self = this as AdminCustomerGroup;
    return 'AdminCustomerGroup('
        'createdAt: ${self.createdAt}, '
        'customers: ${self.customers}, '
        'id: ${self.id}, '
        'name: ${self.name}, '
        'updatedAt: ${self.updatedAt}'
        ')';
  }

  @override
  bool operator ==(Object other) {
    final self = this as AdminCustomerGroup;
    return identical(this, other) ||
        other is AdminCustomerGroup &&
            runtimeType == other.runtimeType &&
            other.createdAt == self.createdAt &&
            _adminCustomerGroupCustomersEquality.equals(other.customers, self.customers) &&
            other.id == self.id &&
            other.name == self.name &&
            other.updatedAt == self.updatedAt;
  }

  @override
  int get hashCode {
    final self = this as AdminCustomerGroup;
    return Object.hashAll([
      runtimeType,
      self.createdAt,
      _adminCustomerGroupCustomersEquality.hash(self.customers),
      self.id,
      self.name,
      self.updatedAt,
    ]);
  }

  Map<String, Object?> serialize() =>
      _$AdminCustomerGroupSerialize(this as AdminCustomerGroup);

  Map<String, Object?> toJson() => serialize();
}

mixin _$AdminCustomerGroupList implements Serializable {
  @override
  String toString() {
    final self = this as AdminCustomerGroupList;
    return 'AdminCustomerGroupList('
        'count: ${self.count}, '
        'customerGroups: ${self.customerGroups}, '
        'limit: ${self.limit}, '
        'offset: ${self.offset}'
        ')';
  }

  @override
  bool operator ==(Object other) {
    final self = this as AdminCustomerGroupList;
    return identical(this, other) ||
        other is AdminCustomerGroupList &&
            runtimeType == other.runtimeType &&
            other.count == self.count &&
            _adminCustomerGroupListCustomerGroupsEquality.equals(other.customerGroups, self.customerGroups) &&
            other.limit == self.limit &&
            other.offset == self.offset;
  }

  @override
  int get hashCode {
    final self = this as AdminCustomerGroupList;
    return Object.hashAll([
      runtimeType,
      self.count,
      _adminCustomerGroupListCustomerGroupsEquality.hash(self.customerGroups),
      self.limit,
      self.offset,
    ]);
  }

  Map<String, Object?> serialize() =>
      _$AdminCustomerGroupListSerialize(this as AdminCustomerGroupList);

  Map<String, Object?> toJson() => serialize();
}

final class $AdminCustomerGroupCustomerSerializer implements Serializer<AdminCustomerGroupCustomer, Map<String, Object?>> {
  const $AdminCustomerGroupCustomerSerializer();

  @override
  Map<String, Object?> serialize(AdminCustomerGroupCustomer value) => _$AdminCustomerGroupCustomerSerialize(value);
}
final class $AdminCustomerGroupCustomerDeserializer implements Deserializer<AdminCustomerGroupCustomer, Map<String, Object?>> {
  const $AdminCustomerGroupCustomerDeserializer();

  @override
  AdminCustomerGroupCustomer deserialize(Map<String, Object?> json) => _$AdminCustomerGroupCustomerDeserialize(json);
}
final class $AdminCustomerGroupSerializer implements Serializer<AdminCustomerGroup, Map<String, Object?>> {
  const $AdminCustomerGroupSerializer();

  @override
  Map<String, Object?> serialize(AdminCustomerGroup value) => _$AdminCustomerGroupSerialize(value);
}
final class $AdminCustomerGroupDeserializer implements Deserializer<AdminCustomerGroup, Map<String, Object?>> {
  const $AdminCustomerGroupDeserializer();

  @override
  AdminCustomerGroup deserialize(Map<String, Object?> json) => _$AdminCustomerGroupDeserialize(json);
}
final class $AdminCustomerGroupListSerializer implements Serializer<AdminCustomerGroupList, Map<String, Object?>> {
  const $AdminCustomerGroupListSerializer();

  @override
  Map<String, Object?> serialize(AdminCustomerGroupList value) => _$AdminCustomerGroupListSerialize(value);
}
final class $AdminCustomerGroupListDeserializer implements Deserializer<AdminCustomerGroupList, Map<String, Object?>> {
  const $AdminCustomerGroupListDeserializer();

  @override
  AdminCustomerGroupList deserialize(Map<String, Object?> json) => _$AdminCustomerGroupListDeserialize(json);
}

Map<String, Object?> _$AdminCustomerGroupCustomerSerialize(AdminCustomerGroupCustomer instance) {
  return <String, Object?>{
    'id': instance.id,
  };
}

Map<String, Object?> _$AdminCustomerGroupCustomerToJson(AdminCustomerGroupCustomer instance) =>
    _$AdminCustomerGroupCustomerSerialize(instance);

// factory AdminCustomerGroupCustomer.fromJson(Map<String, Object?> json) => _$AdminCustomerGroupCustomerFromJson(json);
AdminCustomerGroupCustomer _$AdminCustomerGroupCustomerDeserialize(Map<String, Object?> json) {
  final idValue = JsonHelper.as<String>(json['id'], 'id', 'String');

  return AdminCustomerGroupCustomer(id: idValue);
}

AdminCustomerGroupCustomer _$AdminCustomerGroupCustomerFromJson(Map<String, Object?> json) =>
    _$AdminCustomerGroupCustomerDeserialize(json);

Map<String, Object?> _$AdminCustomerGroupSerialize(AdminCustomerGroup instance) {
  return <String, Object?>{
    'created_at': instance.createdAt.toIso8601String(),
    'customers': instance.customers
        .map((item) => _$AdminCustomerGroupCustomerSerialize(item))
        .toList(),
    'id': instance.id,
    'name': instance.name,
    'updated_at': instance.updatedAt.toIso8601String(),
  };
}

Map<String, Object?> _$AdminCustomerGroupToJson(AdminCustomerGroup instance) =>
    _$AdminCustomerGroupSerialize(instance);

// factory AdminCustomerGroup.fromJson(Map<String, Object?> json) => _$AdminCustomerGroupFromJson(json);
AdminCustomerGroup _$AdminCustomerGroupDeserialize(Map<String, Object?> json) {
  final createdAtValue = JsonHelper.asDateTime(
    json['created_at'],
    'created_at',
  );
  final customersValue = JsonHelper.decodeList(json['customers'], 'customers',
      (item, itemKey) => _$AdminCustomerGroupCustomerDeserialize(JsonHelper.asMap(item, itemKey)));
  final idValue = JsonHelper.as<String>(json['id'], 'id', 'String');
  final nameValue = JsonHelper.as<String>(json['name'], 'name', 'String');
  final updatedAtValue = JsonHelper.asDateTime(
    json['updated_at'],
    'updated_at',
  );

  return AdminCustomerGroup(
    id: idValue,
    name: nameValue,
    customers: customersValue,
    createdAt: createdAtValue,
    updatedAt: updatedAtValue,
  );
}

AdminCustomerGroup _$AdminCustomerGroupFromJson(Map<String, Object?> json) =>
    _$AdminCustomerGroupDeserialize(json);

Map<String, Object?> _$AdminCustomerGroupListSerialize(AdminCustomerGroupList instance) {
  return <String, Object?>{
    'count': instance.count,
    'customer_groups': instance.customerGroups
        .map((item) => _$AdminCustomerGroupSerialize(item))
        .toList(),
    'limit': instance.limit,
    'offset': instance.offset,
  };
}

Map<String, Object?> _$AdminCustomerGroupListToJson(AdminCustomerGroupList instance) =>
    _$AdminCustomerGroupListSerialize(instance);

// factory AdminCustomerGroupList.fromJson(Map<String, Object?> json) => _$AdminCustomerGroupListFromJson(json);
AdminCustomerGroupList _$AdminCustomerGroupListDeserialize(Map<String, Object?> json) {
  final countValue = JsonHelper.as<int>(json['count'], 'count', 'int');
  final customerGroupsValue = JsonHelper.decodeList(json['customer_groups'], 'customer_groups',
      (item, itemKey) => _$AdminCustomerGroupDeserialize(JsonHelper.asMap(item, itemKey)));
  final limitValue = JsonHelper.as<int>(json['limit'], 'limit', 'int');
  final offsetValue = JsonHelper.as<int>(json['offset'], 'offset', 'int');

  return AdminCustomerGroupList(
    customerGroups: customerGroupsValue,
    count: countValue,
    limit: limitValue,
    offset: offsetValue,
  );
}

AdminCustomerGroupList _$AdminCustomerGroupListFromJson(Map<String, Object?> json) =>
    _$AdminCustomerGroupListDeserialize(json);
