// GENERATED CODE - DO NOT MODIFY BY HAND
// coverage:ignore-file
// ignore_for_file: type=lint
// ignore_for_file: unused_element, unused_import, deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: use_function_type_syntax_for_parameters
// ignore_for_file: unnecessary_const, avoid_init_to_null
// ignore_for_file: invalid_override_different_default_values_named
// ignore_for_file: prefer_expression_function_bodies
// ignore_for_file: annotate_overrides, invalid_annotation_target
// ignore_for_file: unnecessary_question_mark
// Generated by dust.

part of 'admin_fulfillment_label.dart';

mixin _$AdminFulfillmentLabel implements Serializable {
  @override
  String toString() {
    final self = this as AdminFulfillmentLabel;
    return 'AdminFulfillmentLabel('
        'createdAt: ${self.createdAt}, '
        'fulfillmentId: ${self.fulfillmentId}, '
        'id: ${self.id}, '
        'labelUrl: ${self.labelUrl}, '
        'trackingNumber: ${self.trackingNumber}, '
        'trackingUrl: ${self.trackingUrl}, '
        'updatedAt: ${self.updatedAt}'
        ')';
  }

  @override
  bool operator ==(Object other) {
    final self = this as AdminFulfillmentLabel;
    return identical(this, other) ||
        other is AdminFulfillmentLabel &&
            runtimeType == other.runtimeType &&
            other.createdAt == self.createdAt &&
            other.fulfillmentId == self.fulfillmentId &&
            other.id == self.id &&
            other.labelUrl == self.labelUrl &&
            other.trackingNumber == self.trackingNumber &&
            other.trackingUrl == self.trackingUrl &&
            other.updatedAt == self.updatedAt;
  }

  @override
  int get hashCode {
    final self = this as AdminFulfillmentLabel;
    return Object.hashAll([
      runtimeType,
      self.createdAt,
      self.fulfillmentId,
      self.id,
      self.labelUrl,
      self.trackingNumber,
      self.trackingUrl,
      self.updatedAt,
    ]);
  }

  Map<String, Object?> serialize() =>
      _$AdminFulfillmentLabelSerialize(this as AdminFulfillmentLabel);

  Map<String, Object?> toJson() => serialize();
}

final class $AdminFulfillmentLabelSerializer implements Serializer<AdminFulfillmentLabel, Map<String, Object?>> {
  const $AdminFulfillmentLabelSerializer();

  @override
  Map<String, Object?> serialize(AdminFulfillmentLabel value) => _$AdminFulfillmentLabelSerialize(value);
}
final class $AdminFulfillmentLabelDeserializer implements Deserializer<AdminFulfillmentLabel, Map<String, Object?>> {
  const $AdminFulfillmentLabelDeserializer();

  @override
  AdminFulfillmentLabel deserialize(Map<String, Object?> json) => _$AdminFulfillmentLabelDeserialize(json);
}

Map<String, Object?> _$AdminFulfillmentLabelSerialize(AdminFulfillmentLabel instance) {
  return <String, Object?>{
    'created_at': instance.createdAt.toIso8601String(),
    'fulfillment_id': instance.fulfillmentId,
    'id': instance.id,
    'label_url': instance.labelUrl,
    'tracking_number': instance.trackingNumber,
    'tracking_url': instance.trackingUrl,
    'updated_at': instance.updatedAt.toIso8601String(),
  };
}

Map<String, Object?> _$AdminFulfillmentLabelToJson(AdminFulfillmentLabel instance) =>
    _$AdminFulfillmentLabelSerialize(instance);

// factory AdminFulfillmentLabel.fromJson(Map<String, Object?> json) => _$AdminFulfillmentLabelFromJson(json);
AdminFulfillmentLabel _$AdminFulfillmentLabelDeserialize(Map<String, Object?> json) {
  final createdAtValue = JsonHelper.asDateTime(
    json['created_at'],
    'created_at',
  );
  final fulfillmentIdValue = JsonHelper.as<String>(
    json['fulfillment_id'],
    'fulfillment_id',
    'String',
  );
  final idValue = JsonHelper.as<String>(json['id'], 'id', 'String');
  final labelUrlValue = JsonHelper.as<String>(
    json['label_url'],
    'label_url',
    'String',
  );
  final trackingNumberValue = JsonHelper.as<String>(
    json['tracking_number'],
    'tracking_number',
    'String',
  );
  final trackingUrlValue = JsonHelper.as<String>(
    json['tracking_url'],
    'tracking_url',
    'String',
  );
  final updatedAtValue = JsonHelper.asDateTime(
    json['updated_at'],
    'updated_at',
  );

  return AdminFulfillmentLabel(
    id: idValue,
    fulfillmentId: fulfillmentIdValue,
    trackingNumber: trackingNumberValue,
    trackingUrl: trackingUrlValue,
    labelUrl: labelUrlValue,
    createdAt: createdAtValue,
    updatedAt: updatedAtValue,
  );
}

AdminFulfillmentLabel _$AdminFulfillmentLabelFromJson(Map<String, Object?> json) =>
    _$AdminFulfillmentLabelDeserialize(json);
