// GENERATED CODE - DO NOT MODIFY BY HAND
// coverage:ignore-file
// ignore_for_file: type=lint
// ignore_for_file: unused_element, unused_import, deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: use_function_type_syntax_for_parameters
// ignore_for_file: unnecessary_const, avoid_init_to_null
// ignore_for_file: invalid_override_different_default_values_named
// ignore_for_file: prefer_expression_function_bodies
// ignore_for_file: annotate_overrides, invalid_annotation_target
// ignore_for_file: unnecessary_question_mark
// Generated by dust.

part of 'admin_product_detail_state.dart';

const DeepCollectionEquality _adminProductDetailStateSalesChannelsEquality = DeepCollectionEquality();

mixin _$AdminProductDetailState {
  @override
  String toString() {
    final self = this as AdminProductDetailState;
    return 'AdminProductDetailState('
        'failure: ${self.failure}, '
        'product: ${self.product}, '
        'salesChannels: ${self.salesChannels}, '
        'status: ${self.status}, '
        'totalSalesChannels: ${self.totalSalesChannels}'
        ')';
  }

  @override
  bool operator ==(Object other) {
    final self = this as AdminProductDetailState;
    return identical(this, other) ||
        other is AdminProductDetailState &&
            runtimeType == other.runtimeType &&
            other.failure == self.failure &&
            other.product == self.product &&
            _adminProductDetailStateSalesChannelsEquality.equals(other.salesChannels, self.salesChannels) &&
            other.status == self.status &&
            other.totalSalesChannels == self.totalSalesChannels;
  }

  @override
  int get hashCode {
    final self = this as AdminProductDetailState;
    return Object.hashAll([
      runtimeType,
      self.failure,
      self.product,
      _adminProductDetailStateSalesChannelsEquality.hash(self.salesChannels),
      self.status,
      self.totalSalesChannels,
    ]);
  }

  /// Creates a copy of this `AdminProductDetailState` with selected fields replaced.
  ///
  /// Usage:
  /// ```dart
  /// final updated = adminProductDetailState.copyWith();
  /// ```
  @pragma('vm:prefer-inline')
  _$AdminProductDetailStateCopyWith<AdminProductDetailState> get copyWith => _$AdminProductDetailStateCopyWithImpl<AdminProductDetailState>(this as AdminProductDetailState, (value) => value);
}

// CopyWith API inspired by Freezed.

/// @nodoc
abstract class _$AdminProductDetailStateCopyWith<$Res> {
  $Res call({
    Option<String>? failure,
    Option<AdminProductDetail>? product,
    List<AdminSalesChannel>? salesChannels,
    AdminProductDetailStatus? status,
    Option<int>? totalSalesChannels,
  });
}

/// @nodoc
final class _$AdminProductDetailStateCopyWithImpl<$Res> implements _$AdminProductDetailStateCopyWith<$Res> {
  const _$AdminProductDetailStateCopyWithImpl(this._self, this._then);

  final AdminProductDetailState _self;
  final $Res Function(AdminProductDetailState) _then;

  @override
  @pragma('vm:prefer-inline')
  $Res call({
    Object? failure = null,
    Object? product = null,
    Object? salesChannels = null,
    Object? status = null,
    Object? totalSalesChannels = null,
  }) {
    return _then(
      AdminProductDetailState(
        status: status == null ? _self.status : status as AdminProductDetailStatus,
        product: product == null ? _self.product : product as Option<AdminProductDetail>,
        failure: failure == null ? _self.failure : failure as Option<String>,
        salesChannels: salesChannels == null ? _self.salesChannels : salesChannels as List<AdminSalesChannel>,
        totalSalesChannels: totalSalesChannels == null ? _self.totalSalesChannels : totalSalesChannels as Option<int>,
      )
    );
  }
}
