// GENERATED CODE - DO NOT MODIFY BY HAND
// coverage:ignore-file
// ignore_for_file: type=lint
// ignore_for_file: unused_element, unused_import, deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: use_function_type_syntax_for_parameters
// ignore_for_file: unnecessary_const, avoid_init_to_null
// ignore_for_file: invalid_override_different_default_values_named
// ignore_for_file: prefer_expression_function_bodies
// ignore_for_file: annotate_overrides, invalid_annotation_target
// ignore_for_file: unnecessary_question_mark
// Generated by dust.

part of 'admin_product_create_state.dart';

const DeepCollectionEquality _adminProductCreateStateCurrencyCodesEquality = DeepCollectionEquality();

mixin _$AdminProductCreateState {
  @override
  String toString() {
    final self = this as AdminProductCreateState;
    return 'AdminProductCreateState('
        'created: ${self.created}, '
        'currencyCodes: ${self.currencyCodes}, '
        'failure: ${self.failure}, '
        'status: ${self.status}'
        ')';
  }

  @override
  bool operator ==(Object other) {
    final self = this as AdminProductCreateState;
    return identical(this, other) ||
        other is AdminProductCreateState &&
            runtimeType == other.runtimeType &&
            other.created == self.created &&
            _adminProductCreateStateCurrencyCodesEquality.equals(other.currencyCodes, self.currencyCodes) &&
            other.failure == self.failure &&
            other.status == self.status;
  }

  @override
  int get hashCode {
    final self = this as AdminProductCreateState;
    return Object.hashAll([
      runtimeType,
      self.created,
      _adminProductCreateStateCurrencyCodesEquality.hash(self.currencyCodes),
      self.failure,
      self.status,
    ]);
  }

  /// Creates a copy of this `AdminProductCreateState` with selected fields replaced.
  ///
  /// Usage:
  /// ```dart
  /// final updated = adminProductCreateState.copyWith();
  /// ```
  @pragma('vm:prefer-inline')
  _$AdminProductCreateStateCopyWith<AdminProductCreateState> get copyWith => _$AdminProductCreateStateCopyWithImpl<AdminProductCreateState>(this as AdminProductCreateState, (value) => value);
}

// CopyWith API inspired by Freezed.

/// @nodoc
abstract class _$AdminProductCreateStateCopyWith<$Res> {
  $Res call({
    Option<AdminProductDetail>? created,
    List<String>? currencyCodes,
    Option<String>? failure,
    AdminProductCreateStatus? status,
  });
}

/// @nodoc
final class _$AdminProductCreateStateCopyWithImpl<$Res> implements _$AdminProductCreateStateCopyWith<$Res> {
  const _$AdminProductCreateStateCopyWithImpl(this._self, this._then);

  final AdminProductCreateState _self;
  final $Res Function(AdminProductCreateState) _then;

  @override
  @pragma('vm:prefer-inline')
  $Res call({
    Object? created = null,
    Object? currencyCodes = null,
    Object? failure = null,
    Object? status = null,
  }) {
    return _then(
      AdminProductCreateState(
        status: status == null ? _self.status : status as AdminProductCreateStatus,
        currencyCodes: currencyCodes == null ? _self.currencyCodes : currencyCodes as List<String>,
        created: created == null ? _self.created : created as Option<AdminProductDetail>,
        failure: failure == null ? _self.failure : failure as Option<String>,
      )
    );
  }
}
