// GENERATED CODE - DO NOT MODIFY BY HAND
// coverage:ignore-file
// ignore_for_file: type=lint
// ignore_for_file: unused_element, unused_import, deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: use_function_type_syntax_for_parameters
// ignore_for_file: unnecessary_const, avoid_init_to_null
// ignore_for_file: invalid_override_different_default_values_named
// ignore_for_file: prefer_expression_function_bodies
// ignore_for_file: annotate_overrides, invalid_annotation_target
// ignore_for_file: unnecessary_question_mark
// Generated by dust.

part of 'model.dart';

mixin _$AdminReturnResponse implements Serializable {
  Map<String, Object?> serialize() =>
      _$AdminReturnResponseSerialize(this as AdminReturnResponse);

  Map<String, Object?> toJson() => serialize();
}

mixin _$AdminReturnListResponse implements Serializable {
  Map<String, Object?> serialize() =>
      _$AdminReturnListResponseSerialize(this as AdminReturnListResponse);

  Map<String, Object?> toJson() => serialize();
}

final class $AdminReturnResponseSerializer implements Serializer<AdminReturnResponse, Map<String, Object?>> {
  const $AdminReturnResponseSerializer();

  @override
  Map<String, Object?> serialize(AdminReturnResponse value) => _$AdminReturnResponseSerialize(value);
}
final class $AdminReturnListResponseSerializer implements Serializer<AdminReturnListResponse, Map<String, Object?>> {
  const $AdminReturnListResponseSerializer();

  @override
  Map<String, Object?> serialize(AdminReturnListResponse value) => _$AdminReturnListResponseSerialize(value);
}
AdminReturnResponse _$AdminReturnResponseFromRow(Row row) {
  return AdminReturnResponse(
    id: row.read<String>('id'),
    orderId: row.read<String>('order_id'),
    displayId: row.read<int>('display_id'),
    status: _ReturnStatus().decode(row.read<String>('status')),
    noNotification: _ReturnBool().decode(row.read<int>('no_notification')),
    refundAmount: row.readNullable<int>('refund_amount'),
    requestedAt: _ReturnDateTime().decode(row.read<String>('requested_at')),
    receivedAt: row.readNullable<Object?>('received_at') == null ? null : _ReturnDateTime().decode(row.read<String>('received_at')),
    canceledAt: row.readNullable<Object?>('canceled_at') == null ? null : _ReturnDateTime().decode(row.read<String>('canceled_at')),
    createdAt: _ReturnDateTime().decode(row.read<String>('created_at')),
    updatedAt: _ReturnDateTime().decode(row.read<String>('updated_at')),
    items: _ReturnItems().decode(row.read<String>('items_json')),
  );
}

/// Row deserializer for [AdminReturnResponse].
final class $AdminReturnResponseRowDeserializer implements RowDeserializer<AdminReturnResponse> {
  const $AdminReturnResponseRowDeserializer();

  @override
  AdminReturnResponse deserialize(Row row) => _$AdminReturnResponseFromRow(row);
}

/// Typed row query terminals for [AdminReturnResponse].
///
/// Resolved from the static type of the receiver, so a row type with no
/// `FromRow` has no terminals and the call does not compile.
extension $AdminReturnResponseQuery on QueryAs<AdminReturnResponse> {
  /// Fetches exactly one row.
  Future<AdminReturnResponse> fetchOne(DatabaseExecutor db) =>
      fetchOneWith(db, _$AdminReturnResponseFromRow);

  /// Fetches zero or one row.
  Future<AdminReturnResponse?> fetchOptional(DatabaseExecutor db) =>
      fetchOptionalWith(db, _$AdminReturnResponseFromRow);

  /// Fetches every row.
  Future<List<AdminReturnResponse>> fetchAll(DatabaseExecutor db) =>
      fetchAllWith(db, _$AdminReturnResponseFromRow);
}

Map<String, Object?> _$AdminReturnResponseSerialize(AdminReturnResponse instance) {
  return <String, Object?>{
    'canceled_at': instance.canceledAt == null
        ? null
        : (instance.canceledAt!).toIso8601String(),
    'created_at': instance.createdAt.toIso8601String(),
    'display_id': instance.displayId,
    'id': instance.id,
    'items': instance.items
        .map((item) => item.toJson())
        .toList(),
    'no_notification': instance.noNotification,
    'order_id': instance.orderId,
    'received_at': instance.receivedAt == null
        ? null
        : (instance.receivedAt!).toIso8601String(),
    'refund_amount': instance.refundAmount,
    'requested_at': instance.requestedAt.toIso8601String(),
    'status': JsonHelper.encodeWithCodec<AdminReturnStatus, Object?>(
      (AdminReturnStatusCodec()),
      instance.status,
    ),
    'updated_at': instance.updatedAt.toIso8601String(),
  };
}

Map<String, Object?> _$AdminReturnResponseToJson(AdminReturnResponse instance) =>
    _$AdminReturnResponseSerialize(instance);

Map<String, Object?> _$AdminReturnListResponseSerialize(AdminReturnListResponse instance) {
  return <String, Object?>{
    'count': instance.count,
    'limit': instance.limit,
    'offset': instance.offset,
    'returns': instance.returns
        .map((item) => _$AdminReturnResponseSerialize(item))
        .toList(),
  };
}

Map<String, Object?> _$AdminReturnListResponseToJson(AdminReturnListResponse instance) =>
    _$AdminReturnListResponseSerialize(instance);
