// GENERATED CODE - DO NOT MODIFY BY HAND
// coverage:ignore-file
// ignore_for_file: type=lint
// ignore_for_file: unused_element, unused_import, deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: use_function_type_syntax_for_parameters
// ignore_for_file: unnecessary_const, avoid_init_to_null
// ignore_for_file: invalid_override_different_default_values_named
// ignore_for_file: prefer_expression_function_bodies
// ignore_for_file: annotate_overrides, invalid_annotation_target
// ignore_for_file: unnecessary_question_mark
// Generated by dust.

part of 'model.dart';

mixin _$AdminPasswordCredential {
  @override
  bool operator ==(Object other) {
    final self = this as AdminPasswordCredential;
    return identical(this, other) ||
        other is AdminPasswordCredential &&
            runtimeType == other.runtimeType &&
            other.authIdentityId == self.authIdentityId &&
            other.passwordHash == self.passwordHash;
  }

  @override
  int get hashCode {
    final self = this as AdminPasswordCredential;
    return Object.hashAll([
      runtimeType,
      self.authIdentityId,
      self.passwordHash,
    ]);
  }
}

mixin _$AdminUserResponse implements Serializable {
  Map<String, Object?> serialize() =>
      _$AdminUserResponseSerialize(this as AdminUserResponse);

  Map<String, Object?> toJson() => serialize();
}

final class $AdminUserResponseSerializer implements Serializer<AdminUserResponse, Map<String, Object?>> {
  const $AdminUserResponseSerializer();

  @override
  Map<String, Object?> serialize(AdminUserResponse value) => _$AdminUserResponseSerialize(value);
}
AdminPasswordCredential _$AdminPasswordCredentialFromRow(Row row) {
  return AdminPasswordCredential(
    authIdentityId: row.read<String>('auth_identity_id'),
    passwordHash: row.read<String>('password_hash'),
  );
}

/// Row deserializer for [AdminPasswordCredential].
final class $AdminPasswordCredentialRowDeserializer implements RowDeserializer<AdminPasswordCredential> {
  const $AdminPasswordCredentialRowDeserializer();

  @override
  AdminPasswordCredential deserialize(Row row) => _$AdminPasswordCredentialFromRow(row);
}

/// Typed row query terminals for [AdminPasswordCredential].
///
/// Resolved from the static type of the receiver, so a row type with no
/// `FromRow` has no terminals and the call does not compile.
extension $AdminPasswordCredentialQuery on QueryAs<AdminPasswordCredential> {
  /// Fetches exactly one row.
  Future<AdminPasswordCredential> fetchOne(DatabaseExecutor db) =>
      fetchOneWith(db, _$AdminPasswordCredentialFromRow);

  /// Fetches zero or one row.
  Future<AdminPasswordCredential?> fetchOptional(DatabaseExecutor db) =>
      fetchOptionalWith(db, _$AdminPasswordCredentialFromRow);

  /// Fetches every row.
  Future<List<AdminPasswordCredential>> fetchAll(DatabaseExecutor db) =>
      fetchAllWith(db, _$AdminPasswordCredentialFromRow);
}

AdminUserResponse _$AdminUserResponseFromRow(Row row) {
  return AdminUserResponse(
    id: row.read<String>('id'),
    email: row.read<String>('email'),
    firstName: row.readNullable<String>('first_name'),
    lastName: row.readNullable<String>('last_name'),
  );
}

/// Row deserializer for [AdminUserResponse].
final class $AdminUserResponseRowDeserializer implements RowDeserializer<AdminUserResponse> {
  const $AdminUserResponseRowDeserializer();

  @override
  AdminUserResponse deserialize(Row row) => _$AdminUserResponseFromRow(row);
}

/// Typed row query terminals for [AdminUserResponse].
///
/// Resolved from the static type of the receiver, so a row type with no
/// `FromRow` has no terminals and the call does not compile.
extension $AdminUserResponseQuery on QueryAs<AdminUserResponse> {
  /// Fetches exactly one row.
  Future<AdminUserResponse> fetchOne(DatabaseExecutor db) =>
      fetchOneWith(db, _$AdminUserResponseFromRow);

  /// Fetches zero or one row.
  Future<AdminUserResponse?> fetchOptional(DatabaseExecutor db) =>
      fetchOptionalWith(db, _$AdminUserResponseFromRow);

  /// Fetches every row.
  Future<List<AdminUserResponse>> fetchAll(DatabaseExecutor db) =>
      fetchAllWith(db, _$AdminUserResponseFromRow);
}

AdminProductCurrencyResponse _$AdminProductCurrencyResponseFromRow(Row row) {
  return AdminProductCurrencyResponse(
    currencyCode: row.read<String>('currency_code'),
  );
}

/// Row deserializer for [AdminProductCurrencyResponse].
final class $AdminProductCurrencyResponseRowDeserializer implements RowDeserializer<AdminProductCurrencyResponse> {
  const $AdminProductCurrencyResponseRowDeserializer();

  @override
  AdminProductCurrencyResponse deserialize(Row row) => _$AdminProductCurrencyResponseFromRow(row);
}

/// Typed row query terminals for [AdminProductCurrencyResponse].
///
/// Resolved from the static type of the receiver, so a row type with no
/// `FromRow` has no terminals and the call does not compile.
extension $AdminProductCurrencyResponseQuery on QueryAs<AdminProductCurrencyResponse> {
  /// Fetches exactly one row.
  Future<AdminProductCurrencyResponse> fetchOne(DatabaseExecutor db) =>
      fetchOneWith(db, _$AdminProductCurrencyResponseFromRow);

  /// Fetches zero or one row.
  Future<AdminProductCurrencyResponse?> fetchOptional(DatabaseExecutor db) =>
      fetchOptionalWith(db, _$AdminProductCurrencyResponseFromRow);

  /// Fetches every row.
  Future<List<AdminProductCurrencyResponse>> fetchAll(DatabaseExecutor db) =>
      fetchAllWith(db, _$AdminProductCurrencyResponseFromRow);
}

Map<String, Object?> _$AdminUserResponseSerialize(AdminUserResponse instance) {
  return <String, Object?>{
    'email': instance.email,
    'first_name': instance.firstName,
    'id': instance.id,
    'last_name': instance.lastName,
  };
}

Map<String, Object?> _$AdminUserResponseToJson(AdminUserResponse instance) =>
    _$AdminUserResponseSerialize(instance);
