// GENERATED CODE - DO NOT MODIFY BY HAND
// coverage:ignore-file
// ignore_for_file: type=lint
// ignore_for_file: unused_element, unused_import, deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: use_function_type_syntax_for_parameters
// ignore_for_file: unnecessary_const, avoid_init_to_null
// ignore_for_file: invalid_override_different_default_values_named
// ignore_for_file: prefer_expression_function_bodies
// ignore_for_file: annotate_overrides, invalid_annotation_target
// ignore_for_file: unnecessary_question_mark
// Generated by dust.

part of 'product_export_model.dart';

AdminProductExportRow _$AdminProductExportRowFromRow(Row row) {
  return AdminProductExportRow(
    productId: row.read<String>('product_id'),
    handle: row.read<String>('handle'),
    title: row.read<String>('title'),
    status: row.read<String>('status'),
    discountable: row.read<int>('discountable'),
    optionsJson: row.read<String>('options_json'),
    variantsJson: row.read<String>('variants_json'),
    imagesJson: row.read<String>('images_json'),
    tagsJson: row.read<String>('tags_json'),
    subtitle: row.readNullable<String>('subtitle'),
    description: row.readNullable<String>('description'),
    thumbnail: row.readNullable<String>('thumbnail'),
    weight: row.readNullable<int>('weight'),
    length: row.readNullable<int>('length'),
    width: row.readNullable<int>('width'),
    height: row.readNullable<int>('height'),
    originCountry: row.readNullable<String>('origin_country'),
    material: row.readNullable<String>('material'),
    collectionId: row.readNullable<String>('collection_id'),
    typeId: row.readNullable<String>('type_id'),
  );
}

/// Row deserializer for [AdminProductExportRow].
final class $AdminProductExportRowRowDeserializer implements RowDeserializer<AdminProductExportRow> {
  const $AdminProductExportRowRowDeserializer();

  @override
  AdminProductExportRow deserialize(Row row) => _$AdminProductExportRowFromRow(row);
}

/// Typed row query terminals for [AdminProductExportRow].
///
/// Resolved from the static type of the receiver, so a row type with no
/// `FromRow` has no terminals and the call does not compile.
extension $AdminProductExportRowQuery on QueryAs<AdminProductExportRow> {
  /// Fetches exactly one row.
  Future<AdminProductExportRow> fetchOne(DatabaseExecutor db) =>
      fetchOneWith(db, _$AdminProductExportRowFromRow);

  /// Fetches zero or one row.
  Future<AdminProductExportRow?> fetchOptional(DatabaseExecutor db) =>
      fetchOptionalWith(db, _$AdminProductExportRowFromRow);

  /// Fetches every row.
  Future<List<AdminProductExportRow>> fetchAll(DatabaseExecutor db) =>
      fetchAllWith(db, _$AdminProductExportRowFromRow);
}
