// GENERATED CODE - DO NOT MODIFY BY HAND
// coverage:ignore-file
// ignore_for_file: type=lint
// ignore_for_file: unused_element, unused_import, deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: use_function_type_syntax_for_parameters
// ignore_for_file: unnecessary_const, avoid_init_to_null
// ignore_for_file: invalid_override_different_default_values_named
// ignore_for_file: prefer_expression_function_bodies
// ignore_for_file: annotate_overrides, invalid_annotation_target
// ignore_for_file: unnecessary_question_mark
// Generated by dust.

part of 'product_list_model.dart';

mixin _$AdminProductResponse implements Serializable {
  Map<String, Object?> serialize() =>
      _$AdminProductResponseSerialize(this as AdminProductResponse);

  Map<String, Object?> toJson() => serialize();
}

mixin _$AdminProductListResponse implements Serializable {
  Map<String, Object?> serialize() =>
      _$AdminProductListResponseSerialize(this as AdminProductListResponse);

  Map<String, Object?> toJson() => serialize();
}

final class $AdminProductResponseSerializer implements Serializer<AdminProductResponse, Map<String, Object?>> {
  const $AdminProductResponseSerializer();

  @override
  Map<String, Object?> serialize(AdminProductResponse value) => _$AdminProductResponseSerialize(value);
}
final class $AdminProductListResponseSerializer implements Serializer<AdminProductListResponse, Map<String, Object?>> {
  const $AdminProductListResponseSerializer();

  @override
  Map<String, Object?> serialize(AdminProductListResponse value) => _$AdminProductListResponseSerialize(value);
}
AdminProductResponse _$AdminProductResponseFromRow(Row row) {
  return AdminProductResponse(
    id: row.read<String>('id'),
    title: row.read<String>('title'),
    thumbnail: row.read<String>('thumbnail'),
    collectionTitle: row.read<String>('collection_title'),
    salesChannels: _AdminProductChannelsSqlxJson().decode(row.read<String>('sales_channels')),
    variantCount: row.read<int>('variant_count'),
    status: _AdminProductLifecycleSqlx().decode(row.read<String>('status')),
  );
}

/// Row deserializer for [AdminProductResponse].
final class $AdminProductResponseRowDeserializer implements RowDeserializer<AdminProductResponse> {
  const $AdminProductResponseRowDeserializer();

  @override
  AdminProductResponse deserialize(Row row) => _$AdminProductResponseFromRow(row);
}

/// Typed row query terminals for [AdminProductResponse].
///
/// Resolved from the static type of the receiver, so a row type with no
/// `FromRow` has no terminals and the call does not compile.
extension $AdminProductResponseQuery on QueryAs<AdminProductResponse> {
  /// Fetches exactly one row.
  Future<AdminProductResponse> fetchOne(DatabaseExecutor db) =>
      fetchOneWith(db, _$AdminProductResponseFromRow);

  /// Fetches zero or one row.
  Future<AdminProductResponse?> fetchOptional(DatabaseExecutor db) =>
      fetchOptionalWith(db, _$AdminProductResponseFromRow);

  /// Fetches every row.
  Future<List<AdminProductResponse>> fetchAll(DatabaseExecutor db) =>
      fetchAllWith(db, _$AdminProductResponseFromRow);
}

Map<String, Object?> _$AdminProductResponseSerialize(AdminProductResponse instance) {
  return <String, Object?>{
    'collection_title': instance.collectionTitle,
    'id': instance.id,
    'sales_channels': instance.salesChannels
        .map((item) => item.toJson())
        .toList(),
    'status': JsonHelper.encodeWithCodec<AdminProductLifecycle, Object?>(
      (AdminProductLifecycleCodec()),
      instance.status,
    ),
    'thumbnail': instance.thumbnail,
    'title': instance.title,
    'variant_count': instance.variantCount,
  };
}

Map<String, Object?> _$AdminProductResponseToJson(AdminProductResponse instance) =>
    _$AdminProductResponseSerialize(instance);

Map<String, Object?> _$AdminProductListResponseSerialize(AdminProductListResponse instance) {
  return <String, Object?>{
    'count': instance.count,
    'limit': instance.limit,
    'offset': instance.offset,
    'products': instance.products
        .map((item) => _$AdminProductResponseSerialize(item))
        .toList(),
  };
}

Map<String, Object?> _$AdminProductListResponseToJson(AdminProductListResponse instance) =>
    _$AdminProductListResponseSerialize(instance);
