// GENERATED CODE - DO NOT MODIFY BY HAND
// coverage:ignore-file
// ignore_for_file: type=lint
// ignore_for_file: unused_element, unused_import, deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: use_function_type_syntax_for_parameters
// ignore_for_file: unnecessary_const, avoid_init_to_null
// ignore_for_file: invalid_override_different_default_values_named
// ignore_for_file: prefer_expression_function_bodies
// ignore_for_file: annotate_overrides, invalid_annotation_target
// ignore_for_file: unnecessary_question_mark
// Generated by dust.

part of 'product_import_model.dart';

AdminProductImportRow _$AdminProductImportRowFromRow(Row row) {
  return AdminProductImportRow(
    id: row.read<String>('id'),
    payloadJson: row.read<String>('payload_json'),
    status: row.read<String>('status'),
    expiresAt: _AdminImportUtcDateTime().decode(row.read<String>('expires_at')),
  );
}

/// Row deserializer for [AdminProductImportRow].
final class $AdminProductImportRowRowDeserializer implements RowDeserializer<AdminProductImportRow> {
  const $AdminProductImportRowRowDeserializer();

  @override
  AdminProductImportRow deserialize(Row row) => _$AdminProductImportRowFromRow(row);
}

/// Typed row query terminals for [AdminProductImportRow].
///
/// Resolved from the static type of the receiver, so a row type with no
/// `FromRow` has no terminals and the call does not compile.
extension $AdminProductImportRowQuery on QueryAs<AdminProductImportRow> {
  /// Fetches exactly one row.
  Future<AdminProductImportRow> fetchOne(DatabaseExecutor db) =>
      fetchOneWith(db, _$AdminProductImportRowFromRow);

  /// Fetches zero or one row.
  Future<AdminProductImportRow?> fetchOptional(DatabaseExecutor db) =>
      fetchOptionalWith(db, _$AdminProductImportRowFromRow);

  /// Fetches every row.
  Future<List<AdminProductImportRow>> fetchAll(DatabaseExecutor db) =>
      fetchAllWith(db, _$AdminProductImportRowFromRow);
}

AdminProductImportIdentityRow _$AdminProductImportIdentityRowFromRow(Row row) {
  return AdminProductImportIdentityRow(
    id: row.read<String>('id'),
    handle: row.read<String>('handle'),
  );
}

/// Row deserializer for [AdminProductImportIdentityRow].
final class $AdminProductImportIdentityRowRowDeserializer implements RowDeserializer<AdminProductImportIdentityRow> {
  const $AdminProductImportIdentityRowRowDeserializer();

  @override
  AdminProductImportIdentityRow deserialize(Row row) => _$AdminProductImportIdentityRowFromRow(row);
}

/// Typed row query terminals for [AdminProductImportIdentityRow].
///
/// Resolved from the static type of the receiver, so a row type with no
/// `FromRow` has no terminals and the call does not compile.
extension $AdminProductImportIdentityRowQuery on QueryAs<AdminProductImportIdentityRow> {
  /// Fetches exactly one row.
  Future<AdminProductImportIdentityRow> fetchOne(DatabaseExecutor db) =>
      fetchOneWith(db, _$AdminProductImportIdentityRowFromRow);

  /// Fetches zero or one row.
  Future<AdminProductImportIdentityRow?> fetchOptional(DatabaseExecutor db) =>
      fetchOptionalWith(db, _$AdminProductImportIdentityRowFromRow);

  /// Fetches every row.
  Future<List<AdminProductImportIdentityRow>> fetchAll(DatabaseExecutor db) =>
      fetchAllWith(db, _$AdminProductImportIdentityRowFromRow);
}

AdminProductImportVariantRow _$AdminProductImportVariantRowFromRow(Row row) {
  return AdminProductImportVariantRow(
    id: row.read<String>('id'),
    productId: row.read<String>('product_id'),
    sku: row.readNullable<String>('sku'),
  );
}

/// Row deserializer for [AdminProductImportVariantRow].
final class $AdminProductImportVariantRowRowDeserializer implements RowDeserializer<AdminProductImportVariantRow> {
  const $AdminProductImportVariantRowRowDeserializer();

  @override
  AdminProductImportVariantRow deserialize(Row row) => _$AdminProductImportVariantRowFromRow(row);
}

/// Typed row query terminals for [AdminProductImportVariantRow].
///
/// Resolved from the static type of the receiver, so a row type with no
/// `FromRow` has no terminals and the call does not compile.
extension $AdminProductImportVariantRowQuery on QueryAs<AdminProductImportVariantRow> {
  /// Fetches exactly one row.
  Future<AdminProductImportVariantRow> fetchOne(DatabaseExecutor db) =>
      fetchOneWith(db, _$AdminProductImportVariantRowFromRow);

  /// Fetches zero or one row.
  Future<AdminProductImportVariantRow?> fetchOptional(DatabaseExecutor db) =>
      fetchOptionalWith(db, _$AdminProductImportVariantRowFromRow);

  /// Fetches every row.
  Future<List<AdminProductImportVariantRow>> fetchAll(DatabaseExecutor db) =>
      fetchAllWith(db, _$AdminProductImportVariantRowFromRow);
}

AdminProductImportIdRow _$AdminProductImportIdRowFromRow(Row row) {
  return AdminProductImportIdRow(id: row.read<String>('id'));
}

/// Row deserializer for [AdminProductImportIdRow].
final class $AdminProductImportIdRowRowDeserializer implements RowDeserializer<AdminProductImportIdRow> {
  const $AdminProductImportIdRowRowDeserializer();

  @override
  AdminProductImportIdRow deserialize(Row row) => _$AdminProductImportIdRowFromRow(row);
}

/// Typed row query terminals for [AdminProductImportIdRow].
///
/// Resolved from the static type of the receiver, so a row type with no
/// `FromRow` has no terminals and the call does not compile.
extension $AdminProductImportIdRowQuery on QueryAs<AdminProductImportIdRow> {
  /// Fetches exactly one row.
  Future<AdminProductImportIdRow> fetchOne(DatabaseExecutor db) =>
      fetchOneWith(db, _$AdminProductImportIdRowFromRow);

  /// Fetches zero or one row.
  Future<AdminProductImportIdRow?> fetchOptional(DatabaseExecutor db) =>
      fetchOptionalWith(db, _$AdminProductImportIdRowFromRow);

  /// Fetches every row.
  Future<List<AdminProductImportIdRow>> fetchAll(DatabaseExecutor db) =>
      fetchAllWith(db, _$AdminProductImportIdRowFromRow);
}

AdminProductImportCurrencyRow _$AdminProductImportCurrencyRowFromRow(Row row) {
  return AdminProductImportCurrencyRow(
    currencyCode: row.read<String>('currency_code'),
  );
}

/// Row deserializer for [AdminProductImportCurrencyRow].
final class $AdminProductImportCurrencyRowRowDeserializer implements RowDeserializer<AdminProductImportCurrencyRow> {
  const $AdminProductImportCurrencyRowRowDeserializer();

  @override
  AdminProductImportCurrencyRow deserialize(Row row) => _$AdminProductImportCurrencyRowFromRow(row);
}

/// Typed row query terminals for [AdminProductImportCurrencyRow].
///
/// Resolved from the static type of the receiver, so a row type with no
/// `FromRow` has no terminals and the call does not compile.
extension $AdminProductImportCurrencyRowQuery on QueryAs<AdminProductImportCurrencyRow> {
  /// Fetches exactly one row.
  Future<AdminProductImportCurrencyRow> fetchOne(DatabaseExecutor db) =>
      fetchOneWith(db, _$AdminProductImportCurrencyRowFromRow);

  /// Fetches zero or one row.
  Future<AdminProductImportCurrencyRow?> fetchOptional(DatabaseExecutor db) =>
      fetchOptionalWith(db, _$AdminProductImportCurrencyRowFromRow);

  /// Fetches every row.
  Future<List<AdminProductImportCurrencyRow>> fetchAll(DatabaseExecutor db) =>
      fetchAllWith(db, _$AdminProductImportCurrencyRowFromRow);
}
