name: dust_commerce
publish_to: none

environment:
  sdk: ">=3.6.0 <4.0.0"

workspace:
  - packages/commerce_shared
  - packages/commerce_server
  - apps/commerce_app

hooks:
  user_defines:
    sqlite3:
      source: system
      name: sqlite3
      name_windows: winsqlite3
