// GENERATED CODE - DO NOT MODIFY BY HAND
// coverage:ignore-file
// ignore_for_file: type=lint
// ignore_for_file: unused_element, unused_import, deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: use_function_type_syntax_for_parameters
// ignore_for_file: unnecessary_const, avoid_init_to_null
// ignore_for_file: invalid_override_different_default_values_named
// ignore_for_file: prefer_expression_function_bodies
// ignore_for_file: annotate_overrides, invalid_annotation_target
// ignore_for_file: unnecessary_question_mark
// Generated by dust.

part of 'catalog_state.dart';

const DeepCollectionEquality _catalogStateProductsEquality = DeepCollectionEquality();
final class _CatalogStateCopyWithUnset {
  const _CatalogStateCopyWithUnset();
}

const _catalogStateCopyWithUnset = _CatalogStateCopyWithUnset();

mixin _$CatalogState {
  @override
  String toString() {
    final self = this as CatalogState;
    return 'CatalogState('
        'currencyCode: ${self.currencyCode}, '
        'message: ${self.message}, '
        'products: ${self.products}, '
        'status: ${self.status}, '
        'total: ${self.total}'
        ')';
  }

  @override
  bool operator ==(Object other) {
    final self = this as CatalogState;
    return identical(this, other) ||
        other is CatalogState &&
            runtimeType == other.runtimeType &&
            other.currencyCode == self.currencyCode &&
            other.message == self.message &&
            _catalogStateProductsEquality.equals(other.products, self.products) &&
            other.status == self.status &&
            other.total == self.total;
  }

  @override
  int get hashCode {
    final self = this as CatalogState;
    return Object.hashAll([
      runtimeType,
      self.currencyCode,
      self.message,
      _catalogStateProductsEquality.hash(self.products),
      self.status,
      self.total,
    ]);
  }

  /// Creates a copy of this `CatalogState` with selected fields replaced.
  ///
  /// Usage:
  /// ```dart
  /// final updated = catalogState.copyWith(currencyCode: 'John');
  /// final cleared = catalogState.copyWith(message: null);
  /// ```
  @pragma('vm:prefer-inline')
  _$CatalogStateCopyWith<CatalogState> get copyWith => _$CatalogStateCopyWithImpl<CatalogState>(this as CatalogState, (value) => value);
}

// CopyWith API inspired by Freezed.

/// @nodoc
abstract class _$CatalogStateCopyWith<$Res> {
  $Res call({
    String? currencyCode,
    String? message,
    List<Product>? products,
    CatalogStatus? status,
    int? total,
  });
}

/// @nodoc
final class _$CatalogStateCopyWithImpl<$Res> implements _$CatalogStateCopyWith<$Res> {
  const _$CatalogStateCopyWithImpl(this._self, this._then);

  final CatalogState _self;
  final $Res Function(CatalogState) _then;

  @override
  @pragma('vm:prefer-inline')
  $Res call({
    Object? currencyCode = null,
    Object? message = _catalogStateCopyWithUnset,
    Object? products = null,
    Object? status = null,
    Object? total = null,
  }) {
    return _then(
      CatalogState(
        status: status == null ? _self.status : status as CatalogStatus,
        products: products == null ? _self.products : products as List<Product>,
        total: total == null ? _self.total : total as int,
        currencyCode: currencyCode == null ? _self.currencyCode : currencyCode as String,
        message: identical(message, _catalogStateCopyWithUnset)
            ? _self.message
            : message as String?,
      )
    );
  }
}
