// GENERATED CODE - DO NOT MODIFY BY HAND
// coverage:ignore-file
// ignore_for_file: type=lint
// ignore_for_file: unused_element, unused_import, deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: use_function_type_syntax_for_parameters
// ignore_for_file: unnecessary_const, avoid_init_to_null
// ignore_for_file: invalid_override_different_default_values_named
// ignore_for_file: prefer_expression_function_bodies
// ignore_for_file: annotate_overrides, invalid_annotation_target
// ignore_for_file: unnecessary_question_mark
// Generated by dust.

part of 'order_return_history_state.dart';

const DeepCollectionEquality _orderReturnHistoryStateReturnsEquality = DeepCollectionEquality();

mixin _$OrderReturnHistoryState {
  @override
  String toString() {
    final self = this as OrderReturnHistoryState;
    return 'OrderReturnHistoryState('
        'count: ${self.count}, '
        'failure: ${self.failure}, '
        'orderId: ${self.orderId}, '
        'offset: ${self.offset}, '
        'returns: ${self.returns}, '
        'status: ${self.status}'
        ')';
  }

  @override
  bool operator ==(Object other) {
    final self = this as OrderReturnHistoryState;
    return identical(this, other) ||
        other is OrderReturnHistoryState &&
            runtimeType == other.runtimeType &&
            other.count == self.count &&
            other.failure == self.failure &&
            other.orderId == self.orderId &&
            other.offset == self.offset &&
            _orderReturnHistoryStateReturnsEquality.equals(other.returns, self.returns) &&
            other.status == self.status;
  }

  @override
  int get hashCode {
    final self = this as OrderReturnHistoryState;
    return Object.hashAll([
      runtimeType,
      self.count,
      self.failure,
      self.orderId,
      self.offset,
      _orderReturnHistoryStateReturnsEquality.hash(self.returns),
      self.status,
    ]);
  }

  /// Creates a copy of this `OrderReturnHistoryState` with selected fields replaced.
  ///
  /// Usage:
  /// ```dart
  /// final updated = orderReturnHistoryState.copyWith(count: 1);
  /// ```
  @pragma('vm:prefer-inline')
  _$OrderReturnHistoryStateCopyWith<OrderReturnHistoryState> get copyWith => _$OrderReturnHistoryStateCopyWithImpl<OrderReturnHistoryState>(this as OrderReturnHistoryState, (value) => value);
}

// CopyWith API inspired by Freezed.

/// @nodoc
abstract class _$OrderReturnHistoryStateCopyWith<$Res> {
  $Res call({
    int? count,
    Option<OrderReturnHistoryFailure>? failure,
    Option<String>? orderId,
    int? offset,
    List<OrderReturnView>? returns,
    OrderReturnHistoryStatus? status,
  });
}

/// @nodoc
final class _$OrderReturnHistoryStateCopyWithImpl<$Res> implements _$OrderReturnHistoryStateCopyWith<$Res> {
  const _$OrderReturnHistoryStateCopyWithImpl(this._self, this._then);

  final OrderReturnHistoryState _self;
  final $Res Function(OrderReturnHistoryState) _then;

  @override
  @pragma('vm:prefer-inline')
  $Res call({
    Object? count = null,
    Object? failure = null,
    Object? orderId = null,
    Object? offset = null,
    Object? returns = null,
    Object? status = null,
  }) {
    return _then(
      OrderReturnHistoryState(
        status: status == null ? _self.status : status as OrderReturnHistoryStatus,
        orderId: orderId == null ? _self.orderId : orderId as Option<String>,
        returns: returns == null ? _self.returns : returns as List<OrderReturnView>,
        count: count == null ? _self.count : count as int,
        offset: offset == null ? _self.offset : offset as int,
        failure: failure == null ? _self.failure : failure as Option<OrderReturnHistoryFailure>,
      )
    );
  }
}
