// GENERATED CODE - DO NOT MODIFY BY HAND
// coverage:ignore-file
// ignore_for_file: type=lint
// ignore_for_file: unused_element, unused_import, deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: use_function_type_syntax_for_parameters
// ignore_for_file: unnecessary_const, avoid_init_to_null
// ignore_for_file: invalid_override_different_default_values_named
// ignore_for_file: prefer_expression_function_bodies
// ignore_for_file: annotate_overrides, invalid_annotation_target
// ignore_for_file: unnecessary_question_mark
// Generated by dust.

part of 'create.dart';

final class _$OrderReturnCreateRepository implements OrderReturnCreateRepository {
  const _$OrderReturnCreateRepository(this._db);

  final DatabaseExecutor _db;

  @override
  Future<Result<ExecResult, SqlxError>> request(String id, String orderId, String customerId, String? note) {
    return _db.execute(
      r'''
INSERT INTO return_requests (id, display_id, order_id, customer_id, note)
SELECT ?, COALESCE(MAX(display_id), 0) + 1, ?, ?, ?
FROM return_requests
''',
      [id, orderId, customerId, note],
    );
  }

  @override
  Future<Result<ExecResult, SqlxError>> item(String id, String returnId, String orderItemId, int quantity, String? reasonId, String? note) {
    return _db.execute(
      r'''
INSERT INTO return_items
  (id, return_id, order_item_id, quantity, reason_id, note)
VALUES (?, ?, ?, ?, ?, ?)
''',
      [id, returnId, orderItemId, quantity, reasonId, note],
    );
  }
}
