// GENERATED CODE - DO NOT MODIFY BY HAND
// coverage:ignore-file
// ignore_for_file: type=lint
// ignore_for_file: unused_element, unused_import, deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: use_function_type_syntax_for_parameters
// ignore_for_file: unnecessary_const, avoid_init_to_null
// ignore_for_file: invalid_override_different_default_values_named
// ignore_for_file: prefer_expression_function_bodies
// ignore_for_file: annotate_overrides, invalid_annotation_target
// ignore_for_file: unnecessary_question_mark
// Generated by dust.

part of 'list.dart';

final class _$OrderReturnListRepository implements OrderReturnListRepository {
  const _$OrderReturnListRepository(this._db);

  final DatabaseExecutor _db;

  @override
  Future<Result<int, SqlxError>> countReasons() {
    return _db.fetchScalar<int>(
      r'''
SELECT count(*)
FROM return_reasons
WHERE deleted_at IS NULL
''',
      [],
    );
  }

  @override
  Future<Result<int, SqlxError>> countForOrder(String orderId, String customerId) {
    return _db.fetchScalar<int>(
      r'''
SELECT count(*)
FROM return_requests
WHERE order_id = ? AND customer_id = ? AND deleted_at IS NULL
''',
      [orderId, customerId],
    );
  }

  @override
  Future<Result<List<OrderReturnResponse>, SqlxError>> forOrder(String orderId, String customerId, int limit, int offset) {
    return _db.fetchAll<OrderReturnResponse>(
      r'''
SELECT request.id, request.display_id, request.order_id, request.status,
       SUM(item.quantity) AS item_quantity, request.requested_at
FROM return_requests request
JOIN return_items item ON item.return_id = request.id
WHERE request.order_id = ? AND request.customer_id = ?
  AND request.deleted_at IS NULL
GROUP BY request.id, request.display_id, request.order_id,
         request.status, request.requested_at
ORDER BY request.requested_at DESC, request.display_id DESC
LIMIT ? OFFSET ?
''',
      [orderId, customerId, limit, offset],
      const $OrderReturnResponseRowDeserializer().deserialize,
    );
  }

  @override
  Future<Result<List<ReturnReasonResponse>, SqlxError>> reasons(int limit, int offset) {
    return _db.fetchAll<ReturnReasonResponse>(
      r'''
SELECT id, value, label, description, parent_return_reason_id,
       created_at, updated_at
FROM return_reasons
WHERE deleted_at IS NULL
ORDER BY COALESCE(parent_return_reason_id, id),
         CASE WHEN parent_return_reason_id IS NULL THEN 0 ELSE 1 END,
         lower(label), id
LIMIT ? OFFSET ?
''',
      [limit, offset],
      const $ReturnReasonResponseRowDeserializer().deserialize,
    );
  }
}
