// GENERATED CODE - DO NOT MODIFY BY HAND
// coverage:ignore-file
// ignore_for_file: type=lint
// ignore_for_file: unused_element, unused_import, deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: use_function_type_syntax_for_parameters
// ignore_for_file: unnecessary_const, avoid_init_to_null
// ignore_for_file: invalid_override_different_default_values_named
// ignore_for_file: prefer_expression_function_bodies
// ignore_for_file: annotate_overrides, invalid_annotation_target
// ignore_for_file: unnecessary_question_mark
// Generated by dust.

part of 'checkout_request.dart';

final class _AddressInputCopyWithUnset {
  const _AddressInputCopyWithUnset();
}

const _addressInputCopyWithUnset = _AddressInputCopyWithUnset();

final class _CheckoutRequestCopyWithUnset {
  const _CheckoutRequestCopyWithUnset();
}

const _checkoutRequestCopyWithUnset = _CheckoutRequestCopyWithUnset();

mixin _$AddressInput implements Validatable, Serializable {
  @override
  String toString() {
    final self = this as AddressInput;
    return 'AddressInput('
        'city: ${self.city}, '
        'countryCode: ${self.countryCode}, '
        'firstName: ${self.firstName}, '
        'lastName: ${self.lastName}, '
        'line1: ${self.line1}, '
        'line2: ${self.line2}, '
        'phone: ${self.phone}, '
        'postalCode: ${self.postalCode}, '
        'province: ${self.province}'
        ')';
  }

  @override
  bool operator ==(Object other) {
    final self = this as AddressInput;
    return identical(this, other) ||
        other is AddressInput &&
            runtimeType == other.runtimeType &&
            other.city == self.city &&
            other.countryCode == self.countryCode &&
            other.firstName == self.firstName &&
            other.lastName == self.lastName &&
            other.line1 == self.line1 &&
            other.line2 == self.line2 &&
            other.phone == self.phone &&
            other.postalCode == self.postalCode &&
            other.province == self.province;
  }

  @override
  int get hashCode {
    final self = this as AddressInput;
    return Object.hashAll([
      runtimeType,
      self.city,
      self.countryCode,
      self.firstName,
      self.lastName,
      self.line1,
      self.line2,
      self.phone,
      self.postalCode,
      self.province,
    ]);
  }

  /// Creates a copy of this `AddressInput` with selected fields replaced.
  ///
  /// Usage:
  /// ```dart
  /// final updated = addressInput.copyWith(city: 'John');
  /// final cleared = addressInput.copyWith(line2: null);
  /// ```
  @pragma('vm:prefer-inline')
  _$AddressInputCopyWith<AddressInput> get copyWith =>
      _$AddressInputCopyWithImpl<AddressInput>(
          this as AddressInput, (value) => value);

  /// Validates this `AddressInput`.
  ///
  /// Usage:
  /// ```dart
  /// final result = value.validate();
  /// if (result case Invalid(:final errors)) {
  ///   print(errors.first.message);
  /// }
  /// ```
  ValidationResult validate() {
    final self = this as AddressInput;
    final errors = <ValidationError>[];
    _AddressInputValidation._validateCity(self.city, errors);
    _AddressInputValidation._validateCountryCode(self.countryCode, errors);
    _AddressInputValidation._validateFirstName(self.firstName, errors);
    _AddressInputValidation._validateLastName(self.lastName, errors);
    _AddressInputValidation._validateLine1(self.line1, errors);
    _AddressInputValidation._validatePostalCode(self.postalCode, errors);
    return errors.isEmpty ? const Valid() : Invalid(errors);
  }

  /// Throws [ValidationException] when this `AddressInput` is invalid.
  ///
  /// Usage:
  /// ```dart
  /// value.validateOrThrow();
  /// ```
  void validateOrThrow() {
    final result = validate();
    if (result case Invalid(errors: final errors)) {
      throw ValidationException(errors);
    }
  }

  Map<String, Object?> serialize() =>
      _$AddressInputSerialize(this as AddressInput);

  Map<String, Object?> toJson() => serialize();
}

mixin _$CheckoutRequest implements Validatable, Serializable {
  @override
  String toString() {
    final self = this as CheckoutRequest;
    return 'CheckoutRequest('
        'billingAddress: ${self.billingAddress}, '
        'cartId: ${self.cartId}, '
        'email: ${self.email}, '
        'shippingAddress: ${self.shippingAddress}'
        ')';
  }

  @override
  bool operator ==(Object other) {
    final self = this as CheckoutRequest;
    return identical(this, other) ||
        other is CheckoutRequest &&
            runtimeType == other.runtimeType &&
            other.billingAddress == self.billingAddress &&
            other.cartId == self.cartId &&
            other.email == self.email &&
            other.shippingAddress == self.shippingAddress;
  }

  @override
  int get hashCode {
    final self = this as CheckoutRequest;
    return Object.hashAll([
      runtimeType,
      self.billingAddress,
      self.cartId,
      self.email,
      self.shippingAddress,
    ]);
  }

  /// Creates a copy of this `CheckoutRequest` with selected fields replaced.
  ///
  /// Usage:
  /// ```dart
  /// final updated = checkoutRequest.copyWith(cartId: 'John');
  /// final cleared = checkoutRequest.copyWith(billingAddress: null);
  /// final nested = checkoutRequest.copyWith.billingAddress(city: 'London');
  /// ```
  @pragma('vm:prefer-inline')
  _$CheckoutRequestCopyWith<CheckoutRequest> get copyWith =>
      _$CheckoutRequestCopyWithImpl<CheckoutRequest>(
          this as CheckoutRequest, (value) => value);

  /// Validates this `CheckoutRequest`.
  ///
  /// Usage:
  /// ```dart
  /// final result = value.validate();
  /// if (result case Invalid(:final errors)) {
  ///   print(errors.first.message);
  /// }
  /// ```
  ValidationResult validate() {
    final self = this as CheckoutRequest;
    final errors = <ValidationError>[];
    _CheckoutRequestValidation._validateCartId(self.cartId, errors);
    _CheckoutRequestValidation._validateEmail(self.email, errors);
    return errors.isEmpty ? const Valid() : Invalid(errors);
  }

  /// Throws [ValidationException] when this `CheckoutRequest` is invalid.
  ///
  /// Usage:
  /// ```dart
  /// value.validateOrThrow();
  /// ```
  void validateOrThrow() {
    final result = validate();
    if (result case Invalid(errors: final errors)) {
      throw ValidationException(errors);
    }
  }

  Map<String, Object?> serialize() =>
      _$CheckoutRequestSerialize(this as CheckoutRequest);

  Map<String, Object?> toJson() => serialize();
}

// CopyWith API inspired by Freezed.

/// @nodoc
abstract class _$AddressInputCopyWith<$Res> {
  $Res call({
    String? city,
    String? countryCode,
    String? firstName,
    String? lastName,
    String? line1,
    String? line2,
    String? phone,
    String? postalCode,
    String? province,
  });
}

/// @nodoc
final class _$AddressInputCopyWithImpl<$Res>
    implements _$AddressInputCopyWith<$Res> {
  const _$AddressInputCopyWithImpl(this._self, this._then);

  final AddressInput _self;
  final $Res Function(AddressInput) _then;

  @override
  @pragma('vm:prefer-inline')
  $Res call({
    Object? city = null,
    Object? countryCode = null,
    Object? firstName = null,
    Object? lastName = null,
    Object? line1 = null,
    Object? line2 = _addressInputCopyWithUnset,
    Object? phone = _addressInputCopyWithUnset,
    Object? postalCode = null,
    Object? province = _addressInputCopyWithUnset,
  }) {
    return _then(AddressInput(
      firstName: firstName == null ? _self.firstName : firstName as String,
      lastName: lastName == null ? _self.lastName : lastName as String,
      line1: line1 == null ? _self.line1 : line1 as String,
      city: city == null ? _self.city : city as String,
      postalCode: postalCode == null ? _self.postalCode : postalCode as String,
      countryCode:
          countryCode == null ? _self.countryCode : countryCode as String,
      line2: identical(line2, _addressInputCopyWithUnset)
          ? _self.line2
          : line2 as String?,
      province: identical(province, _addressInputCopyWithUnset)
          ? _self.province
          : province as String?,
      phone: identical(phone, _addressInputCopyWithUnset)
          ? _self.phone
          : phone as String?,
    ));
  }
}

extension _AddressInputValidation on AddressInput {
  static void _validateCity(String city, List<ValidationError> errors) {
    if (city.length < 1) {
      errors.add(ValidationError(field: 'city', message: 'Enter a city'));
    }
  }

  static void _validateCountryCode(
      String countryCode, List<ValidationError> errors) {
    if (countryCode.length < 2) {
      errors.add(ValidationError(
          field: 'countryCode', message: 'Enter a two-letter country code'));
    }
    if (countryCode.length > 2) {
      errors.add(ValidationError(
          field: 'countryCode', message: 'Enter a two-letter country code'));
    }
  }

  static void _validateFirstName(
      String firstName, List<ValidationError> errors) {
    if (firstName.length < 1) {
      errors.add(
          ValidationError(field: 'firstName', message: 'Enter a first name'));
    }
  }

  static void _validateLastName(String lastName, List<ValidationError> errors) {
    if (lastName.length < 1) {
      errors.add(
          ValidationError(field: 'lastName', message: 'Enter a last name'));
    }
  }

  static void _validateLine1(String line1, List<ValidationError> errors) {
    if (line1.length < 1) {
      errors.add(
          ValidationError(field: 'line1', message: 'Enter a street address'));
    }
  }

  static void _validatePostalCode(
      String postalCode, List<ValidationError> errors) {
    if (postalCode.length < 1) {
      errors.add(
          ValidationError(field: 'postalCode', message: 'Enter a postal code'));
    }
  }
}

/// @nodoc
abstract class _$CheckoutRequestCopyWith<$Res> {
  $Res call({
    AddressInput? billingAddress,
    String? cartId,
    String? email,
    AddressInput? shippingAddress,
  });

  _$AddressInputCopyWith<$Res>? get billingAddress;

  _$AddressInputCopyWith<$Res> get shippingAddress;
}

/// @nodoc
final class _$CheckoutRequestCopyWithImpl<$Res>
    implements _$CheckoutRequestCopyWith<$Res> {
  const _$CheckoutRequestCopyWithImpl(this._self, this._then);

  final CheckoutRequest _self;
  final $Res Function(CheckoutRequest) _then;

  @override
  @pragma('vm:prefer-inline')
  $Res call({
    Object? billingAddress = _checkoutRequestCopyWithUnset,
    Object? cartId = null,
    Object? email = null,
    Object? shippingAddress = null,
  }) {
    return _then(CheckoutRequest(
      cartId: cartId == null ? _self.cartId : cartId as String,
      email: email == null ? _self.email : email as String,
      shippingAddress: shippingAddress == null
          ? _self.shippingAddress
          : shippingAddress as AddressInput,
      billingAddress: identical(billingAddress, _checkoutRequestCopyWithUnset)
          ? _self.billingAddress
          : billingAddress as AddressInput?,
    ));
  }

  @override
  @pragma('vm:prefer-inline')
  _$AddressInputCopyWith<$Res>? get billingAddress {
    final billingAddressValue = _self.billingAddress;
    if (billingAddressValue == null) {
      return null;
    }

    return _$AddressInputCopyWithImpl<$Res>(
      billingAddressValue,
      (value) => call(billingAddress: value),
    );
  }

  @override
  @pragma('vm:prefer-inline')
  _$AddressInputCopyWith<$Res> get shippingAddress {
    return _$AddressInputCopyWithImpl<$Res>(
      _self.shippingAddress,
      (value) => call(shippingAddress: value),
    );
  }
}

extension _CheckoutRequestValidation on CheckoutRequest {
  static void _validateCartId(String cartId, List<ValidationError> errors) {
    if (cartId.length < 1) {
      errors.add(
          ValidationError(field: 'cartId', message: 'A checkout needs a cart'));
    }
  }

  static void _validateEmail(String email, List<ValidationError> errors) {
    if (email.length < 1) {
      errors.add(
          ValidationError(field: 'email', message: 'Enter an email address'));
    }
    if (!ValidationHelper.isEmail(email)) {
      errors.add(ValidationError(
          field: 'email', message: 'Enter a valid email address'));
    }
  }
}

final class $AddressInputSerializer
    implements Serializer<AddressInput, Map<String, Object?>> {
  const $AddressInputSerializer();

  @override
  Map<String, Object?> serialize(AddressInput value) =>
      _$AddressInputSerialize(value);
}

final class $AddressInputDeserializer
    implements Deserializer<AddressInput, Map<String, Object?>> {
  const $AddressInputDeserializer();

  @override
  AddressInput deserialize(Map<String, Object?> json) =>
      _$AddressInputDeserialize(json);
}

final class $CheckoutRequestSerializer
    implements Serializer<CheckoutRequest, Map<String, Object?>> {
  const $CheckoutRequestSerializer();

  @override
  Map<String, Object?> serialize(CheckoutRequest value) =>
      _$CheckoutRequestSerialize(value);
}

final class $CheckoutRequestDeserializer
    implements Deserializer<CheckoutRequest, Map<String, Object?>> {
  const $CheckoutRequestDeserializer();

  @override
  CheckoutRequest deserialize(Map<String, Object?> json) =>
      _$CheckoutRequestDeserialize(json);
}

Map<String, Object?> _$AddressInputSerialize(AddressInput instance) {
  return <String, Object?>{
    'city': instance.city,
    'country_code': instance.countryCode,
    'first_name': instance.firstName,
    'last_name': instance.lastName,
    'line1': instance.line1,
    'line2': instance.line2,
    'phone': instance.phone,
    'postal_code': instance.postalCode,
    'province': instance.province,
  };
}

Map<String, Object?> _$AddressInputToJson(AddressInput instance) =>
    _$AddressInputSerialize(instance);

// factory AddressInput.fromJson(Map<String, Object?> json) => _$AddressInputFromJson(json);
AddressInput _$AddressInputDeserialize(Map<String, Object?> json) {
  final cityValue = JsonHelper.as<String>(json['city'], 'city', 'String');
  final countryCodeValue = JsonHelper.as<String>(
    json['country_code'],
    'country_code',
    'String',
  );
  final firstNameValue = JsonHelper.as<String>(
    json['first_name'],
    'first_name',
    'String',
  );
  final lastNameValue = JsonHelper.as<String>(
    json['last_name'],
    'last_name',
    'String',
  );
  final line1Value = JsonHelper.as<String>(json['line1'], 'line1', 'String');
  final line2Value = json['line2'] == null
      ? null
      : JsonHelper.as<String>(json['line2'], 'line2', 'String');
  final phoneValue = json['phone'] == null
      ? null
      : JsonHelper.as<String>(json['phone'], 'phone', 'String');
  final postalCodeValue = JsonHelper.as<String>(
    json['postal_code'],
    'postal_code',
    'String',
  );
  final provinceValue = json['province'] == null
      ? null
      : JsonHelper.as<String>(json['province'], 'province', 'String');

  return AddressInput(
    firstName: firstNameValue,
    lastName: lastNameValue,
    line1: line1Value,
    city: cityValue,
    postalCode: postalCodeValue,
    countryCode: countryCodeValue,
    line2: line2Value,
    province: provinceValue,
    phone: phoneValue,
  );
}

AddressInput _$AddressInputFromJson(Map<String, Object?> json) =>
    _$AddressInputDeserialize(json);

Map<String, Object?> _$CheckoutRequestSerialize(CheckoutRequest instance) {
  return <String, Object?>{
    'billing_address': instance.billingAddress == null
        ? null
        : _$AddressInputSerialize((instance.billingAddress!)),
    'cart_id': instance.cartId,
    'email': instance.email,
    'shipping_address': _$AddressInputSerialize(instance.shippingAddress),
  };
}

Map<String, Object?> _$CheckoutRequestToJson(CheckoutRequest instance) =>
    _$CheckoutRequestSerialize(instance);

// factory CheckoutRequest.fromJson(Map<String, Object?> json) => _$CheckoutRequestFromJson(json);
CheckoutRequest _$CheckoutRequestDeserialize(Map<String, Object?> json) {
  final billingAddressValue = json['billing_address'] == null
      ? null
      : _$AddressInputDeserialize(
          JsonHelper.asMap(json['billing_address'], 'billing_address'));
  final cartIdValue = JsonHelper.as<String>(
    json['cart_id'],
    'cart_id',
    'String',
  );
  final emailValue = JsonHelper.as<String>(json['email'], 'email', 'String');
  final shippingAddressValue = _$AddressInputDeserialize(
    JsonHelper.asMap(json['shipping_address'], 'shipping_address'),
  );

  return CheckoutRequest(
    cartId: cartIdValue,
    email: emailValue,
    shippingAddress: shippingAddressValue,
    billingAddress: billingAddressValue,
  );
}

CheckoutRequest _$CheckoutRequestFromJson(Map<String, Object?> json) =>
    _$CheckoutRequestDeserialize(json);
