// GENERATED CODE - DO NOT MODIFY BY HAND
// coverage:ignore-file
// ignore_for_file: type=lint
// ignore_for_file: unused_element, unused_import, deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: use_function_type_syntax_for_parameters
// ignore_for_file: unnecessary_const, avoid_init_to_null
// ignore_for_file: invalid_override_different_default_values_named
// ignore_for_file: prefer_expression_function_bodies
// ignore_for_file: annotate_overrides, invalid_annotation_target
// ignore_for_file: unnecessary_question_mark
// Generated by dust.

part of 'order_transfer.dart';

mixin _$OrderTransferView implements Serializable {
  @override
  String toString() {
    final self = this as OrderTransferView;
    return 'OrderTransferView('
        'deliveryStatus: ${self.deliveryStatus}, '
        'expiresAt: ${self.expiresAt}, '
        'id: ${self.id}, '
        'orderId: ${self.orderId}, '
        'status: ${self.status}'
        ')';
  }

  @override
  bool operator ==(Object other) {
    final self = this as OrderTransferView;
    return identical(this, other) ||
        other is OrderTransferView &&
            runtimeType == other.runtimeType &&
            other.deliveryStatus == self.deliveryStatus &&
            other.expiresAt == self.expiresAt &&
            other.id == self.id &&
            other.orderId == self.orderId &&
            other.status == self.status;
  }

  @override
  int get hashCode {
    final self = this as OrderTransferView;
    return Object.hashAll([
      runtimeType,
      self.deliveryStatus,
      self.expiresAt,
      self.id,
      self.orderId,
      self.status,
    ]);
  }

  Map<String, Object?> serialize() =>
      _$OrderTransferViewSerialize(this as OrderTransferView);

  Map<String, Object?> toJson() => serialize();
}

mixin _$OrderTransferDecisionBody implements Validatable, Serializable {
  /// Validates this `OrderTransferDecisionBody`.
  ///
  /// Usage:
  /// ```dart
  /// final result = value.validate();
  /// if (result case Invalid(:final errors)) {
  ///   print(errors.first.message);
  /// }
  /// ```
  ValidationResult validate() {
    final self = this as OrderTransferDecisionBody;
    final errors = <ValidationError>[];
    _OrderTransferDecisionBodyValidation._validateToken(self.token, errors);
    return errors.isEmpty ? const Valid() : Invalid(errors);
  }

  /// Throws [ValidationException] when this `OrderTransferDecisionBody` is invalid.
  ///
  /// Usage:
  /// ```dart
  /// value.validateOrThrow();
  /// ```
  void validateOrThrow() {
    final result = validate();
    if (result case Invalid(errors: final errors)) {
      throw ValidationException(errors);
    }
  }

  Map<String, Object?> serialize() =>
      _$OrderTransferDecisionBodySerialize(this as OrderTransferDecisionBody);

  Map<String, Object?> toJson() => serialize();
}

extension _OrderTransferDecisionBodyValidation on OrderTransferDecisionBody {
  static void _validateToken(String token, List<ValidationError> errors) {
    if (token.length < 1) {
      errors.add(ValidationError(field: 'token', message: 'A transfer token is required'));
    }
    if (token.length > 512) {
      errors.add(ValidationError(field: 'token', message: 'A transfer token is required'));
    }
  }

}
final class $OrderTransferViewSerializer implements Serializer<OrderTransferView, Map<String, Object?>> {
  const $OrderTransferViewSerializer();

  @override
  Map<String, Object?> serialize(OrderTransferView value) => _$OrderTransferViewSerialize(value);
}
final class $OrderTransferViewDeserializer implements Deserializer<OrderTransferView, Map<String, Object?>> {
  const $OrderTransferViewDeserializer();

  @override
  OrderTransferView deserialize(Map<String, Object?> json) => _$OrderTransferViewDeserialize(json);
}
final class $OrderTransferDecisionBodySerializer implements Serializer<OrderTransferDecisionBody, Map<String, Object?>> {
  const $OrderTransferDecisionBodySerializer();

  @override
  Map<String, Object?> serialize(OrderTransferDecisionBody value) => _$OrderTransferDecisionBodySerialize(value);
}
final class $OrderTransferDecisionBodyDeserializer implements Deserializer<OrderTransferDecisionBody, Map<String, Object?>> {
  const $OrderTransferDecisionBodyDeserializer();

  @override
  OrderTransferDecisionBody deserialize(Map<String, Object?> json) => _$OrderTransferDecisionBodyDeserialize(json);
}
final class $OrderTransferStatusSerializer implements Serializer<OrderTransferStatus, Object?> {
  const $OrderTransferStatusSerializer();

  @override
  Object? serialize(OrderTransferStatus value) => _$OrderTransferStatusSerialize(value);
}
final class $OrderTransferStatusDeserializer implements Deserializer<OrderTransferStatus, Object?> {
  const $OrderTransferStatusDeserializer();

  @override
  OrderTransferStatus deserialize(Object? json) => _$OrderTransferStatusDeserialize(json);
}
final class $OrderTransferDeliveryStatusSerializer implements Serializer<OrderTransferDeliveryStatus, Object?> {
  const $OrderTransferDeliveryStatusSerializer();

  @override
  Object? serialize(OrderTransferDeliveryStatus value) => _$OrderTransferDeliveryStatusSerialize(value);
}
final class $OrderTransferDeliveryStatusDeserializer implements Deserializer<OrderTransferDeliveryStatus, Object?> {
  const $OrderTransferDeliveryStatusDeserializer();

  @override
  OrderTransferDeliveryStatus deserialize(Object? json) => _$OrderTransferDeliveryStatusDeserialize(json);
}

Map<String, Object?> _$OrderTransferViewSerialize(OrderTransferView instance) {
  return <String, Object?>{
    'delivery_status': _$OrderTransferDeliveryStatusSerialize(
      instance.deliveryStatus,
    ),
    'expires_at': instance.expiresAt.toIso8601String(),
    'id': instance.id,
    'order_id': instance.orderId,
    'status': _$OrderTransferStatusSerialize(instance.status),
  };
}

Map<String, Object?> _$OrderTransferViewToJson(OrderTransferView instance) =>
    _$OrderTransferViewSerialize(instance);

// factory OrderTransferView.fromJson(Map<String, Object?> json) => _$OrderTransferViewFromJson(json);
OrderTransferView _$OrderTransferViewDeserialize(Map<String, Object?> json) {
  final deliveryStatusValue = _$OrderTransferDeliveryStatusDeserialize(
    json['delivery_status'],
    'delivery_status',
  );
  final expiresAtValue = JsonHelper.asDateTime(
    json['expires_at'],
    'expires_at',
  );
  final idValue = JsonHelper.as<String>(json['id'], 'id', 'String');
  final orderIdValue = JsonHelper.as<String>(
    json['order_id'],
    'order_id',
    'String',
  );
  final statusValue = _$OrderTransferStatusDeserialize(
    json['status'],
    'status',
  );

  return OrderTransferView(
    id: idValue,
    orderId: orderIdValue,
    status: statusValue,
    deliveryStatus: deliveryStatusValue,
    expiresAt: expiresAtValue,
  );
}

OrderTransferView _$OrderTransferViewFromJson(Map<String, Object?> json) =>
    _$OrderTransferViewDeserialize(json);

Map<String, Object?> _$OrderTransferDecisionBodySerialize(OrderTransferDecisionBody instance) {
  return <String, Object?>{
    'token': instance.token,
  };
}

Map<String, Object?> _$OrderTransferDecisionBodyToJson(OrderTransferDecisionBody instance) =>
    _$OrderTransferDecisionBodySerialize(instance);

// factory OrderTransferDecisionBody.fromJson(Map<String, Object?> json) => _$OrderTransferDecisionBodyFromJson(json);
OrderTransferDecisionBody _$OrderTransferDecisionBodyDeserialize(Map<String, Object?> json) {
  final tokenValue = JsonHelper.as<String>(json['token'], 'token', 'String');

  return OrderTransferDecisionBody(token: tokenValue);
}

OrderTransferDecisionBody _$OrderTransferDecisionBodyFromJson(Map<String, Object?> json) =>
    _$OrderTransferDecisionBodyDeserialize(json);

Object? _$OrderTransferStatusSerialize(OrderTransferStatus instance) {
  return switch (instance) {
    OrderTransferStatus.requested => 'requested',
    OrderTransferStatus.accepted => 'accepted',
    OrderTransferStatus.declined => 'declined',
    OrderTransferStatus.expired => 'expired',
  };
}

Object? _$OrderTransferStatusToJson(OrderTransferStatus instance) =>
    _$OrderTransferStatusSerialize(instance);

OrderTransferStatus _$OrderTransferStatusDeserialize(Object? json, [String key = 'json']) {
  return switch (json) {
    'requested' => OrderTransferStatus.requested,
    'accepted' => OrderTransferStatus.accepted,
    'declined' => OrderTransferStatus.declined,
    'expired' => OrderTransferStatus.expired,
    _ => throw ArgumentError.value(json, key, 'unknown value for OrderTransferStatus at $key'),
  };
}

OrderTransferStatus _$OrderTransferStatusFromJson(Object? json, [String key = 'json']) =>
    _$OrderTransferStatusDeserialize(json, key);

Object? _$OrderTransferDeliveryStatusSerialize(OrderTransferDeliveryStatus instance) {
  return switch (instance) {
    OrderTransferDeliveryStatus.queued => 'queued',
    OrderTransferDeliveryStatus.sending => 'sending',
    OrderTransferDeliveryStatus.sent => 'sent',
    OrderTransferDeliveryStatus.cancelled => 'cancelled',
  };
}

Object? _$OrderTransferDeliveryStatusToJson(OrderTransferDeliveryStatus instance) =>
    _$OrderTransferDeliveryStatusSerialize(instance);

OrderTransferDeliveryStatus _$OrderTransferDeliveryStatusDeserialize(Object? json, [String key = 'json']) {
  return switch (json) {
    'queued' => OrderTransferDeliveryStatus.queued,
    'sending' => OrderTransferDeliveryStatus.sending,
    'sent' => OrderTransferDeliveryStatus.sent,
    'cancelled' => OrderTransferDeliveryStatus.cancelled,
    _ => throw ArgumentError.value(json, key, 'unknown value for OrderTransferDeliveryStatus at $key'),
  };
}

OrderTransferDeliveryStatus _$OrderTransferDeliveryStatusFromJson(Object? json, [String key = 'json']) =>
    _$OrderTransferDeliveryStatusDeserialize(json, key);
