// GENERATED CODE - DO NOT MODIFY BY HAND
// coverage:ignore-file
// ignore_for_file: type=lint
// ignore_for_file: unused_element, unused_import, deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: use_function_type_syntax_for_parameters
// ignore_for_file: unnecessary_const, avoid_init_to_null
// ignore_for_file: invalid_override_different_default_values_named
// ignore_for_file: prefer_expression_function_bodies
// ignore_for_file: annotate_overrides, invalid_annotation_target
// ignore_for_file: unnecessary_question_mark
// Generated by dust.

part of 'shipping_method.dart';

mixin _$ShippingMethod implements Serializable {
  @override
  String toString() {
    final self = this as ShippingMethod;
    return 'ShippingMethod('
        'amount: ${self.amount}, '
        'name: ${self.name}, '
        'optionId: ${self.optionId}'
        ')';
  }

  @override
  bool operator ==(Object other) {
    final self = this as ShippingMethod;
    return identical(this, other) ||
        other is ShippingMethod &&
            runtimeType == other.runtimeType &&
            other.amount == self.amount &&
            other.name == self.name &&
            other.optionId == self.optionId;
  }

  @override
  int get hashCode {
    final self = this as ShippingMethod;
    return Object.hashAll([
      runtimeType,
      self.amount,
      self.name,
      self.optionId,
    ]);
  }

  /// Creates a copy of this `ShippingMethod` with selected fields replaced.
  ///
  /// Usage:
  /// ```dart
  /// final updated = shippingMethod.copyWith(name: 'John');
  /// ```
  @pragma('vm:prefer-inline')
  _$ShippingMethodCopyWith<ShippingMethod> get copyWith => _$ShippingMethodCopyWithImpl<ShippingMethod>(this as ShippingMethod, (value) => value);

  Map<String, Object?> serialize() =>
      _$ShippingMethodSerialize(this as ShippingMethod);

  Map<String, Object?> toJson() => serialize();
}

// CopyWith API inspired by Freezed.

/// @nodoc
abstract class _$ShippingMethodCopyWith<$Res> {
  $Res call({
    Money? amount,
    String? name,
    String? optionId,
  });
}

/// @nodoc
final class _$ShippingMethodCopyWithImpl<$Res> implements _$ShippingMethodCopyWith<$Res> {
  const _$ShippingMethodCopyWithImpl(this._self, this._then);

  final ShippingMethod _self;
  final $Res Function(ShippingMethod) _then;

  @override
  @pragma('vm:prefer-inline')
  $Res call({
    Object? amount = null,
    Object? name = null,
    Object? optionId = null,
  }) {
    return _then(
      ShippingMethod(
        optionId: optionId == null ? _self.optionId : optionId as String,
        name: name == null ? _self.name : name as String,
        amount: amount == null ? _self.amount : amount as Money,
      )
    );
  }
}
final class $ShippingMethodSerializer implements Serializer<ShippingMethod, Map<String, Object?>> {
  const $ShippingMethodSerializer();

  @override
  Map<String, Object?> serialize(ShippingMethod value) => _$ShippingMethodSerialize(value);
}
final class $ShippingMethodDeserializer implements Deserializer<ShippingMethod, Map<String, Object?>> {
  const $ShippingMethodDeserializer();

  @override
  ShippingMethod deserialize(Map<String, Object?> json) => _$ShippingMethodDeserialize(json);
}

Map<String, Object?> _$ShippingMethodSerialize(ShippingMethod instance) {
  return <String, Object?>{
    'amount': instance.amount.toJson(),
    'name': instance.name,
    'option_id': instance.optionId,
  };
}

Map<String, Object?> _$ShippingMethodToJson(ShippingMethod instance) =>
    _$ShippingMethodSerialize(instance);

// factory ShippingMethod.fromJson(Map<String, Object?> json) => _$ShippingMethodFromJson(json);
ShippingMethod _$ShippingMethodDeserialize(Map<String, Object?> json) {
  final amountValue = Money.fromJson(
    JsonHelper.asMap(json['amount'], 'amount'),
  );
  final nameValue = JsonHelper.as<String>(json['name'], 'name', 'String');
  final optionIdValue = JsonHelper.as<String>(
    json['option_id'],
    'option_id',
    'String',
  );

  return ShippingMethod(
    optionId: optionIdValue,
    name: nameValue,
    amount: amountValue,
  );
}

ShippingMethod _$ShippingMethodFromJson(Map<String, Object?> json) =>
    _$ShippingMethodDeserialize(json);
