// GENERATED CODE - DO NOT MODIFY BY HAND
// coverage:ignore-file
// ignore_for_file: type=lint
// ignore_for_file: unused_element, unused_import, deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: use_function_type_syntax_for_parameters
// ignore_for_file: unnecessary_const, avoid_init_to_null
// ignore_for_file: invalid_override_different_default_values_named
// ignore_for_file: prefer_expression_function_bodies
// ignore_for_file: annotate_overrides, invalid_annotation_target
// ignore_for_file: unnecessary_question_mark
// Generated by dust.

part of 'shipping_price_rule.dart';

mixin _$ShippingPriceRule implements Serializable {
  @override
  String toString() {
    final self = this as ShippingPriceRule;
    return 'ShippingPriceRule('
        'attribute: ${self.attribute}, '
        'operator: ${self.operator}, '
        'value: ${self.value}'
        ')';
  }

  @override
  bool operator ==(Object other) {
    final self = this as ShippingPriceRule;
    return identical(this, other) ||
        other is ShippingPriceRule &&
            runtimeType == other.runtimeType &&
            other.attribute == self.attribute &&
            other.operator == self.operator &&
            other.value == self.value;
  }

  @override
  int get hashCode {
    final self = this as ShippingPriceRule;
    return Object.hashAll([
      runtimeType,
      self.attribute,
      self.operator,
      self.value,
    ]);
  }

  /// Creates a copy of this `ShippingPriceRule` with selected fields replaced.
  ///
  /// Usage:
  /// ```dart
  /// final updated = shippingPriceRule.copyWith(value: 1);
  /// ```
  @pragma('vm:prefer-inline')
  _$ShippingPriceRuleCopyWith<ShippingPriceRule> get copyWith => _$ShippingPriceRuleCopyWithImpl<ShippingPriceRule>(this as ShippingPriceRule, (value2) => value2);

  Map<String, Object?> serialize() =>
      _$ShippingPriceRuleSerialize(this as ShippingPriceRule);

  Map<String, Object?> toJson() => serialize();
}

// CopyWith API inspired by Freezed.

/// @nodoc
abstract class _$ShippingPriceRuleCopyWith<$Res> {
  $Res call({
    ShippingPriceRuleAttribute? attribute,
    ShippingPriceRuleOperator? operator,
    int? value,
  });
}

/// @nodoc
final class _$ShippingPriceRuleCopyWithImpl<$Res> implements _$ShippingPriceRuleCopyWith<$Res> {
  const _$ShippingPriceRuleCopyWithImpl(this._self, this._then);

  final ShippingPriceRule _self;
  final $Res Function(ShippingPriceRule) _then;

  @override
  @pragma('vm:prefer-inline')
  $Res call({
    Object? attribute = null,
    Object? operator = null,
    Object? value = null,
  }) {
    return _then(
      ShippingPriceRule(
        attribute: attribute == null ? _self.attribute : attribute as ShippingPriceRuleAttribute,
        operator: operator == null ? _self.operator : operator as ShippingPriceRuleOperator,
        value: value == null ? _self.value : value as int,
      )
    );
  }
}
final class $ShippingPriceRuleSerializer implements Serializer<ShippingPriceRule, Map<String, Object?>> {
  const $ShippingPriceRuleSerializer();

  @override
  Map<String, Object?> serialize(ShippingPriceRule value) => _$ShippingPriceRuleSerialize(value);
}
final class $ShippingPriceRuleDeserializer implements Deserializer<ShippingPriceRule, Map<String, Object?>> {
  const $ShippingPriceRuleDeserializer();

  @override
  ShippingPriceRule deserialize(Map<String, Object?> json) => _$ShippingPriceRuleDeserialize(json);
}
final class $ShippingPriceRuleAttributeSerializer implements Serializer<ShippingPriceRuleAttribute, Object?> {
  const $ShippingPriceRuleAttributeSerializer();

  @override
  Object? serialize(ShippingPriceRuleAttribute value) => _$ShippingPriceRuleAttributeSerialize(value);
}
final class $ShippingPriceRuleAttributeDeserializer implements Deserializer<ShippingPriceRuleAttribute, Object?> {
  const $ShippingPriceRuleAttributeDeserializer();

  @override
  ShippingPriceRuleAttribute deserialize(Object? json) => _$ShippingPriceRuleAttributeDeserialize(json);
}
final class $ShippingPriceRuleOperatorSerializer implements Serializer<ShippingPriceRuleOperator, Object?> {
  const $ShippingPriceRuleOperatorSerializer();

  @override
  Object? serialize(ShippingPriceRuleOperator value) => _$ShippingPriceRuleOperatorSerialize(value);
}
final class $ShippingPriceRuleOperatorDeserializer implements Deserializer<ShippingPriceRuleOperator, Object?> {
  const $ShippingPriceRuleOperatorDeserializer();

  @override
  ShippingPriceRuleOperator deserialize(Object? json) => _$ShippingPriceRuleOperatorDeserialize(json);
}

Map<String, Object?> _$ShippingPriceRuleSerialize(ShippingPriceRule instance) {
  return <String, Object?>{
    'attribute': _$ShippingPriceRuleAttributeSerialize(instance.attribute),
    'operator': _$ShippingPriceRuleOperatorSerialize(instance.operator),
    'value': instance.value,
  };
}

Map<String, Object?> _$ShippingPriceRuleToJson(ShippingPriceRule instance) =>
    _$ShippingPriceRuleSerialize(instance);

// factory ShippingPriceRule.fromJson(Map<String, Object?> json) => _$ShippingPriceRuleFromJson(json);
ShippingPriceRule _$ShippingPriceRuleDeserialize(Map<String, Object?> json) {
  final attributeValue = _$ShippingPriceRuleAttributeDeserialize(
    json['attribute'],
    'attribute',
  );
  final operatorValue = _$ShippingPriceRuleOperatorDeserialize(
    json['operator'],
    'operator',
  );
  final valueValue = JsonHelper.as<int>(json['value'], 'value', 'int');

  return ShippingPriceRule(
    attribute: attributeValue,
    operator: operatorValue,
    value: valueValue,
  );
}

ShippingPriceRule _$ShippingPriceRuleFromJson(Map<String, Object?> json) =>
    _$ShippingPriceRuleDeserialize(json);

Object? _$ShippingPriceRuleAttributeSerialize(ShippingPriceRuleAttribute instance) {
  return switch (instance) {
    ShippingPriceRuleAttribute.itemTotal => 'item_total',
  };
}

Object? _$ShippingPriceRuleAttributeToJson(ShippingPriceRuleAttribute instance) =>
    _$ShippingPriceRuleAttributeSerialize(instance);

ShippingPriceRuleAttribute _$ShippingPriceRuleAttributeDeserialize(Object? json, [String key = 'json']) {
  return switch (json) {
    'item_total' => ShippingPriceRuleAttribute.itemTotal,
    _ => throw ArgumentError.value(json, key, 'unknown value for ShippingPriceRuleAttribute at $key'),
  };
}

ShippingPriceRuleAttribute _$ShippingPriceRuleAttributeFromJson(Object? json, [String key = 'json']) =>
    _$ShippingPriceRuleAttributeDeserialize(json, key);

Object? _$ShippingPriceRuleOperatorSerialize(ShippingPriceRuleOperator instance) {
  return switch (instance) {
    ShippingPriceRuleOperator.gt => 'gt',
    ShippingPriceRuleOperator.gte => 'gte',
    ShippingPriceRuleOperator.lt => 'lt',
    ShippingPriceRuleOperator.lte => 'lte',
    ShippingPriceRuleOperator.eq => 'eq',
  };
}

Object? _$ShippingPriceRuleOperatorToJson(ShippingPriceRuleOperator instance) =>
    _$ShippingPriceRuleOperatorSerialize(instance);

ShippingPriceRuleOperator _$ShippingPriceRuleOperatorDeserialize(Object? json, [String key = 'json']) {
  return switch (json) {
    'gt' => ShippingPriceRuleOperator.gt,
    'gte' => ShippingPriceRuleOperator.gte,
    'lt' => ShippingPriceRuleOperator.lt,
    'lte' => ShippingPriceRuleOperator.lte,
    'eq' => ShippingPriceRuleOperator.eq,
    _ => throw ArgumentError.value(json, key, 'unknown value for ShippingPriceRuleOperator at $key'),
  };
}

ShippingPriceRuleOperator _$ShippingPriceRuleOperatorFromJson(Object? json, [String key = 'json']) =>
    _$ShippingPriceRuleOperatorDeserialize(json, key);
