// GENERATED CODE - DO NOT MODIFY BY HAND
// coverage:ignore-file
// ignore_for_file: type=lint
// ignore_for_file: unused_element, unused_import, deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: use_function_type_syntax_for_parameters
// ignore_for_file: unnecessary_const, avoid_init_to_null
// ignore_for_file: invalid_override_different_default_values_named
// ignore_for_file: prefer_expression_function_bodies
// ignore_for_file: annotate_overrides, invalid_annotation_target
// ignore_for_file: unnecessary_question_mark
// Generated by dust.

part of 'shipping_option.dart';

const DeepCollectionEquality _shippingOptionPriceRulesEquality = DeepCollectionEquality();

mixin _$ShippingOption implements Serializable {
  @override
  String toString() {
    final self = this as ShippingOption;
    return 'ShippingOption('
        'amount: ${self.amount}, '
        'name: ${self.name}, '
        'optionId: ${self.optionId}, '
        'priceRules: ${self.priceRules}'
        ')';
  }

  @override
  bool operator ==(Object other) {
    final self = this as ShippingOption;
    return identical(this, other) ||
        other is ShippingOption &&
            runtimeType == other.runtimeType &&
            other.amount == self.amount &&
            other.name == self.name &&
            other.optionId == self.optionId &&
            _shippingOptionPriceRulesEquality.equals(other.priceRules, self.priceRules);
  }

  @override
  int get hashCode {
    final self = this as ShippingOption;
    return Object.hashAll([
      runtimeType,
      self.amount,
      self.name,
      self.optionId,
      _shippingOptionPriceRulesEquality.hash(self.priceRules),
    ]);
  }

  /// Creates a copy of this `ShippingOption` with selected fields replaced.
  ///
  /// Usage:
  /// ```dart
  /// final updated = shippingOption.copyWith(name: 'John');
  /// ```
  @pragma('vm:prefer-inline')
  _$ShippingOptionCopyWith<ShippingOption> get copyWith => _$ShippingOptionCopyWithImpl<ShippingOption>(this as ShippingOption, (value) => value);

  Map<String, Object?> serialize() =>
      _$ShippingOptionSerialize(this as ShippingOption);

  Map<String, Object?> toJson() => serialize();
}

// CopyWith API inspired by Freezed.

/// @nodoc
abstract class _$ShippingOptionCopyWith<$Res> {
  $Res call({
    Money? amount,
    String? name,
    String? optionId,
    List<ShippingPriceRule>? priceRules,
  });
}

/// @nodoc
final class _$ShippingOptionCopyWithImpl<$Res> implements _$ShippingOptionCopyWith<$Res> {
  const _$ShippingOptionCopyWithImpl(this._self, this._then);

  final ShippingOption _self;
  final $Res Function(ShippingOption) _then;

  @override
  @pragma('vm:prefer-inline')
  $Res call({
    Object? amount = null,
    Object? name = null,
    Object? optionId = null,
    Object? priceRules = null,
  }) {
    return _then(
      ShippingOption(
        optionId: optionId == null ? _self.optionId : optionId as String,
        name: name == null ? _self.name : name as String,
        amount: amount == null ? _self.amount : amount as Money,
        priceRules: priceRules == null ? _self.priceRules : priceRules as List<ShippingPriceRule>,
      )
    );
  }
}
final class $ShippingOptionSerializer implements Serializer<ShippingOption, Map<String, Object?>> {
  const $ShippingOptionSerializer();

  @override
  Map<String, Object?> serialize(ShippingOption value) => _$ShippingOptionSerialize(value);
}
final class $ShippingOptionDeserializer implements Deserializer<ShippingOption, Map<String, Object?>> {
  const $ShippingOptionDeserializer();

  @override
  ShippingOption deserialize(Map<String, Object?> json) => _$ShippingOptionDeserialize(json);
}

Map<String, Object?> _$ShippingOptionSerialize(ShippingOption instance) {
  return <String, Object?>{
    'amount': instance.amount.toJson(),
    'name': instance.name,
    'option_id': instance.optionId,
    'price_rules': instance.priceRules
        .map((item) => item.toJson())
        .toList(),
  };
}

Map<String, Object?> _$ShippingOptionToJson(ShippingOption instance) =>
    _$ShippingOptionSerialize(instance);

// factory ShippingOption.fromJson(Map<String, Object?> json) => _$ShippingOptionFromJson(json);
ShippingOption _$ShippingOptionDeserialize(Map<String, Object?> json) {
  final amountValue = Money.fromJson(
    JsonHelper.asMap(json['amount'], 'amount'),
  );
  final nameValue = JsonHelper.as<String>(json['name'], 'name', 'String');
  final optionIdValue = JsonHelper.as<String>(
    json['option_id'],
    'option_id',
    'String',
  );
  final priceRulesValue = JsonHelper.decodeList(json['price_rules'], 'price_rules',
      (item, itemKey) => ShippingPriceRule.fromJson(JsonHelper.asMap(item, itemKey)));

  return ShippingOption(
    optionId: optionIdValue,
    name: nameValue,
    amount: amountValue,
    priceRules: priceRulesValue,
  );
}

ShippingOption _$ShippingOptionFromJson(Map<String, Object?> json) =>
    _$ShippingOptionDeserialize(json);
