// GENERATED CODE - DO NOT MODIFY BY HAND
// coverage:ignore-file
// ignore_for_file: type=lint
// ignore_for_file: unused_element, unused_import, deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: use_function_type_syntax_for_parameters
// ignore_for_file: unnecessary_const, avoid_init_to_null
// ignore_for_file: invalid_override_different_default_values_named
// ignore_for_file: prefer_expression_function_bodies
// ignore_for_file: annotate_overrides, invalid_annotation_target
// ignore_for_file: unnecessary_question_mark
// Generated by dust.

part of 'admin_order_state.dart';

const DeepCollectionEquality _adminOrderStateOrdersEquality = DeepCollectionEquality();
const DeepCollectionEquality _adminOrderStateRegionIdsEquality = DeepCollectionEquality();
const DeepCollectionEquality _adminOrderStateStatusesEquality = DeepCollectionEquality();

mixin _$AdminOrderState {
  @override
  String toString() {
    final self = this as AdminOrderState;
    return 'AdminOrderState('
        'count: ${self.count}, '
        'createdAt: ${self.createdAt}, '
        'failure: ${self.failure}, '
        'limit: ${self.limit}, '
        'offset: ${self.offset}, '
        'order: ${self.order}, '
        'orders: ${self.orders}, '
        'query: ${self.query}, '
        'regionIds: ${self.regionIds}, '
        'status: ${self.status}, '
        'statuses: ${self.statuses}, '
        'updatedAt: ${self.updatedAt}'
        ')';
  }

  @override
  bool operator ==(Object other) {
    final self = this as AdminOrderState;
    return identical(this, other) ||
        other is AdminOrderState &&
            runtimeType == other.runtimeType &&
            other.count == self.count &&
            other.createdAt == self.createdAt &&
            other.failure == self.failure &&
            other.limit == self.limit &&
            other.offset == self.offset &&
            other.order == self.order &&
            _adminOrderStateOrdersEquality.equals(other.orders, self.orders) &&
            other.query == self.query &&
            _adminOrderStateRegionIdsEquality.equals(other.regionIds, self.regionIds) &&
            other.status == self.status &&
            _adminOrderStateStatusesEquality.equals(other.statuses, self.statuses) &&
            other.updatedAt == self.updatedAt;
  }

  @override
  int get hashCode {
    final self = this as AdminOrderState;
    return Object.hashAll([
      runtimeType,
      self.count,
      self.createdAt,
      self.failure,
      self.limit,
      self.offset,
      self.order,
      _adminOrderStateOrdersEquality.hash(self.orders),
      self.query,
      _adminOrderStateRegionIdsEquality.hash(self.regionIds),
      self.status,
      _adminOrderStateStatusesEquality.hash(self.statuses),
      self.updatedAt,
    ]);
  }

  /// Creates a copy of this `AdminOrderState` with selected fields replaced.
  ///
  /// Usage:
  /// ```dart
  /// final updated = adminOrderState.copyWith(count: 1);
  /// ```
  @pragma('vm:prefer-inline')
  _$AdminOrderStateCopyWith<AdminOrderState> get copyWith => _$AdminOrderStateCopyWithImpl<AdminOrderState>(this as AdminOrderState, (value) => value);
}

// CopyWith API inspired by Freezed.

/// @nodoc
abstract class _$AdminOrderStateCopyWith<$Res> {
  $Res call({
    int? count,
    AdminDateFilter? createdAt,
    Option<String>? failure,
    int? limit,
    int? offset,
    AdminOrderOrder? order,
    List<AdminOrder>? orders,
    String? query,
    List<String>? regionIds,
    AdminOrderListStatus? status,
    List<AdminOrderStatus>? statuses,
    AdminDateFilter? updatedAt,
  });
}

/// @nodoc
final class _$AdminOrderStateCopyWithImpl<$Res> implements _$AdminOrderStateCopyWith<$Res> {
  const _$AdminOrderStateCopyWithImpl(this._self, this._then);

  final AdminOrderState _self;
  final $Res Function(AdminOrderState) _then;

  @override
  @pragma('vm:prefer-inline')
  $Res call({
    Object? count = null,
    Object? createdAt = null,
    Object? failure = null,
    Object? limit = null,
    Object? offset = null,
    Object? order = null,
    Object? orders = null,
    Object? query = null,
    Object? regionIds = null,
    Object? status = null,
    Object? statuses = null,
    Object? updatedAt = null,
  }) {
    return _then(
      AdminOrderState(
        status: status == null ? _self.status : status as AdminOrderListStatus,
        orders: orders == null ? _self.orders : orders as List<AdminOrder>,
        count: count == null ? _self.count : count as int,
        limit: limit == null ? _self.limit : limit as int,
        offset: offset == null ? _self.offset : offset as int,
        query: query == null ? _self.query : query as String,
        statuses: statuses == null ? _self.statuses : statuses as List<AdminOrderStatus>,
        regionIds: regionIds == null ? _self.regionIds : regionIds as List<String>,
        createdAt: createdAt == null ? _self.createdAt : createdAt as AdminDateFilter,
        updatedAt: updatedAt == null ? _self.updatedAt : updatedAt as AdminDateFilter,
        order: order == null ? _self.order : order as AdminOrderOrder,
        failure: failure == null ? _self.failure : failure as Option<String>,
      )
    );
  }
}
