// GENERATED CODE - DO NOT MODIFY BY HAND
// coverage:ignore-file
// ignore_for_file: type=lint
// ignore_for_file: unused_element, unused_import, deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: use_function_type_syntax_for_parameters
// ignore_for_file: unnecessary_const, avoid_init_to_null
// ignore_for_file: invalid_override_different_default_values_named
// ignore_for_file: prefer_expression_function_bodies
// ignore_for_file: annotate_overrides, invalid_annotation_target
// ignore_for_file: unnecessary_question_mark
// Generated by dust.

part of 'product.dart';

final class _$AdminProductReadRepository implements AdminProductReadRepository {
  const _$AdminProductReadRepository(this._db);

  final DatabaseExecutor _db;

  @override
  Future<Result<AdminProductDetailResponse?, SqlxError>> findById(String id) {
    return _db.fetchOptional<AdminProductDetailResponse>(
      r'''
SELECT product.id, product.title, product.subtitle, product.handle,
       product.description, product.discountable, product.thumbnail,
       product.material, product.origin_country,
       product.type_id AS product_type_id,
       product_type.value AS product_type,
       product.weight, product.length, product.width,
       product.height, product.status, collection.title AS collection_title,
       coalesce((
         SELECT json_group_array(json(ordered.image_json))
         FROM (
           SELECT json_object(
             'id', image.id,
             'url', image.url,
             'variant_ids', json(coalesce((
               SELECT json_group_array(link.variant_id)
               FROM product_image_variants link
               WHERE link.image_id = image.id
               ORDER BY link.variant_id
             ), '[]'))
           ) AS image_json
           FROM product_images image
           WHERE image.product_id = product.id AND image.deleted_at IS NULL
           ORDER BY image.rank, image.id
         ) ordered
       ), '[]') AS images,
       coalesce((
         SELECT json_group_array(json(ordered.option_json))
         FROM (
           SELECT json_object(
             'id', option.id, 'title', option.title,
             'values', json(coalesce((
               SELECT json_group_array(value_ordered.value)
               FROM (
                 SELECT value.value
                 FROM product_product_option_values availability
                 JOIN product_option_values value
                   ON value.id = availability.product_option_value_id
                 WHERE availability.product_product_option_id = link.id
                   AND value.deleted_at IS NULL
                   AND availability.deleted_at IS NULL
                 ORDER BY value.rank, value.id
               ) value_ordered
             ), '[]'))
           ) AS option_json
           FROM product_product_options link
           JOIN product_options option ON option.id = link.product_option_id
           WHERE link.product_id = product.id
             AND link.deleted_at IS NULL
             AND option.deleted_at IS NULL
           ORDER BY link.rowid
         ) ordered
       ), '[]') AS options,
       coalesce((
         SELECT json_group_array(json(ordered.variant_json))
         FROM (
           SELECT json_object(
             'id', variant.id, 'title', variant.title, 'sku', variant.sku,
             'material', variant.material, 'ean', variant.ean,
             'upc', variant.upc,
             'barcode', variant.barcode,
             'weight', variant.weight, 'width', variant.width,
             'length', variant.length, 'height', variant.height,
             'mid_code', variant.mid_code, 'hs_code', variant.hs_code,
             'origin_country', variant.origin_country,
             'inventory_quantity', variant.inventory_quantity,
             'manage_inventory', json(iif(variant.manage_inventory = 1,
                                          'true', 'false')),
             'allow_backorder', json(iif(variant.allow_backorder = 1,
                                         'true', 'false')),
             'prices', json(coalesce((
               SELECT json_group_array(json(price_ordered.price_json))
               FROM (
                 SELECT json_object(
                   'currency_code', price.currency_code,
                   'amount', price.amount
                 ) AS price_json
                 FROM variant_prices price
                 WHERE price.variant_id = variant.id
                 ORDER BY price.currency_code
               ) price_ordered
             ), '[]')),
             'option_values', json(coalesce((
               SELECT json_group_object(choice.option_id, value.value)
               FROM variant_option_values choice
               JOIN product_option_values value
                 ON value.id = choice.option_value_id
                AND value.option_id = choice.option_id
               WHERE choice.variant_id = variant.id
                 AND value.deleted_at IS NULL
             ), '{}'))
           ) AS variant_json
           FROM product_variants variant
           WHERE variant.product_id = product.id
             AND variant.deleted_at IS NULL
           ORDER BY variant.id
         ) ordered
       ), '[]') AS variants,
       coalesce((
         SELECT json_group_array(ordered.name)
         FROM (
           SELECT category.name
           FROM product_category_products link
           JOIN product_categories category ON category.id = link.category_id
           WHERE link.product_id = product.id
             AND category.deleted_at IS NULL
           ORDER BY link.rank, category.name
         ) ordered
       ), '[]') AS categories,
       coalesce((
         SELECT json_group_array(ordered.value)
         FROM (
           SELECT tag.value
           FROM product_tag_products link
           JOIN product_tags tag ON tag.id = link.tag_id
           WHERE link.product_id = product.id AND tag.deleted_at IS NULL
           ORDER BY tag.value
         ) ordered
       ), '[]') AS tags
FROM products product
LEFT JOIN product_collections collection
  ON collection.id = product.collection_id AND collection.deleted_at IS NULL
LEFT JOIN product_types product_type
  ON product_type.id = product.type_id AND product_type.deleted_at IS NULL
WHERE product.id = ? AND product.deleted_at IS NULL
''',
      [id],
      const $AdminProductDetailResponseRowDeserializer().deserialize,
    );
  }
}
