// GENERATED CODE - DO NOT MODIFY BY HAND
// coverage:ignore-file
// ignore_for_file: type=lint
// ignore_for_file: unused_element, unused_import, deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: use_function_type_syntax_for_parameters
// ignore_for_file: unnecessary_const, avoid_init_to_null
// ignore_for_file: invalid_override_different_default_values_named
// ignore_for_file: prefer_expression_function_bodies
// ignore_for_file: annotate_overrides, invalid_annotation_target
// ignore_for_file: unnecessary_question_mark
// Generated by dust.

part of 'list.dart';

final class _$CheckoutListRepository implements CheckoutListRepository {
  const _$CheckoutListRepository(this._db);

  final DatabaseExecutor _db;

  @override
  Future<Result<List<OrderResponse>, SqlxError>> ordersForCustomer(String customerId) {
    return _db.fetchAll<OrderResponse>(
      r'''
SELECT o.id, o.display_id, o.email, o.customer_id, o.currency_code, o.subtotal,
       o.shipping_total, o.discount_total, o.tax, o.total, o.status,
       o.payment_status, o.placed_at, o.region_id,
       o.shipping_option_id, o.shipping_name,
       payment.provider AS payment_provider,
       payment.amount AS payment_amount,
       payment.created_at AS payment_created_at,
       r.name AS region_name, r.tax_rate, r.tax_inclusive, r.countries,
       coalesce((
         SELECT json_group_array(json_object(
           'id', i.id, 'variant_id', i.variant_id,
           'product_id', i.product_id, 'product_handle', i.product_handle,
           'thumbnail', i.thumbnail, 'title', i.title,
           'variant_title', i.variant_title,
           'unit_price', json_object(
             'amount', i.unit_amount, 'currency_code', i.currency_code
           ),
           'quantity', i.quantity
         ))
         FROM order_items i WHERE i.order_id = o.id ORDER BY i.rowid
       ), '[]') AS items_json,
       json_object(
         'first_name', shipping.first_name, 'last_name', shipping.last_name,
         'company', shipping.company,
         'line1', shipping.line1, 'line2', shipping.line2,
         'city', shipping.city, 'province', shipping.province,
         'postal_code', shipping.postal_code,
         'country_code', shipping.country_code, 'phone', shipping.phone
       ) AS shipping_address_json,
       json_object(
         'first_name', coalesce(billing.first_name, shipping.first_name),
         'last_name', coalesce(billing.last_name, shipping.last_name),
         'company', CASE WHEN billing.order_id IS NULL
                         THEN shipping.company ELSE billing.company END,
         'line1', coalesce(billing.line1, shipping.line1),
         'line2', CASE WHEN billing.order_id IS NULL
                       THEN shipping.line2 ELSE billing.line2 END,
         'city', coalesce(billing.city, shipping.city),
         'province', CASE WHEN billing.order_id IS NULL
                          THEN shipping.province ELSE billing.province END,
         'postal_code', coalesce(billing.postal_code, shipping.postal_code),
         'country_code', coalesce(billing.country_code, shipping.country_code),
         'phone', CASE WHEN billing.order_id IS NULL
                       THEN shipping.phone ELSE billing.phone END
       ) AS billing_address_json
FROM orders o
JOIN regions r ON r.id = o.region_id
JOIN order_addresses shipping
  ON shipping.order_id = o.id AND shipping.kind = 'shipping'
LEFT JOIN order_addresses billing
  ON billing.order_id = o.id AND billing.kind = 'billing'
LEFT JOIN payment_collections payment
  ON payment.order_id = o.id AND payment.deleted_at IS NULL
WHERE o.customer_id = ?
ORDER BY o.placed_at DESC, o.id DESC
''',
      [customerId],
      const $OrderResponseRowDeserializer().deserialize,
    );
  }
}
