// GENERATED CODE - DO NOT MODIFY BY HAND
// coverage:ignore-file
// ignore_for_file: type=lint
// ignore_for_file: unused_element, unused_import, deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: use_function_type_syntax_for_parameters
// ignore_for_file: unnecessary_const, avoid_init_to_null
// ignore_for_file: invalid_override_different_default_values_named
// ignore_for_file: prefer_expression_function_bodies
// ignore_for_file: annotate_overrides, invalid_annotation_target
// ignore_for_file: unnecessary_question_mark
// Generated by dust.

part of 'read.dart';

final class _$CheckoutReadRepository implements CheckoutReadRepository {
  const _$CheckoutReadRepository(this._db);

  final DatabaseExecutor _db;

  @override
  Future<Result<OrderRow?, SqlxError>> findOrder(String id) {
    return _db.fetchOptional<OrderRow>(
      r'''
SELECT o.id, o.email, o.customer_id, o.currency_code, o.subtotal, o.tax,
       o.total, o.status, o.payment_status, o.placed_at, o.region_id,
       r.name AS region_name, r.tax_rate, r.tax_inclusive, r.countries
FROM orders o
JOIN regions r ON r.id = o.region_id
WHERE o.id = ?
''',
      [id],
      const $OrderRowRowDeserializer().deserialize,
    );
  }

  @override
  Future<Result<List<LineItemRow>, SqlxError>> itemsOf(String orderId) {
    return _db.fetchAll<LineItemRow>(
      r'''
SELECT id, variant_id, product_id, title, variant_title,
       unit_amount, currency_code, quantity
FROM order_items
WHERE order_id = ?
ORDER BY rowid
''',
      [orderId],
      const $LineItemRowRowDeserializer().deserialize,
    );
  }

  @override
  Future<Result<List<OrderAddressRow>, SqlxError>> addressesOf(String orderId) {
    return _db.fetchAll<OrderAddressRow>(
      r'''
SELECT kind, first_name, last_name, line1, line2, city, province,
       postal_code, country_code, phone
FROM order_addresses
WHERE order_id = ?
''',
      [orderId],
      const $OrderAddressRowRowDeserializer().deserialize,
    );
  }
}
