// GENERATED CODE - DO NOT MODIFY BY HAND
// coverage:ignore-file
// ignore_for_file: type=lint
// ignore_for_file: unused_element, unused_import, deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: use_function_type_syntax_for_parameters
// ignore_for_file: unnecessary_const, avoid_init_to_null
// ignore_for_file: invalid_override_different_default_values_named
// ignore_for_file: prefer_expression_function_bodies
// ignore_for_file: annotate_overrides, invalid_annotation_target
// ignore_for_file: unnecessary_question_mark
// Generated by dust.

part of 'model.dart';

mixin _$OrderReturnResponse implements Serializable {
  Map<String, Object?> serialize() =>
      _$OrderReturnResponseSerialize(this as OrderReturnResponse);

  Map<String, Object?> toJson() => serialize();
}

final class $OrderReturnResponseSerializer implements Serializer<OrderReturnResponse, Map<String, Object?>> {
  const $OrderReturnResponseSerializer();

  @override
  Map<String, Object?> serialize(OrderReturnResponse value) => _$OrderReturnResponseSerialize(value);
}
OrderReturnCandidate _$OrderReturnCandidateFromRow(Row row) {
  return OrderReturnCandidate(
    status: row.read<String>('status'),
    paymentStatus: row.read<String>('payment_status'),
  );
}

/// Row deserializer for [OrderReturnCandidate].
final class $OrderReturnCandidateRowDeserializer implements RowDeserializer<OrderReturnCandidate> {
  const $OrderReturnCandidateRowDeserializer();

  @override
  OrderReturnCandidate deserialize(Row row) => _$OrderReturnCandidateFromRow(row);
}

/// Typed row query terminals for [OrderReturnCandidate].
///
/// Resolved from the static type of the receiver, so a row type with no
/// `FromRow` has no terminals and the call does not compile.
extension $OrderReturnCandidateQuery on QueryAs<OrderReturnCandidate> {
  /// Fetches exactly one row.
  Future<OrderReturnCandidate> fetchOne(DatabaseExecutor db) =>
      fetchOneWith(db, _$OrderReturnCandidateFromRow);

  /// Fetches zero or one row.
  Future<OrderReturnCandidate?> fetchOptional(DatabaseExecutor db) =>
      fetchOptionalWith(db, _$OrderReturnCandidateFromRow);

  /// Fetches every row.
  Future<List<OrderReturnCandidate>> fetchAll(DatabaseExecutor db) =>
      fetchAllWith(db, _$OrderReturnCandidateFromRow);
}

OrderReturnItemCandidate _$OrderReturnItemCandidateFromRow(Row row) {
  return OrderReturnItemCandidate(
    id: row.read<String>('id'),
    quantity: row.read<int>('quantity'),
    requestedQuantity: row.read<int>('requested_quantity'),
  );
}

/// Row deserializer for [OrderReturnItemCandidate].
final class $OrderReturnItemCandidateRowDeserializer implements RowDeserializer<OrderReturnItemCandidate> {
  const $OrderReturnItemCandidateRowDeserializer();

  @override
  OrderReturnItemCandidate deserialize(Row row) => _$OrderReturnItemCandidateFromRow(row);
}

/// Typed row query terminals for [OrderReturnItemCandidate].
///
/// Resolved from the static type of the receiver, so a row type with no
/// `FromRow` has no terminals and the call does not compile.
extension $OrderReturnItemCandidateQuery on QueryAs<OrderReturnItemCandidate> {
  /// Fetches exactly one row.
  Future<OrderReturnItemCandidate> fetchOne(DatabaseExecutor db) =>
      fetchOneWith(db, _$OrderReturnItemCandidateFromRow);

  /// Fetches zero or one row.
  Future<OrderReturnItemCandidate?> fetchOptional(DatabaseExecutor db) =>
      fetchOptionalWith(db, _$OrderReturnItemCandidateFromRow);

  /// Fetches every row.
  Future<List<OrderReturnItemCandidate>> fetchAll(DatabaseExecutor db) =>
      fetchAllWith(db, _$OrderReturnItemCandidateFromRow);
}

OrderReturnResponse _$OrderReturnResponseFromRow(Row row) {
  return OrderReturnResponse(
    id: row.read<String>('id'),
    displayId: row.read<int>('display_id'),
    orderId: row.read<String>('order_id'),
    status: _OrderReturnStatusSqlx().decode(row.read<String>('status')),
    itemQuantity: row.read<int>('item_quantity'),
    requestedAt: row.readDateTime('requested_at'),
  );
}

/// Row deserializer for [OrderReturnResponse].
final class $OrderReturnResponseRowDeserializer implements RowDeserializer<OrderReturnResponse> {
  const $OrderReturnResponseRowDeserializer();

  @override
  OrderReturnResponse deserialize(Row row) => _$OrderReturnResponseFromRow(row);
}

/// Typed row query terminals for [OrderReturnResponse].
///
/// Resolved from the static type of the receiver, so a row type with no
/// `FromRow` has no terminals and the call does not compile.
extension $OrderReturnResponseQuery on QueryAs<OrderReturnResponse> {
  /// Fetches exactly one row.
  Future<OrderReturnResponse> fetchOne(DatabaseExecutor db) =>
      fetchOneWith(db, _$OrderReturnResponseFromRow);

  /// Fetches zero or one row.
  Future<OrderReturnResponse?> fetchOptional(DatabaseExecutor db) =>
      fetchOptionalWith(db, _$OrderReturnResponseFromRow);

  /// Fetches every row.
  Future<List<OrderReturnResponse>> fetchAll(DatabaseExecutor db) =>
      fetchAllWith(db, _$OrderReturnResponseFromRow);
}

Map<String, Object?> _$OrderReturnResponseSerialize(OrderReturnResponse instance) {
  return <String, Object?>{
    'display_id': instance.displayId,
    'id': instance.id,
    'item_quantity': instance.itemQuantity,
    'order_id': instance.orderId,
    'requested_at': instance.requestedAt.toIso8601String(),
    'status': JsonHelper.encodeWithCodec<OrderReturnStatus, Object?>(
      (_OrderReturnStatusCodec()),
      instance.status,
    ),
  };
}

Map<String, Object?> _$OrderReturnResponseToJson(OrderReturnResponse instance) =>
    _$OrderReturnResponseSerialize(instance);
