// GENERATED CODE - DO NOT MODIFY BY HAND
// coverage:ignore-file
// ignore_for_file: type=lint
// ignore_for_file: unused_element, unused_import, deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: use_function_type_syntax_for_parameters
// ignore_for_file: unnecessary_const, avoid_init_to_null
// ignore_for_file: invalid_override_different_default_values_named
// ignore_for_file: prefer_expression_function_bodies
// ignore_for_file: annotate_overrides, invalid_annotation_target
// ignore_for_file: unnecessary_question_mark
// Generated by dust.

part of 'cancel_fulfillment_model.dart';

AdminCancelFulfillmentTarget _$AdminCancelFulfillmentTargetFromRow(Row row) {
  return AdminCancelFulfillmentTarget(
    providerId: row.read<String>('provider_id'),
    canceled: row.readBool('canceled'),
    shipped: row.readBool('shipped'),
    delivered: row.readBool('delivered'),
  );
}

/// Row deserializer for [AdminCancelFulfillmentTarget].
final class $AdminCancelFulfillmentTargetRowDeserializer implements RowDeserializer<AdminCancelFulfillmentTarget> {
  const $AdminCancelFulfillmentTargetRowDeserializer();

  @override
  AdminCancelFulfillmentTarget deserialize(Row row) => _$AdminCancelFulfillmentTargetFromRow(row);
}

/// Typed row query terminals for [AdminCancelFulfillmentTarget].
///
/// Resolved from the static type of the receiver, so a row type with no
/// `FromRow` has no terminals and the call does not compile.
extension $AdminCancelFulfillmentTargetQuery on QueryAs<AdminCancelFulfillmentTarget> {
  /// Fetches exactly one row.
  Future<AdminCancelFulfillmentTarget> fetchOne(DatabaseExecutor db) =>
      fetchOneWith(db, _$AdminCancelFulfillmentTargetFromRow);

  /// Fetches zero or one row.
  Future<AdminCancelFulfillmentTarget?> fetchOptional(DatabaseExecutor db) =>
      fetchOptionalWith(db, _$AdminCancelFulfillmentTargetFromRow);

  /// Fetches every row.
  Future<List<AdminCancelFulfillmentTarget>> fetchAll(DatabaseExecutor db) =>
      fetchAllWith(db, _$AdminCancelFulfillmentTargetFromRow);
}
