/// Stable supported subset of Medusa's default order export graph.
const adminOrderExportHeaders = <String>[
  'Order Id',
  'Display Id',
  'Status',
  'Payment Status',
  'Fulfillment Status',
  'Created At',
  'Updated At',
  'Email',
  'Customer Name',
  'Currency Code',
  'Subtotal',
  'Shipping Total',
  'Discount Total',
  'Tax Total',
  'Total',
  'Shipping Method',
  'Promotion Code',
  'Item Id',
  'Item Title',
  'Item Variant',
  'Item Quantity',
  'Item Unit Price',
  'Item Total',
  'Shipping Name',
  'Shipping Company',
  'Shipping Address 1',
  'Shipping Address 2',
  'Shipping City',
  'Shipping Province',
  'Shipping Postal Code',
  'Shipping Country Code',
  'Shipping Phone',
  'Billing Name',
  'Billing Company',
  'Billing Address 1',
  'Billing Address 2',
  'Billing City',
  'Billing Province',
  'Billing Postal Code',
  'Billing Country Code',
  'Billing Phone',
  'Payment Provider',
  'Payment Amount',
  'Payment Record Status',
  'Payment Captured At',
];
