// GENERATED CODE - DO NOT MODIFY BY HAND
// coverage:ignore-file
// ignore_for_file: type=lint
// ignore_for_file: unused_element, unused_import, deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: use_function_type_syntax_for_parameters
// ignore_for_file: unnecessary_const, avoid_init_to_null
// ignore_for_file: invalid_override_different_default_values_named
// ignore_for_file: prefer_expression_function_bodies
// ignore_for_file: annotate_overrides, invalid_annotation_target
// ignore_for_file: unnecessary_question_mark
// Generated by dust.

part of 'admin_customer_delete_view_model.dart';

/// Base class generated for AdminCustomerDeleteViewModel.
///
/// Extend it from your ViewModel and forward typed args:
///
/// ```dart
/// final class AdminCustomerDeleteViewModel extends $AdminCustomerDeleteViewModel {
///   AdminCustomerDeleteViewModel(super.args);
/// }
/// ```
abstract class $AdminCustomerDeleteViewModel extends ViewModelBase<AdminCustomerDeleteState, AdminCustomerDeleteViewModelArgs> {
  $AdminCustomerDeleteViewModel(super.args) : super(initialState: const AdminCustomerDeleteState());
}

/// Reads AdminCustomerDeleteViewModel state from `BuildContext`.
///
/// Read `value` when the widget should rebuild for any state change.
///
/// ```dart
/// final state = context.watchAdminCustomerDeleteViewModel().value;
/// ```
class _$AdminCustomerDeleteViewModelProxy {
  _$AdminCustomerDeleteViewModelProxy(this._context);

  final BuildContext _context;

  AdminCustomerDeleteState get value {
    return AdminCustomerDeleteViewModelScope.of(_context).value;
  }
}

/// Rebuilds when a selected AdminCustomerDeleteState value changes.
///
/// Use this for widgets that depend on one field or derived value.
class AdminCustomerDeleteViewModelSelector<R> extends StatefulWidget {
  const AdminCustomerDeleteViewModelSelector({
    super.key,
    required this.selector,
    required this.builder,
    this.child,
    this.equals,
  });

  final R Function(AdminCustomerDeleteState state) selector;
  final Widget Function(BuildContext context, R value, Widget? child) builder;
  final Widget? child;
  final bool Function(R previous, R next)? equals;

  @override
  State<AdminCustomerDeleteViewModelSelector<R>> createState() => _AdminCustomerDeleteViewModelSelectorState<R>();
}

class _AdminCustomerDeleteViewModelSelectorState<R> extends State<AdminCustomerDeleteViewModelSelector<R>> {
  AdminCustomerDeleteViewModel? _viewModel;
  R? _selected;
  bool _hasSelected = false;

  @override
  void didChangeDependencies() {
    super.didChangeDependencies();
    final nextViewModel = AdminCustomerDeleteViewModelScope._watchInstance(context);
    if (identical(_viewModel, nextViewModel)) return;
    _viewModel?.removeListener(_onViewModelStateChanged);
    _viewModel = nextViewModel;
    nextViewModel.addListener(_onViewModelStateChanged);
    _selectCurrent(force: true);
  }

  @override
  void didUpdateWidget(AdminCustomerDeleteViewModelSelector<R> oldWidget) {
    super.didUpdateWidget(oldWidget);
    _selectCurrent(force: true);
  }

  void _onViewModelStateChanged() {
    _selectCurrent();
  }

  void _selectCurrent({bool force = false}) {
    final viewModel = _viewModel;
    if (viewModel == null) return;
    final nextSelected = widget.selector(viewModel.value);
    if (!_hasSelected) {
      _selected = nextSelected;
      _hasSelected = true;
      return;
    }
    final previousSelected = _selected as R;
    final equals = widget.equals;
    final unchanged = equals == null
        ? previousSelected == nextSelected
        : equals(previousSelected, nextSelected);
    if (!force && unchanged) return;
    if (force || !mounted) {
      _selected = nextSelected;
    } else {
      setState(() {
        _selected = nextSelected;
      });
    }
  }

  @override
  void dispose() {
    _viewModel?.removeListener(_onViewModelStateChanged);
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    if (!_hasSelected) {
      _selectCurrent(force: true);
    }
    return widget.builder(context, _selected as R, widget.child);
  }
}

/// Creates and provides AdminCustomerDeleteViewModel to descendants.
///
/// The default constructor owns the ViewModel. Use `.value` for externally
/// owned ViewModels.
///
/// ```dart
/// AdminCustomerDeleteViewModelScope(
///   args: (context) => AdminCustomerDeleteViewModelArgs(...),
///   create: (context, args) => AdminCustomerDeleteViewModel(args),
///   child: const FeaturePage(),
/// )
/// ```
class AdminCustomerDeleteViewModelScope extends StatefulWidget {
  /// Creates and owns AdminCustomerDeleteViewModel from typed args.
  const AdminCustomerDeleteViewModelScope({
    super.key,
    required this.args,
    required this.create,
    required this.child,
    this.identity,
  }) : value = null;

  /// Provides an externally owned AdminCustomerDeleteViewModel without disposing it.
  const AdminCustomerDeleteViewModelScope.value({
    super.key,
    required AdminCustomerDeleteViewModel this.value,
    required this.child,
  }) : args = null,
       create = null,
       identity = null;

  final AdminCustomerDeleteViewModelArgs Function(BuildContext context)? args;
  final AdminCustomerDeleteViewModel Function(BuildContext context, AdminCustomerDeleteViewModelArgs args)? create;
  final Object? Function(BuildContext context)? identity;
  final AdminCustomerDeleteViewModel? value;
  final Widget child;

  /// Reads AdminCustomerDeleteViewModel without rebuilding when state changes.
  static AdminCustomerDeleteViewModel read(BuildContext context) {
    final scope = context
        .getElementForInheritedWidgetOfExactType<_AdminCustomerDeleteViewModelInstance>()
        ?.widget as _AdminCustomerDeleteViewModelInstance?;
    if (scope == null) throw StateError('No AdminCustomerDeleteViewModelScope found in context.');
    return scope.viewModel;
  }

  static AdminCustomerDeleteViewModel _watchInstance(BuildContext context) {
    final scope = context.dependOnInheritedWidgetOfExactType<_AdminCustomerDeleteViewModelInstance>();
    if (scope == null) throw StateError('No AdminCustomerDeleteViewModelScope found in context.');
    return scope.viewModel;
  }

  /// Watches AdminCustomerDeleteViewModel and rebuilds when state changes.
  static AdminCustomerDeleteViewModel of(BuildContext context) {
    final scope = context.dependOnInheritedWidgetOfExactType<_AdminCustomerDeleteViewModelInherited>();
    if (scope == null) throw StateError('No AdminCustomerDeleteViewModelScope found in context.');
    return scope.viewModel;
  }

  @override
  State<AdminCustomerDeleteViewModelScope> createState() => _AdminCustomerDeleteViewModelScopeState();
}

class _AdminCustomerDeleteViewModelScopeState extends State<AdminCustomerDeleteViewModelScope> {
  AdminCustomerDeleteViewModel? _viewModel;
  Object? _identity;
  bool _ownsViewModel = false;

  @override
  void didChangeDependencies() {
    super.didChangeDependencies();
    final external = widget.value;
    if (external != null) {
      _replaceViewModel(external, ownsViewModel: false, notify: false);
      return;
    }
    final nextIdentity = widget.identity?.call(context);
    if (_viewModel == null || nextIdentity != _identity) {
      _identity = nextIdentity;
      _replaceViewModel(_createOwnedViewModel(), ownsViewModel: true, notify: false);
    }
  }

  @override
  void didUpdateWidget(AdminCustomerDeleteViewModelScope oldWidget) {
    super.didUpdateWidget(oldWidget);
    final external = widget.value;
    if (external != null) {
      _replaceViewModel(external, ownsViewModel: false);
    } else if (oldWidget.value != null) {
      _identity = widget.identity?.call(context);
      _replaceViewModel(_createOwnedViewModel(), ownsViewModel: true);
    } else {
      final nextIdentity = widget.identity?.call(context);
      if (nextIdentity != _identity) {
        _identity = nextIdentity;
        _replaceViewModel(_createOwnedViewModel(), ownsViewModel: true);
      }
    }
  }

  AdminCustomerDeleteViewModel _createOwnedViewModel() {
    final argsFactory = widget.args;
    final create = widget.create;
    if (argsFactory == null || create == null) {
      throw StateError('Owned AdminCustomerDeleteViewModelScope requires args and create.');
    }
    late final AdminCustomerDeleteViewModel created;
    try {
      created = create(context, argsFactory(context));
    } catch (error, stackTrace) {
      Error.throwWithStackTrace(error, stackTrace);
    }
    return created;
  }

  void _replaceViewModel(
    AdminCustomerDeleteViewModel nextViewModel, {
    required bool ownsViewModel,
    bool notify = true,
  }) {
    final previous = _viewModel;
    if (identical(previous, nextViewModel)) {
      _ownsViewModel = ownsViewModel;
      _scheduleInit(nextViewModel);
      if (notify && mounted) setState(() {});
      return;
    }
    previous?.removeListener(_onViewModelStateChanged);
    if (_ownsViewModel) previous?.dispose();
    _viewModel = nextViewModel;
    _ownsViewModel = ownsViewModel;
    nextViewModel.addListener(_onViewModelStateChanged);
    _scheduleInit(nextViewModel);
    if (notify && mounted) setState(() {});
  }

  void _scheduleInit(AdminCustomerDeleteViewModel viewModel) {
    scheduleMicrotask(() async {
      if (!mounted || !identical(_viewModel, viewModel)) return;
      try {
        await viewModel.init();
      } catch (error, stackTrace) {
        FlutterError.reportError(
          FlutterErrorDetails(
            exception: error,
            stack: stackTrace,
            library: 'dust state',
            context: ErrorDescription('AdminCustomerDeleteViewModelScope init failed'),
          ),
        );
      }
    });
  }

  void _onViewModelStateChanged() {
    if (mounted) setState(() {});
  }

  @override
  void dispose() {
    final viewModel = _viewModel;
    viewModel?.removeListener(_onViewModelStateChanged);
    if (_ownsViewModel) viewModel?.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    final viewModel = _viewModel;
    if (viewModel == null) {
      throw StateError('AdminCustomerDeleteViewModelScope built before its view model was initialized.');
    }
    return _AdminCustomerDeleteViewModelInstance(
      viewModel: viewModel,
      child: _AdminCustomerDeleteViewModelInherited(
        viewModel: viewModel,
        state: viewModel.value,
        child: widget.child,
      ),
    );
  }
}

class _AdminCustomerDeleteViewModelInstance extends InheritedWidget {
  const _AdminCustomerDeleteViewModelInstance({required this.viewModel, required super.child});

  final AdminCustomerDeleteViewModel viewModel;

  @override
  bool updateShouldNotify(_AdminCustomerDeleteViewModelInstance oldWidget) {
    return !identical(viewModel, oldWidget.viewModel);
  }
}

class _AdminCustomerDeleteViewModelInherited extends InheritedWidget {
  const _AdminCustomerDeleteViewModelInherited({required this.viewModel, required this.state, required super.child});

  final AdminCustomerDeleteViewModel viewModel;
  final AdminCustomerDeleteState state;

  @override
  bool updateShouldNotify(_AdminCustomerDeleteViewModelInherited oldWidget) {
    return !identical(viewModel, oldWidget.viewModel) || state != oldWidget.state;
  }
}

/// Handles one-shot effects from AdminCustomerDeleteViewModel.
///
/// Effects are delivered without changing state and do not rebuild `child`.
///
/// ```dart
/// AdminCustomerDeleteViewModelListener(
///   listener: onEffect,
///   child: const FeaturePage(),
/// )
/// ```
class AdminCustomerDeleteViewModelListener extends StatefulWidget {
  const AdminCustomerDeleteViewModelListener({super.key, required this.listener, required this.child});

  final void Function(BuildContext context, Object effect) listener;
  final Widget child;

  @override
  State<AdminCustomerDeleteViewModelListener> createState() => _AdminCustomerDeleteViewModelListenerState();
}

class _AdminCustomerDeleteViewModelListenerState extends State<AdminCustomerDeleteViewModelListener> {
  StreamSubscription<Object>? _sub;
  AdminCustomerDeleteViewModel? _viewModel;

  @override
  void didChangeDependencies() {
    super.didChangeDependencies();
    final nextViewModel = AdminCustomerDeleteViewModelScope._watchInstance(context);
    if (_viewModel == nextViewModel) return;
    _sub?.cancel();
    _viewModel = nextViewModel;
    _sub = nextViewModel.effects.listen(_onEffect);
  }

  void _onEffect(Object effect) {
    if (mounted) widget.listener(context, effect);
  }

  @override
  void dispose() {
    _sub?.cancel();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) => widget.child;
}

/// BuildContext helpers generated for AdminCustomerDeleteViewModel.
///
/// ```dart
/// final vm = context.readAdminCustomerDeleteViewModel();
/// final state = context.watchAdminCustomerDeleteViewModel().value;
/// ```
extension AdminCustomerDeleteViewModelBuildContext on BuildContext {
  _$AdminCustomerDeleteViewModelProxy watchAdminCustomerDeleteViewModel() {
    return _$AdminCustomerDeleteViewModelProxy(this);
  }

  AdminCustomerDeleteViewModel readAdminCustomerDeleteViewModel() => AdminCustomerDeleteViewModelScope.read(this);
}
