// GENERATED CODE - DO NOT MODIFY BY HAND
// coverage:ignore-file
// ignore_for_file: type=lint
// ignore_for_file: unused_element, unused_import, deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: use_function_type_syntax_for_parameters
// ignore_for_file: unnecessary_const, avoid_init_to_null
// ignore_for_file: invalid_override_different_default_values_named
// ignore_for_file: prefer_expression_function_bodies
// ignore_for_file: annotate_overrides, invalid_annotation_target
// ignore_for_file: unnecessary_question_mark
// Generated by dust.

part of 'admin_customer_detail_view_model.dart';

/// Base class generated for AdminCustomerDetailViewModel.
///
/// Extend it from your ViewModel and forward typed args:
///
/// ```dart
/// final class AdminCustomerDetailViewModel extends $AdminCustomerDetailViewModel {
///   AdminCustomerDetailViewModel(super.args);
/// }
/// ```
abstract class $AdminCustomerDetailViewModel extends ViewModelBase<AdminCustomerDetailState, AdminCustomerDetailViewModelArgs> {
  $AdminCustomerDetailViewModel(super.args) : super(initialState: const AdminCustomerDetailState());
}

/// Reads AdminCustomerDetailViewModel state from `BuildContext`.
///
/// Read `value` when the widget should rebuild for any state change.
///
/// ```dart
/// final state = context.watchAdminCustomerDetailViewModel().value;
/// ```
class _$AdminCustomerDetailViewModelProxy {
  _$AdminCustomerDetailViewModelProxy(this._context);

  final BuildContext _context;

  AdminCustomerDetailState get value {
    return AdminCustomerDetailViewModelScope.of(_context).value;
  }
}

/// Rebuilds when a selected AdminCustomerDetailState value changes.
///
/// Use this for widgets that depend on one field or derived value.
class AdminCustomerDetailViewModelSelector<R> extends StatefulWidget {
  const AdminCustomerDetailViewModelSelector({
    super.key,
    required this.selector,
    required this.builder,
    this.child,
    this.equals,
  });

  final R Function(AdminCustomerDetailState state) selector;
  final Widget Function(BuildContext context, R value, Widget? child) builder;
  final Widget? child;
  final bool Function(R previous, R next)? equals;

  @override
  State<AdminCustomerDetailViewModelSelector<R>> createState() => _AdminCustomerDetailViewModelSelectorState<R>();
}

class _AdminCustomerDetailViewModelSelectorState<R> extends State<AdminCustomerDetailViewModelSelector<R>> {
  AdminCustomerDetailViewModel? _viewModel;
  R? _selected;
  bool _hasSelected = false;

  @override
  void didChangeDependencies() {
    super.didChangeDependencies();
    final nextViewModel = AdminCustomerDetailViewModelScope._watchInstance(context);
    if (identical(_viewModel, nextViewModel)) return;
    _viewModel?.removeListener(_onViewModelStateChanged);
    _viewModel = nextViewModel;
    nextViewModel.addListener(_onViewModelStateChanged);
    _selectCurrent(force: true);
  }

  @override
  void didUpdateWidget(AdminCustomerDetailViewModelSelector<R> oldWidget) {
    super.didUpdateWidget(oldWidget);
    _selectCurrent(force: true);
  }

  void _onViewModelStateChanged() {
    _selectCurrent();
  }

  void _selectCurrent({bool force = false}) {
    final viewModel = _viewModel;
    if (viewModel == null) return;
    final nextSelected = widget.selector(viewModel.value);
    if (!_hasSelected) {
      _selected = nextSelected;
      _hasSelected = true;
      return;
    }
    final previousSelected = _selected as R;
    final equals = widget.equals;
    final unchanged = equals == null
        ? previousSelected == nextSelected
        : equals(previousSelected, nextSelected);
    if (!force && unchanged) return;
    if (force || !mounted) {
      _selected = nextSelected;
    } else {
      setState(() {
        _selected = nextSelected;
      });
    }
  }

  @override
  void dispose() {
    _viewModel?.removeListener(_onViewModelStateChanged);
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    if (!_hasSelected) {
      _selectCurrent(force: true);
    }
    return widget.builder(context, _selected as R, widget.child);
  }
}

/// Creates and provides AdminCustomerDetailViewModel to descendants.
///
/// The default constructor owns the ViewModel. Use `.value` for externally
/// owned ViewModels.
///
/// ```dart
/// AdminCustomerDetailViewModelScope(
///   args: (context) => AdminCustomerDetailViewModelArgs(...),
///   create: (context, args) => AdminCustomerDetailViewModel(args),
///   child: const FeaturePage(),
/// )
/// ```
class AdminCustomerDetailViewModelScope extends StatefulWidget {
  /// Creates and owns AdminCustomerDetailViewModel from typed args.
  const AdminCustomerDetailViewModelScope({
    super.key,
    required this.args,
    required this.create,
    required this.child,
    this.identity,
  }) : value = null;

  /// Provides an externally owned AdminCustomerDetailViewModel without disposing it.
  const AdminCustomerDetailViewModelScope.value({
    super.key,
    required AdminCustomerDetailViewModel this.value,
    required this.child,
  }) : args = null,
       create = null,
       identity = null;

  final AdminCustomerDetailViewModelArgs Function(BuildContext context)? args;
  final AdminCustomerDetailViewModel Function(BuildContext context, AdminCustomerDetailViewModelArgs args)? create;
  final Object? Function(BuildContext context)? identity;
  final AdminCustomerDetailViewModel? value;
  final Widget child;

  /// Reads AdminCustomerDetailViewModel without rebuilding when state changes.
  static AdminCustomerDetailViewModel read(BuildContext context) {
    final scope = context
        .getElementForInheritedWidgetOfExactType<_AdminCustomerDetailViewModelInstance>()
        ?.widget as _AdminCustomerDetailViewModelInstance?;
    if (scope == null) throw StateError('No AdminCustomerDetailViewModelScope found in context.');
    return scope.viewModel;
  }

  static AdminCustomerDetailViewModel _watchInstance(BuildContext context) {
    final scope = context.dependOnInheritedWidgetOfExactType<_AdminCustomerDetailViewModelInstance>();
    if (scope == null) throw StateError('No AdminCustomerDetailViewModelScope found in context.');
    return scope.viewModel;
  }

  /// Watches AdminCustomerDetailViewModel and rebuilds when state changes.
  static AdminCustomerDetailViewModel of(BuildContext context) {
    final scope = context.dependOnInheritedWidgetOfExactType<_AdminCustomerDetailViewModelInherited>();
    if (scope == null) throw StateError('No AdminCustomerDetailViewModelScope found in context.');
    return scope.viewModel;
  }

  @override
  State<AdminCustomerDetailViewModelScope> createState() => _AdminCustomerDetailViewModelScopeState();
}

class _AdminCustomerDetailViewModelScopeState extends State<AdminCustomerDetailViewModelScope> {
  AdminCustomerDetailViewModel? _viewModel;
  Object? _identity;
  bool _ownsViewModel = false;

  @override
  void didChangeDependencies() {
    super.didChangeDependencies();
    final external = widget.value;
    if (external != null) {
      _replaceViewModel(external, ownsViewModel: false, notify: false);
      return;
    }
    final nextIdentity = widget.identity?.call(context);
    if (_viewModel == null || nextIdentity != _identity) {
      _identity = nextIdentity;
      _replaceViewModel(_createOwnedViewModel(), ownsViewModel: true, notify: false);
    }
  }

  @override
  void didUpdateWidget(AdminCustomerDetailViewModelScope oldWidget) {
    super.didUpdateWidget(oldWidget);
    final external = widget.value;
    if (external != null) {
      _replaceViewModel(external, ownsViewModel: false);
    } else if (oldWidget.value != null) {
      _identity = widget.identity?.call(context);
      _replaceViewModel(_createOwnedViewModel(), ownsViewModel: true);
    } else {
      final nextIdentity = widget.identity?.call(context);
      if (nextIdentity != _identity) {
        _identity = nextIdentity;
        _replaceViewModel(_createOwnedViewModel(), ownsViewModel: true);
      }
    }
  }

  AdminCustomerDetailViewModel _createOwnedViewModel() {
    final argsFactory = widget.args;
    final create = widget.create;
    if (argsFactory == null || create == null) {
      throw StateError('Owned AdminCustomerDetailViewModelScope requires args and create.');
    }
    late final AdminCustomerDetailViewModel created;
    try {
      created = create(context, argsFactory(context));
    } catch (error, stackTrace) {
      Error.throwWithStackTrace(error, stackTrace);
    }
    return created;
  }

  void _replaceViewModel(
    AdminCustomerDetailViewModel nextViewModel, {
    required bool ownsViewModel,
    bool notify = true,
  }) {
    final previous = _viewModel;
    if (identical(previous, nextViewModel)) {
      _ownsViewModel = ownsViewModel;
      _scheduleInit(nextViewModel);
      if (notify && mounted) setState(() {});
      return;
    }
    previous?.removeListener(_onViewModelStateChanged);
    if (_ownsViewModel) previous?.dispose();
    _viewModel = nextViewModel;
    _ownsViewModel = ownsViewModel;
    nextViewModel.addListener(_onViewModelStateChanged);
    _scheduleInit(nextViewModel);
    if (notify && mounted) setState(() {});
  }

  void _scheduleInit(AdminCustomerDetailViewModel viewModel) {
    scheduleMicrotask(() async {
      if (!mounted || !identical(_viewModel, viewModel)) return;
      try {
        await viewModel.init();
      } catch (error, stackTrace) {
        FlutterError.reportError(
          FlutterErrorDetails(
            exception: error,
            stack: stackTrace,
            library: 'dust state',
            context: ErrorDescription('AdminCustomerDetailViewModelScope init failed'),
          ),
        );
      }
    });
  }

  void _onViewModelStateChanged() {
    if (mounted) setState(() {});
  }

  @override
  void dispose() {
    final viewModel = _viewModel;
    viewModel?.removeListener(_onViewModelStateChanged);
    if (_ownsViewModel) viewModel?.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    final viewModel = _viewModel;
    if (viewModel == null) {
      throw StateError('AdminCustomerDetailViewModelScope built before its view model was initialized.');
    }
    return _AdminCustomerDetailViewModelInstance(
      viewModel: viewModel,
      child: _AdminCustomerDetailViewModelInherited(
        viewModel: viewModel,
        state: viewModel.value,
        child: widget.child,
      ),
    );
  }
}

class _AdminCustomerDetailViewModelInstance extends InheritedWidget {
  const _AdminCustomerDetailViewModelInstance({required this.viewModel, required super.child});

  final AdminCustomerDetailViewModel viewModel;

  @override
  bool updateShouldNotify(_AdminCustomerDetailViewModelInstance oldWidget) {
    return !identical(viewModel, oldWidget.viewModel);
  }
}

class _AdminCustomerDetailViewModelInherited extends InheritedWidget {
  const _AdminCustomerDetailViewModelInherited({required this.viewModel, required this.state, required super.child});

  final AdminCustomerDetailViewModel viewModel;
  final AdminCustomerDetailState state;

  @override
  bool updateShouldNotify(_AdminCustomerDetailViewModelInherited oldWidget) {
    return !identical(viewModel, oldWidget.viewModel) || state != oldWidget.state;
  }
}

/// Handles one-shot effects from AdminCustomerDetailViewModel.
///
/// Effects are delivered without changing state and do not rebuild `child`.
///
/// ```dart
/// AdminCustomerDetailViewModelListener(
///   listener: onEffect,
///   child: const FeaturePage(),
/// )
/// ```
class AdminCustomerDetailViewModelListener extends StatefulWidget {
  const AdminCustomerDetailViewModelListener({super.key, required this.listener, required this.child});

  final void Function(BuildContext context, Object effect) listener;
  final Widget child;

  @override
  State<AdminCustomerDetailViewModelListener> createState() => _AdminCustomerDetailViewModelListenerState();
}

class _AdminCustomerDetailViewModelListenerState extends State<AdminCustomerDetailViewModelListener> {
  StreamSubscription<Object>? _sub;
  AdminCustomerDetailViewModel? _viewModel;

  @override
  void didChangeDependencies() {
    super.didChangeDependencies();
    final nextViewModel = AdminCustomerDetailViewModelScope._watchInstance(context);
    if (_viewModel == nextViewModel) return;
    _sub?.cancel();
    _viewModel = nextViewModel;
    _sub = nextViewModel.effects.listen(_onEffect);
  }

  void _onEffect(Object effect) {
    if (mounted) widget.listener(context, effect);
  }

  @override
  void dispose() {
    _sub?.cancel();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) => widget.child;
}

/// BuildContext helpers generated for AdminCustomerDetailViewModel.
///
/// ```dart
/// final vm = context.readAdminCustomerDetailViewModel();
/// final state = context.watchAdminCustomerDetailViewModel().value;
/// ```
extension AdminCustomerDetailViewModelBuildContext on BuildContext {
  _$AdminCustomerDetailViewModelProxy watchAdminCustomerDetailViewModel() {
    return _$AdminCustomerDetailViewModelProxy(this);
  }

  AdminCustomerDetailViewModel readAdminCustomerDetailViewModel() => AdminCustomerDetailViewModelScope.read(this);
}
