// GENERATED CODE - DO NOT MODIFY BY HAND
// coverage:ignore-file
// ignore_for_file: type=lint
// ignore_for_file: unused_element, unused_import, deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: use_function_type_syntax_for_parameters
// ignore_for_file: unnecessary_const, avoid_init_to_null
// ignore_for_file: invalid_override_different_default_values_named
// ignore_for_file: prefer_expression_function_bodies
// ignore_for_file: annotate_overrides, invalid_annotation_target
// ignore_for_file: unnecessary_question_mark
// Generated by dust.

part of 'reason_repository.dart';

final class _$AdminRefundReasonRepository implements AdminRefundReasonRepository {
  const _$AdminRefundReasonRepository(this._db);

  final DatabaseExecutor _db;

  @override
  Future<Result<int, SqlxError>> count(String query) {
    return _db.fetchScalar<int>(
      r'''
SELECT count(*) FROM refund_reasons
WHERE deleted_at IS NULL AND (
  ? = '' OR lower(label) LIKE '%' || lower(?) || '%'
          OR lower(coalesce(description, '')) LIKE '%' || lower(?) || '%'
)
''',
      [query, query, query],
    );
  }

  @override
  Future<Result<List<AdminRefundReasonResponse>, SqlxError>> list(String query, int limit, int offset) {
    return _db.fetchAll<AdminRefundReasonResponse>(
      r'''
SELECT id, label, code, description
FROM refund_reasons
WHERE deleted_at IS NULL AND (
  ? = '' OR lower(label) LIKE '%' || lower(?) || '%'
          OR lower(coalesce(description, '')) LIKE '%' || lower(?) || '%'
)
ORDER BY lower(label), id
LIMIT ? OFFSET ?
''',
      [query, query, query, limit, offset],
      const $AdminRefundReasonResponseRowDeserializer().deserialize,
    );
  }
}
