// GENERATED CODE - DO NOT MODIFY BY HAND
// coverage:ignore-file
// ignore_for_file: type=lint
// ignore_for_file: unused_element, unused_import, deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: use_function_type_syntax_for_parameters
// ignore_for_file: unnecessary_const, avoid_init_to_null
// ignore_for_file: invalid_override_different_default_values_named
// ignore_for_file: prefer_expression_function_bodies
// ignore_for_file: annotate_overrides, invalid_annotation_target
// ignore_for_file: unnecessary_question_mark
// Generated by dust.

part of 'admin_customer_group_candidate_view_model.dart';

/// Base class generated for AdminCustomerGroupCandidateViewModel.
///
/// Extend it from your ViewModel and forward typed args:
///
/// ```dart
/// final class AdminCustomerGroupCandidateViewModel extends $AdminCustomerGroupCandidateViewModel {
///   AdminCustomerGroupCandidateViewModel(super.args);
/// }
/// ```
abstract class $AdminCustomerGroupCandidateViewModel extends ViewModelBase<AdminCustomerGroupCandidateState, AdminCustomerGroupCandidateViewModelArgs> {
  $AdminCustomerGroupCandidateViewModel(super.args) : super(initialState: const AdminCustomerGroupCandidateState());
}

/// Reads AdminCustomerGroupCandidateViewModel state from `BuildContext`.
///
/// Read `value` when the widget should rebuild for any state change.
///
/// ```dart
/// final state = context.watchAdminCustomerGroupCandidateViewModel().value;
/// ```
class _$AdminCustomerGroupCandidateViewModelProxy {
  _$AdminCustomerGroupCandidateViewModelProxy(this._context);

  final BuildContext _context;

  AdminCustomerGroupCandidateState get value {
    return AdminCustomerGroupCandidateViewModelScope.of(_context).value;
  }
}

/// Rebuilds when a selected AdminCustomerGroupCandidateState value changes.
///
/// Use this for widgets that depend on one field or derived value.
class AdminCustomerGroupCandidateViewModelSelector<R> extends StatefulWidget {
  const AdminCustomerGroupCandidateViewModelSelector({
    super.key,
    required this.selector,
    required this.builder,
    this.child,
    this.equals,
  });

  final R Function(AdminCustomerGroupCandidateState state) selector;
  final Widget Function(BuildContext context, R value, Widget? child) builder;
  final Widget? child;
  final bool Function(R previous, R next)? equals;

  @override
  State<AdminCustomerGroupCandidateViewModelSelector<R>> createState() => _AdminCustomerGroupCandidateViewModelSelectorState<R>();
}

class _AdminCustomerGroupCandidateViewModelSelectorState<R> extends State<AdminCustomerGroupCandidateViewModelSelector<R>> {
  AdminCustomerGroupCandidateViewModel? _viewModel;
  R? _selected;
  bool _hasSelected = false;

  @override
  void didChangeDependencies() {
    super.didChangeDependencies();
    final nextViewModel = AdminCustomerGroupCandidateViewModelScope._watchInstance(context);
    if (identical(_viewModel, nextViewModel)) return;
    _viewModel?.removeListener(_onViewModelStateChanged);
    _viewModel = nextViewModel;
    nextViewModel.addListener(_onViewModelStateChanged);
    _selectCurrent(force: true);
  }

  @override
  void didUpdateWidget(AdminCustomerGroupCandidateViewModelSelector<R> oldWidget) {
    super.didUpdateWidget(oldWidget);
    _selectCurrent(force: true);
  }

  void _onViewModelStateChanged() {
    _selectCurrent();
  }

  void _selectCurrent({bool force = false}) {
    final viewModel = _viewModel;
    if (viewModel == null) return;
    final nextSelected = widget.selector(viewModel.value);
    if (!_hasSelected) {
      _selected = nextSelected;
      _hasSelected = true;
      return;
    }
    final previousSelected = _selected as R;
    final equals = widget.equals;
    final unchanged = equals == null
        ? previousSelected == nextSelected
        : equals(previousSelected, nextSelected);
    if (!force && unchanged) return;
    if (force || !mounted) {
      _selected = nextSelected;
    } else {
      setState(() {
        _selected = nextSelected;
      });
    }
  }

  @override
  void dispose() {
    _viewModel?.removeListener(_onViewModelStateChanged);
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    if (!_hasSelected) {
      _selectCurrent(force: true);
    }
    return widget.builder(context, _selected as R, widget.child);
  }
}

/// Creates and provides AdminCustomerGroupCandidateViewModel to descendants.
///
/// The default constructor owns the ViewModel. Use `.value` for externally
/// owned ViewModels.
///
/// ```dart
/// AdminCustomerGroupCandidateViewModelScope(
///   args: (context) => AdminCustomerGroupCandidateViewModelArgs(...),
///   create: (context, args) => AdminCustomerGroupCandidateViewModel(args),
///   child: const FeaturePage(),
/// )
/// ```
class AdminCustomerGroupCandidateViewModelScope extends StatefulWidget {
  /// Creates and owns AdminCustomerGroupCandidateViewModel from typed args.
  const AdminCustomerGroupCandidateViewModelScope({
    super.key,
    required this.args,
    required this.create,
    required this.child,
    this.identity,
  }) : value = null;

  /// Provides an externally owned AdminCustomerGroupCandidateViewModel without disposing it.
  const AdminCustomerGroupCandidateViewModelScope.value({
    super.key,
    required AdminCustomerGroupCandidateViewModel this.value,
    required this.child,
  }) : args = null,
       create = null,
       identity = null;

  final AdminCustomerGroupCandidateViewModelArgs Function(BuildContext context)? args;
  final AdminCustomerGroupCandidateViewModel Function(BuildContext context, AdminCustomerGroupCandidateViewModelArgs args)? create;
  final Object? Function(BuildContext context)? identity;
  final AdminCustomerGroupCandidateViewModel? value;
  final Widget child;

  /// Reads AdminCustomerGroupCandidateViewModel without rebuilding when state changes.
  static AdminCustomerGroupCandidateViewModel read(BuildContext context) {
    final scope = context
        .getElementForInheritedWidgetOfExactType<_AdminCustomerGroupCandidateViewModelInstance>()
        ?.widget as _AdminCustomerGroupCandidateViewModelInstance?;
    if (scope == null) throw StateError('No AdminCustomerGroupCandidateViewModelScope found in context.');
    return scope.viewModel;
  }

  static AdminCustomerGroupCandidateViewModel _watchInstance(BuildContext context) {
    final scope = context.dependOnInheritedWidgetOfExactType<_AdminCustomerGroupCandidateViewModelInstance>();
    if (scope == null) throw StateError('No AdminCustomerGroupCandidateViewModelScope found in context.');
    return scope.viewModel;
  }

  /// Watches AdminCustomerGroupCandidateViewModel and rebuilds when state changes.
  static AdminCustomerGroupCandidateViewModel of(BuildContext context) {
    final scope = context.dependOnInheritedWidgetOfExactType<_AdminCustomerGroupCandidateViewModelInherited>();
    if (scope == null) throw StateError('No AdminCustomerGroupCandidateViewModelScope found in context.');
    return scope.viewModel;
  }

  @override
  State<AdminCustomerGroupCandidateViewModelScope> createState() => _AdminCustomerGroupCandidateViewModelScopeState();
}

class _AdminCustomerGroupCandidateViewModelScopeState extends State<AdminCustomerGroupCandidateViewModelScope> {
  AdminCustomerGroupCandidateViewModel? _viewModel;
  Object? _identity;
  bool _ownsViewModel = false;

  @override
  void didChangeDependencies() {
    super.didChangeDependencies();
    final external = widget.value;
    if (external != null) {
      _replaceViewModel(external, ownsViewModel: false, notify: false);
      return;
    }
    final nextIdentity = widget.identity?.call(context);
    if (_viewModel == null || nextIdentity != _identity) {
      _identity = nextIdentity;
      _replaceViewModel(_createOwnedViewModel(), ownsViewModel: true, notify: false);
    }
  }

  @override
  void didUpdateWidget(AdminCustomerGroupCandidateViewModelScope oldWidget) {
    super.didUpdateWidget(oldWidget);
    final external = widget.value;
    if (external != null) {
      _replaceViewModel(external, ownsViewModel: false);
    } else if (oldWidget.value != null) {
      _identity = widget.identity?.call(context);
      _replaceViewModel(_createOwnedViewModel(), ownsViewModel: true);
    } else {
      final nextIdentity = widget.identity?.call(context);
      if (nextIdentity != _identity) {
        _identity = nextIdentity;
        _replaceViewModel(_createOwnedViewModel(), ownsViewModel: true);
      }
    }
  }

  AdminCustomerGroupCandidateViewModel _createOwnedViewModel() {
    final argsFactory = widget.args;
    final create = widget.create;
    if (argsFactory == null || create == null) {
      throw StateError('Owned AdminCustomerGroupCandidateViewModelScope requires args and create.');
    }
    late final AdminCustomerGroupCandidateViewModel created;
    try {
      created = create(context, argsFactory(context));
    } catch (error, stackTrace) {
      Error.throwWithStackTrace(error, stackTrace);
    }
    return created;
  }

  void _replaceViewModel(
    AdminCustomerGroupCandidateViewModel nextViewModel, {
    required bool ownsViewModel,
    bool notify = true,
  }) {
    final previous = _viewModel;
    if (identical(previous, nextViewModel)) {
      _ownsViewModel = ownsViewModel;
      _scheduleInit(nextViewModel);
      if (notify && mounted) setState(() {});
      return;
    }
    previous?.removeListener(_onViewModelStateChanged);
    if (_ownsViewModel) previous?.dispose();
    _viewModel = nextViewModel;
    _ownsViewModel = ownsViewModel;
    nextViewModel.addListener(_onViewModelStateChanged);
    _scheduleInit(nextViewModel);
    if (notify && mounted) setState(() {});
  }

  void _scheduleInit(AdminCustomerGroupCandidateViewModel viewModel) {
    scheduleMicrotask(() async {
      if (!mounted || !identical(_viewModel, viewModel)) return;
      try {
        await viewModel.init();
      } catch (error, stackTrace) {
        FlutterError.reportError(
          FlutterErrorDetails(
            exception: error,
            stack: stackTrace,
            library: 'dust state',
            context: ErrorDescription('AdminCustomerGroupCandidateViewModelScope init failed'),
          ),
        );
      }
    });
  }

  void _onViewModelStateChanged() {
    if (mounted) setState(() {});
  }

  @override
  void dispose() {
    final viewModel = _viewModel;
    viewModel?.removeListener(_onViewModelStateChanged);
    if (_ownsViewModel) viewModel?.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    final viewModel = _viewModel;
    if (viewModel == null) {
      throw StateError('AdminCustomerGroupCandidateViewModelScope built before its view model was initialized.');
    }
    return _AdminCustomerGroupCandidateViewModelInstance(
      viewModel: viewModel,
      child: _AdminCustomerGroupCandidateViewModelInherited(
        viewModel: viewModel,
        state: viewModel.value,
        child: widget.child,
      ),
    );
  }
}

class _AdminCustomerGroupCandidateViewModelInstance extends InheritedWidget {
  const _AdminCustomerGroupCandidateViewModelInstance({required this.viewModel, required super.child});

  final AdminCustomerGroupCandidateViewModel viewModel;

  @override
  bool updateShouldNotify(_AdminCustomerGroupCandidateViewModelInstance oldWidget) {
    return !identical(viewModel, oldWidget.viewModel);
  }
}

class _AdminCustomerGroupCandidateViewModelInherited extends InheritedWidget {
  const _AdminCustomerGroupCandidateViewModelInherited({required this.viewModel, required this.state, required super.child});

  final AdminCustomerGroupCandidateViewModel viewModel;
  final AdminCustomerGroupCandidateState state;

  @override
  bool updateShouldNotify(_AdminCustomerGroupCandidateViewModelInherited oldWidget) {
    return !identical(viewModel, oldWidget.viewModel) || state != oldWidget.state;
  }
}

/// Handles one-shot effects from AdminCustomerGroupCandidateViewModel.
///
/// Effects are delivered without changing state and do not rebuild `child`.
///
/// ```dart
/// AdminCustomerGroupCandidateViewModelListener(
///   listener: onEffect,
///   child: const FeaturePage(),
/// )
/// ```
class AdminCustomerGroupCandidateViewModelListener extends StatefulWidget {
  const AdminCustomerGroupCandidateViewModelListener({super.key, required this.listener, required this.child});

  final void Function(BuildContext context, Object effect) listener;
  final Widget child;

  @override
  State<AdminCustomerGroupCandidateViewModelListener> createState() => _AdminCustomerGroupCandidateViewModelListenerState();
}

class _AdminCustomerGroupCandidateViewModelListenerState extends State<AdminCustomerGroupCandidateViewModelListener> {
  StreamSubscription<Object>? _sub;
  AdminCustomerGroupCandidateViewModel? _viewModel;

  @override
  void didChangeDependencies() {
    super.didChangeDependencies();
    final nextViewModel = AdminCustomerGroupCandidateViewModelScope._watchInstance(context);
    if (_viewModel == nextViewModel) return;
    _sub?.cancel();
    _viewModel = nextViewModel;
    _sub = nextViewModel.effects.listen(_onEffect);
  }

  void _onEffect(Object effect) {
    if (mounted) widget.listener(context, effect);
  }

  @override
  void dispose() {
    _sub?.cancel();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) => widget.child;
}

/// BuildContext helpers generated for AdminCustomerGroupCandidateViewModel.
///
/// ```dart
/// final vm = context.readAdminCustomerGroupCandidateViewModel();
/// final state = context.watchAdminCustomerGroupCandidateViewModel().value;
/// ```
extension AdminCustomerGroupCandidateViewModelBuildContext on BuildContext {
  _$AdminCustomerGroupCandidateViewModelProxy watchAdminCustomerGroupCandidateViewModel() {
    return _$AdminCustomerGroupCandidateViewModelProxy(this);
  }

  AdminCustomerGroupCandidateViewModel readAdminCustomerGroupCandidateViewModel() => AdminCustomerGroupCandidateViewModelScope.read(this);
}
