// GENERATED CODE - DO NOT MODIFY BY HAND
// coverage:ignore-file
// ignore_for_file: type=lint
// ignore_for_file: unused_element, unused_import, deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: use_function_type_syntax_for_parameters
// ignore_for_file: unnecessary_const, avoid_init_to_null
// ignore_for_file: invalid_override_different_default_values_named
// ignore_for_file: prefer_expression_function_bodies
// ignore_for_file: annotate_overrides, invalid_annotation_target
// ignore_for_file: unnecessary_question_mark
// Generated by dust.

part of 'admin_customer_group_edit_view_model.dart';

/// Base class generated for AdminCustomerGroupEditViewModel.
///
/// Extend it from your ViewModel and forward typed args:
///
/// ```dart
/// final class AdminCustomerGroupEditViewModel extends $AdminCustomerGroupEditViewModel {
///   AdminCustomerGroupEditViewModel(super.args);
/// }
/// ```
abstract class $AdminCustomerGroupEditViewModel extends ViewModelBase<AdminCustomerGroupEditState, AdminCustomerGroupEditViewModelArgs> {
  $AdminCustomerGroupEditViewModel(super.args) : super(initialState: const AdminCustomerGroupEditState());
}

/// Reads AdminCustomerGroupEditViewModel state from `BuildContext`.
///
/// Read `value` when the widget should rebuild for any state change.
///
/// ```dart
/// final state = context.watchAdminCustomerGroupEditViewModel().value;
/// ```
class _$AdminCustomerGroupEditViewModelProxy {
  _$AdminCustomerGroupEditViewModelProxy(this._context);

  final BuildContext _context;

  AdminCustomerGroupEditState get value {
    return AdminCustomerGroupEditViewModelScope.of(_context).value;
  }
}

/// Rebuilds when a selected AdminCustomerGroupEditState value changes.
///
/// Use this for widgets that depend on one field or derived value.
class AdminCustomerGroupEditViewModelSelector<R> extends StatefulWidget {
  const AdminCustomerGroupEditViewModelSelector({
    super.key,
    required this.selector,
    required this.builder,
    this.child,
    this.equals,
  });

  final R Function(AdminCustomerGroupEditState state) selector;
  final Widget Function(BuildContext context, R value, Widget? child) builder;
  final Widget? child;
  final bool Function(R previous, R next)? equals;

  @override
  State<AdminCustomerGroupEditViewModelSelector<R>> createState() => _AdminCustomerGroupEditViewModelSelectorState<R>();
}

class _AdminCustomerGroupEditViewModelSelectorState<R> extends State<AdminCustomerGroupEditViewModelSelector<R>> {
  AdminCustomerGroupEditViewModel? _viewModel;
  R? _selected;
  bool _hasSelected = false;

  @override
  void didChangeDependencies() {
    super.didChangeDependencies();
    final nextViewModel = AdminCustomerGroupEditViewModelScope._watchInstance(context);
    if (identical(_viewModel, nextViewModel)) return;
    _viewModel?.removeListener(_onViewModelStateChanged);
    _viewModel = nextViewModel;
    nextViewModel.addListener(_onViewModelStateChanged);
    _selectCurrent(force: true);
  }

  @override
  void didUpdateWidget(AdminCustomerGroupEditViewModelSelector<R> oldWidget) {
    super.didUpdateWidget(oldWidget);
    _selectCurrent(force: true);
  }

  void _onViewModelStateChanged() {
    _selectCurrent();
  }

  void _selectCurrent({bool force = false}) {
    final viewModel = _viewModel;
    if (viewModel == null) return;
    final nextSelected = widget.selector(viewModel.value);
    if (!_hasSelected) {
      _selected = nextSelected;
      _hasSelected = true;
      return;
    }
    final previousSelected = _selected as R;
    final equals = widget.equals;
    final unchanged = equals == null
        ? previousSelected == nextSelected
        : equals(previousSelected, nextSelected);
    if (!force && unchanged) return;
    if (force || !mounted) {
      _selected = nextSelected;
    } else {
      setState(() {
        _selected = nextSelected;
      });
    }
  }

  @override
  void dispose() {
    _viewModel?.removeListener(_onViewModelStateChanged);
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    if (!_hasSelected) {
      _selectCurrent(force: true);
    }
    return widget.builder(context, _selected as R, widget.child);
  }
}

/// Creates and provides AdminCustomerGroupEditViewModel to descendants.
///
/// The default constructor owns the ViewModel. Use `.value` for externally
/// owned ViewModels.
///
/// ```dart
/// AdminCustomerGroupEditViewModelScope(
///   args: (context) => AdminCustomerGroupEditViewModelArgs(...),
///   create: (context, args) => AdminCustomerGroupEditViewModel(args),
///   child: const FeaturePage(),
/// )
/// ```
class AdminCustomerGroupEditViewModelScope extends StatefulWidget {
  /// Creates and owns AdminCustomerGroupEditViewModel from typed args.
  const AdminCustomerGroupEditViewModelScope({
    super.key,
    required this.args,
    required this.create,
    required this.child,
    this.identity,
  }) : value = null;

  /// Provides an externally owned AdminCustomerGroupEditViewModel without disposing it.
  const AdminCustomerGroupEditViewModelScope.value({
    super.key,
    required AdminCustomerGroupEditViewModel this.value,
    required this.child,
  }) : args = null,
       create = null,
       identity = null;

  final AdminCustomerGroupEditViewModelArgs Function(BuildContext context)? args;
  final AdminCustomerGroupEditViewModel Function(BuildContext context, AdminCustomerGroupEditViewModelArgs args)? create;
  final Object? Function(BuildContext context)? identity;
  final AdminCustomerGroupEditViewModel? value;
  final Widget child;

  /// Reads AdminCustomerGroupEditViewModel without rebuilding when state changes.
  static AdminCustomerGroupEditViewModel read(BuildContext context) {
    final scope = context
        .getElementForInheritedWidgetOfExactType<_AdminCustomerGroupEditViewModelInstance>()
        ?.widget as _AdminCustomerGroupEditViewModelInstance?;
    if (scope == null) throw StateError('No AdminCustomerGroupEditViewModelScope found in context.');
    return scope.viewModel;
  }

  static AdminCustomerGroupEditViewModel _watchInstance(BuildContext context) {
    final scope = context.dependOnInheritedWidgetOfExactType<_AdminCustomerGroupEditViewModelInstance>();
    if (scope == null) throw StateError('No AdminCustomerGroupEditViewModelScope found in context.');
    return scope.viewModel;
  }

  /// Watches AdminCustomerGroupEditViewModel and rebuilds when state changes.
  static AdminCustomerGroupEditViewModel of(BuildContext context) {
    final scope = context.dependOnInheritedWidgetOfExactType<_AdminCustomerGroupEditViewModelInherited>();
    if (scope == null) throw StateError('No AdminCustomerGroupEditViewModelScope found in context.');
    return scope.viewModel;
  }

  @override
  State<AdminCustomerGroupEditViewModelScope> createState() => _AdminCustomerGroupEditViewModelScopeState();
}

class _AdminCustomerGroupEditViewModelScopeState extends State<AdminCustomerGroupEditViewModelScope> {
  AdminCustomerGroupEditViewModel? _viewModel;
  Object? _identity;
  bool _ownsViewModel = false;

  @override
  void didChangeDependencies() {
    super.didChangeDependencies();
    final external = widget.value;
    if (external != null) {
      _replaceViewModel(external, ownsViewModel: false, notify: false);
      return;
    }
    final nextIdentity = widget.identity?.call(context);
    if (_viewModel == null || nextIdentity != _identity) {
      _identity = nextIdentity;
      _replaceViewModel(_createOwnedViewModel(), ownsViewModel: true, notify: false);
    }
  }

  @override
  void didUpdateWidget(AdminCustomerGroupEditViewModelScope oldWidget) {
    super.didUpdateWidget(oldWidget);
    final external = widget.value;
    if (external != null) {
      _replaceViewModel(external, ownsViewModel: false);
    } else if (oldWidget.value != null) {
      _identity = widget.identity?.call(context);
      _replaceViewModel(_createOwnedViewModel(), ownsViewModel: true);
    } else {
      final nextIdentity = widget.identity?.call(context);
      if (nextIdentity != _identity) {
        _identity = nextIdentity;
        _replaceViewModel(_createOwnedViewModel(), ownsViewModel: true);
      }
    }
  }

  AdminCustomerGroupEditViewModel _createOwnedViewModel() {
    final argsFactory = widget.args;
    final create = widget.create;
    if (argsFactory == null || create == null) {
      throw StateError('Owned AdminCustomerGroupEditViewModelScope requires args and create.');
    }
    late final AdminCustomerGroupEditViewModel created;
    try {
      created = create(context, argsFactory(context));
    } catch (error, stackTrace) {
      Error.throwWithStackTrace(error, stackTrace);
    }
    return created;
  }

  void _replaceViewModel(
    AdminCustomerGroupEditViewModel nextViewModel, {
    required bool ownsViewModel,
    bool notify = true,
  }) {
    final previous = _viewModel;
    if (identical(previous, nextViewModel)) {
      _ownsViewModel = ownsViewModel;
      _scheduleInit(nextViewModel);
      if (notify && mounted) setState(() {});
      return;
    }
    previous?.removeListener(_onViewModelStateChanged);
    if (_ownsViewModel) previous?.dispose();
    _viewModel = nextViewModel;
    _ownsViewModel = ownsViewModel;
    nextViewModel.addListener(_onViewModelStateChanged);
    _scheduleInit(nextViewModel);
    if (notify && mounted) setState(() {});
  }

  void _scheduleInit(AdminCustomerGroupEditViewModel viewModel) {
    scheduleMicrotask(() async {
      if (!mounted || !identical(_viewModel, viewModel)) return;
      try {
        await viewModel.init();
      } catch (error, stackTrace) {
        FlutterError.reportError(
          FlutterErrorDetails(
            exception: error,
            stack: stackTrace,
            library: 'dust state',
            context: ErrorDescription('AdminCustomerGroupEditViewModelScope init failed'),
          ),
        );
      }
    });
  }

  void _onViewModelStateChanged() {
    if (mounted) setState(() {});
  }

  @override
  void dispose() {
    final viewModel = _viewModel;
    viewModel?.removeListener(_onViewModelStateChanged);
    if (_ownsViewModel) viewModel?.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    final viewModel = _viewModel;
    if (viewModel == null) {
      throw StateError('AdminCustomerGroupEditViewModelScope built before its view model was initialized.');
    }
    return _AdminCustomerGroupEditViewModelInstance(
      viewModel: viewModel,
      child: _AdminCustomerGroupEditViewModelInherited(
        viewModel: viewModel,
        state: viewModel.value,
        child: widget.child,
      ),
    );
  }
}

class _AdminCustomerGroupEditViewModelInstance extends InheritedWidget {
  const _AdminCustomerGroupEditViewModelInstance({required this.viewModel, required super.child});

  final AdminCustomerGroupEditViewModel viewModel;

  @override
  bool updateShouldNotify(_AdminCustomerGroupEditViewModelInstance oldWidget) {
    return !identical(viewModel, oldWidget.viewModel);
  }
}

class _AdminCustomerGroupEditViewModelInherited extends InheritedWidget {
  const _AdminCustomerGroupEditViewModelInherited({required this.viewModel, required this.state, required super.child});

  final AdminCustomerGroupEditViewModel viewModel;
  final AdminCustomerGroupEditState state;

  @override
  bool updateShouldNotify(_AdminCustomerGroupEditViewModelInherited oldWidget) {
    return !identical(viewModel, oldWidget.viewModel) || state != oldWidget.state;
  }
}

/// Handles one-shot effects from AdminCustomerGroupEditViewModel.
///
/// Effects are delivered without changing state and do not rebuild `child`.
///
/// ```dart
/// AdminCustomerGroupEditViewModelListener(
///   listener: onEffect,
///   child: const FeaturePage(),
/// )
/// ```
class AdminCustomerGroupEditViewModelListener extends StatefulWidget {
  const AdminCustomerGroupEditViewModelListener({super.key, required this.listener, required this.child});

  final void Function(BuildContext context, Object effect) listener;
  final Widget child;

  @override
  State<AdminCustomerGroupEditViewModelListener> createState() => _AdminCustomerGroupEditViewModelListenerState();
}

class _AdminCustomerGroupEditViewModelListenerState extends State<AdminCustomerGroupEditViewModelListener> {
  StreamSubscription<Object>? _sub;
  AdminCustomerGroupEditViewModel? _viewModel;

  @override
  void didChangeDependencies() {
    super.didChangeDependencies();
    final nextViewModel = AdminCustomerGroupEditViewModelScope._watchInstance(context);
    if (_viewModel == nextViewModel) return;
    _sub?.cancel();
    _viewModel = nextViewModel;
    _sub = nextViewModel.effects.listen(_onEffect);
  }

  void _onEffect(Object effect) {
    if (mounted) widget.listener(context, effect);
  }

  @override
  void dispose() {
    _sub?.cancel();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) => widget.child;
}

/// BuildContext helpers generated for AdminCustomerGroupEditViewModel.
///
/// ```dart
/// final vm = context.readAdminCustomerGroupEditViewModel();
/// final state = context.watchAdminCustomerGroupEditViewModel().value;
/// ```
extension AdminCustomerGroupEditViewModelBuildContext on BuildContext {
  _$AdminCustomerGroupEditViewModelProxy watchAdminCustomerGroupEditViewModel() {
    return _$AdminCustomerGroupEditViewModelProxy(this);
  }

  AdminCustomerGroupEditViewModel readAdminCustomerGroupEditViewModel() => AdminCustomerGroupEditViewModelScope.read(this);
}
