// GENERATED CODE - DO NOT MODIFY BY HAND
// coverage:ignore-file
// ignore_for_file: type=lint
// ignore_for_file: unused_element, unused_import, deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: use_function_type_syntax_for_parameters
// ignore_for_file: unnecessary_const, avoid_init_to_null
// ignore_for_file: invalid_override_different_default_values_named
// ignore_for_file: prefer_expression_function_bodies
// ignore_for_file: annotate_overrides, invalid_annotation_target
// ignore_for_file: unnecessary_question_mark
// Generated by dust.

part of 'admin_customer_group_state.dart';

const DeepCollectionEquality _adminCustomerGroupStateCustomerGroupsEquality = DeepCollectionEquality();

mixin _$AdminCustomerGroupState {
  @override
  String toString() {
    final self = this as AdminCustomerGroupState;
    return 'AdminCustomerGroupState('
        'count: ${self.count}, '
        'createdAt: ${self.createdAt}, '
        'customerGroups: ${self.customerGroups}, '
        'failure: ${self.failure}, '
        'limit: ${self.limit}, '
        'offset: ${self.offset}, '
        'order: ${self.order}, '
        'query: ${self.query}, '
        'status: ${self.status}, '
        'updatedAt: ${self.updatedAt}'
        ')';
  }

  @override
  bool operator ==(Object other) {
    final self = this as AdminCustomerGroupState;
    return identical(this, other) ||
        other is AdminCustomerGroupState &&
            runtimeType == other.runtimeType &&
            other.count == self.count &&
            other.createdAt == self.createdAt &&
            _adminCustomerGroupStateCustomerGroupsEquality.equals(other.customerGroups, self.customerGroups) &&
            other.failure == self.failure &&
            other.limit == self.limit &&
            other.offset == self.offset &&
            other.order == self.order &&
            other.query == self.query &&
            other.status == self.status &&
            other.updatedAt == self.updatedAt;
  }

  @override
  int get hashCode {
    final self = this as AdminCustomerGroupState;
    return Object.hashAll([
      runtimeType,
      self.count,
      self.createdAt,
      _adminCustomerGroupStateCustomerGroupsEquality.hash(self.customerGroups),
      self.failure,
      self.limit,
      self.offset,
      self.order,
      self.query,
      self.status,
      self.updatedAt,
    ]);
  }

  /// Creates a copy of this `AdminCustomerGroupState` with selected fields replaced.
  ///
  /// Usage:
  /// ```dart
  /// final updated = adminCustomerGroupState.copyWith(count: 1);
  /// ```
  @pragma('vm:prefer-inline')
  _$AdminCustomerGroupStateCopyWith<AdminCustomerGroupState> get copyWith => _$AdminCustomerGroupStateCopyWithImpl<AdminCustomerGroupState>(this as AdminCustomerGroupState, (value) => value);
}

// CopyWith API inspired by Freezed.

/// @nodoc
abstract class _$AdminCustomerGroupStateCopyWith<$Res> {
  $Res call({
    int? count,
    AdminDateFilter? createdAt,
    List<AdminCustomerGroup>? customerGroups,
    Option<String>? failure,
    int? limit,
    int? offset,
    AdminCustomerGroupOrder? order,
    String? query,
    AdminCustomerGroupStatus? status,
    AdminDateFilter? updatedAt,
  });
}

/// @nodoc
final class _$AdminCustomerGroupStateCopyWithImpl<$Res> implements _$AdminCustomerGroupStateCopyWith<$Res> {
  const _$AdminCustomerGroupStateCopyWithImpl(this._self, this._then);

  final AdminCustomerGroupState _self;
  final $Res Function(AdminCustomerGroupState) _then;

  @override
  @pragma('vm:prefer-inline')
  $Res call({
    Object? count = null,
    Object? createdAt = null,
    Object? customerGroups = null,
    Object? failure = null,
    Object? limit = null,
    Object? offset = null,
    Object? order = null,
    Object? query = null,
    Object? status = null,
    Object? updatedAt = null,
  }) {
    return _then(
      AdminCustomerGroupState(
        status: status == null ? _self.status : status as AdminCustomerGroupStatus,
        customerGroups: customerGroups == null ? _self.customerGroups : customerGroups as List<AdminCustomerGroup>,
        count: count == null ? _self.count : count as int,
        limit: limit == null ? _self.limit : limit as int,
        offset: offset == null ? _self.offset : offset as int,
        query: query == null ? _self.query : query as String,
        createdAt: createdAt == null ? _self.createdAt : createdAt as AdminDateFilter,
        updatedAt: updatedAt == null ? _self.updatedAt : updatedAt as AdminDateFilter,
        order: order == null ? _self.order : order as AdminCustomerGroupOrder,
        failure: failure == null ? _self.failure : failure as Option<String>,
      )
    );
  }
}
