// GENERATED CODE - DO NOT MODIFY BY HAND
// coverage:ignore-file
// ignore_for_file: type=lint
// ignore_for_file: unused_element, unused_import, deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: use_function_type_syntax_for_parameters
// ignore_for_file: unnecessary_const, avoid_init_to_null
// ignore_for_file: invalid_override_different_default_values_named
// ignore_for_file: prefer_expression_function_bodies
// ignore_for_file: annotate_overrides, invalid_annotation_target
// ignore_for_file: unnecessary_question_mark
// Generated by dust.

part of 'catalog_repository.dart';

final class _$CatalogRepository implements CatalogRepository {
  const _$CatalogRepository(this._db);

  final DatabaseExecutor _db;

  @override
  Future<Result<List<ProductRow>, SqlxError>> listPublished(int limit, int offset) {
    return _db.fetchAll<ProductRow>(
      r'''
SELECT id, title, handle, description, thumbnail, status
FROM products
WHERE status = 'published'
ORDER BY handle
LIMIT ? OFFSET ?
''',
      [limit, offset],
      const $ProductRowRowDeserializer().deserialize,
    );
  }

  @override
  Future<Result<ProductRow?, SqlxError>> findByHandle(String handle) {
    return _db.fetchOptional<ProductRow>(
      r'''
SELECT id, title, handle, description, thumbnail, status
FROM products
WHERE handle = ? AND status = 'published'
''',
      [handle],
      const $ProductRowRowDeserializer().deserialize,
    );
  }

  @override
  Future<Result<List<VariantRow>, SqlxError>> variantsOf(String productId, String currencyCode) {
    return _db.fetchAll<VariantRow>(
      r'''
SELECT v.id, v.product_id, v.title, v.sku, v.inventory_quantity,
       v.manage_inventory, v.allow_backorder,
       p.currency_code, p.amount
FROM product_variants v
JOIN variant_prices p ON p.variant_id = v.id
WHERE v.product_id = ? AND p.currency_code = ?
ORDER BY v.id
''',
      [productId, currencyCode],
      const $VariantRowRowDeserializer().deserialize,
    );
  }

  @override
  Future<Result<VariantRow?, SqlxError>> findVariant(String variantId, String currencyCode) {
    return _db.fetchOptional<VariantRow>(
      r'''
SELECT v.id, v.product_id, v.title, v.sku, v.inventory_quantity,
       v.manage_inventory, v.allow_backorder,
       p.currency_code, p.amount
FROM product_variants v
JOIN variant_prices p ON p.variant_id = v.id
WHERE v.id = ? AND p.currency_code = ?
''',
      [variantId, currencyCode],
      const $VariantRowRowDeserializer().deserialize,
    );
  }

  @override
  Future<Result<int, SqlxError>> countPublished() {
    return _db.fetchScalar<int>(
      r'''
SELECT COUNT(*) AS total
FROM products
WHERE status = 'published'
''',
      [],
    );
  }
}
