// GENERATED CODE - DO NOT MODIFY BY HAND
// coverage:ignore-file
// ignore_for_file: type=lint
// ignore_for_file: unused_element, unused_import, deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: use_function_type_syntax_for_parameters
// ignore_for_file: unnecessary_const, avoid_init_to_null
// ignore_for_file: invalid_override_different_default_values_named
// ignore_for_file: prefer_expression_function_bodies
// ignore_for_file: annotate_overrides, invalid_annotation_target
// ignore_for_file: unnecessary_question_mark
// Generated by dust.

part of 'product_row.dart';

mixin _$ProductRow {
  @override
  String toString() {
    final self = this as ProductRow;
    return 'ProductRow('
        'description: ${self.description}, '
        'handle: ${self.handle}, '
        'id: ${self.id}, '
        'status: ${self.status}, '
        'thumbnail: ${self.thumbnail}, '
        'title: ${self.title}'
        ')';
  }

  @override
  bool operator ==(Object other) {
    final self = this as ProductRow;
    return identical(this, other) ||
        other is ProductRow &&
            runtimeType == other.runtimeType &&
            other.description == self.description &&
            other.handle == self.handle &&
            other.id == self.id &&
            other.status == self.status &&
            other.thumbnail == self.thumbnail &&
            other.title == self.title;
  }

  @override
  int get hashCode {
    final self = this as ProductRow;
    return Object.hashAll([
      runtimeType,
      self.description,
      self.handle,
      self.id,
      self.status,
      self.thumbnail,
      self.title,
    ]);
  }
}

mixin _$VariantRow {
  @override
  String toString() {
    final self = this as VariantRow;
    return 'VariantRow('
        'allowBackorder: ${self.allowBackorder}, '
        'amount: ${self.amount}, '
        'currencyCode: ${self.currencyCode}, '
        'id: ${self.id}, '
        'inventoryQuantity: ${self.inventoryQuantity}, '
        'manageInventory: ${self.manageInventory}, '
        'productId: ${self.productId}, '
        'sku: ${self.sku}, '
        'title: ${self.title}'
        ')';
  }

  @override
  bool operator ==(Object other) {
    final self = this as VariantRow;
    return identical(this, other) ||
        other is VariantRow &&
            runtimeType == other.runtimeType &&
            other.allowBackorder == self.allowBackorder &&
            other.amount == self.amount &&
            other.currencyCode == self.currencyCode &&
            other.id == self.id &&
            other.inventoryQuantity == self.inventoryQuantity &&
            other.manageInventory == self.manageInventory &&
            other.productId == self.productId &&
            other.sku == self.sku &&
            other.title == self.title;
  }

  @override
  int get hashCode {
    final self = this as VariantRow;
    return Object.hashAll([
      runtimeType,
      self.allowBackorder,
      self.amount,
      self.currencyCode,
      self.id,
      self.inventoryQuantity,
      self.manageInventory,
      self.productId,
      self.sku,
      self.title,
    ]);
  }
}

ProductRow _$ProductRowFromRow(Row row) {
  return ProductRow(
    id: row.read<String>('id'),
    title: row.read<String>('title'),
    handle: row.read<String>('handle'),
    status: row.read<String>('status'),
    description: row.readNullable<String>('description'),
    thumbnail: row.readNullable<String>('thumbnail'),
  );
}

/// Row deserializer for [ProductRow].
final class $ProductRowRowDeserializer implements RowDeserializer<ProductRow> {
  const $ProductRowRowDeserializer();

  @override
  ProductRow deserialize(Row row) => _$ProductRowFromRow(row);
}

/// Typed row query terminals for [ProductRow].
///
/// Resolved from the static type of the receiver, so a row type with no
/// `FromRow` has no terminals and the call does not compile.
extension $ProductRowQuery on QueryAs<ProductRow> {
  /// Fetches exactly one row.
  Future<ProductRow> fetchOne(DatabaseExecutor db) =>
      fetchOneWith(db, _$ProductRowFromRow);

  /// Fetches zero or one row.
  Future<ProductRow?> fetchOptional(DatabaseExecutor db) =>
      fetchOptionalWith(db, _$ProductRowFromRow);

  /// Fetches every row.
  Future<List<ProductRow>> fetchAll(DatabaseExecutor db) =>
      fetchAllWith(db, _$ProductRowFromRow);
}

VariantRow _$VariantRowFromRow(Row row) {
  return VariantRow(
    id: row.read<String>('id'),
    productId: row.read<String>('product_id'),
    title: row.read<String>('title'),
    inventoryQuantity: row.read<int>('inventory_quantity'),
    manageInventory: row.read<int>('manage_inventory'),
    allowBackorder: row.read<int>('allow_backorder'),
    currencyCode: row.read<String>('currency_code'),
    amount: row.read<int>('amount'),
    sku: row.readNullable<String>('sku'),
  );
}

/// Row deserializer for [VariantRow].
final class $VariantRowRowDeserializer implements RowDeserializer<VariantRow> {
  const $VariantRowRowDeserializer();

  @override
  VariantRow deserialize(Row row) => _$VariantRowFromRow(row);
}

/// Typed row query terminals for [VariantRow].
///
/// Resolved from the static type of the receiver, so a row type with no
/// `FromRow` has no terminals and the call does not compile.
extension $VariantRowQuery on QueryAs<VariantRow> {
  /// Fetches exactly one row.
  Future<VariantRow> fetchOne(DatabaseExecutor db) =>
      fetchOneWith(db, _$VariantRowFromRow);

  /// Fetches zero or one row.
  Future<VariantRow?> fetchOptional(DatabaseExecutor db) =>
      fetchOptionalWith(db, _$VariantRowFromRow);

  /// Fetches every row.
  Future<List<VariantRow>> fetchAll(DatabaseExecutor db) =>
      fetchAllWith(db, _$VariantRowFromRow);
}
