const adminOrderDetailJson = <String, Object?>{
  'id': 'ord_detail',
  'display_id': 1001,
  'email': 'ada@example.com',
  'customer_name': 'Ada Lovelace',
  'currency_code': 'eur',
  'subtotal': 4500,
  'shipping_total': 500,
  'discount_total': 500,
  'tax': 900,
  'total': 5400,
  'status': 'completed',
  'payment_status': 'captured',
  'fulfillment_status': 'not_fulfilled',
  'shipping_name': 'Standard shipping',
  'promotion_code': 'WELCOME10',
  'placed_at': '2026-09-10T10:00:00.000Z',
  'created_at': '2026-09-10T10:00:00.000Z',
  'updated_at': '2026-09-10T10:05:00.000Z',
  'payment_provider': 'manual',
  'payment_amount': 5400,
  'payment_record_status': 'captured',
  'payment_created_at': '2026-09-10T10:01:00.000Z',
  'payment_captured_at': '2026-09-10T10:02:00.000Z',
  'items': <Object?>[
    <String, Object?>{
      'id': 'item_cup',
      'variant_id': 'var_cup',
      'product_id': 'prod_cup',
      'product_handle': 'espresso-cup',
      'thumbnail': null,
      'title': 'Espresso cup',
      'variant_title': 'Default',
      'unit_amount': 1500,
      'currency_code': 'eur',
      'quantity': 1,
      'created_at': '2026-09-10T10:00:00.000Z',
    },
  ],
  'shipping_address': <String, Object?>{
    'first_name': 'Ada',
    'last_name': 'Lovelace',
    'company': null,
    'line1': '1 Harbour Way',
    'line2': null,
    'city': 'Copenhagen',
    'province': null,
    'postal_code': '1050',
    'country_code': 'dk',
    'phone': '+45 12345678',
  },
  'billing_address': null,
};
