part of 'development_seed.dart';

/// Product rows stay explicit so demo copy, lifecycle and taxonomy are stable.
const _demoProductStatements = <_Statement>[
  _Statement(r'''
INSERT OR IGNORE INTO product_collections (id, title, handle)
VALUES ('pcol_seasonal', 'Seasonal', 'seasonal')
'''),
  _Statement(r'''
INSERT OR IGNORE INTO products
  (id, collection_id, type_id, title, handle, description, thumbnail, weight,
   status)
VALUES
  ('prod_demo_01', 'pcol_featured', 'ptyp_shirt', 'Classic White Tee',
   'classic-white-tee', 'A clean everyday tee in soft cotton.',
   'https://medusa-public-images.s3.eu-west-1.amazonaws.com/tee-white-front.png',
   380, 'published'),
  ('prod_demo_02', 'pcol_featured', 'ptyp_shirt', 'Heavyweight Black Tee',
   'heavyweight-black-tee', 'A structured heavyweight cotton tee.',
   'https://medusa-public-images.s3.eu-west-1.amazonaws.com/tee-black-front.png',
   460, 'published'),
  ('prod_demo_03', 'pcol_seasonal', 'ptyp_shirt', 'Ribbed Long Sleeve',
   'ribbed-long-sleeve', 'A fitted long sleeve for cooler days.',
   'https://medusa-public-images.s3.eu-west-1.amazonaws.com/tee-white-back.png',
   420, 'published'),
  ('prod_demo_04', 'pcol_featured', 'ptyp_shirt', 'Everyday Polo',
   'everyday-polo', 'A polished knit polo for daily wear.',
   'https://medusa-public-images.s3.eu-west-1.amazonaws.com/tee-black-back.png',
   440, 'published'),
  ('prod_demo_05', 'pcol_featured', 'ptyp_sweatshirt', 'Fleece Crewneck',
   'fleece-crewneck', 'A brushed fleece layer with a relaxed fit.',
   'https://medusa-public-images.s3.eu-west-1.amazonaws.com/sweatshirt-vintage-front.png',
   640, 'published'),
  ('prod_demo_06', 'pcol_seasonal', 'ptyp_sweatshirt', 'Zip Hoodie',
   'zip-hoodie', 'A versatile zip layer with soft interior fleece.',
   'https://medusa-public-images.s3.eu-west-1.amazonaws.com/sweatshirt-vintage-back.png',
   720, 'published'),
  ('prod_demo_07', 'pcol_featured', 'ptyp_sweatshirt', 'Oversized Hoodie',
   'oversized-hoodie', 'A roomy heavyweight hoodie for colder days.',
   'https://medusa-public-images.s3.eu-west-1.amazonaws.com/sweatshirt-vintage-front.png',
   760, 'published'),
  ('prod_demo_08', 'pcol_seasonal', 'ptyp_sweatshirt', 'Studio Pullover',
   'studio-pullover', 'A simple pullover made for work and travel.',
   'https://medusa-public-images.s3.eu-west-1.amazonaws.com/sweatshirt-vintage-back.png',
   680, 'published'),
  ('prod_demo_09', 'pcol_featured', 'ptyp_pants', 'Straight Leg Joggers',
   'straight-leg-joggers', 'Straight cut joggers in brushed cotton.',
   'https://medusa-public-images.s3.eu-west-1.amazonaws.com/sweatpants-gray-front.png',
   590, 'published'),
  ('prod_demo_10', 'pcol_seasonal', 'ptyp_pants', 'Cargo Trousers',
   'cargo-trousers', 'Utility trousers with a comfortable tapered fit.',
   'https://medusa-public-images.s3.eu-west-1.amazonaws.com/sweatpants-gray-back.png',
   610, 'published'),
  ('prod_demo_11', 'pcol_featured', 'ptyp_pants', 'Tailored Chinos',
   'tailored-chinos', 'Clean cotton chinos with subtle stretch.',
   'https://medusa-public-images.s3.eu-west-1.amazonaws.com/sweatpants-gray-front.png',
   560, 'published'),
  ('prod_demo_12', 'pcol_seasonal', 'ptyp_pants', 'Weekend Track Pants',
   'weekend-track-pants', 'Easy track pants with a relaxed silhouette.',
   'https://medusa-public-images.s3.eu-west-1.amazonaws.com/sweatpants-gray-back.png',
   580, 'published'),
  ('prod_demo_13', 'pcol_featured', 'ptyp_shorts', 'Linen Shorts',
   'linen-shorts', 'Lightweight shorts for warm weather.',
   'https://medusa-public-images.s3.eu-west-1.amazonaws.com/shorts-vintage-front.png',
   300, 'published'),
  ('prod_demo_14', 'pcol_seasonal', 'ptyp_shorts', 'Training Shorts',
   'training-shorts', 'Flexible shorts for active days.',
   'https://medusa-public-images.s3.eu-west-1.amazonaws.com/shorts-vintage-back.png',
   260, 'published'),
  ('prod_demo_15', 'pcol_featured', 'ptyp_shorts', 'Pleated Shorts',
   'pleated-shorts', 'Structured shorts with a clean front pleat.',
   'https://medusa-public-images.s3.eu-west-1.amazonaws.com/shorts-vintage-front.png',
   320, 'published'),
  ('prod_demo_16', 'pcol_seasonal', 'ptyp_shorts', 'Swim Shorts',
   'swim-shorts', 'Quick-drying shorts with secure pockets.',
   'https://medusa-public-images.s3.eu-west-1.amazonaws.com/shorts-vintage-back.png',
   240, 'published'),
  ('prod_demo_17', 'pcol_seasonal', 'ptyp_shirt', 'Sample Pocket Tee',
   'sample-pocket-tee', 'A draft pocket tee awaiting merchant review.',
   'https://medusa-public-images.s3.eu-west-1.amazonaws.com/tee-white-front.png',
   390, 'draft'),
  ('prod_demo_18', 'pcol_seasonal', 'ptyp_sweatshirt', 'Archive Hoodie',
   'archive-hoodie', 'A rejected concept retained for workflow testing.',
   'https://medusa-public-images.s3.eu-west-1.amazonaws.com/sweatshirt-vintage-front.png',
   740, 'rejected'),
  ('prod_demo_19', 'pcol_seasonal', 'ptyp_pants', 'Launch Trousers',
   'launch-trousers', 'A proposed trouser ready for approval.',
   'https://medusa-public-images.s3.eu-west-1.amazonaws.com/sweatpants-gray-front.png',
   600, 'proposed'),
  ('prod_demo_20', 'pcol_seasonal', 'ptyp_shorts', 'Sample Utility Shorts',
   'sample-utility-shorts', 'A draft utility short for catalogue review.',
   'https://medusa-public-images.s3.eu-west-1.amazonaws.com/shorts-vintage-front.png',
   310, 'draft'),
  ('prod_demo_21', 'pcol_featured', 'ptyp_shirt', 'Split Raglan Tee',
   'split-raglan-tee',
   'A two-axis demo tee with one intentionally unavailable combination.',
   'https://medusa-public-images.s3.eu-west-1.amazonaws.com/tee-black-front.png',
   410, 'published')
'''),
];
