// GENERATED CODE - DO NOT MODIFY BY HAND
// coverage:ignore-file
// ignore_for_file: type=lint
// ignore_for_file: unused_element, unused_import, deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: use_function_type_syntax_for_parameters
// ignore_for_file: unnecessary_const, avoid_init_to_null
// ignore_for_file: invalid_override_different_default_values_named
// ignore_for_file: prefer_expression_function_bodies
// ignore_for_file: annotate_overrides, invalid_annotation_target
// ignore_for_file: unnecessary_question_mark
// Generated by dust.

part of 'product.dart';

final class _$AdminProductDeleteRepository implements AdminProductDeleteRepository {
  const _$AdminProductDeleteRepository(this._db);

  final DatabaseExecutor _db;

  @override
  Future<Result<ExecResult, SqlxError>> product(String productId) {
    return _db.execute(
      r'''
UPDATE products
SET deleted_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id = ? AND deleted_at IS NULL
''',
      [productId],
    );
  }

  @override
  Future<Result<ExecResult, SqlxError>> variants(String productId) {
    return _db.execute(
      r'''
UPDATE product_variants
SET deleted_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE product_id = ? AND deleted_at IS NULL
''',
      [productId],
    );
  }

  @override
  Future<Result<ExecResult, SqlxError>> images(String productId) {
    return _db.execute(
      r'''
UPDATE product_images
SET deleted_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE product_id = ? AND deleted_at IS NULL
''',
      [productId],
    );
  }

  @override
  Future<Result<ExecResult, SqlxError>> exclusiveOptionValues(String productId) {
    return _db.execute(
      r'''
UPDATE product_option_values
SET deleted_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE deleted_at IS NULL AND option_id IN (
  SELECT link.product_option_id
  FROM product_product_options link
  JOIN product_options option ON option.id = link.product_option_id
  WHERE link.product_id = ? AND option.is_exclusive = 1
)
''',
      [productId],
    );
  }

  @override
  Future<Result<ExecResult, SqlxError>> exclusiveOptions(String productId) {
    return _db.execute(
      r'''
UPDATE product_options
SET deleted_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE deleted_at IS NULL AND is_exclusive = 1 AND id IN (
  SELECT product_option_id FROM product_product_options WHERE product_id = ?
)
''',
      [productId],
    );
  }

  @override
  Future<Result<ExecResult, SqlxError>> productOptionValues(String productId) {
    return _db.execute(
      r'''
UPDATE product_product_option_values
SET deleted_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE deleted_at IS NULL AND product_product_option_id IN (
  SELECT id FROM product_product_options WHERE product_id = ?
)
''',
      [productId],
    );
  }

  @override
  Future<Result<ExecResult, SqlxError>> productOptions(String productId) {
    return _db.execute(
      r'''
UPDATE product_product_options
SET deleted_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE product_id = ? AND deleted_at IS NULL
''',
      [productId],
    );
  }
}
