// GENERATED CODE - DO NOT MODIFY BY HAND
// coverage:ignore-file
// ignore_for_file: type=lint
// ignore_for_file: unused_element, unused_import, deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: use_function_type_syntax_for_parameters
// ignore_for_file: unnecessary_const, avoid_init_to_null
// ignore_for_file: invalid_override_different_default_values_named
// ignore_for_file: prefer_expression_function_bodies
// ignore_for_file: annotate_overrides, invalid_annotation_target
// ignore_for_file: unnecessary_question_mark
// Generated by dust.

part of 'image_variants.dart';

final class _$AdminProductImageVariantRepository implements AdminProductImageVariantRepository {
  const _$AdminProductImageVariantRepository(this._db);

  final DatabaseExecutor _db;

  @override
  Future<Result<String?, SqlxError>> imageProduct(String imageId) {
    return _db.fetchScalar<String?>(
      r'''
SELECT product_id
FROM product_images
WHERE id = ? AND deleted_at IS NULL
''',
      [imageId],
    );
  }

  @override
  Future<Result<String?, SqlxError>> variantProduct(String variantId) {
    return _db.fetchScalar<String?>(
      r'''
SELECT product_id
FROM product_variants
WHERE id = ? AND deleted_at IS NULL
''',
      [variantId],
    );
  }

  @override
  Future<Result<ExecResult, SqlxError>> add(String imageId, String variantId) {
    return _db.execute(
      r'''
INSERT INTO product_image_variants (image_id, variant_id)
VALUES (?, ?)
ON CONFLICT (image_id, variant_id) DO NOTHING
''',
      [imageId, variantId],
    );
  }

  @override
  Future<Result<ExecResult, SqlxError>> remove(String imageId, String variantId) {
    return _db.execute(
      r'''
DELETE FROM product_image_variants
WHERE image_id = ? AND variant_id = ?
''',
      [imageId, variantId],
    );
  }

  @override
  Future<Result<ExecResult, SqlxError>> removeForShiftedImages(String productId, int minimumRank) {
    return _db.execute(
      r'''
DELETE FROM product_image_variants
WHERE image_id IN (
  SELECT id
  FROM product_images
  WHERE product_id = ? AND deleted_at IS NULL AND rank >= ?
)
''',
      [productId, minimumRank],
    );
  }
}
