// GENERATED CODE - DO NOT MODIFY BY HAND
// coverage:ignore-file
// ignore_for_file: type=lint
// ignore_for_file: unused_element, unused_import, deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: use_function_type_syntax_for_parameters
// ignore_for_file: unnecessary_const, avoid_init_to_null
// ignore_for_file: invalid_override_different_default_values_named
// ignore_for_file: prefer_expression_function_bodies
// ignore_for_file: annotate_overrides, invalid_annotation_target
// ignore_for_file: unnecessary_question_mark
// Generated by dust.

part of 'update.dart';

final class _$AdminProductUpdateRepository implements AdminProductUpdateRepository {
  const _$AdminProductUpdateRepository(this._db);

  final DatabaseExecutor _db;

  @override
  Future<Result<ExecResult, SqlxError>> updateGeneral(String id, String title, String handle, String? subtitle, String? material, String? description, int discountable, String status) {
    return _db.execute(
      r'''
UPDATE products
SET title = trim(?),
    handle = ?,
    subtitle = nullif(trim(?), ''),
    material = nullif(trim(?), ''),
    description = nullif(trim(?), ''),
    discountable = ?,
    status = ?
WHERE id = ?
  AND deleted_at IS NULL
  AND NOT EXISTS (
    SELECT 1
    FROM products other
    WHERE other.handle = ?
      AND other.id <> ?
      AND other.deleted_at IS NULL
  )
''',
      [title, handle, subtitle, material, description, discountable, status, id, handle, id],
    );
  }
}
