// GENERATED CODE - DO NOT MODIFY BY HAND
// coverage:ignore-file
// ignore_for_file: type=lint
// ignore_for_file: unused_element, unused_import, deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: use_function_type_syntax_for_parameters
// ignore_for_file: unnecessary_const, avoid_init_to_null
// ignore_for_file: invalid_override_different_default_values_named
// ignore_for_file: prefer_expression_function_bodies
// ignore_for_file: annotate_overrides, invalid_annotation_target
// ignore_for_file: unnecessary_question_mark
// Generated by dust.

part of 'update.dart';

final class _$AccountUpdateRepository implements AccountUpdateRepository {
  const _$AccountUpdateRepository(this._db);

  final DatabaseExecutor _db;

  @override
  Future<Result<ExecResult, SqlxError>> updatePassword(String authIdentityId, String expectedHash, String newHash) {
    return _db.execute(
      r'''
UPDATE provider_identity
SET provider_metadata = json_set(
      coalesce(provider_metadata, '{}'), '$.password', ?
    )
WHERE auth_identity_id = ?
  AND provider = 'emailpass'
  AND CAST(json_extract(provider_metadata, '$.password') AS TEXT) = ?
  AND deleted_at IS NULL
''',
      [newHash, authIdentityId, expectedHash],
    );
  }

  @override
  Future<Result<CustomerResponse?, SqlxError>> updateProfile(String customerId, String firstName, String lastName, String? phone) {
    return _db.fetchOptional<CustomerResponse>(
      r'''
UPDATE customers
SET first_name = ?, last_name = ?, phone = ?
WHERE id = ? AND has_account = 1 AND deleted_at IS NULL
RETURNING id, coalesce(email, '') AS email, first_name, last_name, phone
''',
      [firstName, lastName, phone, customerId],
      const $CustomerResponseRowDeserializer().deserialize,
    );
  }

  @override
  Future<Result<CustomerAddressResponse?, SqlxError>> updateAddress(String id, String customerId, String firstName, String lastName, String? company, String? phone, String line1, String? line2, String city, String? province, String postalCode, String countryCode, int isDefaultShipping, int isDefaultBilling) {
    return _db.fetchOptional<CustomerAddressResponse>(
      r'''
UPDATE customer_addresses
SET first_name = ?, last_name = ?, company = ?, phone = ?,
    address_1 = ?, address_2 = ?, city = ?, province = ?,
    postal_code = ?, country_code = ?,
    is_default_shipping = ?, is_default_billing = ?
WHERE id = ? AND customer_id = ? AND deleted_at IS NULL
RETURNING id, first_name, last_name, company, phone, address_1, address_2,
          city, province, postal_code, country_code,
          is_default_shipping, is_default_billing
''',
      [firstName, lastName, company, phone, line1, line2, city, province, postalCode, countryCode, isDefaultShipping, isDefaultBilling, id, customerId],
      const $CustomerAddressResponseRowDeserializer().deserialize,
    );
  }
}
