// GENERATED CODE - DO NOT MODIFY BY HAND
// coverage:ignore-file
// ignore_for_file: type=lint
// ignore_for_file: unused_element, unused_import, deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: use_function_type_syntax_for_parameters
// ignore_for_file: unnecessary_const, avoid_init_to_null
// ignore_for_file: invalid_override_different_default_values_named
// ignore_for_file: prefer_expression_function_bodies
// ignore_for_file: annotate_overrides, invalid_annotation_target
// ignore_for_file: unnecessary_question_mark
// Generated by dust.

part of 'cart_request.dart';

mixin _$CreateCartBody implements Validatable, Serializable {
  @override
  String toString() {
    final self = this as CreateCartBody;
    return 'CreateCartBody('
        'email: ${self.email}, '
        'regionId: ${self.regionId}'
        ')';
  }

  @override
  bool operator ==(Object other) {
    final self = this as CreateCartBody;
    return identical(this, other) ||
        other is CreateCartBody &&
            runtimeType == other.runtimeType &&
            other.email == self.email &&
            other.regionId == self.regionId;
  }

  @override
  int get hashCode {
    final self = this as CreateCartBody;
    return Object.hashAll([
      runtimeType,
      self.email,
      self.regionId,
    ]);
  }

  /// Validates this `CreateCartBody`.
  ///
  /// Usage:
  /// ```dart
  /// final result = value.validate();
  /// if (result case Invalid(:final errors)) {
  ///   print(errors.first.message);
  /// }
  /// ```
  ValidationResult validate() {
    final self = this as CreateCartBody;
    final errors = <ValidationError>[];
    _CreateCartBodyValidation._validateEmail(self.email, errors);
    return errors.isEmpty ? const Valid() : Invalid(errors);
  }

  /// Throws [ValidationException] when this `CreateCartBody` is invalid.
  ///
  /// Usage:
  /// ```dart
  /// value.validateOrThrow();
  /// ```
  void validateOrThrow() {
    final result = validate();
    if (result case Invalid(errors: final errors)) {
      throw ValidationException(errors);
    }
  }

  Map<String, Object?> serialize() =>
      _$CreateCartBodySerialize(this as CreateCartBody);

  Map<String, Object?> toJson() => serialize();
}

mixin _$AddLineBody implements Validatable, Serializable {
  @override
  String toString() {
    final self = this as AddLineBody;
    return 'AddLineBody('
        'quantity: ${self.quantity}, '
        'variantId: ${self.variantId}'
        ')';
  }

  @override
  bool operator ==(Object other) {
    final self = this as AddLineBody;
    return identical(this, other) ||
        other is AddLineBody &&
            runtimeType == other.runtimeType &&
            other.quantity == self.quantity &&
            other.variantId == self.variantId;
  }

  @override
  int get hashCode {
    final self = this as AddLineBody;
    return Object.hashAll([
      runtimeType,
      self.quantity,
      self.variantId,
    ]);
  }

  /// Validates this `AddLineBody`.
  ///
  /// Usage:
  /// ```dart
  /// final result = value.validate();
  /// if (result case Invalid(:final errors)) {
  ///   print(errors.first.message);
  /// }
  /// ```
  ValidationResult validate() {
    final self = this as AddLineBody;
    final errors = <ValidationError>[];
    _AddLineBodyValidation._validateQuantity(self.quantity, errors);
    _AddLineBodyValidation._validateVariantId(self.variantId, errors);
    return errors.isEmpty ? const Valid() : Invalid(errors);
  }

  /// Throws [ValidationException] when this `AddLineBody` is invalid.
  ///
  /// Usage:
  /// ```dart
  /// value.validateOrThrow();
  /// ```
  void validateOrThrow() {
    final result = validate();
    if (result case Invalid(errors: final errors)) {
      throw ValidationException(errors);
    }
  }

  Map<String, Object?> serialize() =>
      _$AddLineBodySerialize(this as AddLineBody);

  Map<String, Object?> toJson() => serialize();
}

mixin _$ChooseShippingBody implements Validatable, Serializable {
  @override
  String toString() {
    final self = this as ChooseShippingBody;
    return 'ChooseShippingBody('
        'optionId: ${self.optionId}'
        ')';
  }

  @override
  bool operator ==(Object other) {
    final self = this as ChooseShippingBody;
    return identical(this, other) ||
        other is ChooseShippingBody &&
            runtimeType == other.runtimeType &&
            other.optionId == self.optionId;
  }

  @override
  int get hashCode {
    final self = this as ChooseShippingBody;
    return Object.hashAll([
      runtimeType,
      self.optionId,
    ]);
  }

  /// Validates this `ChooseShippingBody`.
  ///
  /// Usage:
  /// ```dart
  /// final result = value.validate();
  /// if (result case Invalid(:final errors)) {
  ///   print(errors.first.message);
  /// }
  /// ```
  ValidationResult validate() {
    final self = this as ChooseShippingBody;
    final errors = <ValidationError>[];
    _ChooseShippingBodyValidation._validateOptionId(self.optionId, errors);
    return errors.isEmpty ? const Valid() : Invalid(errors);
  }

  /// Throws [ValidationException] when this `ChooseShippingBody` is invalid.
  ///
  /// Usage:
  /// ```dart
  /// value.validateOrThrow();
  /// ```
  void validateOrThrow() {
    final result = validate();
    if (result case Invalid(errors: final errors)) {
      throw ValidationException(errors);
    }
  }

  Map<String, Object?> serialize() =>
      _$ChooseShippingBodySerialize(this as ChooseShippingBody);

  Map<String, Object?> toJson() => serialize();
}

mixin _$ApplyPromotionBody implements Validatable, Serializable {
  @override
  String toString() {
    final self = this as ApplyPromotionBody;
    return 'ApplyPromotionBody('
        'code: ${self.code}'
        ')';
  }

  @override
  bool operator ==(Object other) {
    final self = this as ApplyPromotionBody;
    return identical(this, other) ||
        other is ApplyPromotionBody &&
            runtimeType == other.runtimeType &&
            other.code == self.code;
  }

  @override
  int get hashCode {
    final self = this as ApplyPromotionBody;
    return Object.hashAll([
      runtimeType,
      self.code,
    ]);
  }

  /// Validates this `ApplyPromotionBody`.
  ///
  /// Usage:
  /// ```dart
  /// final result = value.validate();
  /// if (result case Invalid(:final errors)) {
  ///   print(errors.first.message);
  /// }
  /// ```
  ValidationResult validate() {
    final self = this as ApplyPromotionBody;
    final errors = <ValidationError>[];
    _ApplyPromotionBodyValidation._validateCode(self.code, errors);
    return errors.isEmpty ? const Valid() : Invalid(errors);
  }

  /// Throws [ValidationException] when this `ApplyPromotionBody` is invalid.
  ///
  /// Usage:
  /// ```dart
  /// value.validateOrThrow();
  /// ```
  void validateOrThrow() {
    final result = validate();
    if (result case Invalid(errors: final errors)) {
      throw ValidationException(errors);
    }
  }

  Map<String, Object?> serialize() =>
      _$ApplyPromotionBodySerialize(this as ApplyPromotionBody);

  Map<String, Object?> toJson() => serialize();
}

extension _CreateCartBodyValidation on CreateCartBody {
  static void _validateEmail(String? email, List<ValidationError> errors) {
    if (email != null) {
      if (!ValidationHelper.isEmail(email)) {
        errors.add(ValidationError(field: 'email', message: 'Enter a valid email address'));
      }
    }
  }

}
extension _AddLineBodyValidation on AddLineBody {
  static void _validateQuantity(int quantity, List<ValidationError> errors) {
    if (quantity < 1) {
      errors.add(ValidationError(field: 'quantity', message: 'Order at least one'));
    }
  }

  static void _validateVariantId(String variantId, List<ValidationError> errors) {
    if (variantId.length < 1) {
      errors.add(ValidationError(field: 'variantId', message: 'variant_id is required'));
    }
  }

}
extension _ChooseShippingBodyValidation on ChooseShippingBody {
  static void _validateOptionId(String optionId, List<ValidationError> errors) {
    if (optionId.length < 1) {
      errors.add(ValidationError(field: 'optionId', message: 'option_id is required'));
    }
  }

}
extension _ApplyPromotionBodyValidation on ApplyPromotionBody {
  static void _validateCode(String code, List<ValidationError> errors) {
    if (code.length < 1) {
      errors.add(ValidationError(field: 'code', message: 'code is required'));
    }
  }

}
final class $CreateCartBodySerializer implements Serializer<CreateCartBody, Map<String, Object?>> {
  const $CreateCartBodySerializer();

  @override
  Map<String, Object?> serialize(CreateCartBody value) => _$CreateCartBodySerialize(value);
}
final class $CreateCartBodyDeserializer implements Deserializer<CreateCartBody, Map<String, Object?>> {
  const $CreateCartBodyDeserializer();

  @override
  CreateCartBody deserialize(Map<String, Object?> json) => _$CreateCartBodyDeserialize(json);
}
final class $AddLineBodySerializer implements Serializer<AddLineBody, Map<String, Object?>> {
  const $AddLineBodySerializer();

  @override
  Map<String, Object?> serialize(AddLineBody value) => _$AddLineBodySerialize(value);
}
final class $AddLineBodyDeserializer implements Deserializer<AddLineBody, Map<String, Object?>> {
  const $AddLineBodyDeserializer();

  @override
  AddLineBody deserialize(Map<String, Object?> json) => _$AddLineBodyDeserialize(json);
}
final class $ChooseShippingBodySerializer implements Serializer<ChooseShippingBody, Map<String, Object?>> {
  const $ChooseShippingBodySerializer();

  @override
  Map<String, Object?> serialize(ChooseShippingBody value) => _$ChooseShippingBodySerialize(value);
}
final class $ChooseShippingBodyDeserializer implements Deserializer<ChooseShippingBody, Map<String, Object?>> {
  const $ChooseShippingBodyDeserializer();

  @override
  ChooseShippingBody deserialize(Map<String, Object?> json) => _$ChooseShippingBodyDeserialize(json);
}
final class $ApplyPromotionBodySerializer implements Serializer<ApplyPromotionBody, Map<String, Object?>> {
  const $ApplyPromotionBodySerializer();

  @override
  Map<String, Object?> serialize(ApplyPromotionBody value) => _$ApplyPromotionBodySerialize(value);
}
final class $ApplyPromotionBodyDeserializer implements Deserializer<ApplyPromotionBody, Map<String, Object?>> {
  const $ApplyPromotionBodyDeserializer();

  @override
  ApplyPromotionBody deserialize(Map<String, Object?> json) => _$ApplyPromotionBodyDeserialize(json);
}

Map<String, Object?> _$CreateCartBodySerialize(CreateCartBody instance) {
  return <String, Object?>{
    'email': instance.email,
    'region_id': instance.regionId,
  };
}

Map<String, Object?> _$CreateCartBodyToJson(CreateCartBody instance) =>
    _$CreateCartBodySerialize(instance);

// factory CreateCartBody.fromJson(Map<String, Object?> json) => _$CreateCartBodyFromJson(json);
CreateCartBody _$CreateCartBodyDeserialize(Map<String, Object?> json) {
  final emailValue = json['email'] == null
      ? null
      : JsonHelper.as<String>(json['email'], 'email', 'String');
  final regionIdValue = json['region_id'] == null
      ? null
      : JsonHelper.as<String>(json['region_id'], 'region_id', 'String');

  return CreateCartBody(regionId: regionIdValue, email: emailValue);
}

CreateCartBody _$CreateCartBodyFromJson(Map<String, Object?> json) =>
    _$CreateCartBodyDeserialize(json);

Map<String, Object?> _$AddLineBodySerialize(AddLineBody instance) {
  return <String, Object?>{
    'quantity': instance.quantity,
    'variant_id': instance.variantId,
  };
}

Map<String, Object?> _$AddLineBodyToJson(AddLineBody instance) =>
    _$AddLineBodySerialize(instance);

// factory AddLineBody.fromJson(Map<String, Object?> json) => _$AddLineBodyFromJson(json);
AddLineBody _$AddLineBodyDeserialize(Map<String, Object?> json) {
  final quantityValue = json.containsKey('quantity')
      ? JsonHelper.as<int>(json['quantity'], 'quantity', 'int')
      : 1;
  final variantIdValue = JsonHelper.as<String>(
    json['variant_id'],
    'variant_id',
    'String',
  );

  return AddLineBody(variantId: variantIdValue, quantity: quantityValue);
}

AddLineBody _$AddLineBodyFromJson(Map<String, Object?> json) =>
    _$AddLineBodyDeserialize(json);

Map<String, Object?> _$ChooseShippingBodySerialize(ChooseShippingBody instance) {
  return <String, Object?>{
    'option_id': instance.optionId,
  };
}

Map<String, Object?> _$ChooseShippingBodyToJson(ChooseShippingBody instance) =>
    _$ChooseShippingBodySerialize(instance);

// factory ChooseShippingBody.fromJson(Map<String, Object?> json) => _$ChooseShippingBodyFromJson(json);
ChooseShippingBody _$ChooseShippingBodyDeserialize(Map<String, Object?> json) {
  final optionIdValue = JsonHelper.as<String>(
    json['option_id'],
    'option_id',
    'String',
  );

  return ChooseShippingBody(optionId: optionIdValue);
}

ChooseShippingBody _$ChooseShippingBodyFromJson(Map<String, Object?> json) =>
    _$ChooseShippingBodyDeserialize(json);

Map<String, Object?> _$ApplyPromotionBodySerialize(ApplyPromotionBody instance) {
  return <String, Object?>{
    'code': instance.code,
  };
}

Map<String, Object?> _$ApplyPromotionBodyToJson(ApplyPromotionBody instance) =>
    _$ApplyPromotionBodySerialize(instance);

// factory ApplyPromotionBody.fromJson(Map<String, Object?> json) => _$ApplyPromotionBodyFromJson(json);
ApplyPromotionBody _$ApplyPromotionBodyDeserialize(Map<String, Object?> json) {
  final codeValue = JsonHelper.as<String>(json['code'], 'code', 'String');

  return ApplyPromotionBody(code: codeValue);
}

ApplyPromotionBody _$ApplyPromotionBodyFromJson(Map<String, Object?> json) =>
    _$ApplyPromotionBodyDeserialize(json);
