// GENERATED CODE - DO NOT MODIFY BY HAND
// coverage:ignore-file
// ignore_for_file: type=lint
// ignore_for_file: unused_element, unused_import, deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: use_function_type_syntax_for_parameters
// ignore_for_file: unnecessary_const, avoid_init_to_null
// ignore_for_file: invalid_override_different_default_values_named
// ignore_for_file: prefer_expression_function_bodies
// ignore_for_file: annotate_overrides, invalid_annotation_target
// ignore_for_file: unnecessary_question_mark
// Generated by dust.

part of 'delete_repository.dart';

final class _$AdminCustomerDeleteRepository implements AdminCustomerDeleteRepository {
  const _$AdminCustomerDeleteRepository(this._db);

  final DatabaseExecutor _db;

  @override
  Future<Result<AdminCustomerDeleteContext?, SqlxError>> find(String id) {
    return _db.fetchOptional<AdminCustomerDeleteContext>(
      r'''
WITH active_identity AS (
  SELECT id, app_metadata
  FROM auth_identity
  WHERE deleted_at IS NULL
    AND json_extract(app_metadata, '$.customer_id') = ?
)
SELECT customer.has_account,
       (SELECT min(id) FROM active_identity) AS auth_identity_id,
       (SELECT count(*) FROM active_identity) AS auth_identity_count,
       CASE WHEN EXISTS (
         SELECT 1 FROM active_identity, json_each(active_identity.app_metadata)
         WHERE json_each.key <> 'customer_id' AND json_each.value IS NOT NULL
       ) THEN 1 ELSE 0 END AS has_other_actor
FROM customers customer
WHERE customer.id = ? AND customer.deleted_at IS NULL
''',
      [id, id],
      const $AdminCustomerDeleteContextRowDeserializer().deserialize,
    );
  }

  @override
  Future<Result<ExecResult, SqlxError>> customer(String id) {
    return _db.execute(
      r'''
UPDATE customers
SET deleted_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id = ? AND deleted_at IS NULL
''',
      [id],
    );
  }

  @override
  Future<Result<ExecResult, SqlxError>> addresses(String customerId) {
    return _db.execute(
      r'''
UPDATE customer_addresses
SET deleted_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE customer_id = ? AND deleted_at IS NULL
''',
      [customerId],
    );
  }

  @override
  Future<Result<ExecResult, SqlxError>> detachCustomer(String authIdentityId) {
    return _db.execute(
      r'''
UPDATE auth_identity
SET app_metadata = json_remove(app_metadata, '$.customer_id')
WHERE id = ? AND deleted_at IS NULL
''',
      [authIdentityId],
    );
  }

  @override
  Future<Result<ExecResult, SqlxError>> tokens(String authIdentityId) {
    return _db.execute(
      r'''DELETE FROM auth_tokens WHERE auth_identity_id = ?''',
      [authIdentityId],
    );
  }

  @override
  Future<Result<ExecResult, SqlxError>> verification(String authIdentityId) {
    return _db.execute(
      r'''DELETE FROM email_verifications WHERE auth_identity_id = ?''',
      [authIdentityId],
    );
  }

  @override
  Future<Result<ExecResult, SqlxError>> providers(String authIdentityId) {
    return _db.execute(
      r'''
UPDATE provider_identity
SET deleted_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE auth_identity_id = ? AND deleted_at IS NULL
''',
      [authIdentityId],
    );
  }

  @override
  Future<Result<ExecResult, SqlxError>> identity(String authIdentityId) {
    return _db.execute(
      r'''
UPDATE auth_identity
SET deleted_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id = ? AND deleted_at IS NULL
''',
      [authIdentityId],
    );
  }
}
