// GENERATED CODE - DO NOT MODIFY BY HAND
// coverage:ignore-file
// ignore_for_file: type=lint
// ignore_for_file: unused_element, unused_import, deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: use_function_type_syntax_for_parameters
// ignore_for_file: unnecessary_const, avoid_init_to_null
// ignore_for_file: invalid_override_different_default_values_named
// ignore_for_file: prefer_expression_function_bodies
// ignore_for_file: annotate_overrides, invalid_annotation_target
// ignore_for_file: unnecessary_question_mark
// Generated by dust.

part of 'detail_model.dart';

mixin _$AdminCustomerDetailResponse implements Serializable {
  Map<String, Object?> serialize() =>
      _$AdminCustomerDetailResponseSerialize(this as AdminCustomerDetailResponse);

  Map<String, Object?> toJson() => serialize();
}

final class $AdminCustomerDetailResponseSerializer implements Serializer<AdminCustomerDetailResponse, Map<String, Object?>> {
  const $AdminCustomerDetailResponseSerializer();

  @override
  Map<String, Object?> serialize(AdminCustomerDetailResponse value) => _$AdminCustomerDetailResponseSerialize(value);
}
AdminCustomerDetailResponse _$AdminCustomerDetailResponseFromRow(Row row) {
  return AdminCustomerDetailResponse(
    id: row.read<String>('id'),
    email: row.readNullable<String>('email'),
    companyName: row.readNullable<String>('company_name'),
    firstName: row.readNullable<String>('first_name'),
    lastName: row.readNullable<String>('last_name'),
    phone: row.readNullable<String>('phone'),
    hasAccount: _AdminCustomerDetailFlag().decode(row.read<int>('has_account')),
    createdAt: _AdminCustomerDetailDateTime().decode(row.read<String>('created_at')),
    updatedAt: _AdminCustomerDetailDateTime().decode(row.read<String>('updated_at')),
    addresses: _AdminCustomerAddressesFromString().decode(row.read<String>('addresses_json')),
  );
}

/// Row deserializer for [AdminCustomerDetailResponse].
final class $AdminCustomerDetailResponseRowDeserializer implements RowDeserializer<AdminCustomerDetailResponse> {
  const $AdminCustomerDetailResponseRowDeserializer();

  @override
  AdminCustomerDetailResponse deserialize(Row row) => _$AdminCustomerDetailResponseFromRow(row);
}

/// Typed row query terminals for [AdminCustomerDetailResponse].
///
/// Resolved from the static type of the receiver, so a row type with no
/// `FromRow` has no terminals and the call does not compile.
extension $AdminCustomerDetailResponseQuery on QueryAs<AdminCustomerDetailResponse> {
  /// Fetches exactly one row.
  Future<AdminCustomerDetailResponse> fetchOne(DatabaseExecutor db) =>
      fetchOneWith(db, _$AdminCustomerDetailResponseFromRow);

  /// Fetches zero or one row.
  Future<AdminCustomerDetailResponse?> fetchOptional(DatabaseExecutor db) =>
      fetchOptionalWith(db, _$AdminCustomerDetailResponseFromRow);

  /// Fetches every row.
  Future<List<AdminCustomerDetailResponse>> fetchAll(DatabaseExecutor db) =>
      fetchAllWith(db, _$AdminCustomerDetailResponseFromRow);
}

Map<String, Object?> _$AdminCustomerDetailResponseSerialize(AdminCustomerDetailResponse instance) {
  return <String, Object?>{
    'addresses': instance.addresses
        .map((item) => item.toJson())
        .toList(),
    'company_name': instance.companyName,
    'created_at': instance.createdAt.toIso8601String(),
    'email': instance.email,
    'first_name': instance.firstName,
    'has_account': instance.hasAccount,
    'id': instance.id,
    'last_name': instance.lastName,
    'phone': instance.phone,
    'updated_at': instance.updatedAt.toIso8601String(),
  };
}

Map<String, Object?> _$AdminCustomerDetailResponseToJson(AdminCustomerDetailResponse instance) =>
    _$AdminCustomerDetailResponseSerialize(instance);
