// GENERATED CODE - DO NOT MODIFY BY HAND
// coverage:ignore-file
// ignore_for_file: type=lint
// ignore_for_file: unused_element, unused_import, deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: use_function_type_syntax_for_parameters
// ignore_for_file: unnecessary_const, avoid_init_to_null
// ignore_for_file: invalid_override_different_default_values_named
// ignore_for_file: prefer_expression_function_bodies
// ignore_for_file: annotate_overrides, invalid_annotation_target
// ignore_for_file: unnecessary_question_mark
// Generated by dust.

part of 'detail_repository.dart';

final class _$AdminCustomerDetailRepository implements AdminCustomerDetailRepository {
  const _$AdminCustomerDetailRepository(this._db);

  final DatabaseExecutor _db;

  @override
  Future<Result<AdminCustomerDetailResponse?, SqlxError>> find(String id) {
    return _db.fetchOptional<AdminCustomerDetailResponse>(
      r'''
SELECT customer.id,
       customer.email,
       customer.company_name,
       customer.first_name,
       customer.last_name,
       customer.phone,
       customer.has_account,
       customer.created_at,
       customer.updated_at,
       coalesce((
         SELECT json_group_array(json_object(
           'id', address.id,
           'first_name', address.first_name,
           'last_name', address.last_name,
           'company', address.company,
           'phone', address.phone,
           'address_1', address.address_1,
           'address_2', address.address_2,
           'city', address.city,
           'province', address.province,
           'postal_code', address.postal_code,
           'country_code', address.country_code,
           'is_default_shipping', json(iif(
             address.is_default_shipping = 1, 'true', 'false'
           )),
           'is_default_billing', json(iif(
             address.is_default_billing = 1, 'true', 'false'
           ))
         ))
         FROM (
           SELECT * FROM customer_addresses
           WHERE customer_id = customer.id AND deleted_at IS NULL
           ORDER BY is_default_shipping DESC, is_default_billing DESC,
                    created_at, id
         ) address
       ), '[]') AS addresses_json
FROM customers customer
WHERE customer.id = ? AND customer.deleted_at IS NULL
''',
      [id],
      const $AdminCustomerDetailResponseRowDeserializer().deserialize,
    );
  }
}
