// GENERATED CODE - DO NOT MODIFY BY HAND
// coverage:ignore-file
// ignore_for_file: type=lint
// ignore_for_file: unused_element, unused_import, deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: use_function_type_syntax_for_parameters
// ignore_for_file: unnecessary_const, avoid_init_to_null
// ignore_for_file: invalid_override_different_default_values_named
// ignore_for_file: prefer_expression_function_bodies
// ignore_for_file: annotate_overrides, invalid_annotation_target
// ignore_for_file: unnecessary_question_mark
// Generated by dust.

part of 'repository.dart';

final class _$AdminCustomerRepository implements AdminCustomerRepository {
  const _$AdminCustomerRepository(this._db);

  final DatabaseExecutor _db;

  @override
  Future<Result<List<AdminCustomerResponse>, SqlxError>> list(String query, int hasAccount, String createdAfter, String createdFrom, String createdBefore, String createdTo, String updatedAfter, String updatedFrom, String updatedBefore, String updatedTo, String order, int limit, int offset) {
    return _db.fetchAll<AdminCustomerResponse>(
      r'''
SELECT customer.id,
       customer.email,
       customer.first_name,
       customer.last_name,
       customer.has_account,
       customer.created_at,
       customer.updated_at
FROM customers customer
WHERE customer.deleted_at IS NULL
  AND (? = '' OR lower(customer.id) LIKE '%' || lower(?) || '%'
       OR lower(coalesce(customer.email, '')) LIKE '%' || lower(?) || '%'
       OR lower(coalesce(customer.company_name, '')) LIKE '%' || lower(?) || '%'
       OR lower(coalesce(customer.first_name, '')) LIKE '%' || lower(?) || '%'
       OR lower(coalesce(customer.last_name, '')) LIKE '%' || lower(?) || '%'
       OR lower(trim(coalesce(customer.first_name, '') || ' ' ||
                     coalesce(customer.last_name, '')))
          LIKE '%' || lower(?) || '%')
  AND (? = -1 OR customer.has_account = ?)
  AND (? = '' OR customer.created_at > ?)
  AND (? = '' OR customer.created_at >= ?)
  AND (? = '' OR customer.created_at < ?)
  AND (? = '' OR customer.created_at <= ?)
  AND (? = '' OR customer.updated_at > ?)
  AND (? = '' OR customer.updated_at >= ?)
  AND (? = '' OR customer.updated_at < ?)
  AND (? = '' OR customer.updated_at <= ?)
ORDER BY
  CASE WHEN ? = 'email' THEN lower(customer.email) END ASC,
  CASE WHEN ? = '-email' THEN lower(customer.email) END DESC,
  CASE WHEN ? = 'first_name' THEN lower(customer.first_name) END ASC,
  CASE WHEN ? = '-first_name' THEN lower(customer.first_name) END DESC,
  CASE WHEN ? = 'last_name' THEN lower(customer.last_name) END ASC,
  CASE WHEN ? = '-last_name' THEN lower(customer.last_name) END DESC,
  CASE WHEN ? = 'has_account' THEN customer.has_account END ASC,
  CASE WHEN ? = '-has_account' THEN customer.has_account END DESC,
  CASE WHEN ? = 'created_at' THEN customer.created_at END ASC,
  CASE WHEN ? = '-created_at' THEN customer.created_at END DESC,
  CASE WHEN ? = 'updated_at' THEN customer.updated_at END ASC,
  CASE WHEN ? = '-updated_at' THEN customer.updated_at END DESC,
  customer.created_at DESC,
  customer.id
LIMIT ? OFFSET ?
''',
      [query, query, query, query, query, query, query, hasAccount, hasAccount, createdAfter, createdAfter, createdFrom, createdFrom, createdBefore, createdBefore, createdTo, createdTo, updatedAfter, updatedAfter, updatedFrom, updatedFrom, updatedBefore, updatedBefore, updatedTo, updatedTo, order, order, order, order, order, order, order, order, order, order, order, order, limit, offset],
      const $AdminCustomerResponseRowDeserializer().deserialize,
    );
  }

  @override
  Future<Result<int, SqlxError>> count(String query, int hasAccount, String createdAfter, String createdFrom, String createdBefore, String createdTo, String updatedAfter, String updatedFrom, String updatedBefore, String updatedTo) {
    return _db.fetchScalar<int>(
      r'''
SELECT count(*)
FROM customers customer
WHERE customer.deleted_at IS NULL
  AND (? = '' OR lower(customer.id) LIKE '%' || lower(?) || '%'
       OR lower(coalesce(customer.email, '')) LIKE '%' || lower(?) || '%'
       OR lower(coalesce(customer.company_name, '')) LIKE '%' || lower(?) || '%'
       OR lower(coalesce(customer.first_name, '')) LIKE '%' || lower(?) || '%'
       OR lower(coalesce(customer.last_name, '')) LIKE '%' || lower(?) || '%'
       OR lower(trim(coalesce(customer.first_name, '') || ' ' ||
                     coalesce(customer.last_name, '')))
          LIKE '%' || lower(?) || '%')
  AND (? = -1 OR customer.has_account = ?)
  AND (? = '' OR customer.created_at > ?)
  AND (? = '' OR customer.created_at >= ?)
  AND (? = '' OR customer.created_at < ?)
  AND (? = '' OR customer.created_at <= ?)
  AND (? = '' OR customer.updated_at > ?)
  AND (? = '' OR customer.updated_at >= ?)
  AND (? = '' OR customer.updated_at < ?)
  AND (? = '' OR customer.updated_at <= ?)
''',
      [query, query, query, query, query, query, query, hasAccount, hasAccount, createdAfter, createdAfter, createdFrom, createdFrom, createdBefore, createdBefore, createdTo, createdTo, updatedAfter, updatedAfter, updatedFrom, updatedFrom, updatedBefore, updatedBefore, updatedTo, updatedTo],
    );
  }
}
