// GENERATED CODE - DO NOT MODIFY BY HAND
// coverage:ignore-file
// ignore_for_file: type=lint
// ignore_for_file: unused_element, unused_import, deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: use_function_type_syntax_for_parameters
// ignore_for_file: unnecessary_const, avoid_init_to_null
// ignore_for_file: invalid_override_different_default_values_named
// ignore_for_file: prefer_expression_function_bodies
// ignore_for_file: annotate_overrides, invalid_annotation_target
// ignore_for_file: unnecessary_question_mark
// Generated by dust.

part of 'admin_product_option_state.dart';

const DeepCollectionEquality _adminProductOptionStateProductOptionsEquality = DeepCollectionEquality();

mixin _$AdminProductOptionState {
  @override
  String toString() {
    final self = this as AdminProductOptionState;
    return 'AdminProductOptionState('
        'count: ${self.count}, '
        'failure: ${self.failure}, '
        'limit: ${self.limit}, '
        'offset: ${self.offset}, '
        'productOptions: ${self.productOptions}, '
        'query: ${self.query}, '
        'status: ${self.status}'
        ')';
  }

  @override
  bool operator ==(Object other) {
    final self = this as AdminProductOptionState;
    return identical(this, other) ||
        other is AdminProductOptionState &&
            runtimeType == other.runtimeType &&
            other.count == self.count &&
            other.failure == self.failure &&
            other.limit == self.limit &&
            other.offset == self.offset &&
            _adminProductOptionStateProductOptionsEquality.equals(other.productOptions, self.productOptions) &&
            other.query == self.query &&
            other.status == self.status;
  }

  @override
  int get hashCode {
    final self = this as AdminProductOptionState;
    return Object.hashAll([
      runtimeType,
      self.count,
      self.failure,
      self.limit,
      self.offset,
      _adminProductOptionStateProductOptionsEquality.hash(self.productOptions),
      self.query,
      self.status,
    ]);
  }

  /// Creates a copy of this `AdminProductOptionState` with selected fields replaced.
  ///
  /// Usage:
  /// ```dart
  /// final updated = adminProductOptionState.copyWith(count: 1);
  /// ```
  @pragma('vm:prefer-inline')
  _$AdminProductOptionStateCopyWith<AdminProductOptionState> get copyWith => _$AdminProductOptionStateCopyWithImpl<AdminProductOptionState>(this as AdminProductOptionState, (value) => value);
}

// CopyWith API inspired by Freezed.

/// @nodoc
abstract class _$AdminProductOptionStateCopyWith<$Res> {
  $Res call({
    int? count,
    Option<String>? failure,
    int? limit,
    int? offset,
    List<AdminProductOptionSummary>? productOptions,
    String? query,
    AdminProductOptionStatus? status,
  });
}

/// @nodoc
final class _$AdminProductOptionStateCopyWithImpl<$Res> implements _$AdminProductOptionStateCopyWith<$Res> {
  const _$AdminProductOptionStateCopyWithImpl(this._self, this._then);

  final AdminProductOptionState _self;
  final $Res Function(AdminProductOptionState) _then;

  @override
  @pragma('vm:prefer-inline')
  $Res call({
    Object? count = null,
    Object? failure = null,
    Object? limit = null,
    Object? offset = null,
    Object? productOptions = null,
    Object? query = null,
    Object? status = null,
  }) {
    return _then(
      AdminProductOptionState(
        status: status == null ? _self.status : status as AdminProductOptionStatus,
        productOptions: productOptions == null ? _self.productOptions : productOptions as List<AdminProductOptionSummary>,
        count: count == null ? _self.count : count as int,
        limit: limit == null ? _self.limit : limit as int,
        offset: offset == null ? _self.offset : offset as int,
        query: query == null ? _self.query : query as String,
        failure: failure == null ? _self.failure : failure as Option<String>,
      )
    );
  }
}
