// GENERATED CODE - DO NOT MODIFY BY HAND
// coverage:ignore-file
// ignore_for_file: type=lint
// ignore_for_file: unused_element, unused_import, deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: use_function_type_syntax_for_parameters
// ignore_for_file: unnecessary_const, avoid_init_to_null
// ignore_for_file: invalid_override_different_default_values_named
// ignore_for_file: prefer_expression_function_bodies
// ignore_for_file: annotate_overrides, invalid_annotation_target
// ignore_for_file: unnecessary_question_mark
// Generated by dust.

part of 'checkout_view_model.dart';

/// Base class generated for CheckoutViewModel.
///
/// Extend it from your ViewModel and forward typed args:
///
/// ```dart
/// final class CheckoutViewModel extends $CheckoutViewModel {
///   CheckoutViewModel(super.args);
/// }
/// ```
abstract class $CheckoutViewModel extends ViewModelBase<CheckoutState, CheckoutViewModelArgs> {
  $CheckoutViewModel(super.args) : super(initialState: const CheckoutState());
}

/// Reads CheckoutViewModel state from `BuildContext`.
///
/// Read `value` when the widget should rebuild for any state change.
///
/// ```dart
/// final state = context.watchCheckoutViewModel().value;
/// ```
class _$CheckoutViewModelProxy {
  _$CheckoutViewModelProxy(this._context);

  final BuildContext _context;

  CheckoutState get value {
    return CheckoutViewModelScope.of(_context).value;
  }
}

/// Rebuilds when a selected CheckoutState value changes.
///
/// Use this for widgets that depend on one field or derived value.
class CheckoutViewModelSelector<R> extends StatefulWidget {
  const CheckoutViewModelSelector({
    super.key,
    required this.selector,
    required this.builder,
    this.child,
    this.equals,
  });

  final R Function(CheckoutState state) selector;
  final Widget Function(BuildContext context, R value, Widget? child) builder;
  final Widget? child;
  final bool Function(R previous, R next)? equals;

  @override
  State<CheckoutViewModelSelector<R>> createState() => _CheckoutViewModelSelectorState<R>();
}

class _CheckoutViewModelSelectorState<R> extends State<CheckoutViewModelSelector<R>> {
  CheckoutViewModel? _viewModel;
  R? _selected;
  bool _hasSelected = false;

  @override
  void didChangeDependencies() {
    super.didChangeDependencies();
    final nextViewModel = CheckoutViewModelScope._watchInstance(context);
    if (identical(_viewModel, nextViewModel)) return;
    _viewModel?.removeListener(_onViewModelStateChanged);
    _viewModel = nextViewModel;
    nextViewModel.addListener(_onViewModelStateChanged);
    _selectCurrent(force: true);
  }

  @override
  void didUpdateWidget(CheckoutViewModelSelector<R> oldWidget) {
    super.didUpdateWidget(oldWidget);
    _selectCurrent(force: true);
  }

  void _onViewModelStateChanged() {
    _selectCurrent();
  }

  void _selectCurrent({bool force = false}) {
    final viewModel = _viewModel;
    if (viewModel == null) return;
    final nextSelected = widget.selector(viewModel.value);
    if (!_hasSelected) {
      _selected = nextSelected;
      _hasSelected = true;
      return;
    }
    final previousSelected = _selected as R;
    final equals = widget.equals;
    final unchanged = equals == null
        ? previousSelected == nextSelected
        : equals(previousSelected, nextSelected);
    if (!force && unchanged) return;
    if (force || !mounted) {
      _selected = nextSelected;
    } else {
      setState(() {
        _selected = nextSelected;
      });
    }
  }

  @override
  void dispose() {
    _viewModel?.removeListener(_onViewModelStateChanged);
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    if (!_hasSelected) {
      _selectCurrent(force: true);
    }
    return widget.builder(context, _selected as R, widget.child);
  }
}

/// Creates and provides CheckoutViewModel to descendants.
///
/// The default constructor owns the ViewModel. Use `.value` for externally
/// owned ViewModels.
///
/// ```dart
/// CheckoutViewModelScope(
///   args: (context) => CheckoutViewModelArgs(...),
///   create: (context, args) => CheckoutViewModel(args),
///   child: const FeaturePage(),
/// )
/// ```
class CheckoutViewModelScope extends StatefulWidget {
  /// Creates and owns CheckoutViewModel from typed args.
  const CheckoutViewModelScope({
    super.key,
    required this.args,
    required this.create,
    required this.child,
    this.identity,
  }) : value = null;

  /// Provides an externally owned CheckoutViewModel without disposing it.
  const CheckoutViewModelScope.value({
    super.key,
    required CheckoutViewModel this.value,
    required this.child,
  }) : args = null,
       create = null,
       identity = null;

  final CheckoutViewModelArgs Function(BuildContext context)? args;
  final CheckoutViewModel Function(BuildContext context, CheckoutViewModelArgs args)? create;
  final Object? Function(BuildContext context)? identity;
  final CheckoutViewModel? value;
  final Widget child;

  /// Reads CheckoutViewModel without rebuilding when state changes.
  static CheckoutViewModel read(BuildContext context) {
    final scope = context
        .getElementForInheritedWidgetOfExactType<_CheckoutViewModelInstance>()
        ?.widget as _CheckoutViewModelInstance?;
    if (scope == null) throw StateError('No CheckoutViewModelScope found in context.');
    return scope.viewModel;
  }

  static CheckoutViewModel _watchInstance(BuildContext context) {
    final scope = context.dependOnInheritedWidgetOfExactType<_CheckoutViewModelInstance>();
    if (scope == null) throw StateError('No CheckoutViewModelScope found in context.');
    return scope.viewModel;
  }

  /// Watches CheckoutViewModel and rebuilds when state changes.
  static CheckoutViewModel of(BuildContext context) {
    final scope = context.dependOnInheritedWidgetOfExactType<_CheckoutViewModelInherited>();
    if (scope == null) throw StateError('No CheckoutViewModelScope found in context.');
    return scope.viewModel;
  }

  @override
  State<CheckoutViewModelScope> createState() => _CheckoutViewModelScopeState();
}

class _CheckoutViewModelScopeState extends State<CheckoutViewModelScope> {
  CheckoutViewModel? _viewModel;
  Object? _identity;
  bool _ownsViewModel = false;

  @override
  void didChangeDependencies() {
    super.didChangeDependencies();
    final external = widget.value;
    if (external != null) {
      _replaceViewModel(external, ownsViewModel: false, notify: false);
      return;
    }
    final nextIdentity = widget.identity?.call(context);
    if (_viewModel == null || nextIdentity != _identity) {
      _identity = nextIdentity;
      _replaceViewModel(_createOwnedViewModel(), ownsViewModel: true, notify: false);
    }
  }

  @override
  void didUpdateWidget(CheckoutViewModelScope oldWidget) {
    super.didUpdateWidget(oldWidget);
    final external = widget.value;
    if (external != null) {
      _replaceViewModel(external, ownsViewModel: false);
    } else if (oldWidget.value != null) {
      _identity = widget.identity?.call(context);
      _replaceViewModel(_createOwnedViewModel(), ownsViewModel: true);
    } else {
      final nextIdentity = widget.identity?.call(context);
      if (nextIdentity != _identity) {
        _identity = nextIdentity;
        _replaceViewModel(_createOwnedViewModel(), ownsViewModel: true);
      }
    }
  }

  CheckoutViewModel _createOwnedViewModel() {
    final argsFactory = widget.args;
    final create = widget.create;
    if (argsFactory == null || create == null) {
      throw StateError('Owned CheckoutViewModelScope requires args and create.');
    }
    late final CheckoutViewModel created;
    try {
      created = create(context, argsFactory(context));
    } catch (error, stackTrace) {
      Error.throwWithStackTrace(error, stackTrace);
    }
    return created;
  }

  void _replaceViewModel(
    CheckoutViewModel nextViewModel, {
    required bool ownsViewModel,
    bool notify = true,
  }) {
    final previous = _viewModel;
    if (identical(previous, nextViewModel)) {
      _ownsViewModel = ownsViewModel;
      _scheduleInit(nextViewModel);
      if (notify && mounted) setState(() {});
      return;
    }
    previous?.removeListener(_onViewModelStateChanged);
    if (_ownsViewModel) previous?.dispose();
    _viewModel = nextViewModel;
    _ownsViewModel = ownsViewModel;
    nextViewModel.addListener(_onViewModelStateChanged);
    _scheduleInit(nextViewModel);
    if (notify && mounted) setState(() {});
  }

  void _scheduleInit(CheckoutViewModel viewModel) {
    scheduleMicrotask(() async {
      if (!mounted || !identical(_viewModel, viewModel)) return;
      try {
        await viewModel.init();
      } catch (error, stackTrace) {
        FlutterError.reportError(
          FlutterErrorDetails(
            exception: error,
            stack: stackTrace,
            library: 'dust state',
            context: ErrorDescription('CheckoutViewModelScope init failed'),
          ),
        );
      }
    });
  }

  void _onViewModelStateChanged() {
    if (mounted) setState(() {});
  }

  @override
  void dispose() {
    final viewModel = _viewModel;
    viewModel?.removeListener(_onViewModelStateChanged);
    if (_ownsViewModel) viewModel?.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    final viewModel = _viewModel;
    if (viewModel == null) {
      throw StateError('CheckoutViewModelScope built before its view model was initialized.');
    }
    return _CheckoutViewModelInstance(
      viewModel: viewModel,
      child: _CheckoutViewModelInherited(
        viewModel: viewModel,
        state: viewModel.value,
        child: widget.child,
      ),
    );
  }
}

class _CheckoutViewModelInstance extends InheritedWidget {
  const _CheckoutViewModelInstance({required this.viewModel, required super.child});

  final CheckoutViewModel viewModel;

  @override
  bool updateShouldNotify(_CheckoutViewModelInstance oldWidget) {
    return !identical(viewModel, oldWidget.viewModel);
  }
}

class _CheckoutViewModelInherited extends InheritedWidget {
  const _CheckoutViewModelInherited({required this.viewModel, required this.state, required super.child});

  final CheckoutViewModel viewModel;
  final CheckoutState state;

  @override
  bool updateShouldNotify(_CheckoutViewModelInherited oldWidget) {
    return !identical(viewModel, oldWidget.viewModel) || state != oldWidget.state;
  }
}

/// Handles one-shot effects from CheckoutViewModel.
///
/// Effects are delivered without changing state and do not rebuild `child`.
///
/// ```dart
/// CheckoutViewModelListener(
///   listener: onEffect,
///   child: const FeaturePage(),
/// )
/// ```
class CheckoutViewModelListener extends StatefulWidget {
  const CheckoutViewModelListener({super.key, required this.listener, required this.child});

  final void Function(BuildContext context, Object effect) listener;
  final Widget child;

  @override
  State<CheckoutViewModelListener> createState() => _CheckoutViewModelListenerState();
}

class _CheckoutViewModelListenerState extends State<CheckoutViewModelListener> {
  StreamSubscription<Object>? _sub;
  CheckoutViewModel? _viewModel;

  @override
  void didChangeDependencies() {
    super.didChangeDependencies();
    final nextViewModel = CheckoutViewModelScope._watchInstance(context);
    if (_viewModel == nextViewModel) return;
    _sub?.cancel();
    _viewModel = nextViewModel;
    _sub = nextViewModel.effects.listen(_onEffect);
  }

  void _onEffect(Object effect) {
    if (mounted) widget.listener(context, effect);
  }

  @override
  void dispose() {
    _sub?.cancel();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) => widget.child;
}

/// BuildContext helpers generated for CheckoutViewModel.
///
/// ```dart
/// final vm = context.readCheckoutViewModel();
/// final state = context.watchCheckoutViewModel().value;
/// ```
extension CheckoutViewModelBuildContext on BuildContext {
  _$CheckoutViewModelProxy watchCheckoutViewModel() {
    return _$CheckoutViewModelProxy(this);
  }

  CheckoutViewModel readCheckoutViewModel() => CheckoutViewModelScope.read(this);
}
