// GENERATED CODE - DO NOT MODIFY BY HAND
// coverage:ignore-file
// ignore_for_file: type=lint
// ignore_for_file: unused_element, unused_import, deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: use_function_type_syntax_for_parameters
// ignore_for_file: unnecessary_const, avoid_init_to_null
// ignore_for_file: invalid_override_different_default_values_named
// ignore_for_file: prefer_expression_function_bodies
// ignore_for_file: annotate_overrides, invalid_annotation_target
// ignore_for_file: unnecessary_question_mark
// Generated by dust.

part of 'model.dart';

mixin _$SellingRegionResponse implements Serializable {
  Map<String, Object?> serialize() =>
      _$SellingRegionResponseSerialize(this as SellingRegionResponse);

  Map<String, Object?> toJson() => serialize();
}

mixin _$SellingRegionListResponse implements Serializable {
  Map<String, Object?> serialize() =>
      _$SellingRegionListResponseSerialize(this as SellingRegionListResponse);

  Map<String, Object?> toJson() => serialize();
}

final class $SellingRegionResponseSerializer implements Serializer<SellingRegionResponse, Map<String, Object?>> {
  const $SellingRegionResponseSerializer();

  @override
  Map<String, Object?> serialize(SellingRegionResponse value) => _$SellingRegionResponseSerialize(value);
}
final class $SellingRegionListResponseSerializer implements Serializer<SellingRegionListResponse, Map<String, Object?>> {
  const $SellingRegionListResponseSerializer();

  @override
  Map<String, Object?> serialize(SellingRegionListResponse value) => _$SellingRegionListResponseSerialize(value);
}
SellingRegionResponse _$SellingRegionResponseFromRow(Row row) {
  return SellingRegionResponse(
    id: row.read<String>('id'),
    name: row.read<String>('name'),
    currencyCode: row.read<String>('currency_code'),
    taxRate: row.read<int>('tax_rate'),
    countries: RegionCountriesFromCsv().decode(row.read<String>('countries')),
    taxInclusive: RegionBoolFromInt().decode(row.read<int>('tax_inclusive')),
  );
}

/// Row deserializer for [SellingRegionResponse].
final class $SellingRegionResponseRowDeserializer implements RowDeserializer<SellingRegionResponse> {
  const $SellingRegionResponseRowDeserializer();

  @override
  SellingRegionResponse deserialize(Row row) => _$SellingRegionResponseFromRow(row);
}

/// Typed row query terminals for [SellingRegionResponse].
///
/// Resolved from the static type of the receiver, so a row type with no
/// `FromRow` has no terminals and the call does not compile.
extension $SellingRegionResponseQuery on QueryAs<SellingRegionResponse> {
  /// Fetches exactly one row.
  Future<SellingRegionResponse> fetchOne(DatabaseExecutor db) =>
      fetchOneWith(db, _$SellingRegionResponseFromRow);

  /// Fetches zero or one row.
  Future<SellingRegionResponse?> fetchOptional(DatabaseExecutor db) =>
      fetchOptionalWith(db, _$SellingRegionResponseFromRow);

  /// Fetches every row.
  Future<List<SellingRegionResponse>> fetchAll(DatabaseExecutor db) =>
      fetchAllWith(db, _$SellingRegionResponseFromRow);
}

Map<String, Object?> _$SellingRegionResponseSerialize(SellingRegionResponse instance) {
  return <String, Object?>{
    'countries': instance.countries
        .map((item) => item)
        .toList(),
    'currency_code': instance.currencyCode,
    'id': instance.id,
    'name': instance.name,
    'tax_inclusive': instance.taxInclusive,
    'tax_rate': instance.taxRate,
  };
}

Map<String, Object?> _$SellingRegionResponseToJson(SellingRegionResponse instance) =>
    _$SellingRegionResponseSerialize(instance);

Map<String, Object?> _$SellingRegionListResponseSerialize(SellingRegionListResponse instance) {
  return <String, Object?>{
    'count': instance.count,
    'regions': instance.regions
        .map((item) => _$SellingRegionResponseSerialize(item))
        .toList(),
  };
}

Map<String, Object?> _$SellingRegionListResponseToJson(SellingRegionListResponse instance) =>
    _$SellingRegionListResponseSerialize(instance);
