// GENERATED CODE - DO NOT MODIFY BY HAND
// coverage:ignore-file
// ignore_for_file: type=lint
// ignore_for_file: unused_element, unused_import, deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: use_function_type_syntax_for_parameters
// ignore_for_file: unnecessary_const, avoid_init_to_null
// ignore_for_file: invalid_override_different_default_values_named
// ignore_for_file: prefer_expression_function_bodies
// ignore_for_file: annotate_overrides, invalid_annotation_target
// ignore_for_file: unnecessary_question_mark
// Generated by dust.

part of 'repository.dart';

final class _$SellingRegionRepository implements SellingRegionRepository {
  const _$SellingRegionRepository(this._db);

  final DatabaseExecutor _db;

  @override
  Future<Result<List<SellingRegionResponse>, SqlxError>> list() {
    return _db.fetchAll<SellingRegionResponse>(
      r'''
SELECT id, name, currency_code, tax_rate, tax_inclusive, countries
FROM regions
WHERE deleted_at IS NULL
ORDER BY name, id
''',
      [],
      const $SellingRegionResponseRowDeserializer().deserialize,
    );
  }
}
