-- Stages validated merchant CSV imports before a separate confirmation mutates products.
-- UTC timestamps use ISO-8601 TEXT because SQLite has no native TIMESTAMPTZ.
CREATE TABLE product_imports (
  -- Opaque transaction identifier returned to the Admin import workflow.
  id            TEXT PRIMARY KEY,
  -- Proven merchant who owns and may later confirm this staged import.
  admin_user_id TEXT NOT NULL REFERENCES admin_users (id) ON DELETE RESTRICT,
  -- Original safe display name helps the merchant recognize the staged file.
  filename      TEXT NOT NULL CHECK (length(filename) BETWEEN 1 AND 255),
  -- Validated normalized rows are retained so confirmation never reparses a new file.
  payload_json  TEXT NOT NULL CHECK (json_valid(payload_json)),
  -- Unique products that confirmation would create.
  to_create     INTEGER NOT NULL CHECK (to_create >= 0),
  -- Unique active products that confirmation would update.
  to_update     INTEGER NOT NULL CHECK (to_update >= 0),
  -- Only pending imports can be consumed by the later confirmation operation.
  status        TEXT NOT NULL DEFAULT 'pending'
                CHECK (status IN ('pending', 'completed', 'expired')),
  -- Short lifetime limits how long uploaded catalogue data remains actionable.
  expires_at    TEXT NOT NULL,
  -- Audit creation instant generated by SQLite in UTC.
  created_at    TEXT NOT NULL DEFAULT
                (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  -- Audit mutation instant maintained by the trigger below.
  updated_at    TEXT NOT NULL DEFAULT
                (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  -- Soft deletion preserves an audit trail without exposing stale imports.
  deleted_at    TEXT
);

CREATE INDEX idx_product_imports_owner_pending
ON product_imports (admin_user_id, expires_at)
WHERE status = 'pending' AND deleted_at IS NULL;

-- SQLite has no automatic ON UPDATE timestamp, so this maintains updated_at.
CREATE TRIGGER product_imports_touch_updated_at AFTER UPDATE ON product_imports
WHEN NEW.updated_at = OLD.updated_at BEGIN
  UPDATE product_imports
  SET updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
  WHERE id = NEW.id;
END;
