-- Stores people allowed to operate the merchant-only admin API.
-- Authentication credentials remain in provider_identity, not this profile.
-- UTC timestamps use ISO-8601 TEXT because SQLite has no native TIMESTAMPTZ.
CREATE TABLE admin_users (
  -- Opaque public identifier; authorization resolves it through auth_identity.
  id         TEXT PRIMARY KEY,
  -- Normalized sign-in address and operational contact identifier.
  email      TEXT NOT NULL COLLATE NOCASE
             CHECK (length(email) BETWEEN 3 AND 254),
  -- Optional display names must never be used as authorization facts.
  first_name TEXT CHECK (first_name IS NULL OR length(first_name) BETWEEN 1 AND 100),
  -- Optional family name is display data, never an authorization fact.
  last_name  TEXT CHECK (last_name IS NULL OR length(last_name) BETWEEN 1 AND 100),
  -- Disabled users retain audit relationships but cannot authenticate.
  status     TEXT NOT NULL DEFAULT 'active'
             CHECK (status IN ('active', 'disabled')),
  -- Audit creation instant generated by SQLite in UTC.
  created_at TEXT NOT NULL DEFAULT
             (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  -- Audit mutation instant maintained by the trigger below.
  updated_at TEXT NOT NULL DEFAULT
             (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  -- Soft deletion preserves the actor named by future audit records.
  deleted_at TEXT
);

CREATE UNIQUE INDEX idx_admin_users_email_active
ON admin_users (email COLLATE NOCASE)
WHERE deleted_at IS NULL;

-- SQLite has no automatic ON UPDATE timestamp, so this maintains updated_at.
CREATE TRIGGER admin_users_touch_updated_at AFTER UPDATE ON admin_users
WHEN NEW.updated_at = OLD.updated_at BEGIN
  UPDATE admin_users
  SET updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
  WHERE id = NEW.id;
END;
