// GENERATED CODE - DO NOT MODIFY BY HAND
// coverage:ignore-file
// ignore_for_file: type=lint
// ignore_for_file: unused_element, unused_import, deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: use_function_type_syntax_for_parameters
// ignore_for_file: unnecessary_const, avoid_init_to_null
// ignore_for_file: invalid_override_different_default_values_named
// ignore_for_file: prefer_expression_function_bodies
// ignore_for_file: annotate_overrides, invalid_annotation_target
// ignore_for_file: unnecessary_question_mark
// Generated by dust.

part of 'list_response.dart';

mixin _$AdminCustomerGroupCustomerResponse implements Serializable {
  Map<String, Object?> serialize() =>
      _$AdminCustomerGroupCustomerResponseSerialize(this as AdminCustomerGroupCustomerResponse);

  Map<String, Object?> toJson() => serialize();
}

mixin _$AdminCustomerGroupResponse implements Serializable {
  Map<String, Object?> serialize() =>
      _$AdminCustomerGroupResponseSerialize(this as AdminCustomerGroupResponse);

  Map<String, Object?> toJson() => serialize();
}

mixin _$AdminCustomerGroupListResponse implements Serializable {
  Map<String, Object?> serialize() =>
      _$AdminCustomerGroupListResponseSerialize(this as AdminCustomerGroupListResponse);

  Map<String, Object?> toJson() => serialize();
}

final class $AdminCustomerGroupCustomerResponseSerializer implements Serializer<AdminCustomerGroupCustomerResponse, Map<String, Object?>> {
  const $AdminCustomerGroupCustomerResponseSerializer();

  @override
  Map<String, Object?> serialize(AdminCustomerGroupCustomerResponse value) => _$AdminCustomerGroupCustomerResponseSerialize(value);
}
final class $AdminCustomerGroupCustomerResponseDeserializer implements Deserializer<AdminCustomerGroupCustomerResponse, Map<String, Object?>> {
  const $AdminCustomerGroupCustomerResponseDeserializer();

  @override
  AdminCustomerGroupCustomerResponse deserialize(Map<String, Object?> json) => _$AdminCustomerGroupCustomerResponseDeserialize(json);
}
final class $AdminCustomerGroupResponseSerializer implements Serializer<AdminCustomerGroupResponse, Map<String, Object?>> {
  const $AdminCustomerGroupResponseSerializer();

  @override
  Map<String, Object?> serialize(AdminCustomerGroupResponse value) => _$AdminCustomerGroupResponseSerialize(value);
}
final class $AdminCustomerGroupListResponseSerializer implements Serializer<AdminCustomerGroupListResponse, Map<String, Object?>> {
  const $AdminCustomerGroupListResponseSerializer();

  @override
  Map<String, Object?> serialize(AdminCustomerGroupListResponse value) => _$AdminCustomerGroupListResponseSerialize(value);
}
AdminCustomerGroupResponse _$AdminCustomerGroupResponseFromRow(Row row) {
  return AdminCustomerGroupResponse(
    id: row.read<String>('id'),
    name: row.read<String>('name'),
    customers: _AdminCustomerGroupCustomers().decode(row.read<String>('customers_json')),
    createdAt: _AdminCustomerGroupDateTime().decode(row.read<String>('created_at')),
    updatedAt: _AdminCustomerGroupDateTime().decode(row.read<String>('updated_at')),
  );
}

/// Row deserializer for [AdminCustomerGroupResponse].
final class $AdminCustomerGroupResponseRowDeserializer implements RowDeserializer<AdminCustomerGroupResponse> {
  const $AdminCustomerGroupResponseRowDeserializer();

  @override
  AdminCustomerGroupResponse deserialize(Row row) => _$AdminCustomerGroupResponseFromRow(row);
}

/// Typed row query terminals for [AdminCustomerGroupResponse].
///
/// Resolved from the static type of the receiver, so a row type with no
/// `FromRow` has no terminals and the call does not compile.
extension $AdminCustomerGroupResponseQuery on QueryAs<AdminCustomerGroupResponse> {
  /// Fetches exactly one row.
  Future<AdminCustomerGroupResponse> fetchOne(DatabaseExecutor db) =>
      fetchOneWith(db, _$AdminCustomerGroupResponseFromRow);

  /// Fetches zero or one row.
  Future<AdminCustomerGroupResponse?> fetchOptional(DatabaseExecutor db) =>
      fetchOptionalWith(db, _$AdminCustomerGroupResponseFromRow);

  /// Fetches every row.
  Future<List<AdminCustomerGroupResponse>> fetchAll(DatabaseExecutor db) =>
      fetchAllWith(db, _$AdminCustomerGroupResponseFromRow);
}

Map<String, Object?> _$AdminCustomerGroupCustomerResponseSerialize(AdminCustomerGroupCustomerResponse instance) {
  return <String, Object?>{
    'id': instance.id,
  };
}

Map<String, Object?> _$AdminCustomerGroupCustomerResponseToJson(AdminCustomerGroupCustomerResponse instance) =>
    _$AdminCustomerGroupCustomerResponseSerialize(instance);

// factory AdminCustomerGroupCustomerResponse.fromJson(Map<String, Object?> json) => _$AdminCustomerGroupCustomerResponseFromJson(json);
AdminCustomerGroupCustomerResponse _$AdminCustomerGroupCustomerResponseDeserialize(Map<String, Object?> json) {
  final idValue = JsonHelper.as<String>(json['id'], 'id', 'String');

  return AdminCustomerGroupCustomerResponse(id: idValue);
}

AdminCustomerGroupCustomerResponse _$AdminCustomerGroupCustomerResponseFromJson(Map<String, Object?> json) =>
    _$AdminCustomerGroupCustomerResponseDeserialize(json);

Map<String, Object?> _$AdminCustomerGroupResponseSerialize(AdminCustomerGroupResponse instance) {
  return <String, Object?>{
    'created_at': instance.createdAt.toIso8601String(),
    'customers': instance.customers
        .map((item) => _$AdminCustomerGroupCustomerResponseSerialize(item))
        .toList(),
    'id': instance.id,
    'name': instance.name,
    'updated_at': instance.updatedAt.toIso8601String(),
  };
}

Map<String, Object?> _$AdminCustomerGroupResponseToJson(AdminCustomerGroupResponse instance) =>
    _$AdminCustomerGroupResponseSerialize(instance);

Map<String, Object?> _$AdminCustomerGroupListResponseSerialize(AdminCustomerGroupListResponse instance) {
  return <String, Object?>{
    'count': instance.count,
    'customer_groups': instance.customerGroups
        .map((item) => _$AdminCustomerGroupResponseSerialize(item))
        .toList(),
    'limit': instance.limit,
    'offset': instance.offset,
  };
}

Map<String, Object?> _$AdminCustomerGroupListResponseToJson(AdminCustomerGroupListResponse instance) =>
    _$AdminCustomerGroupListResponseSerialize(instance);
