// GENERATED CODE - DO NOT MODIFY BY HAND
// coverage:ignore-file
// ignore_for_file: type=lint
// ignore_for_file: unused_element, unused_import, deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: use_function_type_syntax_for_parameters
// ignore_for_file: unnecessary_const, avoid_init_to_null
// ignore_for_file: invalid_override_different_default_values_named
// ignore_for_file: prefer_expression_function_bodies
// ignore_for_file: annotate_overrides, invalid_annotation_target
// ignore_for_file: unnecessary_question_mark
// Generated by dust.

part of 'order_item_response.dart';

mixin _$OrderLineItemDetailResponse implements Serializable {
  Map<String, Object?> serialize() =>
      _$OrderLineItemDetailResponseSerialize(this as OrderLineItemDetailResponse);

  Map<String, Object?> toJson() => serialize();
}

mixin _$OrderLineItemResponse implements Serializable {
  Map<String, Object?> serialize() =>
      _$OrderLineItemResponseSerialize(this as OrderLineItemResponse);

  Map<String, Object?> toJson() => serialize();
}

final class $OrderLineItemDetailResponseSerializer implements Serializer<OrderLineItemDetailResponse, Map<String, Object?>> {
  const $OrderLineItemDetailResponseSerializer();

  @override
  Map<String, Object?> serialize(OrderLineItemDetailResponse value) => _$OrderLineItemDetailResponseSerialize(value);
}
final class $OrderLineItemDetailResponseDeserializer implements Deserializer<OrderLineItemDetailResponse, Map<String, Object?>> {
  const $OrderLineItemDetailResponseDeserializer();

  @override
  OrderLineItemDetailResponse deserialize(Map<String, Object?> json) => _$OrderLineItemDetailResponseDeserialize(json);
}
final class $OrderLineItemResponseSerializer implements Serializer<OrderLineItemResponse, Map<String, Object?>> {
  const $OrderLineItemResponseSerializer();

  @override
  Map<String, Object?> serialize(OrderLineItemResponse value) => _$OrderLineItemResponseSerialize(value);
}
final class $OrderLineItemResponseDeserializer implements Deserializer<OrderLineItemResponse, Map<String, Object?>> {
  const $OrderLineItemResponseDeserializer();

  @override
  OrderLineItemResponse deserialize(Map<String, Object?> json) => _$OrderLineItemResponseDeserialize(json);
}

Map<String, Object?> _$OrderLineItemDetailResponseSerialize(OrderLineItemDetailResponse instance) {
  return <String, Object?>{
    'delivered_quantity': instance.deliveredQuantity,
    'return_dismissed_quantity': instance.returnDismissedQuantity,
    'return_received_quantity': instance.returnReceivedQuantity,
    'return_requested_quantity': instance.returnRequestedQuantity,
  };
}

Map<String, Object?> _$OrderLineItemDetailResponseToJson(OrderLineItemDetailResponse instance) =>
    _$OrderLineItemDetailResponseSerialize(instance);

// factory OrderLineItemDetailResponse.fromJson(Map<String, Object?> json) => _$OrderLineItemDetailResponseFromJson(json);
OrderLineItemDetailResponse _$OrderLineItemDetailResponseDeserialize(Map<String, Object?> json) {
  final deliveredQuantityValue = JsonHelper.as<int>(
    json['delivered_quantity'],
    'delivered_quantity',
    'int',
  );
  final returnDismissedQuantityValue = JsonHelper.as<int>(
    json['return_dismissed_quantity'],
    'return_dismissed_quantity',
    'int',
  );
  final returnReceivedQuantityValue = JsonHelper.as<int>(
    json['return_received_quantity'],
    'return_received_quantity',
    'int',
  );
  final returnRequestedQuantityValue = JsonHelper.as<int>(
    json['return_requested_quantity'],
    'return_requested_quantity',
    'int',
  );

  return OrderLineItemDetailResponse(
    deliveredQuantity: deliveredQuantityValue,
    returnRequestedQuantity: returnRequestedQuantityValue,
    returnReceivedQuantity: returnReceivedQuantityValue,
    returnDismissedQuantity: returnDismissedQuantityValue,
  );
}

OrderLineItemDetailResponse _$OrderLineItemDetailResponseFromJson(Map<String, Object?> json) =>
    _$OrderLineItemDetailResponseDeserialize(json);

Map<String, Object?> _$OrderLineItemResponseSerialize(OrderLineItemResponse instance) {
  return <String, Object?>{
    'detail': _$OrderLineItemDetailResponseSerialize(instance.detail),
    'id': instance.id,
    'product_id': instance.productId,
    'product_handle': instance.productHandle,
    'quantity': instance.quantity,
    'title': instance.title,
    'thumbnail': instance.thumbnail,
    'unit_price': instance.unitPrice.toJson(),
    'variant_id': instance.variantId,
    'variant_title': instance.variantTitle,
  };
}

Map<String, Object?> _$OrderLineItemResponseToJson(OrderLineItemResponse instance) =>
    _$OrderLineItemResponseSerialize(instance);

// factory OrderLineItemResponse.fromJson(Map<String, Object?> json) => _$OrderLineItemResponseFromJson(json);
OrderLineItemResponse _$OrderLineItemResponseDeserialize(Map<String, Object?> json) {
  final detailValue = _$OrderLineItemDetailResponseDeserialize(
    JsonHelper.asMap(json['detail'], 'detail'),
  );
  final idValue = JsonHelper.as<String>(json['id'], 'id', 'String');
  final productIdValue = JsonHelper.as<String>(
    json['product_id'],
    'product_id',
    'String',
  );
  final productHandleValue = JsonHelper.as<String>(
    json['product_handle'],
    'product_handle',
    'String',
  );
  final quantityValue = JsonHelper.as<int>(json['quantity'], 'quantity', 'int');
  final titleValue = JsonHelper.as<String>(json['title'], 'title', 'String');
  final thumbnailValue = json['thumbnail'] == null
      ? null
      : JsonHelper.as<String>(json['thumbnail'], 'thumbnail', 'String');
  final unitPriceValue = Money.fromJson(
    JsonHelper.asMap(json['unit_price'], 'unit_price'),
  );
  final variantIdValue = JsonHelper.as<String>(
    json['variant_id'],
    'variant_id',
    'String',
  );
  final variantTitleValue = json['variant_title'] == null
      ? null
      : JsonHelper.as<String>(json['variant_title'], 'variant_title', 'String');

  return OrderLineItemResponse(
    id: idValue,
    variantId: variantIdValue,
    productId: productIdValue,
    productHandle: productHandleValue,
    title: titleValue,
    unitPrice: unitPriceValue,
    quantity: quantityValue,
    detail: detailValue,
    variantTitle: variantTitleValue,
    thumbnail: thumbnailValue,
  );
}

OrderLineItemResponse _$OrderLineItemResponseFromJson(Map<String, Object?> json) =>
    _$OrderLineItemResponseDeserialize(json);
