// GENERATED CODE - DO NOT MODIFY BY HAND
// coverage:ignore-file
// ignore_for_file: type=lint
// ignore_for_file: unused_element, unused_import, deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: use_function_type_syntax_for_parameters
// ignore_for_file: unnecessary_const, avoid_init_to_null
// ignore_for_file: invalid_override_different_default_values_named
// ignore_for_file: prefer_expression_function_bodies
// ignore_for_file: annotate_overrides, invalid_annotation_target
// ignore_for_file: unnecessary_question_mark
// Generated by dust.

part of 'account_view_model.dart';

/// Base class generated for AccountViewModel.
///
/// Extend it from your ViewModel and forward typed args:
///
/// ```dart
/// final class AccountViewModel extends $AccountViewModel {
///   AccountViewModel(super.args);
/// }
/// ```
abstract class $AccountViewModel extends ViewModelBase<AccountState, AccountViewModelArgs> {
  $AccountViewModel(super.args) : super(initialState: const AccountState());
}

/// Reads AccountViewModel state from `BuildContext`.
///
/// Read `value` when the widget should rebuild for any state change.
///
/// ```dart
/// final state = context.watchAccountViewModel().value;
/// ```
class _$AccountViewModelProxy {
  _$AccountViewModelProxy(this._context);

  final BuildContext _context;

  AccountState get value {
    return AccountViewModelScope.of(_context).value;
  }
}

/// Rebuilds when a selected AccountState value changes.
///
/// Use this for widgets that depend on one field or derived value.
class AccountViewModelSelector<R> extends StatefulWidget {
  const AccountViewModelSelector({
    super.key,
    required this.selector,
    required this.builder,
    this.child,
    this.equals,
  });

  final R Function(AccountState state) selector;
  final Widget Function(BuildContext context, R value, Widget? child) builder;
  final Widget? child;
  final bool Function(R previous, R next)? equals;

  @override
  State<AccountViewModelSelector<R>> createState() => _AccountViewModelSelectorState<R>();
}

class _AccountViewModelSelectorState<R> extends State<AccountViewModelSelector<R>> {
  AccountViewModel? _viewModel;
  R? _selected;
  bool _hasSelected = false;

  @override
  void didChangeDependencies() {
    super.didChangeDependencies();
    final nextViewModel = AccountViewModelScope._watchInstance(context);
    if (identical(_viewModel, nextViewModel)) return;
    _viewModel?.removeListener(_onViewModelStateChanged);
    _viewModel = nextViewModel;
    nextViewModel.addListener(_onViewModelStateChanged);
    _selectCurrent(force: true);
  }

  @override
  void didUpdateWidget(AccountViewModelSelector<R> oldWidget) {
    super.didUpdateWidget(oldWidget);
    _selectCurrent(force: true);
  }

  void _onViewModelStateChanged() {
    _selectCurrent();
  }

  void _selectCurrent({bool force = false}) {
    final viewModel = _viewModel;
    if (viewModel == null) return;
    final nextSelected = widget.selector(viewModel.value);
    if (!_hasSelected) {
      _selected = nextSelected;
      _hasSelected = true;
      return;
    }
    final previousSelected = _selected as R;
    final equals = widget.equals;
    final unchanged = equals == null
        ? previousSelected == nextSelected
        : equals(previousSelected, nextSelected);
    if (!force && unchanged) return;
    if (force || !mounted) {
      _selected = nextSelected;
    } else {
      setState(() {
        _selected = nextSelected;
      });
    }
  }

  @override
  void dispose() {
    _viewModel?.removeListener(_onViewModelStateChanged);
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    if (!_hasSelected) {
      _selectCurrent(force: true);
    }
    return widget.builder(context, _selected as R, widget.child);
  }
}

/// Creates and provides AccountViewModel to descendants.
///
/// The default constructor owns the ViewModel. Use `.value` for externally
/// owned ViewModels.
///
/// ```dart
/// AccountViewModelScope(
///   args: (context) => AccountViewModelArgs(...),
///   create: (context, args) => AccountViewModel(args),
///   child: const FeaturePage(),
/// )
/// ```
class AccountViewModelScope extends StatefulWidget {
  /// Creates and owns AccountViewModel from typed args.
  const AccountViewModelScope({
    super.key,
    required this.args,
    required this.create,
    required this.child,
    this.identity,
  }) : value = null;

  /// Provides an externally owned AccountViewModel without disposing it.
  const AccountViewModelScope.value({
    super.key,
    required AccountViewModel this.value,
    required this.child,
  }) : args = null,
       create = null,
       identity = null;

  final AccountViewModelArgs Function(BuildContext context)? args;
  final AccountViewModel Function(BuildContext context, AccountViewModelArgs args)? create;
  final Object? Function(BuildContext context)? identity;
  final AccountViewModel? value;
  final Widget child;

  /// Reads AccountViewModel without rebuilding when state changes.
  static AccountViewModel read(BuildContext context) {
    final scope = context
        .getElementForInheritedWidgetOfExactType<_AccountViewModelInstance>()
        ?.widget as _AccountViewModelInstance?;
    if (scope == null) throw StateError('No AccountViewModelScope found in context.');
    return scope.viewModel;
  }

  static AccountViewModel _watchInstance(BuildContext context) {
    final scope = context.dependOnInheritedWidgetOfExactType<_AccountViewModelInstance>();
    if (scope == null) throw StateError('No AccountViewModelScope found in context.');
    return scope.viewModel;
  }

  /// Watches AccountViewModel and rebuilds when state changes.
  static AccountViewModel of(BuildContext context) {
    final scope = context.dependOnInheritedWidgetOfExactType<_AccountViewModelInherited>();
    if (scope == null) throw StateError('No AccountViewModelScope found in context.');
    return scope.viewModel;
  }

  @override
  State<AccountViewModelScope> createState() => _AccountViewModelScopeState();
}

class _AccountViewModelScopeState extends State<AccountViewModelScope> {
  AccountViewModel? _viewModel;
  Object? _identity;
  bool _ownsViewModel = false;

  @override
  void didChangeDependencies() {
    super.didChangeDependencies();
    final external = widget.value;
    if (external != null) {
      _replaceViewModel(external, ownsViewModel: false, notify: false);
      return;
    }
    final nextIdentity = widget.identity?.call(context);
    if (_viewModel == null || nextIdentity != _identity) {
      _identity = nextIdentity;
      _replaceViewModel(_createOwnedViewModel(), ownsViewModel: true, notify: false);
    }
  }

  @override
  void didUpdateWidget(AccountViewModelScope oldWidget) {
    super.didUpdateWidget(oldWidget);
    final external = widget.value;
    if (external != null) {
      _replaceViewModel(external, ownsViewModel: false);
    } else if (oldWidget.value != null) {
      _identity = widget.identity?.call(context);
      _replaceViewModel(_createOwnedViewModel(), ownsViewModel: true);
    } else {
      final nextIdentity = widget.identity?.call(context);
      if (nextIdentity != _identity) {
        _identity = nextIdentity;
        _replaceViewModel(_createOwnedViewModel(), ownsViewModel: true);
      }
    }
  }

  AccountViewModel _createOwnedViewModel() {
    final argsFactory = widget.args;
    final create = widget.create;
    if (argsFactory == null || create == null) {
      throw StateError('Owned AccountViewModelScope requires args and create.');
    }
    late final AccountViewModel created;
    try {
      created = create(context, argsFactory(context));
    } catch (error, stackTrace) {
      Error.throwWithStackTrace(error, stackTrace);
    }
    return created;
  }

  void _replaceViewModel(
    AccountViewModel nextViewModel, {
    required bool ownsViewModel,
    bool notify = true,
  }) {
    final previous = _viewModel;
    if (identical(previous, nextViewModel)) {
      _ownsViewModel = ownsViewModel;
      _scheduleInit(nextViewModel);
      if (notify && mounted) setState(() {});
      return;
    }
    previous?.removeListener(_onViewModelStateChanged);
    if (_ownsViewModel) previous?.dispose();
    _viewModel = nextViewModel;
    _ownsViewModel = ownsViewModel;
    nextViewModel.addListener(_onViewModelStateChanged);
    _scheduleInit(nextViewModel);
    if (notify && mounted) setState(() {});
  }

  void _scheduleInit(AccountViewModel viewModel) {
    scheduleMicrotask(() async {
      if (!mounted || !identical(_viewModel, viewModel)) return;
      try {
        await viewModel.init();
      } catch (error, stackTrace) {
        FlutterError.reportError(
          FlutterErrorDetails(
            exception: error,
            stack: stackTrace,
            library: 'dust state',
            context: ErrorDescription('AccountViewModelScope init failed'),
          ),
        );
      }
    });
  }

  void _onViewModelStateChanged() {
    if (mounted) setState(() {});
  }

  @override
  void dispose() {
    final viewModel = _viewModel;
    viewModel?.removeListener(_onViewModelStateChanged);
    if (_ownsViewModel) viewModel?.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    final viewModel = _viewModel;
    if (viewModel == null) {
      throw StateError('AccountViewModelScope built before its view model was initialized.');
    }
    return _AccountViewModelInstance(
      viewModel: viewModel,
      child: _AccountViewModelInherited(
        viewModel: viewModel,
        state: viewModel.value,
        child: widget.child,
      ),
    );
  }
}

class _AccountViewModelInstance extends InheritedWidget {
  const _AccountViewModelInstance({required this.viewModel, required super.child});

  final AccountViewModel viewModel;

  @override
  bool updateShouldNotify(_AccountViewModelInstance oldWidget) {
    return !identical(viewModel, oldWidget.viewModel);
  }
}

class _AccountViewModelInherited extends InheritedWidget {
  const _AccountViewModelInherited({required this.viewModel, required this.state, required super.child});

  final AccountViewModel viewModel;
  final AccountState state;

  @override
  bool updateShouldNotify(_AccountViewModelInherited oldWidget) {
    return !identical(viewModel, oldWidget.viewModel) || state != oldWidget.state;
  }
}

/// Handles one-shot effects from AccountViewModel.
///
/// Effects are delivered without changing state and do not rebuild `child`.
///
/// ```dart
/// AccountViewModelListener(
///   listener: onEffect,
///   child: const FeaturePage(),
/// )
/// ```
class AccountViewModelListener extends StatefulWidget {
  const AccountViewModelListener({super.key, required this.listener, required this.child});

  final void Function(BuildContext context, Object effect) listener;
  final Widget child;

  @override
  State<AccountViewModelListener> createState() => _AccountViewModelListenerState();
}

class _AccountViewModelListenerState extends State<AccountViewModelListener> {
  StreamSubscription<Object>? _sub;
  AccountViewModel? _viewModel;

  @override
  void didChangeDependencies() {
    super.didChangeDependencies();
    final nextViewModel = AccountViewModelScope._watchInstance(context);
    if (_viewModel == nextViewModel) return;
    _sub?.cancel();
    _viewModel = nextViewModel;
    _sub = nextViewModel.effects.listen(_onEffect);
  }

  void _onEffect(Object effect) {
    if (mounted) widget.listener(context, effect);
  }

  @override
  void dispose() {
    _sub?.cancel();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) => widget.child;
}

/// BuildContext helpers generated for AccountViewModel.
///
/// ```dart
/// final vm = context.readAccountViewModel();
/// final state = context.watchAccountViewModel().value;
/// ```
extension AccountViewModelBuildContext on BuildContext {
  _$AccountViewModelProxy watchAccountViewModel() {
    return _$AccountViewModelProxy(this);
  }

  AccountViewModel readAccountViewModel() => AccountViewModelScope.read(this);
}
