// GENERATED CODE - DO NOT MODIFY BY HAND
// coverage:ignore-file
// ignore_for_file: type=lint
// ignore_for_file: unused_element, unused_import, deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: use_function_type_syntax_for_parameters
// ignore_for_file: unnecessary_const, avoid_init_to_null
// ignore_for_file: invalid_override_different_default_values_named
// ignore_for_file: prefer_expression_function_bodies
// ignore_for_file: annotate_overrides, invalid_annotation_target
// ignore_for_file: unnecessary_question_mark
// Generated by dust.

part of 'address_book_view_model.dart';

/// Base class generated for AddressBookViewModel.
///
/// Extend it from your ViewModel and forward typed args:
///
/// ```dart
/// final class AddressBookViewModel extends $AddressBookViewModel {
///   AddressBookViewModel(super.args);
/// }
/// ```
abstract class $AddressBookViewModel extends ViewModelBase<AddressBookState, AddressBookViewModelArgs> {
  $AddressBookViewModel(super.args) : super(initialState: const AddressBookState());
}

/// Reads AddressBookViewModel state from `BuildContext`.
///
/// Read `value` when the widget should rebuild for any state change.
///
/// ```dart
/// final state = context.watchAddressBookViewModel().value;
/// ```
class _$AddressBookViewModelProxy {
  _$AddressBookViewModelProxy(this._context);

  final BuildContext _context;

  AddressBookState get value {
    return AddressBookViewModelScope.of(_context).value;
  }
}

/// Rebuilds when a selected AddressBookState value changes.
///
/// Use this for widgets that depend on one field or derived value.
class AddressBookViewModelSelector<R> extends StatefulWidget {
  const AddressBookViewModelSelector({
    super.key,
    required this.selector,
    required this.builder,
    this.child,
    this.equals,
  });

  final R Function(AddressBookState state) selector;
  final Widget Function(BuildContext context, R value, Widget? child) builder;
  final Widget? child;
  final bool Function(R previous, R next)? equals;

  @override
  State<AddressBookViewModelSelector<R>> createState() => _AddressBookViewModelSelectorState<R>();
}

class _AddressBookViewModelSelectorState<R> extends State<AddressBookViewModelSelector<R>> {
  AddressBookViewModel? _viewModel;
  R? _selected;
  bool _hasSelected = false;

  @override
  void didChangeDependencies() {
    super.didChangeDependencies();
    final nextViewModel = AddressBookViewModelScope._watchInstance(context);
    if (identical(_viewModel, nextViewModel)) return;
    _viewModel?.removeListener(_onViewModelStateChanged);
    _viewModel = nextViewModel;
    nextViewModel.addListener(_onViewModelStateChanged);
    _selectCurrent(force: true);
  }

  @override
  void didUpdateWidget(AddressBookViewModelSelector<R> oldWidget) {
    super.didUpdateWidget(oldWidget);
    _selectCurrent(force: true);
  }

  void _onViewModelStateChanged() {
    _selectCurrent();
  }

  void _selectCurrent({bool force = false}) {
    final viewModel = _viewModel;
    if (viewModel == null) return;
    final nextSelected = widget.selector(viewModel.value);
    if (!_hasSelected) {
      _selected = nextSelected;
      _hasSelected = true;
      return;
    }
    final previousSelected = _selected as R;
    final equals = widget.equals;
    final unchanged = equals == null
        ? previousSelected == nextSelected
        : equals(previousSelected, nextSelected);
    if (!force && unchanged) return;
    if (force || !mounted) {
      _selected = nextSelected;
    } else {
      setState(() {
        _selected = nextSelected;
      });
    }
  }

  @override
  void dispose() {
    _viewModel?.removeListener(_onViewModelStateChanged);
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    if (!_hasSelected) {
      _selectCurrent(force: true);
    }
    return widget.builder(context, _selected as R, widget.child);
  }
}

/// Creates and provides AddressBookViewModel to descendants.
///
/// The default constructor owns the ViewModel. Use `.value` for externally
/// owned ViewModels.
///
/// ```dart
/// AddressBookViewModelScope(
///   args: (context) => AddressBookViewModelArgs(...),
///   create: (context, args) => AddressBookViewModel(args),
///   child: const FeaturePage(),
/// )
/// ```
class AddressBookViewModelScope extends StatefulWidget {
  /// Creates and owns AddressBookViewModel from typed args.
  const AddressBookViewModelScope({
    super.key,
    required this.args,
    required this.create,
    required this.child,
    this.identity,
  }) : value = null;

  /// Provides an externally owned AddressBookViewModel without disposing it.
  const AddressBookViewModelScope.value({
    super.key,
    required AddressBookViewModel this.value,
    required this.child,
  }) : args = null,
       create = null,
       identity = null;

  final AddressBookViewModelArgs Function(BuildContext context)? args;
  final AddressBookViewModel Function(BuildContext context, AddressBookViewModelArgs args)? create;
  final Object? Function(BuildContext context)? identity;
  final AddressBookViewModel? value;
  final Widget child;

  /// Reads AddressBookViewModel without rebuilding when state changes.
  static AddressBookViewModel read(BuildContext context) {
    final scope = context
        .getElementForInheritedWidgetOfExactType<_AddressBookViewModelInstance>()
        ?.widget as _AddressBookViewModelInstance?;
    if (scope == null) throw StateError('No AddressBookViewModelScope found in context.');
    return scope.viewModel;
  }

  static AddressBookViewModel _watchInstance(BuildContext context) {
    final scope = context.dependOnInheritedWidgetOfExactType<_AddressBookViewModelInstance>();
    if (scope == null) throw StateError('No AddressBookViewModelScope found in context.');
    return scope.viewModel;
  }

  /// Watches AddressBookViewModel and rebuilds when state changes.
  static AddressBookViewModel of(BuildContext context) {
    final scope = context.dependOnInheritedWidgetOfExactType<_AddressBookViewModelInherited>();
    if (scope == null) throw StateError('No AddressBookViewModelScope found in context.');
    return scope.viewModel;
  }

  @override
  State<AddressBookViewModelScope> createState() => _AddressBookViewModelScopeState();
}

class _AddressBookViewModelScopeState extends State<AddressBookViewModelScope> {
  AddressBookViewModel? _viewModel;
  Object? _identity;
  bool _ownsViewModel = false;

  @override
  void didChangeDependencies() {
    super.didChangeDependencies();
    final external = widget.value;
    if (external != null) {
      _replaceViewModel(external, ownsViewModel: false, notify: false);
      return;
    }
    final nextIdentity = widget.identity?.call(context);
    if (_viewModel == null || nextIdentity != _identity) {
      _identity = nextIdentity;
      _replaceViewModel(_createOwnedViewModel(), ownsViewModel: true, notify: false);
    }
  }

  @override
  void didUpdateWidget(AddressBookViewModelScope oldWidget) {
    super.didUpdateWidget(oldWidget);
    final external = widget.value;
    if (external != null) {
      _replaceViewModel(external, ownsViewModel: false);
    } else if (oldWidget.value != null) {
      _identity = widget.identity?.call(context);
      _replaceViewModel(_createOwnedViewModel(), ownsViewModel: true);
    } else {
      final nextIdentity = widget.identity?.call(context);
      if (nextIdentity != _identity) {
        _identity = nextIdentity;
        _replaceViewModel(_createOwnedViewModel(), ownsViewModel: true);
      }
    }
  }

  AddressBookViewModel _createOwnedViewModel() {
    final argsFactory = widget.args;
    final create = widget.create;
    if (argsFactory == null || create == null) {
      throw StateError('Owned AddressBookViewModelScope requires args and create.');
    }
    late final AddressBookViewModel created;
    try {
      created = create(context, argsFactory(context));
    } catch (error, stackTrace) {
      Error.throwWithStackTrace(error, stackTrace);
    }
    return created;
  }

  void _replaceViewModel(
    AddressBookViewModel nextViewModel, {
    required bool ownsViewModel,
    bool notify = true,
  }) {
    final previous = _viewModel;
    if (identical(previous, nextViewModel)) {
      _ownsViewModel = ownsViewModel;
      _scheduleInit(nextViewModel);
      if (notify && mounted) setState(() {});
      return;
    }
    previous?.removeListener(_onViewModelStateChanged);
    if (_ownsViewModel) previous?.dispose();
    _viewModel = nextViewModel;
    _ownsViewModel = ownsViewModel;
    nextViewModel.addListener(_onViewModelStateChanged);
    _scheduleInit(nextViewModel);
    if (notify && mounted) setState(() {});
  }

  void _scheduleInit(AddressBookViewModel viewModel) {
    scheduleMicrotask(() async {
      if (!mounted || !identical(_viewModel, viewModel)) return;
      try {
        await viewModel.init();
      } catch (error, stackTrace) {
        FlutterError.reportError(
          FlutterErrorDetails(
            exception: error,
            stack: stackTrace,
            library: 'dust state',
            context: ErrorDescription('AddressBookViewModelScope init failed'),
          ),
        );
      }
    });
  }

  void _onViewModelStateChanged() {
    if (mounted) setState(() {});
  }

  @override
  void dispose() {
    final viewModel = _viewModel;
    viewModel?.removeListener(_onViewModelStateChanged);
    if (_ownsViewModel) viewModel?.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    final viewModel = _viewModel;
    if (viewModel == null) {
      throw StateError('AddressBookViewModelScope built before its view model was initialized.');
    }
    return _AddressBookViewModelInstance(
      viewModel: viewModel,
      child: _AddressBookViewModelInherited(
        viewModel: viewModel,
        state: viewModel.value,
        child: widget.child,
      ),
    );
  }
}

class _AddressBookViewModelInstance extends InheritedWidget {
  const _AddressBookViewModelInstance({required this.viewModel, required super.child});

  final AddressBookViewModel viewModel;

  @override
  bool updateShouldNotify(_AddressBookViewModelInstance oldWidget) {
    return !identical(viewModel, oldWidget.viewModel);
  }
}

class _AddressBookViewModelInherited extends InheritedWidget {
  const _AddressBookViewModelInherited({required this.viewModel, required this.state, required super.child});

  final AddressBookViewModel viewModel;
  final AddressBookState state;

  @override
  bool updateShouldNotify(_AddressBookViewModelInherited oldWidget) {
    return !identical(viewModel, oldWidget.viewModel) || state != oldWidget.state;
  }
}

/// Handles one-shot effects from AddressBookViewModel.
///
/// Effects are delivered without changing state and do not rebuild `child`.
///
/// ```dart
/// AddressBookViewModelListener(
///   listener: onEffect,
///   child: const FeaturePage(),
/// )
/// ```
class AddressBookViewModelListener extends StatefulWidget {
  const AddressBookViewModelListener({super.key, required this.listener, required this.child});

  final void Function(BuildContext context, Object effect) listener;
  final Widget child;

  @override
  State<AddressBookViewModelListener> createState() => _AddressBookViewModelListenerState();
}

class _AddressBookViewModelListenerState extends State<AddressBookViewModelListener> {
  StreamSubscription<Object>? _sub;
  AddressBookViewModel? _viewModel;

  @override
  void didChangeDependencies() {
    super.didChangeDependencies();
    final nextViewModel = AddressBookViewModelScope._watchInstance(context);
    if (_viewModel == nextViewModel) return;
    _sub?.cancel();
    _viewModel = nextViewModel;
    _sub = nextViewModel.effects.listen(_onEffect);
  }

  void _onEffect(Object effect) {
    if (mounted) widget.listener(context, effect);
  }

  @override
  void dispose() {
    _sub?.cancel();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) => widget.child;
}

/// BuildContext helpers generated for AddressBookViewModel.
///
/// ```dart
/// final vm = context.readAddressBookViewModel();
/// final state = context.watchAddressBookViewModel().value;
/// ```
extension AddressBookViewModelBuildContext on BuildContext {
  _$AddressBookViewModelProxy watchAddressBookViewModel() {
    return _$AddressBookViewModelProxy(this);
  }

  AddressBookViewModel readAddressBookViewModel() => AddressBookViewModelScope.read(this);
}
