// GENERATED CODE - DO NOT MODIFY BY HAND.
// Generated by dust.
//
// ignore_for_file: unused_import, unnecessary_import

import 'package:flutter/widgets.dart';
import 'package:dust_flutter/route.dart';

import 'paths.g.dart';
extension CommerceRouterContext on BuildContext {
  RouterController<CommerceRoute> get _routerController =>
      RouterController.of<CommerceRoute>(this);
  CommerceRoutesNavigator get navigator => CommerceRoutesNavigator(_routerController);
}

final class CommerceRoutesNavigator {
  const CommerceRoutesNavigator(this._router);

  final RouterController<CommerceRoute> _router;

  CommerceRouteAction<void> catalog() =>
      CommerceRouteAction(_router, CatalogRoute());

  CommerceRouteAction<void> notFound() =>
      CommerceRouteAction(_router, NotFoundRoute());

  CommerceRouteAction<void> account() =>
      CommerceRouteAction(_router, AccountRoute());

  CommerceRouteAction<void> accountOrders() =>
      CommerceRouteAction(_router, AccountOrdersRoute());

  CommerceRouteAction<void> cart() => CommerceRouteAction(_router, CartRoute());

  CommerceRouteAction<void> category({required String handle, int page = 1, String sortBy = 'created_at'}) =>
      CommerceRouteAction(_router, CategoryRoute(handle: handle, page: page, sortBy: sortBy));

  CommerceRouteAction<void> checkout() =>
      CommerceRouteAction(_router, CheckoutRoute());

  CommerceRouteAction<void> collection({required String handle, int page = 1, String sortBy = 'created_at'}) =>
      CommerceRouteAction(_router, CollectionRoute(handle: handle, page: page, sortBy: sortBy));

  CommerceRouteAction<void> orderConfirmed({required String id}) =>
      CommerceRouteAction(_router, OrderConfirmedRoute(id: id));

  CommerceRouteAction<void> product({required String handle}) =>
      CommerceRouteAction(_router, ProductRoute(handle: handle));

  CommerceRouteAction<void> store({int page = 1, String sortBy = 'created_at'}) =>
      CommerceRouteAction(_router, StoreRoute(page: page, sortBy: sortBy));

  bool pop<R>([R? result]) => _router.pop<R>(result);
}

final class CommerceRouteAction<R> {
  const CommerceRouteAction(this._router, this.route);

  final RouterController<CommerceRoute> _router;
  final CommerceRoute<R> route;

  void go() => _router.go(route);
  Future<R?> push() => _router.push<R>(route);
  void replace() => _router.replace(route);
}
