// GENERATED CODE - DO NOT MODIFY BY HAND.
// Generated by dust.
//
// ignore_for_file: unused_import, unnecessary_import

import 'package:dust_flutter/route.dart';

sealed class CommerceRoute<R> {
  const CommerceRoute();

  String get location;

  /// Defaults to true. Override and return false for public routes
  /// (login, invite, forbidden, checkout, notFound).
  bool get requiresAuth => true;
}

/// Typed route data for `CatalogRoute`.
final class CatalogRoute extends CommerceRoute<void> {
  const CatalogRoute();

  @override
  String get location {
    return generatedRoutePath(
      const [],
      uriExtras: generatedRouteUriExtrasOf(this),
    );
  }

  @override
  bool get requiresAuth => false;
}

/// Typed route data for `NotFoundRoute`.
final class NotFoundRoute extends CommerceRoute<void> {
  const NotFoundRoute();

  @override
  String get location {
    return generatedRoutePath(
      ['404'],
      uriExtras: generatedRouteUriExtrasOf(this),
    );
  }

  @override
  bool get requiresAuth => false;
}

/// Typed route data for `AccountRoute`.
final class AccountRoute extends CommerceRoute<void> {
  const AccountRoute();

  @override
  String get location {
    return generatedRoutePath(
      ['account'],
      uriExtras: generatedRouteUriExtrasOf(this),
    );
  }

  @override
  bool get requiresAuth => false;
}

/// Typed route data for `AccountAddressesRoute`.
final class AccountAddressesRoute extends CommerceRoute<void> {
  const AccountAddressesRoute();

  @override
  String get location {
    return generatedRoutePath(
      ['account', 'addresses'],
      uriExtras: generatedRouteUriExtrasOf(this),
    );
  }
}

/// Typed route data for `AccountOrdersRoute`.
final class AccountOrdersRoute extends CommerceRoute<void> {
  const AccountOrdersRoute();

  @override
  String get location {
    return generatedRoutePath(
      ['account', 'orders'],
      uriExtras: generatedRouteUriExtrasOf(this),
    );
  }
}

/// Typed route data for `AccountOrderDetailRoute`.
final class AccountOrderDetailRoute extends CommerceRoute<void> {
  const AccountOrderDetailRoute({required this.id});

  final String id;

  @override
  String get location {
    return generatedRoutePath(
      ['account', 'orders', 'details', id],
      uriExtras: generatedRouteUriExtrasOf(this),
    );
  }
}

/// Typed route data for `AccountProfileRoute`.
final class AccountProfileRoute extends CommerceRoute<void> {
  const AccountProfileRoute();

  @override
  String get location {
    return generatedRoutePath(
      ['account', 'profile'],
      uriExtras: generatedRouteUriExtrasOf(this),
    );
  }
}

/// Typed route data for `CartRoute`.
final class CartRoute extends CommerceRoute<void> {
  const CartRoute();

  @override
  String get location {
    return generatedRoutePath(
      ['cart'],
      uriExtras: generatedRouteUriExtrasOf(this),
    );
  }

  @override
  bool get requiresAuth => false;
}

/// Typed route data for `CategoryRoute`.
final class CategoryRoute extends CommerceRoute<void> {
  const CategoryRoute({required this.handle, this.page = 1, this.sortBy = 'created_at', this.optionValueIds = const []});

  final String handle;
  final int page;
  final String sortBy;
  final List<String> optionValueIds;

  @override
  String get location {
    final query = <String, dynamic>{};
    if (page != 1) {
      query['page'] = page.toString();
    }
    if (sortBy != 'created_at') {
      query['sortBy'] = sortBy;
    }
    if (!generatedRouteListEquals(optionValueIds, const [])) {
      query['optionValueIds'] = optionValueIds;
    }
    return generatedRoutePath(
      ['categories', handle],
      queryParameters: query.isEmpty ? null : query,
      uriExtras: generatedRouteUriExtrasOf(this),
    );
  }

  @override
  bool get requiresAuth => false;
}

/// Typed route data for `CheckoutRoute`.
final class CheckoutRoute extends CommerceRoute<void> {
  const CheckoutRoute();

  @override
  String get location {
    return generatedRoutePath(
      ['checkout'],
      uriExtras: generatedRouteUriExtrasOf(this),
    );
  }
}

/// Typed route data for `CollectionRoute`.
final class CollectionRoute extends CommerceRoute<void> {
  const CollectionRoute({required this.handle, this.page = 1, this.sortBy = 'created_at', this.optionValueIds = const []});

  final String handle;
  final int page;
  final String sortBy;
  final List<String> optionValueIds;

  @override
  String get location {
    final query = <String, dynamic>{};
    if (page != 1) {
      query['page'] = page.toString();
    }
    if (sortBy != 'created_at') {
      query['sortBy'] = sortBy;
    }
    if (!generatedRouteListEquals(optionValueIds, const [])) {
      query['optionValueIds'] = optionValueIds;
    }
    return generatedRoutePath(
      ['collections', handle],
      queryParameters: query.isEmpty ? null : query,
      uriExtras: generatedRouteUriExtrasOf(this),
    );
  }

  @override
  bool get requiresAuth => false;
}

/// Typed route data for `OrderConfirmedRoute`.
final class OrderConfirmedRoute extends CommerceRoute<void> {
  const OrderConfirmedRoute({required this.id});

  final String id;

  @override
  String get location {
    return generatedRoutePath(
      ['order', id, 'confirmed'],
      uriExtras: generatedRouteUriExtrasOf(this),
    );
  }

  @override
  bool get requiresAuth => false;
}

/// Typed route data for `OrderTransferRoute`.
final class OrderTransferRoute extends CommerceRoute<void> {
  const OrderTransferRoute({required this.id, required this.token});

  final String id;
  final String token;

  @override
  String get location {
    return generatedRoutePath(
      ['order', id, 'transfer', token],
      uriExtras: generatedRouteUriExtrasOf(this),
    );
  }

  @override
  bool get requiresAuth => false;
}

/// Typed route data for `ProductRoute`.
final class ProductRoute extends CommerceRoute<void> {
  const ProductRoute({required this.handle});

  final String handle;

  @override
  String get location {
    return generatedRoutePath(
      ['products', handle],
      uriExtras: generatedRouteUriExtrasOf(this),
    );
  }

  @override
  bool get requiresAuth => false;
}

/// Typed route data for `StoreRoute`.
final class StoreRoute extends CommerceRoute<void> {
  const StoreRoute({this.page = 1, this.sortBy = 'created_at', this.optionValueIds = const []});

  final int page;
  final String sortBy;
  final List<String> optionValueIds;

  @override
  String get location {
    final query = <String, dynamic>{};
    if (page != 1) {
      query['page'] = page.toString();
    }
    if (sortBy != 'created_at') {
      query['sortBy'] = sortBy;
    }
    if (!generatedRouteListEquals(optionValueIds, const [])) {
      query['optionValueIds'] = optionValueIds;
    }
    return generatedRoutePath(
      ['store'],
      queryParameters: query.isEmpty ? null : query,
      uriExtras: generatedRouteUriExtrasOf(this),
    );
  }

  @override
  bool get requiresAuth => false;
}

String commerceRouteLocation(CommerceRoute route) => route.location;

CommerceRoute parseCommerceRoute(Uri uri) {
  final segments = uri.pathSegments;

  if (segments.isEmpty) {
    final route = CatalogRoute();
    return withGeneratedRouteUriExtras(route, uri, const <String>{});
  }
  if (segments.length == 1 && segments[0] == '404') {
    final route = NotFoundRoute();
    return withGeneratedRouteUriExtras(route, uri, const <String>{});
  }
  if (segments.length == 1 && segments[0] == 'account') {
    final route = AccountRoute();
    return withGeneratedRouteUriExtras(route, uri, const <String>{});
  }
  if (
    segments.length == 2 &&
    segments[0] == 'account' &&
    segments[1] == 'addresses'
  ) {
    final route = AccountAddressesRoute();
    return withGeneratedRouteUriExtras(route, uri, const <String>{});
  }
  if (segments.length == 2 && segments[0] == 'account' && segments[1] == 'orders') {
    final route = AccountOrdersRoute();
    return withGeneratedRouteUriExtras(route, uri, const <String>{});
  }
  if (
    segments.length == 4 &&
    segments[0] == 'account' &&
    segments[1] == 'orders' &&
    segments[2] == 'details'
  ) {
    final id = segments[3];
    final route = AccountOrderDetailRoute(id: id);
    return withGeneratedRouteUriExtras(route, uri, const <String>{});
  }
  if (segments.length == 2 && segments[0] == 'account' && segments[1] == 'profile') {
    final route = AccountProfileRoute();
    return withGeneratedRouteUriExtras(route, uri, const <String>{});
  }
  if (segments.length == 1 && segments[0] == 'cart') {
    final route = CartRoute();
    return withGeneratedRouteUriExtras(route, uri, const <String>{});
  }
  if (segments.length == 2 && segments[0] == 'categories') {
    final handle = segments[1];
    final page = uri.queryParameters.containsKey('page') ? int.tryParse(uri.queryParameters['page'] ?? '') : 1;
    final sortBy = uri.queryParameters['sortBy'] ?? 'created_at';
    final optionValueIds = uri.queryParametersAll['optionValueIds'] ?? const [];
    if (page == null) {
      return _$notFoundRoute(uri);
    }
    final route = CategoryRoute(
      handle: handle,
      page: page,
      sortBy: sortBy,
      optionValueIds: optionValueIds,
    );
    return withGeneratedRouteUriExtras(route, uri, const <String>{'page', 'sortBy', 'optionValueIds'});
  }
  if (segments.length == 1 && segments[0] == 'checkout') {
    final route = CheckoutRoute();
    return withGeneratedRouteUriExtras(route, uri, const <String>{});
  }
  if (segments.length == 2 && segments[0] == 'collections') {
    final handle = segments[1];
    final page = uri.queryParameters.containsKey('page') ? int.tryParse(uri.queryParameters['page'] ?? '') : 1;
    final sortBy = uri.queryParameters['sortBy'] ?? 'created_at';
    final optionValueIds = uri.queryParametersAll['optionValueIds'] ?? const [];
    if (page == null) {
      return _$notFoundRoute(uri);
    }
    final route = CollectionRoute(
      handle: handle,
      page: page,
      sortBy: sortBy,
      optionValueIds: optionValueIds,
    );
    return withGeneratedRouteUriExtras(route, uri, const <String>{'page', 'sortBy', 'optionValueIds'});
  }
  if (segments.length == 3 && segments[0] == 'order' && segments[2] == 'confirmed') {
    final id = segments[1];
    final route = OrderConfirmedRoute(id: id);
    return withGeneratedRouteUriExtras(route, uri, const <String>{});
  }
  if (segments.length == 4 && segments[0] == 'order' && segments[2] == 'transfer') {
    final id = segments[1];
    final token = segments[3];
    final route = OrderTransferRoute(id: id, token: token);
    return withGeneratedRouteUriExtras(route, uri, const <String>{});
  }
  if (segments.length == 2 && segments[0] == 'products') {
    final handle = segments[1];
    final route = ProductRoute(handle: handle);
    return withGeneratedRouteUriExtras(route, uri, const <String>{});
  }
  if (segments.length == 1 && segments[0] == 'store') {
    final page = uri.queryParameters.containsKey('page') ? int.tryParse(uri.queryParameters['page'] ?? '') : 1;
    final sortBy = uri.queryParameters['sortBy'] ?? 'created_at';
    final optionValueIds = uri.queryParametersAll['optionValueIds'] ?? const [];
    if (page == null) {
      return _$notFoundRoute(uri);
    }
    final route = StoreRoute(
      page: page,
      sortBy: sortBy,
      optionValueIds: optionValueIds,
    );
    return withGeneratedRouteUriExtras(route, uri, const <String>{'page', 'sortBy', 'optionValueIds'});
  }
  return _$notFoundRoute(uri);
}

CommerceRoute _$notFoundRoute(Uri uri) => const NotFoundRoute();
