// GENERATED CODE - DO NOT MODIFY BY HAND.
// Generated by dust.
//
// ignore_for_file: unused_import, unnecessary_import

import 'package:dust_flutter/route.dart';

sealed class CommerceRoute<R> {
  const CommerceRoute();

  String get location;

  /// Defaults to true. Override and return false for public routes
  /// (login, invite, forbidden, checkout, notFound).
  bool get requiresAuth => true;
}

/// Typed route data for `CatalogRoute`.
final class CatalogRoute extends CommerceRoute<void> {
  const CatalogRoute();

  @override
  String get location {
    return generatedRoutePath(
      const [],
      uriExtras: generatedRouteUriExtrasOf(this),
    );
  }
}

/// Typed route data for `NotFoundRoute`.
final class NotFoundRoute extends CommerceRoute<void> {
  const NotFoundRoute();

  @override
  String get location {
    return generatedRoutePath(
      ['404'],
      uriExtras: generatedRouteUriExtrasOf(this),
    );
  }

  @override
  bool get requiresAuth => false;
}

String commerceRouteLocation(CommerceRoute route) => route.location;

CommerceRoute parseCommerceRoute(Uri uri) {
  final segments = uri.pathSegments;

  if (segments.isEmpty) {
    final route = CatalogRoute();
    return withGeneratedRouteUriExtras(route, uri, const <String>{});
  }
  if (segments.length == 1 && segments[0] == '404') {
    final route = NotFoundRoute();
    return withGeneratedRouteUriExtras(route, uri, const <String>{});
  }
  return _$notFoundRoute(uri);
}

CommerceRoute _$notFoundRoute(Uri uri) => const NotFoundRoute();
