// GENERATED CODE - DO NOT MODIFY BY HAND
// coverage:ignore-file
// ignore_for_file: type=lint
// ignore_for_file: unused_element, unused_import, deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: use_function_type_syntax_for_parameters
// ignore_for_file: unnecessary_const, avoid_init_to_null
// ignore_for_file: invalid_override_different_default_values_named
// ignore_for_file: prefer_expression_function_bodies
// ignore_for_file: annotate_overrides, invalid_annotation_target
// ignore_for_file: unnecessary_question_mark
// Generated by dust.

part of 'details.dart';

final class _ProductDetailsCopyWithUnset {
  const _ProductDetailsCopyWithUnset();
}

const _productDetailsCopyWithUnset = _ProductDetailsCopyWithUnset();

mixin _$ProductDetails implements Serializable {
  @override
  String toString() {
    final self = this as ProductDetails;
    return 'ProductDetails('
        'height: ${self.height}, '
        'length: ${self.length}, '
        'material: ${self.material}, '
        'originCountry: ${self.originCountry}, '
        'productType: ${self.productType}, '
        'weight: ${self.weight}, '
        'width: ${self.width}'
        ')';
  }

  @override
  bool operator ==(Object other) {
    final self = this as ProductDetails;
    return identical(this, other) ||
        other is ProductDetails &&
            runtimeType == other.runtimeType &&
            other.height == self.height &&
            other.length == self.length &&
            other.material == self.material &&
            other.originCountry == self.originCountry &&
            other.productType == self.productType &&
            other.weight == self.weight &&
            other.width == self.width;
  }

  @override
  int get hashCode {
    final self = this as ProductDetails;
    return Object.hashAll([
      runtimeType,
      self.height,
      self.length,
      self.material,
      self.originCountry,
      self.productType,
      self.weight,
      self.width,
    ]);
  }

  /// Creates a copy of this `ProductDetails` with selected fields replaced.
  ///
  /// Usage:
  /// ```dart
  /// final updated = productDetails.copyWith();
  /// final cleared = productDetails.copyWith(height: null);
  /// ```
  @pragma('vm:prefer-inline')
  _$ProductDetailsCopyWith<ProductDetails> get copyWith => _$ProductDetailsCopyWithImpl<ProductDetails>(this as ProductDetails, (value) => value);

  Map<String, Object?> serialize() =>
      _$ProductDetailsSerialize(this as ProductDetails);

  Map<String, Object?> toJson() => serialize();
}

// CopyWith API inspired by Freezed.

/// @nodoc
abstract class _$ProductDetailsCopyWith<$Res> {
  $Res call({
    int? height,
    int? length,
    String? material,
    String? originCountry,
    String? productType,
    int? weight,
    int? width,
  });
}

/// @nodoc
final class _$ProductDetailsCopyWithImpl<$Res> implements _$ProductDetailsCopyWith<$Res> {
  const _$ProductDetailsCopyWithImpl(this._self, this._then);

  final ProductDetails _self;
  final $Res Function(ProductDetails) _then;

  @override
  @pragma('vm:prefer-inline')
  $Res call({
    Object? height = _productDetailsCopyWithUnset,
    Object? length = _productDetailsCopyWithUnset,
    Object? material = _productDetailsCopyWithUnset,
    Object? originCountry = _productDetailsCopyWithUnset,
    Object? productType = _productDetailsCopyWithUnset,
    Object? weight = _productDetailsCopyWithUnset,
    Object? width = _productDetailsCopyWithUnset,
  }) {
    return _then(
      ProductDetails(
        material: identical(material, _productDetailsCopyWithUnset)
            ? _self.material
            : material as String?,
        originCountry: identical(originCountry, _productDetailsCopyWithUnset)
            ? _self.originCountry
            : originCountry as String?,
        productType: identical(productType, _productDetailsCopyWithUnset)
            ? _self.productType
            : productType as String?,
        weight: identical(weight, _productDetailsCopyWithUnset)
            ? _self.weight
            : weight as int?,
        length: identical(length, _productDetailsCopyWithUnset)
            ? _self.length
            : length as int?,
        width: identical(width, _productDetailsCopyWithUnset)
            ? _self.width
            : width as int?,
        height: identical(height, _productDetailsCopyWithUnset)
            ? _self.height
            : height as int?,
      )
    );
  }
}
final class $ProductDetailsSerializer implements Serializer<ProductDetails, Map<String, Object?>> {
  const $ProductDetailsSerializer();

  @override
  Map<String, Object?> serialize(ProductDetails value) => _$ProductDetailsSerialize(value);
}
final class $ProductDetailsDeserializer implements Deserializer<ProductDetails, Map<String, Object?>> {
  const $ProductDetailsDeserializer();

  @override
  ProductDetails deserialize(Map<String, Object?> json) => _$ProductDetailsDeserialize(json);
}

Map<String, Object?> _$ProductDetailsSerialize(ProductDetails instance) {
  return <String, Object?>{
    'height': instance.height,
    'length': instance.length,
    'material': instance.material,
    'origin_country': instance.originCountry,
    'product_type': instance.productType,
    'weight': instance.weight,
    'width': instance.width,
  };
}

Map<String, Object?> _$ProductDetailsToJson(ProductDetails instance) =>
    _$ProductDetailsSerialize(instance);

// factory ProductDetails.fromJson(Map<String, Object?> json) => _$ProductDetailsFromJson(json);
ProductDetails _$ProductDetailsDeserialize(Map<String, Object?> json) {
  final heightValue = json['height'] == null
      ? null
      : JsonHelper.as<int>(json['height'], 'height', 'int');
  final lengthValue = json['length'] == null
      ? null
      : JsonHelper.as<int>(json['length'], 'length', 'int');
  final materialValue = json['material'] == null
      ? null
      : JsonHelper.as<String>(json['material'], 'material', 'String');
  final originCountryValue = json['origin_country'] == null
      ? null
      : JsonHelper.as<String>(json['origin_country'], 'origin_country', 'String');
  final productTypeValue = json['product_type'] == null
      ? null
      : JsonHelper.as<String>(json['product_type'], 'product_type', 'String');
  final weightValue = json['weight'] == null
      ? null
      : JsonHelper.as<int>(json['weight'], 'weight', 'int');
  final widthValue = json['width'] == null
      ? null
      : JsonHelper.as<int>(json['width'], 'width', 'int');

  return ProductDetails(
    material: materialValue,
    originCountry: originCountryValue,
    productType: productTypeValue,
    weight: weightValue,
    length: lengthValue,
    width: widthValue,
    height: heightValue,
  );
}

ProductDetails _$ProductDetailsFromJson(Map<String, Object?> json) =>
    _$ProductDetailsDeserialize(json);
