// GENERATED CODE - DO NOT MODIFY BY HAND
// coverage:ignore-file
// ignore_for_file: type=lint
// ignore_for_file: unused_element, unused_import, deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: use_function_type_syntax_for_parameters
// ignore_for_file: unnecessary_const, avoid_init_to_null
// ignore_for_file: invalid_override_different_default_values_named
// ignore_for_file: prefer_expression_function_bodies
// ignore_for_file: annotate_overrides, invalid_annotation_target
// ignore_for_file: unnecessary_question_mark
// Generated by dust.

part of 'option.dart';

const DeepCollectionEquality _productOptionValuesEquality = DeepCollectionEquality();

mixin _$ProductOption implements Serializable {
  @override
  String toString() {
    final self = this as ProductOption;
    return 'ProductOption('
        'id: ${self.id}, '
        'title: ${self.title}, '
        'values: ${self.values}'
        ')';
  }

  @override
  bool operator ==(Object other) {
    final self = this as ProductOption;
    return identical(this, other) ||
        other is ProductOption &&
            runtimeType == other.runtimeType &&
            other.id == self.id &&
            other.title == self.title &&
            _productOptionValuesEquality.equals(other.values, self.values);
  }

  @override
  int get hashCode {
    final self = this as ProductOption;
    return Object.hashAll([
      runtimeType,
      self.id,
      self.title,
      _productOptionValuesEquality.hash(self.values),
    ]);
  }

  /// Creates a copy of this `ProductOption` with selected fields replaced.
  ///
  /// Usage:
  /// ```dart
  /// final updated = productOption.copyWith(id: 'John');
  /// ```
  @pragma('vm:prefer-inline')
  _$ProductOptionCopyWith<ProductOption> get copyWith => _$ProductOptionCopyWithImpl<ProductOption>(this as ProductOption, (value) => value);

  Map<String, Object?> serialize() =>
      _$ProductOptionSerialize(this as ProductOption);

  Map<String, Object?> toJson() => serialize();
}

// CopyWith API inspired by Freezed.

/// @nodoc
abstract class _$ProductOptionCopyWith<$Res> {
  $Res call({
    String? id,
    String? title,
    List<String>? values,
  });
}

/// @nodoc
final class _$ProductOptionCopyWithImpl<$Res> implements _$ProductOptionCopyWith<$Res> {
  const _$ProductOptionCopyWithImpl(this._self, this._then);

  final ProductOption _self;
  final $Res Function(ProductOption) _then;

  @override
  @pragma('vm:prefer-inline')
  $Res call({
    Object? id = null,
    Object? title = null,
    Object? values = null,
  }) {
    return _then(
      ProductOption(
        id: id == null ? _self.id : id as String,
        title: title == null ? _self.title : title as String,
        values: values == null ? _self.values : values as List<String>,
      )
    );
  }
}
final class $ProductOptionSerializer implements Serializer<ProductOption, Map<String, Object?>> {
  const $ProductOptionSerializer();

  @override
  Map<String, Object?> serialize(ProductOption value) => _$ProductOptionSerialize(value);
}
final class $ProductOptionDeserializer implements Deserializer<ProductOption, Map<String, Object?>> {
  const $ProductOptionDeserializer();

  @override
  ProductOption deserialize(Map<String, Object?> json) => _$ProductOptionDeserialize(json);
}

Map<String, Object?> _$ProductOptionSerialize(ProductOption instance) {
  return <String, Object?>{
    'id': instance.id,
    'title': instance.title,
    'values': instance.values
        .map((item) => item)
        .toList(),
  };
}

Map<String, Object?> _$ProductOptionToJson(ProductOption instance) =>
    _$ProductOptionSerialize(instance);

// factory ProductOption.fromJson(Map<String, Object?> json) => _$ProductOptionFromJson(json);
ProductOption _$ProductOptionDeserialize(Map<String, Object?> json) {
  final idValue = JsonHelper.as<String>(json['id'], 'id', 'String');
  final titleValue = JsonHelper.as<String>(json['title'], 'title', 'String');
  final valuesValue = JsonHelper.decodeList(json['values'], 'values',
      (item, itemKey) => JsonHelper.as<String>(item, itemKey, 'String'));

  return ProductOption(id: idValue, title: titleValue, values: valuesValue);
}

ProductOption _$ProductOptionFromJson(Map<String, Object?> json) =>
    _$ProductOptionDeserialize(json);
