// GENERATED CODE - DO NOT MODIFY BY HAND
// coverage:ignore-file
// ignore_for_file: type=lint
// ignore_for_file: unused_element, unused_import, deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: use_function_type_syntax_for_parameters
// ignore_for_file: unnecessary_const, avoid_init_to_null
// ignore_for_file: invalid_override_different_default_values_named
// ignore_for_file: prefer_expression_function_bodies
// ignore_for_file: annotate_overrides, invalid_annotation_target
// ignore_for_file: unnecessary_question_mark
// Generated by dust.

part of 'product.dart';

const DeepCollectionEquality _productCategoriesEquality = DeepCollectionEquality();
const DeepCollectionEquality _productImagesEquality = DeepCollectionEquality();
const DeepCollectionEquality _productOptionsEquality = DeepCollectionEquality();
const DeepCollectionEquality _productTagsEquality = DeepCollectionEquality();
const DeepCollectionEquality _productVariantsEquality = DeepCollectionEquality();
final class _ProductCopyWithUnset {
  const _ProductCopyWithUnset();
}

const _productCopyWithUnset = _ProductCopyWithUnset();

mixin _$Product implements Serializable {
  @override
  String toString() {
    final self = this as Product;
    return 'Product('
        'description: ${self.description}, '
        'categories: ${self.categories}, '
        'collection: ${self.collection}, '
        'details: ${self.details}, '
        'handle: ${self.handle}, '
        'id: ${self.id}, '
        'images: ${self.images}, '
        'options: ${self.options}, '
        'status: ${self.status}, '
        'title: ${self.title}, '
        'thumbnail: ${self.thumbnail}, '
        'tags: ${self.tags}, '
        'variants: ${self.variants}'
        ')';
  }

  @override
  bool operator ==(Object other) {
    final self = this as Product;
    return identical(this, other) ||
        other is Product &&
            runtimeType == other.runtimeType &&
            other.description == self.description &&
            _productCategoriesEquality.equals(other.categories, self.categories) &&
            other.collection == self.collection &&
            other.details == self.details &&
            other.handle == self.handle &&
            other.id == self.id &&
            _productImagesEquality.equals(other.images, self.images) &&
            _productOptionsEquality.equals(other.options, self.options) &&
            other.status == self.status &&
            other.title == self.title &&
            other.thumbnail == self.thumbnail &&
            _productTagsEquality.equals(other.tags, self.tags) &&
            _productVariantsEquality.equals(other.variants, self.variants);
  }

  @override
  int get hashCode {
    final self = this as Product;
    return Object.hashAll([
      runtimeType,
      self.description,
      _productCategoriesEquality.hash(self.categories),
      self.collection,
      self.details,
      self.handle,
      self.id,
      _productImagesEquality.hash(self.images),
      _productOptionsEquality.hash(self.options),
      self.status,
      self.title,
      self.thumbnail,
      _productTagsEquality.hash(self.tags),
      _productVariantsEquality.hash(self.variants),
    ]);
  }

  /// Creates a copy of this `Product` with selected fields replaced.
  ///
  /// Usage:
  /// ```dart
  /// final updated = product.copyWith(handle: 'John');
  /// final cleared = product.copyWith(description: null);
  /// ```
  @pragma('vm:prefer-inline')
  _$ProductCopyWith<Product> get copyWith => _$ProductCopyWithImpl<Product>(this as Product, (value) => value);

  Map<String, Object?> serialize() => _$ProductSerialize(this as Product);

  Map<String, Object?> toJson() => serialize();
}

// CopyWith API inspired by Freezed.

/// @nodoc
abstract class _$ProductCopyWith<$Res> {
  $Res call({
    String? description,
    List<ProductCategory>? categories,
    ProductCollection? collection,
    ProductDetails? details,
    String? handle,
    String? id,
    List<StoreProductImage>? images,
    List<ProductOption>? options,
    ProductStatus? status,
    String? title,
    String? thumbnail,
    List<ProductTag>? tags,
    List<ProductVariant>? variants,
  });
}

/// @nodoc
final class _$ProductCopyWithImpl<$Res> implements _$ProductCopyWith<$Res> {
  const _$ProductCopyWithImpl(this._self, this._then);

  final Product _self;
  final $Res Function(Product) _then;

  @override
  @pragma('vm:prefer-inline')
  $Res call({
    Object? description = _productCopyWithUnset,
    Object? categories = null,
    Object? collection = _productCopyWithUnset,
    Object? details = null,
    Object? handle = null,
    Object? id = null,
    Object? images = null,
    Object? options = null,
    Object? status = null,
    Object? title = null,
    Object? thumbnail = _productCopyWithUnset,
    Object? tags = null,
    Object? variants = null,
  }) {
    return _then(
      Product(
        id: id == null ? _self.id : id as String,
        title: title == null ? _self.title : title as String,
        handle: handle == null ? _self.handle : handle as String,
        status: status == null ? _self.status : status as ProductStatus,
        options: options == null ? _self.options : options as List<ProductOption>,
        variants: variants == null ? _self.variants : variants as List<ProductVariant>,
        categories: categories == null ? _self.categories : categories as List<ProductCategory>,
        collection: identical(collection, _productCopyWithUnset)
            ? _self.collection
            : collection as ProductCollection?,
        details: details == null ? _self.details : details as ProductDetails,
        description: identical(description, _productCopyWithUnset)
            ? _self.description
            : description as String?,
        images: images == null ? _self.images : images as List<StoreProductImage>,
        thumbnail: identical(thumbnail, _productCopyWithUnset)
            ? _self.thumbnail
            : thumbnail as String?,
        tags: tags == null ? _self.tags : tags as List<ProductTag>,
      )
    );
  }
}
final class $ProductSerializer implements Serializer<Product, Map<String, Object?>> {
  const $ProductSerializer();

  @override
  Map<String, Object?> serialize(Product value) => _$ProductSerialize(value);
}
final class $ProductDeserializer implements Deserializer<Product, Map<String, Object?>> {
  const $ProductDeserializer();

  @override
  Product deserialize(Map<String, Object?> json) => _$ProductDeserialize(json);
}
final class $ProductStatusSerializer implements Serializer<ProductStatus, Object?> {
  const $ProductStatusSerializer();

  @override
  Object? serialize(ProductStatus value) => _$ProductStatusSerialize(value);
}
final class $ProductStatusDeserializer implements Deserializer<ProductStatus, Object?> {
  const $ProductStatusDeserializer();

  @override
  ProductStatus deserialize(Object? json) => _$ProductStatusDeserialize(json);
}

Map<String, Object?> _$ProductSerialize(Product instance) {
  return <String, Object?>{
    'description': instance.description,
    'categories': instance.categories
        .map((item) => item.toJson())
        .toList(),
    'collection': instance.collection == null
        ? null
        : (instance.collection!).toJson(),
    'details': instance.details.toJson(),
    'handle': instance.handle,
    'id': instance.id,
    'images': instance.images
        .map((item) => item.toJson())
        .toList(),
    'options': instance.options
        .map((item) => item.toJson())
        .toList(),
    'status': _$ProductStatusSerialize(instance.status),
    'title': instance.title,
    'thumbnail': instance.thumbnail,
    'tags': instance.tags
        .map((item) => item.toJson())
        .toList(),
    'variants': instance.variants
        .map((item) => item.toJson())
        .toList(),
  };
}

Map<String, Object?> _$ProductToJson(Product instance) =>
    _$ProductSerialize(instance);

// factory Product.fromJson(Map<String, Object?> json) => _$ProductFromJson(json);
Product _$ProductDeserialize(Map<String, Object?> json) {
  final descriptionValue = json['description'] == null
      ? null
      : JsonHelper.as<String>(json['description'], 'description', 'String');
  final categoriesValue = JsonHelper.decodeList(json['categories'], 'categories',
      (item, itemKey) => ProductCategory.fromJson(JsonHelper.asMap(item, itemKey)));
  final collectionValue = json['collection'] == null
      ? null
      : ProductCollection.fromJson(JsonHelper.asMap(json['collection'], 'collection'));
  final detailsValue = ProductDetails.fromJson(
    JsonHelper.asMap(json['details'], 'details'),
  );
  final handleValue = JsonHelper.as<String>(json['handle'], 'handle', 'String');
  final idValue = JsonHelper.as<String>(json['id'], 'id', 'String');
  final imagesValue = JsonHelper.decodeList(json['images'], 'images',
      (item, itemKey) => StoreProductImage.fromJson(JsonHelper.asMap(item, itemKey)));
  final optionsValue = JsonHelper.decodeList(json['options'], 'options',
      (item, itemKey) => ProductOption.fromJson(JsonHelper.asMap(item, itemKey)));
  final statusValue = _$ProductStatusDeserialize(json['status'], 'status');
  final titleValue = JsonHelper.as<String>(json['title'], 'title', 'String');
  final thumbnailValue = json['thumbnail'] == null
      ? null
      : JsonHelper.as<String>(json['thumbnail'], 'thumbnail', 'String');
  final tagsValue = JsonHelper.decodeList(json['tags'], 'tags',
      (item, itemKey) => ProductTag.fromJson(JsonHelper.asMap(item, itemKey)));
  final variantsValue = JsonHelper.decodeList(json['variants'], 'variants',
      (item, itemKey) => ProductVariant.fromJson(JsonHelper.asMap(item, itemKey)));

  return Product(
    id: idValue,
    title: titleValue,
    handle: handleValue,
    status: statusValue,
    options: optionsValue,
    variants: variantsValue,
    categories: categoriesValue,
    collection: collectionValue,
    details: detailsValue,
    description: descriptionValue,
    images: imagesValue,
    thumbnail: thumbnailValue,
    tags: tagsValue,
  );
}

Product _$ProductFromJson(Map<String, Object?> json) =>
    _$ProductDeserialize(json);

Object? _$ProductStatusSerialize(ProductStatus instance) {
  return switch (instance) {
    ProductStatus.draft => 'draft',
    ProductStatus.proposed => 'proposed',
    ProductStatus.published => 'published',
    ProductStatus.rejected => 'rejected',
  };
}

Object? _$ProductStatusToJson(ProductStatus instance) =>
    _$ProductStatusSerialize(instance);

ProductStatus _$ProductStatusDeserialize(Object? json, [String key = 'json']) {
  return switch (json) {
    'draft' => ProductStatus.draft,
    'proposed' => ProductStatus.proposed,
    'published' => ProductStatus.published,
    'rejected' => ProductStatus.rejected,
    _ => throw ArgumentError.value(json, key, 'unknown value for ProductStatus at $key'),
  };
}

ProductStatus _$ProductStatusFromJson(Object? json, [String key = 'json']) =>
    _$ProductStatusDeserialize(json, key);
