// GENERATED CODE - DO NOT MODIFY BY HAND
// coverage:ignore-file
// ignore_for_file: type=lint
// ignore_for_file: unused_element, unused_import, deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: use_function_type_syntax_for_parameters
// ignore_for_file: unnecessary_const, avoid_init_to_null
// ignore_for_file: invalid_override_different_default_values_named
// ignore_for_file: prefer_expression_function_bodies
// ignore_for_file: annotate_overrides, invalid_annotation_target
// ignore_for_file: unnecessary_question_mark
// Generated by dust.

part of 'product_listing_view_model.dart';

/// Base class generated for ProductListingViewModel.
///
/// Extend it from your ViewModel and forward typed args:
///
/// ```dart
/// final class ProductListingViewModel extends $ProductListingViewModel {
///   ProductListingViewModel(super.args);
/// }
/// ```
abstract class $ProductListingViewModel extends ViewModelBase<ProductListingState, ProductListingViewModelArgs> {
  $ProductListingViewModel(super.args) : super(initialState: const ProductListingState());
}

/// Reads ProductListingViewModel state from `BuildContext`.
///
/// Read `value` when the widget should rebuild for any state change.
///
/// ```dart
/// final state = context.watchProductListingViewModel().value;
/// ```
class _$ProductListingViewModelProxy {
  _$ProductListingViewModelProxy(this._context);

  final BuildContext _context;

  ProductListingState get value {
    return ProductListingViewModelScope.of(_context).value;
  }
}

/// Rebuilds when a selected ProductListingState value changes.
///
/// Use this for widgets that depend on one field or derived value.
class ProductListingViewModelSelector<R> extends StatefulWidget {
  const ProductListingViewModelSelector({
    super.key,
    required this.selector,
    required this.builder,
    this.child,
    this.equals,
  });

  final R Function(ProductListingState state) selector;
  final Widget Function(BuildContext context, R value, Widget? child) builder;
  final Widget? child;
  final bool Function(R previous, R next)? equals;

  @override
  State<ProductListingViewModelSelector<R>> createState() => _ProductListingViewModelSelectorState<R>();
}

class _ProductListingViewModelSelectorState<R> extends State<ProductListingViewModelSelector<R>> {
  ProductListingViewModel? _viewModel;
  R? _selected;
  bool _hasSelected = false;

  @override
  void didChangeDependencies() {
    super.didChangeDependencies();
    final nextViewModel = ProductListingViewModelScope._watchInstance(context);
    if (identical(_viewModel, nextViewModel)) return;
    _viewModel?.removeListener(_onViewModelStateChanged);
    _viewModel = nextViewModel;
    nextViewModel.addListener(_onViewModelStateChanged);
    _selectCurrent(force: true);
  }

  @override
  void didUpdateWidget(ProductListingViewModelSelector<R> oldWidget) {
    super.didUpdateWidget(oldWidget);
    _selectCurrent(force: true);
  }

  void _onViewModelStateChanged() {
    _selectCurrent();
  }

  void _selectCurrent({bool force = false}) {
    final viewModel = _viewModel;
    if (viewModel == null) return;
    final nextSelected = widget.selector(viewModel.value);
    if (!_hasSelected) {
      _selected = nextSelected;
      _hasSelected = true;
      return;
    }
    final previousSelected = _selected as R;
    final equals = widget.equals;
    final unchanged = equals == null
        ? previousSelected == nextSelected
        : equals(previousSelected, nextSelected);
    if (!force && unchanged) return;
    if (force || !mounted) {
      _selected = nextSelected;
    } else {
      setState(() {
        _selected = nextSelected;
      });
    }
  }

  @override
  void dispose() {
    _viewModel?.removeListener(_onViewModelStateChanged);
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    if (!_hasSelected) {
      _selectCurrent(force: true);
    }
    return widget.builder(context, _selected as R, widget.child);
  }
}

/// Creates and provides ProductListingViewModel to descendants.
///
/// The default constructor owns the ViewModel. Use `.value` for externally
/// owned ViewModels.
///
/// ```dart
/// ProductListingViewModelScope(
///   args: (context) => ProductListingViewModelArgs(...),
///   create: (context, args) => ProductListingViewModel(args),
///   child: const FeaturePage(),
/// )
/// ```
class ProductListingViewModelScope extends StatefulWidget {
  /// Creates and owns ProductListingViewModel from typed args.
  const ProductListingViewModelScope({
    super.key,
    required this.args,
    required this.create,
    required this.child,
    this.identity,
  }) : value = null;

  /// Provides an externally owned ProductListingViewModel without disposing it.
  const ProductListingViewModelScope.value({
    super.key,
    required ProductListingViewModel this.value,
    required this.child,
  }) : args = null,
       create = null,
       identity = null;

  final ProductListingViewModelArgs Function(BuildContext context)? args;
  final ProductListingViewModel Function(BuildContext context, ProductListingViewModelArgs args)? create;
  final Object? Function(BuildContext context)? identity;
  final ProductListingViewModel? value;
  final Widget child;

  /// Reads ProductListingViewModel without rebuilding when state changes.
  static ProductListingViewModel read(BuildContext context) {
    final scope = context
        .getElementForInheritedWidgetOfExactType<_ProductListingViewModelInstance>()
        ?.widget as _ProductListingViewModelInstance?;
    if (scope == null) throw StateError('No ProductListingViewModelScope found in context.');
    return scope.viewModel;
  }

  static ProductListingViewModel _watchInstance(BuildContext context) {
    final scope = context.dependOnInheritedWidgetOfExactType<_ProductListingViewModelInstance>();
    if (scope == null) throw StateError('No ProductListingViewModelScope found in context.');
    return scope.viewModel;
  }

  /// Watches ProductListingViewModel and rebuilds when state changes.
  static ProductListingViewModel of(BuildContext context) {
    final scope = context.dependOnInheritedWidgetOfExactType<_ProductListingViewModelInherited>();
    if (scope == null) throw StateError('No ProductListingViewModelScope found in context.');
    return scope.viewModel;
  }

  @override
  State<ProductListingViewModelScope> createState() => _ProductListingViewModelScopeState();
}

class _ProductListingViewModelScopeState extends State<ProductListingViewModelScope> {
  ProductListingViewModel? _viewModel;
  Object? _identity;
  bool _ownsViewModel = false;

  @override
  void didChangeDependencies() {
    super.didChangeDependencies();
    final external = widget.value;
    if (external != null) {
      _replaceViewModel(external, ownsViewModel: false, notify: false);
      return;
    }
    final nextIdentity = widget.identity?.call(context);
    if (_viewModel == null || nextIdentity != _identity) {
      _identity = nextIdentity;
      _replaceViewModel(_createOwnedViewModel(), ownsViewModel: true, notify: false);
    }
  }

  @override
  void didUpdateWidget(ProductListingViewModelScope oldWidget) {
    super.didUpdateWidget(oldWidget);
    final external = widget.value;
    if (external != null) {
      _replaceViewModel(external, ownsViewModel: false);
    } else if (oldWidget.value != null) {
      _identity = widget.identity?.call(context);
      _replaceViewModel(_createOwnedViewModel(), ownsViewModel: true);
    } else {
      final nextIdentity = widget.identity?.call(context);
      if (nextIdentity != _identity) {
        _identity = nextIdentity;
        _replaceViewModel(_createOwnedViewModel(), ownsViewModel: true);
      }
    }
  }

  ProductListingViewModel _createOwnedViewModel() {
    final argsFactory = widget.args;
    final create = widget.create;
    if (argsFactory == null || create == null) {
      throw StateError('Owned ProductListingViewModelScope requires args and create.');
    }
    late final ProductListingViewModel created;
    try {
      created = create(context, argsFactory(context));
    } catch (error, stackTrace) {
      Error.throwWithStackTrace(error, stackTrace);
    }
    return created;
  }

  void _replaceViewModel(
    ProductListingViewModel nextViewModel, {
    required bool ownsViewModel,
    bool notify = true,
  }) {
    final previous = _viewModel;
    if (identical(previous, nextViewModel)) {
      _ownsViewModel = ownsViewModel;
      _scheduleInit(nextViewModel);
      if (notify && mounted) setState(() {});
      return;
    }
    previous?.removeListener(_onViewModelStateChanged);
    if (_ownsViewModel) previous?.dispose();
    _viewModel = nextViewModel;
    _ownsViewModel = ownsViewModel;
    nextViewModel.addListener(_onViewModelStateChanged);
    _scheduleInit(nextViewModel);
    if (notify && mounted) setState(() {});
  }

  void _scheduleInit(ProductListingViewModel viewModel) {
    scheduleMicrotask(() async {
      if (!mounted || !identical(_viewModel, viewModel)) return;
      try {
        await viewModel.init();
      } catch (error, stackTrace) {
        FlutterError.reportError(
          FlutterErrorDetails(
            exception: error,
            stack: stackTrace,
            library: 'dust state',
            context: ErrorDescription('ProductListingViewModelScope init failed'),
          ),
        );
      }
    });
  }

  void _onViewModelStateChanged() {
    if (mounted) setState(() {});
  }

  @override
  void dispose() {
    final viewModel = _viewModel;
    viewModel?.removeListener(_onViewModelStateChanged);
    if (_ownsViewModel) viewModel?.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    final viewModel = _viewModel;
    if (viewModel == null) {
      throw StateError('ProductListingViewModelScope built before its view model was initialized.');
    }
    return _ProductListingViewModelInstance(
      viewModel: viewModel,
      child: _ProductListingViewModelInherited(
        viewModel: viewModel,
        state: viewModel.value,
        child: widget.child,
      ),
    );
  }
}

class _ProductListingViewModelInstance extends InheritedWidget {
  const _ProductListingViewModelInstance({required this.viewModel, required super.child});

  final ProductListingViewModel viewModel;

  @override
  bool updateShouldNotify(_ProductListingViewModelInstance oldWidget) {
    return !identical(viewModel, oldWidget.viewModel);
  }
}

class _ProductListingViewModelInherited extends InheritedWidget {
  const _ProductListingViewModelInherited({required this.viewModel, required this.state, required super.child});

  final ProductListingViewModel viewModel;
  final ProductListingState state;

  @override
  bool updateShouldNotify(_ProductListingViewModelInherited oldWidget) {
    return !identical(viewModel, oldWidget.viewModel) || state != oldWidget.state;
  }
}

/// Handles one-shot effects from ProductListingViewModel.
///
/// Effects are delivered without changing state and do not rebuild `child`.
///
/// ```dart
/// ProductListingViewModelListener(
///   listener: onEffect,
///   child: const FeaturePage(),
/// )
/// ```
class ProductListingViewModelListener extends StatefulWidget {
  const ProductListingViewModelListener({super.key, required this.listener, required this.child});

  final void Function(BuildContext context, Object effect) listener;
  final Widget child;

  @override
  State<ProductListingViewModelListener> createState() => _ProductListingViewModelListenerState();
}

class _ProductListingViewModelListenerState extends State<ProductListingViewModelListener> {
  StreamSubscription<Object>? _sub;
  ProductListingViewModel? _viewModel;

  @override
  void didChangeDependencies() {
    super.didChangeDependencies();
    final nextViewModel = ProductListingViewModelScope._watchInstance(context);
    if (_viewModel == nextViewModel) return;
    _sub?.cancel();
    _viewModel = nextViewModel;
    _sub = nextViewModel.effects.listen(_onEffect);
  }

  void _onEffect(Object effect) {
    if (mounted) widget.listener(context, effect);
  }

  @override
  void dispose() {
    _sub?.cancel();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) => widget.child;
}

/// BuildContext helpers generated for ProductListingViewModel.
///
/// ```dart
/// final vm = context.readProductListingViewModel();
/// final state = context.watchProductListingViewModel().value;
/// ```
extension ProductListingViewModelBuildContext on BuildContext {
  _$ProductListingViewModelProxy watchProductListingViewModel() {
    return _$ProductListingViewModelProxy(this);
  }

  ProductListingViewModel readProductListingViewModel() => ProductListingViewModelScope.read(this);
}
