// GENERATED CODE - DO NOT MODIFY BY HAND
// coverage:ignore-file
// ignore_for_file: type=lint
// ignore_for_file: unused_element, unused_import, deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: use_function_type_syntax_for_parameters
// ignore_for_file: unnecessary_const, avoid_init_to_null
// ignore_for_file: invalid_override_different_default_values_named
// ignore_for_file: prefer_expression_function_bodies
// ignore_for_file: annotate_overrides, invalid_annotation_target
// ignore_for_file: unnecessary_question_mark
// Generated by dust.

part of 'delete_response.dart';

mixin _$AdminCustomerAddressDeleteResponse implements Serializable {
  Map<String, Object?> serialize() =>
      _$AdminCustomerAddressDeleteResponseSerialize(this as AdminCustomerAddressDeleteResponse);

  Map<String, Object?> toJson() => serialize();
}

final class $AdminCustomerAddressDeleteResponseSerializer implements Serializer<AdminCustomerAddressDeleteResponse, Map<String, Object?>> {
  const $AdminCustomerAddressDeleteResponseSerializer();

  @override
  Map<String, Object?> serialize(AdminCustomerAddressDeleteResponse value) => _$AdminCustomerAddressDeleteResponseSerialize(value);
}

Map<String, Object?> _$AdminCustomerAddressDeleteResponseSerialize(AdminCustomerAddressDeleteResponse instance) {
  return <String, Object?>{
    'deleted': instance.deleted,
    'id': instance.id,
    'object': instance.object,
    'parent': instance.parent.toJson(),
  };
}

Map<String, Object?> _$AdminCustomerAddressDeleteResponseToJson(AdminCustomerAddressDeleteResponse instance) =>
    _$AdminCustomerAddressDeleteResponseSerialize(instance);
