// GENERATED CODE - DO NOT MODIFY BY HAND
// coverage:ignore-file
// ignore_for_file: type=lint
// ignore_for_file: unused_element, unused_import, deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: use_function_type_syntax_for_parameters
// ignore_for_file: unnecessary_const, avoid_init_to_null
// ignore_for_file: invalid_override_different_default_values_named
// ignore_for_file: prefer_expression_function_bodies
// ignore_for_file: annotate_overrides, invalid_annotation_target
// ignore_for_file: unnecessary_question_mark
// Generated by dust.

part of 'cart_view_model.dart';

/// Base class generated for CartViewModel.
///
/// Extend it from your ViewModel and forward typed args:
///
/// ```dart
/// final class CartViewModel extends $CartViewModel {
///   CartViewModel(super.args);
/// }
/// ```
abstract class $CartViewModel extends ViewModelBase<CartState, CartViewModelArgs> {
  $CartViewModel(super.args) : super(initialState: const CartState());
}

/// Reads CartViewModel state from `BuildContext`.
///
/// Read `value` when the widget should rebuild for any state change.
///
/// ```dart
/// final state = context.watchCartViewModel().value;
/// ```
class _$CartViewModelProxy {
  _$CartViewModelProxy(this._context);

  final BuildContext _context;

  CartState get value {
    return CartViewModelScope.of(_context).value;
  }
}

/// Rebuilds when a selected CartState value changes.
///
/// Use this for widgets that depend on one field or derived value.
class CartViewModelSelector<R> extends StatefulWidget {
  const CartViewModelSelector({
    super.key,
    required this.selector,
    required this.builder,
    this.child,
    this.equals,
  });

  final R Function(CartState state) selector;
  final Widget Function(BuildContext context, R value, Widget? child) builder;
  final Widget? child;
  final bool Function(R previous, R next)? equals;

  @override
  State<CartViewModelSelector<R>> createState() => _CartViewModelSelectorState<R>();
}

class _CartViewModelSelectorState<R> extends State<CartViewModelSelector<R>> {
  CartViewModel? _viewModel;
  R? _selected;
  bool _hasSelected = false;

  @override
  void didChangeDependencies() {
    super.didChangeDependencies();
    final nextViewModel = CartViewModelScope._watchInstance(context);
    if (identical(_viewModel, nextViewModel)) return;
    _viewModel?.removeListener(_onViewModelStateChanged);
    _viewModel = nextViewModel;
    nextViewModel.addListener(_onViewModelStateChanged);
    _selectCurrent(force: true);
  }

  @override
  void didUpdateWidget(CartViewModelSelector<R> oldWidget) {
    super.didUpdateWidget(oldWidget);
    _selectCurrent(force: true);
  }

  void _onViewModelStateChanged() {
    _selectCurrent();
  }

  void _selectCurrent({bool force = false}) {
    final viewModel = _viewModel;
    if (viewModel == null) return;
    final nextSelected = widget.selector(viewModel.value);
    if (!_hasSelected) {
      _selected = nextSelected;
      _hasSelected = true;
      return;
    }
    final previousSelected = _selected as R;
    final equals = widget.equals;
    final unchanged = equals == null
        ? previousSelected == nextSelected
        : equals(previousSelected, nextSelected);
    if (!force && unchanged) return;
    if (force || !mounted) {
      _selected = nextSelected;
    } else {
      setState(() {
        _selected = nextSelected;
      });
    }
  }

  @override
  void dispose() {
    _viewModel?.removeListener(_onViewModelStateChanged);
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    if (!_hasSelected) {
      _selectCurrent(force: true);
    }
    return widget.builder(context, _selected as R, widget.child);
  }
}

/// Creates and provides CartViewModel to descendants.
///
/// The default constructor owns the ViewModel. Use `.value` for externally
/// owned ViewModels.
///
/// ```dart
/// CartViewModelScope(
///   args: (context) => CartViewModelArgs(...),
///   create: (context, args) => CartViewModel(args),
///   child: const FeaturePage(),
/// )
/// ```
class CartViewModelScope extends StatefulWidget {
  /// Creates and owns CartViewModel from typed args.
  const CartViewModelScope({
    super.key,
    required this.args,
    required this.create,
    required this.child,
    this.identity,
  }) : value = null;

  /// Provides an externally owned CartViewModel without disposing it.
  const CartViewModelScope.value({
    super.key,
    required CartViewModel this.value,
    required this.child,
  }) : args = null,
       create = null,
       identity = null;

  final CartViewModelArgs Function(BuildContext context)? args;
  final CartViewModel Function(BuildContext context, CartViewModelArgs args)? create;
  final Object? Function(BuildContext context)? identity;
  final CartViewModel? value;
  final Widget child;

  /// Reads CartViewModel without rebuilding when state changes.
  static CartViewModel read(BuildContext context) {
    final scope = context
        .getElementForInheritedWidgetOfExactType<_CartViewModelInstance>()
        ?.widget as _CartViewModelInstance?;
    if (scope == null) throw StateError('No CartViewModelScope found in context.');
    return scope.viewModel;
  }

  static CartViewModel _watchInstance(BuildContext context) {
    final scope = context.dependOnInheritedWidgetOfExactType<_CartViewModelInstance>();
    if (scope == null) throw StateError('No CartViewModelScope found in context.');
    return scope.viewModel;
  }

  /// Watches CartViewModel and rebuilds when state changes.
  static CartViewModel of(BuildContext context) {
    final scope = context.dependOnInheritedWidgetOfExactType<_CartViewModelInherited>();
    if (scope == null) throw StateError('No CartViewModelScope found in context.');
    return scope.viewModel;
  }

  @override
  State<CartViewModelScope> createState() => _CartViewModelScopeState();
}

class _CartViewModelScopeState extends State<CartViewModelScope> {
  CartViewModel? _viewModel;
  Object? _identity;
  bool _ownsViewModel = false;

  @override
  void didChangeDependencies() {
    super.didChangeDependencies();
    final external = widget.value;
    if (external != null) {
      _replaceViewModel(external, ownsViewModel: false, notify: false);
      return;
    }
    final nextIdentity = widget.identity?.call(context);
    if (_viewModel == null || nextIdentity != _identity) {
      _identity = nextIdentity;
      _replaceViewModel(_createOwnedViewModel(), ownsViewModel: true, notify: false);
    }
  }

  @override
  void didUpdateWidget(CartViewModelScope oldWidget) {
    super.didUpdateWidget(oldWidget);
    final external = widget.value;
    if (external != null) {
      _replaceViewModel(external, ownsViewModel: false);
    } else if (oldWidget.value != null) {
      _identity = widget.identity?.call(context);
      _replaceViewModel(_createOwnedViewModel(), ownsViewModel: true);
    } else {
      final nextIdentity = widget.identity?.call(context);
      if (nextIdentity != _identity) {
        _identity = nextIdentity;
        _replaceViewModel(_createOwnedViewModel(), ownsViewModel: true);
      }
    }
  }

  CartViewModel _createOwnedViewModel() {
    final argsFactory = widget.args;
    final create = widget.create;
    if (argsFactory == null || create == null) {
      throw StateError('Owned CartViewModelScope requires args and create.');
    }
    late final CartViewModel created;
    try {
      created = create(context, argsFactory(context));
    } catch (error, stackTrace) {
      Error.throwWithStackTrace(error, stackTrace);
    }
    return created;
  }

  void _replaceViewModel(
    CartViewModel nextViewModel, {
    required bool ownsViewModel,
    bool notify = true,
  }) {
    final previous = _viewModel;
    if (identical(previous, nextViewModel)) {
      _ownsViewModel = ownsViewModel;
      _scheduleInit(nextViewModel);
      if (notify && mounted) setState(() {});
      return;
    }
    previous?.removeListener(_onViewModelStateChanged);
    if (_ownsViewModel) previous?.dispose();
    _viewModel = nextViewModel;
    _ownsViewModel = ownsViewModel;
    nextViewModel.addListener(_onViewModelStateChanged);
    _scheduleInit(nextViewModel);
    if (notify && mounted) setState(() {});
  }

  void _scheduleInit(CartViewModel viewModel) {
    scheduleMicrotask(() async {
      if (!mounted || !identical(_viewModel, viewModel)) return;
      try {
        await viewModel.init();
      } catch (error, stackTrace) {
        FlutterError.reportError(
          FlutterErrorDetails(
            exception: error,
            stack: stackTrace,
            library: 'dust state',
            context: ErrorDescription('CartViewModelScope init failed'),
          ),
        );
      }
    });
  }

  void _onViewModelStateChanged() {
    if (mounted) setState(() {});
  }

  @override
  void dispose() {
    final viewModel = _viewModel;
    viewModel?.removeListener(_onViewModelStateChanged);
    if (_ownsViewModel) viewModel?.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    final viewModel = _viewModel;
    if (viewModel == null) {
      throw StateError('CartViewModelScope built before its view model was initialized.');
    }
    return _CartViewModelInstance(
      viewModel: viewModel,
      child: _CartViewModelInherited(
        viewModel: viewModel,
        state: viewModel.value,
        child: widget.child,
      ),
    );
  }
}

class _CartViewModelInstance extends InheritedWidget {
  const _CartViewModelInstance({required this.viewModel, required super.child});

  final CartViewModel viewModel;

  @override
  bool updateShouldNotify(_CartViewModelInstance oldWidget) {
    return !identical(viewModel, oldWidget.viewModel);
  }
}

class _CartViewModelInherited extends InheritedWidget {
  const _CartViewModelInherited({required this.viewModel, required this.state, required super.child});

  final CartViewModel viewModel;
  final CartState state;

  @override
  bool updateShouldNotify(_CartViewModelInherited oldWidget) {
    return !identical(viewModel, oldWidget.viewModel) || state != oldWidget.state;
  }
}

/// Handles one-shot effects from CartViewModel.
///
/// Effects are delivered without changing state and do not rebuild `child`.
///
/// ```dart
/// CartViewModelListener(
///   listener: onEffect,
///   child: const FeaturePage(),
/// )
/// ```
class CartViewModelListener extends StatefulWidget {
  const CartViewModelListener({super.key, required this.listener, required this.child});

  final void Function(BuildContext context, Object effect) listener;
  final Widget child;

  @override
  State<CartViewModelListener> createState() => _CartViewModelListenerState();
}

class _CartViewModelListenerState extends State<CartViewModelListener> {
  StreamSubscription<Object>? _sub;
  CartViewModel? _viewModel;

  @override
  void didChangeDependencies() {
    super.didChangeDependencies();
    final nextViewModel = CartViewModelScope._watchInstance(context);
    if (_viewModel == nextViewModel) return;
    _sub?.cancel();
    _viewModel = nextViewModel;
    _sub = nextViewModel.effects.listen(_onEffect);
  }

  void _onEffect(Object effect) {
    if (mounted) widget.listener(context, effect);
  }

  @override
  void dispose() {
    _sub?.cancel();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) => widget.child;
}

/// BuildContext helpers generated for CartViewModel.
///
/// ```dart
/// final vm = context.readCartViewModel();
/// final state = context.watchCartViewModel().value;
/// ```
extension CartViewModelBuildContext on BuildContext {
  _$CartViewModelProxy watchCartViewModel() {
    return _$CartViewModelProxy(this);
  }

  CartViewModel readCartViewModel() => CartViewModelScope.read(this);
}
