// GENERATED CODE - DO NOT MODIFY BY HAND
// coverage:ignore-file
// ignore_for_file: type=lint
// ignore_for_file: unused_element, unused_import, deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: use_function_type_syntax_for_parameters
// ignore_for_file: unnecessary_const, avoid_init_to_null
// ignore_for_file: invalid_override_different_default_values_named
// ignore_for_file: prefer_expression_function_bodies
// ignore_for_file: annotate_overrides, invalid_annotation_target
// ignore_for_file: unnecessary_question_mark
// Generated by dust.

part of 'count.dart';

final class _$CatalogCountRepository implements CatalogCountRepository {
  const _$CatalogCountRepository(this._db);

  final DatabaseExecutor _db;

  @override
  Future<Result<int, SqlxError>> countPublished(String currencyCode, String? collectionHandle, String? categoryHandle, String? tag, String optionValueIdsJson) {
    return _db.fetchScalar<int>(
      r'''
SELECT COUNT(*) AS total
FROM products product
LEFT JOIN product_collections collection
  ON collection.id = product.collection_id AND collection.deleted_at IS NULL
WHERE product.status = 'published' AND product.deleted_at IS NULL
  AND EXISTS (
    SELECT 1
    FROM product_variants sellable_variant
    JOIN variant_prices sellable_price
      ON sellable_price.variant_id = sellable_variant.id
    WHERE sellable_variant.product_id = product.id
      AND sellable_variant.deleted_at IS NULL
      AND sellable_price.currency_code = ?
  )
  AND (? IS NULL OR collection.handle = ?)
  AND (? IS NULL OR EXISTS (
    SELECT 1
    FROM product_category_products filter_link
    JOIN product_categories filter_category
      ON filter_category.id = filter_link.category_id
    WHERE filter_link.product_id = product.id
      AND filter_category.handle = ?
      AND filter_category.is_active = 1
      AND filter_category.deleted_at IS NULL
  ))
  AND (? IS NULL OR EXISTS (
    SELECT 1
    FROM product_tag_products filter_link
    JOIN product_tags filter_tag ON filter_tag.id = filter_link.tag_id
    WHERE filter_link.product_id = product.id
      AND lower(filter_tag.value) = lower(?)
      AND filter_tag.deleted_at IS NULL
  ))
  AND (json_array_length(?) = 0 OR EXISTS (
    SELECT 1
    FROM product_variants filter_variant
    JOIN variant_prices filter_price
      ON filter_price.variant_id = filter_variant.id
    JOIN variant_option_values filter_choice
      ON filter_choice.variant_id = filter_variant.id
    JOIN product_options filter_option
      ON filter_option.id = filter_choice.option_id
     AND filter_option.product_id = product.id
    JOIN product_option_values filter_value
      ON filter_value.id = filter_choice.option_value_id
     AND filter_value.option_id = filter_choice.option_id
    WHERE filter_variant.product_id = product.id
      AND filter_variant.deleted_at IS NULL
      AND filter_price.currency_code = ?
      AND filter_option.deleted_at IS NULL
      AND filter_value.deleted_at IS NULL
      AND filter_choice.option_value_id IN (
        SELECT value FROM json_each(?)
      )
  ))
''',
      [currencyCode, collectionHandle, collectionHandle, categoryHandle, categoryHandle, tag, tag, optionValueIdsJson, currencyCode, optionValueIdsJson],
    );
  }
}
